function adc_forensic_overlay(sys, base)
% adc_forensic_overlay -- T8.3 ADC ingest forensic register (AXI 0x15C).
%
% One packed uint32, cap_cad-style, measuring the modem's TRUE adc ingest at
% the TxRxComposite boundary (full clk rate, the enb domain -- the same
% domain the AdcCap latch samples adc_validIn/adc_dataInI in):
%
%   [7:0]   validDuty : adc_validIn beats in the last completed 2^13-clk
%           window, divided by 32 (saturate 255). Expect 128 = exactly the
%           1-in-2 SSI cadence (CADENCE FIX v6 + util_valid_regularizer
%           contract). <128 = slow/underrun, >128 = fast/overrate.
%   [15:8]  maxGap    : max consecutive clks with adc_validIn low since
%           reset (sat 255). Expect 1 (valid every 2nd clk).
%   [23:16] maxBurst  : max consecutive-clk adc_validIn run since reset
%           (sat 255). Expect 1; >1 = upstream CDC clumping.
%   [31:24] levelLog  : bit position of the MSB of max(|adc_dataInI|) since
%           reset (1..16, 0 = all-zero input). Reads the MODEM-RAIL level
%           with no DMA: rms~286 peaks ~1k -> levelLog~10-11; a healthy
%           lockable rail (rms>=512, peaks >=2k) -> >=12; the DMA-tap
%           confusion (voltage0 = debug mux, NOT the rail; see
%           PHASEB_AGC_REPORT.txt T8.3) is bypassed entirely.
%
% Cleared by the modem soft-reset 0x000 (persistent state -> HDL registers
% on the DUT reset). Read register only; no register map change other than
% NEW 0x15C (0x158 stays reserved).
%
% Apply at assemble Phase 2.12 (after taps_240k5_overlay, before pre-synth
% gates). AXI mapping added by patch_hdlworkflow_forensic.m (Phase 0).
% Idempotent.

if nargin < 1 || isempty(sys),  sys  = bdroot; end
if nargin < 2 || isempty(base), base = sys;    end
loop = base;

% Idempotency marker
if ~isempty(find_system(loop,'SearchDepth',1,'BlockType','Outport','Name','adc_forensic'))
    fprintf('adc_forensic_overlay: already present -- skipping\n');
    return;
end
assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Inport','Name','adc_validIn')), ...
    'adc_forensic_overlay: adc_validIn inport not found at %s', loop);
assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Inport','Name','adc_dataInI')), ...
    'adc_forensic_overlay: adc_dataInI inport not found at %s', loop);

% (1) AdcForensic MATLAB Function at composite level (branches off the
%     adc_validIn / adc_dataInI inport signals; full-rate like AdcCap).
add_block('simulink/User-Defined Functions/MATLAB Function', [loop '/AdcForensic'], ...
    'Position',[300 1400 420 1470]);
set_fcn_script([loop '/AdcForensic'], sprintf([ ...
'function y = adcForensic(v, dI)\n' ...
'%%#codegen\n' ...
'%% T8.3 ingest forensic (AXI 0x15C): [validDuty|maxGap|maxBurst|levelLog].\n' ...
'%% Full-clk-rate; cleared by modem soft-reset 0x000 via persistent init.\n' ...
'persistent wcnt vcnt duty gapc maxGap burc maxBur mx\n' ...
'if isempty(wcnt)\n' ...
'    wcnt = uint16(0); vcnt = uint16(0); duty = uint8(0);\n' ...
'    gapc = uint8(0); maxGap = uint8(0); burc = uint8(0); maxBur = uint8(0);\n' ...
'    mx = uint16(0);\n' ...
'end\n' ...
'w = wcnt; vc = vcnt; d = duty; g = gapc; mg = maxGap;\n' ...
'b = burc; mb = maxBur; m = mx;\n' ...
'if v\n' ...
'    vc = vc + uint16(1);\n' ...
'    if b < uint8(255), b = b + uint8(1); end\n' ...
'    if b > mb, mb = b; end\n' ...
'    g = uint8(0);\n' ...
'    a = uint16(min(abs(int32(dI)), int32(32767)));\n' ...
'    if a > m, m = a; end\n' ...
'else\n' ...
'    if g < uint8(255), g = g + uint8(1); end\n' ...
'    if g > mg, mg = g; end\n' ...
'    b = uint8(0);\n' ...
'end\n' ...
'w = w + uint16(1);\n' ...
'if w >= uint16(8192)\n' ...
'    d = uint8(min(bitshift(vc, -5), uint16(255)));\n' ...
'    w = uint16(0); vc = uint16(0);\n' ...
'end\n' ...
'lv = uint8(0);\n' ...
'for k = 0:15\n' ...
'    if bitshift(m, -k) ~= uint16(0)\n' ...
'        lv = uint8(k + 1);\n' ...
'    end\n' ...
'end\n' ...
'y = bitor(bitor(uint32(d), bitshift(uint32(mg), 8)), ...\n' ...
'          bitor(bitshift(uint32(mb), 16), bitshift(uint32(lv), 24)));\n' ...
'wcnt = w; vcnt = vc; duty = d; gapc = g; maxGap = mg;\n' ...
'burc = b; maxBur = mb; mx = m;\n']));
add_line(loop, 'adc_validIn/1',  'AdcForensic/1', 'autorouting','on');
add_line(loop, 'adc_dataInI/1',  'AdcForensic/2', 'autorouting','on');
fprintf('adc_forensic_overlay: AdcForensic block added (adc_validIn + adc_dataInI, full rate)\n');

% (2) new TxRxComposite outport (explicit port number, taps-overlay style)
nOut = numel(find_system(loop,'SearchDepth',1,'LookUnderMasks','all','BlockType','Outport'));
add_block('built-in/Outport', [loop '/adc_forensic'], 'Port', num2str(nOut+1), ...
    'Position',[470 1420 500 1440]);
add_line(loop, 'AdcForensic/1', 'adc_forensic/1', 'autorouting','on');
fprintf('adc_forensic_overlay: TxRxComposite adc_forensic outport %d (AXI 0x15C in workflow)\n', nOut+1);

fprintf('adc_forensic_overlay: DONE\n');
end

% ===================== helpers =====================
function set_fcn_script(blk, src)
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',blk);
chart.Script = src;
end
