function fec_tx_encoder_overlay_k5(sys, loop)
% fec_tx_encoder_overlay_k5 -- IN-FABRIC K=5 FEC Tx encode chain for the
% modem kit. Splices, INSIDE <loop>/Transmitter/Input Data,
% between the ByteBitShifter (byte_tx_overlay_k5.m) and the BitMux:
%
%   ByteBitShifter bit --> [FEC Tx Encoder K5] --> BitMux/1 (u1, byte branch)
%
% so tx_data_source=0 keeps the pre-coded K5 ROM (BIST) bit-for-bit and
% tx_data_source=1 transmits the HOST info bytes encoded IN FABRIC to the
% IDENTICAL on-air contract (contract/PACKET_K5.txt):
%   * K=5 [35 23] rate-1/2 conv encoder, per-frame zero state ('term'):
%     1084 info bits (the frame's first 1084 byte-stream bits) + 4 zero
%     tail -> 2176 coded bits
%   * 136x16 block interleave, legacy read perm = r*COLS+c
%     (r=mod(beat,136), c=floor(beat/136)) -- ping-pong banks, the fec_dut
%     donor scheduling (write current frame 2 bits/beat, read PREVIOUS
%     frame 1 bit/beat) => ONE-FRAME pipeline latency on the byte branch
%   * + the 64-bit PN9 FILLER (T8 waveform fix, contract commit 6bcaa62: the
%     legacy 64-ones filler made a 32-symbol DC dwell on air that the
%     ADRV9002 TX LOL tracking cal notches, killing ~24 coded bits/frame;
%     PN9 x^9+x^5+1 seed all-ones has max run ~9 -> no DC dwell). The
%     filler constant is read from golden_k5.mat payload(2177:2240) at
%     overlay time, independently re-derived from the LFSR spec, and baked
%     into the chart as a 64-bit literal.
%     -> 2240 bits/frame, emitted at the msggen chart's exact cadence (same
%     enable/start the ROM chart uses), so the BitMux branches are
%     beat-aligned and the Bit Packetizer framing is unchanged.
%
% CRITICAL (the documented historical failure class, memory
% qpsk-fec-zed-encoder-fix + docs_session/qpsk-two-board-link-state.md):
% the encoder shift register ADVANCES ONLY ON infoValid BEATS (holds
% otherwise). An ungated encoder zero-stuffs the info stream on any
% non-valid beat and corrupts every coded bit. The gated MATLAB-Function
% encoder here is the fec_zed_noscr3/fec_fix_encoder_gate.m pattern
% (iverilog-proven CAP_IN bit-exact), migrated K=7 [171 133] -> K=5 [35 23],
% with one refinement: encReset zeroes the state USED AND STORED on the
% start beat *before* shifting in bit 0 (reset-then-advance), so frame 0's
% pair AND frame-boundary state are bit-exact to convenc even if the state
% were corrupted (the donor's clear-instead-of-shift was only exact because
% 'A' starts with a 0 bit). Equations verified against convenc (random
% trials) at overlay-authoring time and re-checked by sim_byte_gate_k5.m.
%
% Chain FSMs are sync-semantics compliant (RXROOT E11c: locals in, reads
% before writes, persist last) like the K5 Rx overlay sources.
%
% Idempotent: skips if 'FEC Tx Encoder K5' already present. Does NOT save.

if nargin < 1, sys = bdroot; end %#ok<NASGU>
if nargin < 2 || isempty(loop), loop = [bdroot '/TxRxComposite']; end
id = [loop '/Transmitter/Input Data'];

% FEC params (single source of truth: frame_config_k5; MUST match
% contract/PACKET_K5.txt + fec_insert_overlay_rxonly_k5)
cfg = frame_config_k5();
INFO_BITS = cfg.InfoBits; TAIL_BITS = cfg.TailBits;
CODED_BITS = cfg.CodedBits;                        % 2176 = 2*(INFO_BITS+TAIL_BITS)
COLS = cfg.InterleaveCols; ROWS = cfg.InterleaveRows;   % 16 x 136
PAYLOAD = cfg.PayloadBits; NFILL = cfg.FillerBits;      % 2240, 64 (PN9 filler)
% cfg-vs-cfg consistency check (values sourced from frame_config_k5); the
% independent literal pinning lives in frame_config_k5.m's per-frame
% golden-anchor block.
assert(CODED_BITS==2*(INFO_BITS+TAIL_BITS) && CODED_BITS==ROWS*COLS && NFILL==PAYLOAD-CODED_BITS, ...
    'K5 contract mismatch');
% PN9 filler constant (T8 fix, 6bcaa62): single-source = the regenerated
% golden payload tail; independently re-derived from the LFSR spec here so
% a stale golden_k5.mat cannot slip through.
Gf = load(fullfile(fileparts(fileparts(mfilename('fullpath'))),'contract', ...
    sprintf('golden_%s.mat',cfg.Frame)),'payload');
FILLBITS = double(Gf.payload(CODED_BITS+1:PAYLOAD));
% The FILLREF_LEN literal below is INTENTIONAL: it is the independent PN9
% reference length anchor (NOT derived from cfg), so a wrong
% cfg.CodedBits/PayloadBits would make this length check fire instead of
% silently sliding. Each frame supplies its own PN reference length here.
FILLREF_LEN = 64;                                    % k5 PN9 filler length
if strcmp(cfg.Frame,'f1536'), FILLREF_LEN = 48; end  % f1536 PN9 filler length
assert(numel(FILLBITS)==FILLREF_LEN && ~all(FILLBITS==1), ...
    'golden filler is %d ones -- STALE golden_%s.mat (pre-6bcaa62)?', FILLREF_LEN, cfg.Frame);
lfsr = ones(9,1); f2 = zeros(FILLREF_LEN,1);
for fk = 1:FILLREF_LEN
    fb = xor(lfsr(9), lfsr(5));
    f2(fk) = lfsr(9);
    lfsr = [fb; lfsr(1:8)]; %#ok<AGROW>
end
assert(isequal(FILLBITS(:), f2(:)), ...
    'golden filler != PN9(x^9+x^5+1, seed all-ones) -- contract drift');
fillLit = strjoin(arrayfun(@(b) sprintf('%d',b), FILLBITS(:).', 'UniformOutput', false), ' ');

enc = [id '/FEC Tx Encoder K5'];
if ~isempty(find_system(id,'SearchDepth',1,'LookUnderMasks','all', ...
        'FollowLinks','on','Name','FEC Tx Encoder K5'))
    fprintf('fec_tx_encoder_overlay_k5: encoder chain already present -- skipping\n');
    return;
end

% preconditions: byte_tx_overlay_k5 applied (shifter + mux present, wired)
assert(~isempty(find_system(id,'SearchDepth',1,'LookUnderMasks','all', ...
    'FollowLinks','on','Name','ByteBitShifter')), 'ByteBitShifter missing -- run byte_tx_overlay_k5 first');
assert(~isempty(find_system(id,'SearchDepth',1,'LookUnderMasks','all', ...
    'FollowLinks','on','Name','BitMux')), 'BitMux missing -- run byte_tx_overlay_k5 first');

% --- (1) the encoder chain subsystem ---
add_block('built-in/Subsystem', enc, 'Position',[460 420 560 520]);
inn = {'bitIn','enable','reset','start'};
for k=1:4, add_block('built-in/Inport',[enc '/' inn{k}],'Port',num2str(k), ...
        'Position',[20 40+40*k 50 60+40*k]); end
add_block('built-in/Outport',[enc '/encBit'],'Port','1','Position',[760 120 790 140]);

% (1a) TxGateK5: beat framing at the msggen cadence
add_block('simulink/User-Defined Functions/MATLAB Function',[enc '/TxGateK5'], ...
    'Position',[120 60 260 200]);
set_fcn_script([enc '/TxGateK5'], fecTxGateK5_src(INFO_BITS, TAIL_BITS, PAYLOAD));

% (1b) ConvEncK5: infoValid-GATED K=5 [35 23] encoder (THE load-bearing gate)
add_block('simulink/User-Defined Functions/MATLAB Function',[enc '/ConvEncK5'], ...
    'Position',[320 60 440 200]);
set_fcn_script([enc '/ConvEncK5'], fecConvEncK5_src());

% (1c) TxInterleaveK5: ping-pong 136x16 interleaver + PN9 filler
add_block('simulink/User-Defined Functions/MATLAB Function',[enc '/TxInterleaveK5'], ...
    'Position',[520 60 660 200]);
set_fcn_script([enc '/TxInterleaveK5'], fecTxInterleaveK5_src(CODED_BITS, COLS, ROWS, fillLit, strcmp(cfg.Frame,'f1536')));

% wiring inside the subsystem
add_line(enc, 'bitIn/1',  'TxGateK5/1', 'autorouting','on');
add_line(enc, 'enable/1', 'TxGateK5/2', 'autorouting','on');
add_line(enc, 'reset/1',  'TxGateK5/3', 'autorouting','on');
add_line(enc, 'start/1',  'TxGateK5/4', 'autorouting','on');
% TxGateK5 outs: 1 infoBit 2 encReset 3 infoValid 4 beatIdx 5 frameValid 6 frameStart
add_line(enc, 'TxGateK5/1', 'ConvEncK5/1', 'autorouting','on');   % infoBit
add_line(enc, 'TxGateK5/2', 'ConvEncK5/2', 'autorouting','on');   % encReset
add_line(enc, 'TxGateK5/3', 'ConvEncK5/3', 'autorouting','on');   % infoValid (THE FIX)
add_line(enc, 'ConvEncK5/1',  'TxInterleaveK5/1', 'autorouting','on'); % codedPair[2x1]
add_line(enc, 'TxGateK5/3',   'TxInterleaveK5/2', 'autorouting','on'); % infoValid
add_line(enc, 'TxGateK5/4',   'TxInterleaveK5/3', 'autorouting','on'); % beatIdx
add_line(enc, 'TxGateK5/5',   'TxInterleaveK5/4', 'autorouting','on'); % frameValid
add_line(enc, 'TxGateK5/6',   'TxInterleaveK5/5', 'autorouting','on'); % frameStart
add_line(enc, 'TxInterleaveK5/1', 'encBit/1', 'autorouting','on');

% --- (2) splice into the byte branch: shifter -> encoder -> BitMux u1 ---
delete_line(id, 'ByteBitShifter/1', 'BitMux/1');
add_line(id, 'ByteBitShifter/1',     'FEC Tx Encoder K5/1', 'autorouting','on');
add_line(id, 'enb/1',                'FEC Tx Encoder K5/2', 'autorouting','on');
add_line(id, 'Cast To Boolean/1',    'FEC Tx Encoder K5/3', 'autorouting','on');
add_line(id, 'Message Generator/3',  'FEC Tx Encoder K5/4', 'autorouting','on');
add_line(id, 'FEC Tx Encoder K5/1',  'BitMux/1', 'autorouting','on');

% --- (3) verify the gating structure (what assemble gate (c) re-asserts) ---
ce = sfroot().find('-isa','Stateflow.EMChart','Path',[id '/FEC Tx Encoder K5/ConvEncK5']);
assert(~isempty(ce), 'ConvEncK5 chart not found post-build');
assert(contains(ce(1).Script,'if infoValid') && contains(ce(1).Script,'sr = [in, srUse(1:3)];'), ...
    'ConvEncK5 script lost the infoValid-gated advance');

% --- (4) RAM mapping for the ping-pong interleaver banks (f1536 ONLY) ---
% At f1536 scale the two persistent banks are CODED=24592 bits each (~49k
% flops for this MLFB); request BRAM inference so they map to on-chip RAM.
% MapPersistentVarsToRAM is a CODEGEN-only property (no simulation effect, so
% the G1 sim gate is blind to it -- BRAM fit is verified at HDL-build time,
% see the assemble-time present-check and task-A2-report). Gated on f1536 so
% the k5 generated HDL stays byte-identical to today (k5 banks = 2176 flops,
% deliberately left as registers). NOTE the fecRxDeint/fecTxInterleaveK5
% multi-access-per-step read pattern is the documented BRAM-fit risk.
if strcmp(cfg.Frame,'f1536')
    hdlset_param([enc '/TxInterleaveK5'], 'MapPersistentVarsToRAM', 'on');
    fprintf('fec_tx_encoder_overlay_k5: TxInterleaveK5 MapPersistentVarsToRAM=on (f1536 BRAM request)\n');
end

fprintf(['fec_tx_encoder_overlay_k5: DONE (K=5 [35 23] info %d + tail %d -> coded %d,\n' ...
         '  %dx%d interleave perm r*%d+c ping-pong, +%d-bit PN9 filler; encoder advance\n' ...
         '  GATED by infoValid; byte branch = encode(previous frame) one-frame latency)\n'], ...
    INFO_BITS, TAIL_BITS, CODED_BITS, ROWS, COLS, COLS, NFILL);
end

% ----------------------------------------------------------------------------
function set_fcn_script(blk, src)
chart = sfroot().find('-isa','Stateflow.EMChart','Path',blk);
assert(~isempty(chart), 'chart not found at %s', blk);
chart.Script = src;
end

function src = fecTxGateK5_src(INFO, TAIL, PAYLOAD)
% Beat framing at the msggen chart cadence: 'start' (chart indexCount==0)
% zeroes the beat counter; enabled beats then step 0..PAYLOAD-1 in lockstep
% with the ROM chart's indexCount. Beats 0..INFO-1 present the shifter bit
% as encoder info; beats INFO..INFO+TAIL-1 present the K-1 zero tail flush;
% infoValid tags exactly those NIN encoder-advance beats. frameValid covers
% the whole PAYLOAD window (the read/filler side runs every beat).
src = sprintf([ ...
'function [infoBit, encReset, infoValid, beatIdx, frameValid, frameStart] = fecTxGateK5(bitIn, enable, reset, start)\n' ...
'%%#codegen\n' ...
'%% sync-semantics (RXROOT E11c): locals in, outputs from locals, persist last.\n' ...
'persistent beat armed;\n' ...
'INFO=uint16(%d); NIN=uint16(%d); PAYLOAD=uint16(%d);\n' ...
'if isempty(beat), beat=uint16(0); armed=false; end\n' ...
'b=beat; a=armed;\n' ...
'infoBit=false; encReset=false; infoValid=false; beatIdx=uint16(0);\n' ...
'frameValid=false; frameStart=false;\n' ...
'en = logical(enable) && ~logical(reset);\n' ...
'if en\n' ...
'  if start, b=uint16(0); a=true; encReset=true; end\n' ...
'  if a\n' ...
'    if b < INFO\n' ...
'      infoBit = logical(bitIn); infoValid = true;\n' ...
'    elseif b < NIN\n' ...
'      infoBit = false;          infoValid = true;   %% K-1 zero tail flush\n' ...
'    end\n' ...
'    beatIdx = b; frameValid = true; frameStart = (b==uint16(0));\n' ...
'    if b < PAYLOAD-uint16(1), b=b+uint16(1); else, b=uint16(0); end\n' ...
'  end\n' ...
'end\n' ...
'beat=b; armed=a;\n'], INFO, INFO+TAIL, PAYLOAD);
end

function src = fecConvEncK5_src()
% infoValid-GATED K=5 [35 23] rate-1/2 encoder (fec_zed_noscr3
% fec_fix_encoder_gate.m pattern, K=5 taps, reset-then-advance refinement).
%   g0 = 35 (oct) = 11101 -> out0 = s0^s1^s2^s4
%   g1 = 23 (oct) = 10011 -> out1 = s0^s3^s4
% where s0 = current infoBit, s1..s4 = shift register (s1 most recent).
% codedPair = [g0; g1] (2x1 boolean) = the convenc output order.
% State ADVANCES ONLY ON infoValid (holds otherwise -- the anti-zero-stuff
% gate); encReset (frame start) zeroes the state BEFORE the bit-0 shift so
% each frame encodes from the zero state exactly like per-frame convenc
% ('term' contract; the 4 zero tail bits leave the state zero anyway).
src = sprintf([ ...
'function codedPair = fecConvEncK5(infoBit, encReset, infoValid)\n' ...
'%%#codegen\n' ...
'persistent sr;\n' ...
'if isempty(sr), sr = false(1,4); end\n' ...
'srUse = sr;\n' ...
'if encReset, srUse = false(1,4); end   %% reset-then-advance (zero frame state)\n' ...
'in = logical(infoBit);\n' ...
's0=in; s1=srUse(1); s2=srUse(2); s3=srUse(3); s4=srUse(4);\n' ...
'g0 = xor(s0, xor(s1, xor(s2, s4)));   %% poly 35 oct = 11101\n' ...
'g1 = xor(s0, xor(s3, s4));            %% poly 23 oct = 10011\n' ...
'codedPair = [g0; g1];\n' ...
'%% state update: advance ONLY on infoValid, else HOLD (anti-zero-stuff gate)\n' ...
'if infoValid\n' ...
'  sr = [in, srUse(1:3)];\n' ...
'else\n' ...
'  sr = srUse;\n' ...
'end\n']);
end

function src = fecTxInterleaveK5_src(CODED, COLS, ROWS, fillLit, useRam)
% useRam (f1536): store the ping-pong banks as ufix1 (fi(.,0,1,0)) and match the
% RAM read/write ports to it, so MapPersistentVarsToRAM does not fail "read and
% write data types do not agree for RAM block". dataOut (block OUTPUT) stays
% boolean (interface unchanged) -- the RAM read is cast boolean via logical(),
% the write is cast ufix1 via fi(). Values are IDENTICAL (0/1). k5
% (useRam=false) keeps boolean banks -> byte-identical HDL.
if nargin < 5, useRam = false; end
if useRam
    bInit = 'fi(zeros(1,%d),0,1,0)';         % bank init (contains one %%d)
    vInit = 'fi(0,0,1,0)';                    % v0/v1 write-local init (ufix1)
    rdA   = 'logical(ramA(double(perm)+1))'; % read bank A -> boolean dataOut
    rdB   = 'logical(ramB(double(perm)+1))';
    wCast = 'fi(double(%s),0,1,0)';          % write-bit cast (%%s = expr)
else
    bInit = 'false(1,%d)';
    vInit = 'false';
    rdA   = 'ramA(double(perm)+1)';
    rdB   = 'ramB(double(perm)+1)';
    wCast = '(%s)';
end
w0expr = sprintf(wCast, 'codedPair(1)~=0');
w1expr = sprintf(wCast, 'codedPair(2)~=0');
% Ping-pong 136x16 block interleaver + PN9 filler (fec_dut fecTxInterleave
% scheduling, K5 geometry + the T8/6bcaa62 filler): WRITE the current
% frame's encoder pairs (2 bits per infoValid beat, row-linear) into the
% write bank; READ the PREVIOUS frame's CODED bits from the other bank with
% the legacy perm = r*COLS + c (r=mod(beat,ROWS), c=floor(beat/ROWS)) on
% beats 0..CODED-1; beats CODED..PAYLOAD-1 emit the 64-bit PN9 FILLER
% literal (x^9+x^5+1, seed all-ones -- golden_k5.mat payload tail; the
% 64-ones filler's DC dwell was notched by the TX LOL tracking cal). Read
% lags write by one frame => no read-before-write hazard, per-frame
% self-contained. Sync-semantics compliant (locals, reads before writes,
% persist last).
src = sprintf([ ...
'function dataOut = fecTxInterleaveK5(codedPair, infoValid, beatIdx, frameValid, frameStart)\n' ...
'%%#codegen\n' ...
'persistent ramA ramB rdBank wptr rrow rcol;\n' ...
'CODED=uint16(%d); COLS=uint16(%d); ROWS=uint16(%d);\n' ...
'FILL = logical([%s]);   %% 64-bit PN9 filler (T8 fix 6bcaa62)\n' ...
'if isempty(ramA), ramA=' bInit '; ramB=' bInit '; rdBank=false; wptr=uint16(0); rrow=uint16(0); rcol=uint16(0); end\n' ...
'rb=rdBank; w=wptr; rr=rrow; cc=rcol;\n' ...
'dataOut=false;\n' ...
'wr0=uint16(0); wr1=uint16(0); v0=' vInit '; v1=' vInit '; doW0=false; doW1=false;\n' ...
'if frameValid\n' ...
'  if frameStart, w=uint16(0); rb=~rb; end\n' ...
'  %% ---- READ side (previous frame, opposite bank), legacy perm r*COLS+c ----\n' ...
'  %% divisionless read address: rr (row 0..ROWS-1) / cc (col 0..COLS-1) are\n' ...
'  %% incremental counters, reset on beatIdx==0, advancing +1 row with col carry\n' ...
'  %% per in-range beat -- replaces the old per-beat divide-by-ROWS. No divide.\n' ...
'  if beatIdx < CODED\n' ...
'    %% precondition: bit-exactness requires a contiguous beatIdx hitting 0 once per\n' ...
'    %% frame to re-seed the row/col counters (the old stateless per-beat address\n' ...
'    %% arithmetic derived the address from beatIdx alone and needed no such reset).\n' ...
'    if beatIdx == 0, rr = uint16(0); cc = uint16(0); end\n' ...
'    perm = rr*COLS + cc;\n' ...
'    if perm < CODED\n' ...
'      if rb, dataOut = ' rdB '; else, dataOut = ' rdA '; end\n' ...
'    end\n' ...
'    rr = rr + uint16(1);\n' ...
'    if rr == ROWS, rr = uint16(0); cc = cc + uint16(1); end\n' ...
'  else\n' ...
'    dataOut = FILL(double(beatIdx-CODED)+1);   %% PN9 filler, beats CODED..2239\n' ...
'  end\n' ...
'  %% ---- WRITE side: two coded bits per encoder-advance beat ----\n' ...
'  if infoValid\n' ...
'    if w < CODED, wr0=w; v0=' w0expr '; doW0=true; w=w+uint16(1); end\n' ...
'    if w < CODED, wr1=w; v1=' w1expr '; doW1=true; w=w+uint16(1); end\n' ...
'  end\n' ...
'end\n' ...
'%% ---- persist state last (write bank = opposite of read bank) ----\n' ...
'if doW0\n' ...
'  if rb, ramA(double(wr0)+1)=v0; else, ramB(double(wr0)+1)=v0; end\n' ...
'end\n' ...
'if doW1\n' ...
'  if rb, ramA(double(wr1)+1)=v1; else, ramB(double(wr1)+1)=v1; end\n' ...
'end\n' ...
'rdBank=rb; wptr=w; rrow=rr; rcol=cc;\n'], CODED, COLS, ROWS, fillLit, CODED, CODED);
end
