function msggen_rom_overlay_k5(sys, loop)
% msggen_rom_overlay_k5 -- jupiter_240k5 Tx bit source: replace the in-FPGA
% Message Generator ROM so it emits the PRE-CODED K=5 packet from
% /mnt/onetb/scratch/qpsk_variants/k5_240/rom_words_70_k5.txt on the
% CONTINUOUS in-FPGA generator path. Same proven mechanism as donor
% jupiter_msggenrom/msggen_rom_overlay.m (packed 70 x uint32 literal; a
% 2240-element inline logical literal crashes the Stateflow compiler), only
% the ROM words differ (K=5 [35 23] contract, see contract/PACKET_K5.txt:
% interleaved 2176 coded bits [msg 120 + PN 964 + 4 tail, ROWS=136 COLS=16]
% + 64 ones filler = 2240 bits). NO in-FPGA FEC encoder (packet pre-coded),
% NO PRBS keep-alive, scrambler bypassed separately (fec_remove_scrambler).
%
% The stock chart control flow (indexCount 0..2239, start@0, stop@2239,
% valid=1, msgCount housekeeping) is kept verbatim; only the ROM changes.
% Build-only; repo master and donor kits untouched.

cfg = frame_config_k5();   % single source of truth for frame geometry
% ROM word file is per-frame: rom_words_<RomWords32>_<Frame>.txt
%   k5    -> rom_words_70_k5.txt      f1536 -> rom_words_770_f1536.txt
k5dir = fullfile(fileparts(fileparts(mfilename('fullpath'))),'contract');
wordsFile = fullfile(k5dir, sprintf('rom_words_%d_%s.txt', cfg.RomWords32, cfg.Frame));
romLiteral = strtrim(fileread(wordsFile));
assert(startsWith(romLiteral, 'uint32([') && endsWith(romLiteral, '])'), ...
    'rom words file is not a single-line uint32([...]) literal');
words = eval(romLiteral); %#ok<EVLDIR> % trusted kit artifact (packet_<frame>.m output)
assert(isa(words, 'uint32') && numel(words) == cfg.RomWords32, ...
    'expected %d uint32 words, got %d %s', cfg.RomWords32, numel(words), class(words));
% word[0] pin: k5 keeps its hand-verified literal (0x47CE0176); other frames
% cross-check the ROM txt against their golden .mat (catches wrong/stale file).
if strcmp(cfg.Frame, 'k5')
    assert(words(1) == uint32(1204691830), ...
        'word[0]=%u != 1204691830 (0x47CE0176) -- wrong ROM file?', words(1));
else
    Gm = load(fullfile(k5dir, sprintf('golden_%s.mat', cfg.Frame)), 'words');
    assert(words(1) == Gm.words(1), ...
        'word[0]=%u != golden %s words(1)=%u -- wrong/stale ROM file?', ...
        words(1), cfg.Frame, Gm.words(1));
end

% New chart Script: identical control/flow to the stock msggen, EXCEPT the ROM
% lookup uses the packed 70-word table + bit extraction (msgbitsLen=2240 so
% indexCount<msgbitsLen covers the whole payload). Stock message ROM removed.
% NOTE: this kit's stock chart signature is msggen(enable, reset) with
% fullMessageLen = uint32(2240-1) HARDCODED (the fec_jupiter_rxfix model,
% slx bccd5303, differs from the jupiter_msggenrom model whose chart takes a
% dataBitsPerPacket parameter). Keep the 2-arg signature -- adding a third
% symbol creates a grounded double input and a checkhdl "Double type" error.
newScript = strjoin({ ...
'function [out, start, stop, valid, count_out, msg_count_out] = msggen(enable, reset)' ...
'' ...
'persistent indexCount;' ...
'persistent toggle;' ...
'persistent msgCount;' ...
'persistent msgCountAll;' ...
'persistent msgCountBitIndex;' ...
'' ...
'if isempty(indexCount) || isempty(toggle) || isempty(msgCount) || isempty(msgCountBitIndex) || isempty(msgCountAll)' ...
'    indexCount = uint32(0);' ...
'    msgCount = uint32(1);' ...
'    msgCountAll = uint32(1);' ...
'    msgCountBitIndex = uint8(0);' ...
'    toggle = false;' ...
'end' ...
'' ...
['%% Constants -- FIXED pre-coded K=5 packet ROM (' sprintf('rom_words_%d_%s.txt',cfg.RomWords32,cfg.Frame) ', ' num2str(cfg.PayloadBits) ' bits,'] ...
['%% word w = bits[32w..32w+31] MSB-first). Stored as ' num2str(cfg.RomWords32) ' x uint32 packed words'] ...
'%% (a large inline logical literal crashes the Stateflow compiler),' ...
['%% unpacked into the ' num2str(cfg.PayloadBits) '-element msgbits logical ROM and indexed with the'] ...
'%% STOCK msgbits(indexCount+1) pattern. Replaces the stock 120-bit message ROM.' ...
['%% Content: K=5 [35 23] rate-1/2 coded info(' num2str(cfg.InfoBits) ')+tail(' num2str(cfg.TailBits) ') -> ' num2str(cfg.CodedBits) ' bits,'] ...
['%% ' num2str(cfg.InterleaveRows) 'x' num2str(cfg.InterleaveCols) ' block-interleaved (perm r*' num2str(cfg.InterleaveCols) '+c), + ' num2str(cfg.FillerBits) '-bit PN9 filler. The K=5 Rx'] ...
['%% deint(perm c*' num2str(cfg.InterleaveRows) '+r) + Viterbi(TB=25) recovers the 120-bit BIST message.'] ...
['romWords = ' romLiteral ';'] ...
['msgbits = false(1,' num2str(cfg.PayloadBits) ');'] ...
['for w = 0:' num2str(cfg.RomWords32-1)] ...
'    wv = romWords(w+1);' ...
'    for bb = 0:31' ...
'        msgbits(w*32 + bb + 1) = bitget(wv, 32 - bb) ~= uint32(0);' ...
'    end' ...
'end' ...
'msgbitsLen = uint32(length(msgbits));' ...
'' ...
['fullMessageLen = uint32(' num2str(cfg.PayloadBits) '-1); %% Need the -1 to eat the feedback delay (stock hardcoded value in this model)'] ...
'' ...
'%% Logic' ...
'if enable && ~reset' ...
'    %% Set out data' ...
'    if indexCount < msgbitsLen %% Emit the fixed pre-coded packet bit (unpacked ROM)' ...
'        out = msgbits(indexCount + 1);' ...
'        msgCountBitIndex = uint8(0);' ...
'    else %% beyond the ROM (should not occur: msgbitsLen==dataBitsPerPacket)' ...
'        out = false;' ...
'        msgCountBitIndex = uint8(0);' ...
'    end' ...
'' ...
'    %% Flags' ...
'    start = indexCount == uint32(0);' ...
'    stop = indexCount == fullMessageLen;' ...
'    valid = true;' ...
'' ...
'    %% Counters' ...
'    if fullMessageLen == indexCount' ...
'        if msgCount >= 9' ...
'            msgCount = uint32(1);' ...
'        else' ...
'            msgCount = msgCount +  1;' ...
'            msgCountAll = msgCountAll + 1;' ...
'        end' ...
'    end' ...
'    if indexCount <= fullMessageLen' ...
'        indexCount = indexCount + 1;' ...
'    end' ...
'' ...
'else %% Enable == false' ...
'' ...
'    if reset' ...
'        indexCount = uint32(0);' ...
'        msgCountBitIndex = uint8(0);' ...
'        toggle = false;' ...
'    end' ...
'    out = false;' ...
'    start = false;' ...
'    stop = false;' ...
'    valid = false;' ...
'end' ...
'' ...
'if isempty(indexCount)' ...
'    count_out = uint32(0);' ...
'else' ...
'    count_out = indexCount;' ...
'end' ...
'' ...
'msg_count_out = msgCountAll;' ...
}, newline);

% Locate the Message Generator MATLAB Function chart in the loaded composite model.
chartPath = [loop '/Transmitter/Input Data/Message Generator/MATLAB Function'];
ch = sfroot().find('-isa','Stateflow.EMChart','Path',chartPath);
if isempty(ch)
    allch = sfroot().find('-isa','Stateflow.EMChart');
    for i=1:numel(allch)
        if contains(allch(i).Path, [loop '/Transmitter/Input Data/Message Generator'])
            ch = allch(i); break;
        end
    end
end
assert(~isempty(ch), 'Message Generator chart not found at %s', chartPath);
ch = ch(1);

oldScript = ch.Script;
if contains(oldScript, romLiteral)
    fprintf('msggen_rom_overlay_k5: K5 ROM already in chart -- skipping\n');
    return;
end
assert(contains(oldScript,'ADI Hello World'), ...
    'stock chart does not contain the ADI Hello World ROM -- unexpected base');

ch.Script = newScript;

% Verify the swap took: packed ROM literal present, stock identifiers gone.
assert(contains(ch.Script, romLiteral), 'ROM literal not present after set');
assert(~contains(ch.Script, 'dec2bin'), 'dec2bin still present after set');
assert(~contains(ch.Script, 'ADI Hello World'), 'ADI Hello World still present after set');

fprintf('=== MSGGEN ROM OVERLAY (K5) APPLIED (packed %dxuint32, frame=%s) ===\n', ...
    cfg.RomWords32, cfg.Frame);
fprintf('chart: %s\n', ch.Path);
fprintf('ROM source: %s\n', wordsFile);
fprintf('romWords(1..2) = %u %u  (word0 = 0x%08X; literal %d chars)\n', ...
    words(1), words(2), words(1), numel(romLiteral));
fprintf('msgbits now the %d-bit pre-coded K=5 packet; stock message ROM removed.\n', ...
    cfg.PayloadBits);
end
