function [word, avail, ready, wordFirst, state] = qpskByteWordBufferSkid(state, dataIn, validIn, popReq, firstIn)
% qpskByteWordBufferSkid -- pipeline-consistent skid word FIFO between the
% AXI-Stream byte DMA and the Transmitter's bit shifter (f1536 TX-ingress
% fix, TXMUX task 2026-07-25). Replaces qpskByteWordBuffer on the f1536
% byte-TX path (cfg-gated in byte_plumbing_overlay_k5.m; k5 HDL untouched).
%
% DEFECT FIXED (root cause of the R0 f1536 byte-plane failure, reproduced on
% the shipped netlist by rtl_sim/sim_byte_mm2s.cpp): HDL Coder delay
% balancing inserts a register chain on the byte_ready OUTPUT path
% (netlist: readyNext -> ReadyDly -> delayMatch19_reg[0..3] -> pin), so the
% tready the axi_dmac sees is the FIFO's internal ready delayed by
% SKID_READY_LAG beats. The legacy 2-deep buffer gates its push on the
% INTERNAL (fresh) ready: during a burst into an empty FIFO (idle-exit =
% the qpsk_tun arm case) the pin stays high SKID_READY_LAG beats after the
% FIFO fills, the dmac legally pushes that many beats, and the push guard
% (count < 2) silently DROPS them. The frame's head words are eaten; the
% downstream shifter then free-runs with a PERMANENT word-phase offset
% (silicon: +4 words = the "fixed PN9 vector" / 32-byte shift).
%
% FIX: gate the push on the SAME view of ready the source acts on -- the
% internal ready delayed by SKID_READY_LAG (a replica of the generated
% ReadyDly+delayMatch chain). Source-accept and FIFO-store are then
% identical sets by construction: no drops, no duplicates, at ANY burst
% rate. DEPTH/MARGIN guarantee space for the in-flight beats: pin high at
% t implies count(t-LAG) <= DEPTH-MARGIN, and at most LAG pushes can land
% since, so count < DEPTH always (the count<DEPTH term can never refuse an
% accepted beat; it remains as structural defense only).
%
% CONTRACT PIN (verified by the netlist gate): SKID_READY_LAG must equal
% the generated byte_ready output pipeline depth MINUS the one ReadyDly
% beat already accounted by the entry-ready semantics (shipped f1536
% netlist: ReadyDly + delayMatch chain => pin = entry-ready delayed by
% qpskByteSkidLag()).
% rtl_sim/run_mm2s_gate.sh empirically enforces this end-to-end: any
% codegen change to the balanced delay makes the adversarial gate fail
% with drops (offset) or duplicates.
%
% Interface identical to qpskByteWordBuffer: word/avail/wordFirst expose
% the head entry; popReq && avail consumes it; firstIn (in-band first-word
% marker) is stored alongside each word.

SKID_READY_LAG = qpskByteSkidLag();   % pinned codegen artifact, see that file
DEPTH  = uint8(16);
MARGIN = uint8(10);   % ready threshold = DEPTH-MARGIN = 6; worst fill 6+lag(8) = 14 < 16

if nargin == 0
    word = struct('buf', zeros(16,1,'uint64'), ...
                  'bufF', false(16,1), 'count', uint8(0), ...
                  'rd', uint8(0), 'readyReg', true, ...
                  'readyHist', false(1,8));   % matches the delayMatch chain's reset-0 (len 8 >= any lag)

    return
end

ready     = state.readyReg;
avail     = state.count > 0;
word      = state.buf(state.rd + 1);
wordFirst = state.bufF(state.rd + 1);

% push on the PIN-consistent (delayed) ready view -- the exact signal the
% dmac accepted the beat against; count<DEPTH is defense-in-depth only.
readyAtPin = state.readyHist(SKID_READY_LAG);
push = logical(validIn) && readyAtPin && state.count < DEPTH;
popp = logical(popReq) && avail;

if push
    wr = bitand(state.rd + state.count, uint8(15));
    state.buf(wr + 1)  = uint64(dataIn);
    state.bufF(wr + 1) = logical(firstIn);
end
newCount = state.count + uint8(push) - uint8(popp);
if popp
    state.rd = bitand(state.rd + 1, uint8(15));
end
state.count = newCount;
state.readyHist = [state.readyReg, state.readyHist(1:7)];
state.readyReg = newCount <= (DEPTH - MARGIN);
end
