function byte_rxfifo_overlay(sys, base)
% byte_rxfifo_overlay -- elastic FIFO in the byte-rx presentation path.
%
% ROOT CAUSE (canary4 census, sessions 20260714_1803/1819): the modem decodes
% at full rate through tick episodes (CS census + fstart + rxw all agree),
% but ~3 frames/episode die between the byte-DMA offer and the host, plus a
% matching junk class from frame misalignment. The byte-rx path holds exactly
% ONE word between the serializer and the AXIS handshake ("unaccepted beats
% are simply superseded") -- a tick-induced DMA/bus stall of ~14 ms drops
% ~50 words (~3 frames) and shifts host framing.
%
% FIX: ByteRxFifo -- 64-deep {word64, last, first} circular FIFO (registers)
% between the serializer word stream and the AXIS pins. Absorbs ~19 ms of
% stall at 16 words/frame x 211.77 fps. Enqueue on serializer toggle edge;
% dequeue on accepted beat (valid && ready). Overflow counter surfaced at
% AXI 0x1B0 (must stay ZERO post-fix; nonzero = stall longer than the FIFO).
%
% Replaces ByteRxBeatGate + the direct SerWordRT/SerLastRT/SerFirstRT wiring
% to the byte_rx_* outports. Apply AFTER byte_plumbing_overlay_k5, BEFORE
% canary4 (so ByteCensus taps the FIFO's valid). Content-equivalent: the
% byte oracle gate must still PASS (word sequence unchanged; only
% presentation latency differs).

if nargin < 1 || isempty(sys),  sys  = bdroot; end
if nargin < 2 || isempty(base), base = sys;    end
loop = base;

if ~isempty(find_system(loop,'SearchDepth',1,'LookUnderMasks','all', ...
        'FollowLinks','on','Name','ByteRxFifo'))
    fprintf('byte_rxfifo_overlay: already present -- skipping\n');
    return;
end
assert(~isempty(find_system(loop,'SearchDepth',1,'LookUnderMasks','all', ...
    'FollowLinks','on','Name','ByteRxBeatGate')), ...
    'byte_rxfifo_overlay: apply after byte_plumbing_overlay_k5');

% ---- sever the old single-word presentation wiring ----
for spec = {{'SerWordRT',1,'byte_rx_data'},{'ByteRxBeatGate',1,'byte_rx_valid'}, ...
            {'SerLastRT',1,'byte_rx_last'},{'SerFirstRT',1,'byte_rx_user'}}
    srcb = spec{1}{1}; dstb = spec{1}{3};
    lh = get_param([loop '/' dstb],'LineHandles');
    if lh.Inport(1) ~= -1, delete_line(lh.Inport(1)); end
end
% BeatGate inputs (tog, ready) then the block itself
lhBG = get_param([loop '/ByteRxBeatGate'],'LineHandles');
for L = [lhBG.Inport lhBG.Outport]
    if L ~= -1, try, delete_line(L); end, end %#ok<TRYNC>
end
delete_block([loop '/ByteRxBeatGate']);

% ---- the FIFO MLFB ----
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/ByteRxFifo'], ...
    'Position',[920 1280 1030 1420]);
fifoCh = sfroot().find('-isa','Stateflow.EMChart','Path',[loop '/ByteRxFifo']);
fifoCh.Script = sprintf([ ...
'function [outWord, valid, outLast, outFirst, ovf] = byteRxFifo(word, tog, wLast, wFirst, ready)\n' ...
'%%#codegen\n' ...
'%% 64-deep elastic FIFO: enqueue on serializer toggle edge, dequeue on\n' ...
'%% accepted AXIS beat. Drop-newest + count on full (stall > ~19 ms).\n' ...
'persistent mem memFl wr rd prev ovfCnt\n' ...
'if isempty(wr)\n' ...
'    mem = zeros(64,1,''uint64''); memFl = zeros(64,1,''uint8'');\n' ...
'    wr = uint16(0); rd = uint16(0); prev = false; ovfCnt = uint32(0);\n' ...
'end\n' ...
'if logical(tog) ~= prev\n' ...
'    nxt = uint16(mod(uint32(wr) + 1, 64));\n' ...
'    if nxt == rd\n' ...
'        %% full: DROP OLDEST (advance rd) so the presented head converges\n' ...
'        %% to fresh data when unconsumed -- preserves the DMA start-sync\n' ...
'        %% contract (the old supersede semantics) while keeping 64 words\n' ...
'        %% of elasticity for transient stalls. Never deadlocks on a\n' ...
'        %% mid-frame stale head.\n' ...
'        rd = uint16(mod(uint32(rd) + 1, 64));\n' ...
'        ovfCnt = ovfCnt + uint32(1);\n' ...
'    end\n' ...
'    mem(uint32(wr)+1)   = uint64(word);\n' ...
'    memFl(uint32(wr)+1) = uint8(wLast) + uint8(2)*uint8(wFirst);\n' ...
'    wr = nxt;\n' ...
'end\n' ...
'prev = logical(tog);\n' ...
'valid = (wr ~= rd);\n' ...
'outWord  = mem(uint32(rd)+1);\n' ...
'fl = memFl(uint32(rd)+1);\n' ...
'outLast  = bitand(fl, uint8(1)) ~= uint8(0);\n' ...
'outFirst = bitand(fl, uint8(2)) ~= uint8(0);\n' ...
'if valid && logical(ready)\n' ...
'    rd = uint16(mod(uint32(rd) + 1, 64));\n' ...
'end\n' ...
'ovf = ovfCnt;\n']);
% pin port types (double-probe discipline)
for d = fifoCh.getChildren()'
    if ~isa(d,'Stateflow.Data'), continue; end
    switch d.Name
        case 'word',    d.DataType = 'uint64';
        case 'outWord', d.DataType = 'uint64';
        case 'ovf',     d.DataType = 'uint32';
        case {'tog','wLast','wFirst','ready','valid','outLast','outFirst'}
            d.DataType = 'boolean';
    end
end
% REGISTERS, not RAM: MapPersistentVarsToRAM adds a read cycle that
% misaligns outWord against valid at the netlist level (S1B FAIL
% 2026-07-14: cap_out golden but zero golden frames in the byte stream).
% 64x72 flops + 64:1 mux at 30.72 MHz is trivially safe and still absorbs
% ~19 ms of DMA stall (~10x the observed live stalls).

% ---- wire it ----
add_line(loop, 'SerWordRT/1',      'ByteRxFifo/1', 'autorouting','on');
add_line(loop, 'SerTogRT/1',       'ByteRxFifo/2', 'autorouting','on');
add_line(loop, 'SerLastRT/1',      'ByteRxFifo/3', 'autorouting','on');
add_line(loop, 'SerFirstRT/1',     'ByteRxFifo/4', 'autorouting','on');
add_line(loop, 'byte_rx_ready/1',  'ByteRxFifo/5', 'autorouting','on');
add_line(loop, 'ByteRxFifo/1', 'byte_rx_data/1',  'autorouting','on');
add_line(loop, 'ByteRxFifo/2', 'byte_rx_valid/1', 'autorouting','on');
add_line(loop, 'ByteRxFifo/3', 'byte_rx_last/1',  'autorouting','on');
add_line(loop, 'ByteRxFifo/4', 'byte_rx_user/1',  'autorouting','on');

% ---- surface the overflow counter at composite level (AXI 0x1B0) ----
nB = numel(find_system(loop,'SearchDepth',1,'LookUnderMasks','all','BlockType','Outport'));
add_block('built-in/Outport',[loop '/byte_fifo_ovf'],'Port',num2str(nB+1), ...
    'Position',[1080 1440 1110 1456]);
add_line(loop, 'ByteRxFifo/5', 'byte_fifo_ovf/1', 'autorouting','on');

fprintf('byte_rxfifo_overlay: DONE (64-deep elastic byte-rx FIFO; ovf -> 0x1B0)\n');
end
