function byte_plumbing_overlay_k5(sys, loop)
% byte_plumbing_overlay_k5 -- sections (1d)/(1e) of the donor
% variant_pre_composite_bytetx.m (Host->Tx byte ingress + Rx->Host byte
% egress + the hdlworkflow RD/port-mapping patch), ported to the
% jupiter_240k5_byte composite, with TWO deliberate deltas from the donor:
%
%   DELTA 1: ByteSerializer WORDS_PER_PACKET = 16 (donor: 35). The K5
%     recovered stream is the DECODED 1084 info bits/frame (not the 2240-bit
%     raw payload), so the serializer delivers the first 16 x 64 = 1024 info
%     bits = 128 B/frame; the trailing 60 info bits of each frame are
%     discarded (the serializer's start-reset drops the partial word).
%   DELTA 2: tx_data_source maps to AXI x"158", NOT the donor's x"11C" --
%     0x11C is this kit's dbg_sentinel (fec_counters_overlay) and would
%     COLLIDE. 0x150/0x154 are the taps_240k5 registers, so 0x158 is the
%     next free slot.
%
% Everything else is donor-verbatim: 30.72 MHz AXIS-side ByteWordBuffer
% (qpskByteWordBuffer, 2-deep, registered tready via ReadyDly IC=1), word/
% avail/first RateTransitions into the Transmitter's 15.36 MHz rail (T8 rate fix: Rsym=1.92e6, sps8),
% extWordPop toggle edge-detected back at 30.72 MHz, tx_data_source ->
% boolean -> extBitSel; Rx mirror: ByteSerializer (qpskByteSerializer) at
% 15.36 MHz (raised rail) on the recBit/recBitValid/recStart taps, toggle + BeatGate
% valid-until-accepted at 30.72 MHz. ReferenceDesign retargeted at
% AnalogDevices.jupiter.plugin_rd_rxtx_byte() (name read from the plugin);
% ReferenceDesignParameter (incl. multiple=2) untouched.
%
% Port numbers are INTROSPECTED (this composite already has host inports
% 7..10 + skip_count and the fec/taps outports), not donor-hardcoded.
% Idempotent (model marker = ByteWordBuffer; workflow marker = the
% 'composite-byte mappings' comment). Does NOT save.

if nargin < 1 || isempty(sys), sys = bdroot; end
if nargin < 2 || isempty(loop), loop = [sys '/TxRxComposite']; end
cfg = frame_config_k5();      % single source of truth for frame geometry
WPP = cfg.WordsPerPacketRx;   % DELTA 1 (was literal 16)
TXDS_ADDR = 'x"158"';% DELTA 2
% f1536 TX-ingress fix (TXMUX task 2026-07-25), cfg-gated so the k5
% generated HDL stays byte-identical (G0): qpskByteWordBufferSkid (depth-16,
% pin-consistent delayed-ready push gate) replaces the 2-deep buffer whose
% push gate used the INTERNAL ready while HDL Coder delay balancing made the
% PIN tready 4 beats staler -- idle-exit bursts dropped the accepted head
% words (the silicon +4-word permanent offset). The W0x5 egress fix lives in
% byte_rxfifo_overlay.m (the shipped egress; the BeatGate below is replaced
% by it in assemble phase 2.16b).
isF1536 = strcmp(cfg.Frame, 'f1536');
if isF1536
    bwbFcn = 'qpskByteWordBufferSkid';
else
    bwbFcn = 'qpskByteWordBuffer';
end

if isempty(find_system(loop,'SearchDepth',1,'LookUnderMasks','all', ...
        'FollowLinks','on','Name','ByteWordBuffer'))

% --- (0) preconditions + introspected port bases ---
tx = [loop '/Transmitter'];
txph = get_param(tx,'PortHandles');
assert(numel(txph.Inport)==8 && numel(txph.Outport)==9, ...
    'Transmitter ports %d/%d (expected 8/9) -- run byte_tx_overlay_k5 first', ...
    numel(txph.Inport), numel(txph.Outport));
rx = [loop '/Receiver'];
recP = struct();
for nm = {'recBit','recBitValid','recStart'}
    b = find_system(rx,'SearchDepth',1,'LookUnderMasks','all','FollowLinks','on', ...
        'BlockType','Outport','Name',nm{1});
    assert(~isempty(b), '%s tap missing -- run byte_rx_overlay_k5 first', nm{1});
    recP.(nm{1}) = str2double(get_param(b{1},'Port'));
end
inports  = find_system(loop,'SearchDepth',1,'BlockType','Inport');
outports = find_system(loop,'SearchDepth',1,'BlockType','Outport');
nIn = numel(inports); nOut = numel(outports);
assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Inport','Name','skip_count')), ...
    'skip_count inport missing -- byte plumbing must run after the fec overlays');
fprintf('byte_plumbing_overlay_k5: composite has %d inports / %d outports; Receiver taps at %d/%d/%d\n', ...
    nIn, nOut, recP.recBit, recP.recBitValid, recP.recStart);

% --- (1d) host->FPGA byte-transfer path ---
in_byte = { 'byte_data','uint64','1/30.72e6'; 'byte_valid','boolean','1/30.72e6'; ...
            'tx_data_source','uint32','1/15.36e6'; 'byte_first','boolean','1/30.72e6' };
for k = 1:size(in_byte,1)
    blk = [loop '/' in_byte{k,1}];
    add_block('built-in/Inport', blk, 'Port', num2str(nIn+k), ...
        'Position', [40 1020+40*k 70 1040+40*k]);
    set_param(blk, 'OutDataTypeStr', in_byte{k,2}, 'SampleTime', in_byte{k,3});
end
add_block('built-in/Outport', [loop '/byte_ready'], 'Port', num2str(nOut+1), ...
    'Position', [800 1040 830 1060]);

% extWordPop toggle: 15.36M -> 30.72M (slow->fast RT is safe), then edge-detect
add_block('built-in/RateTransition', [loop '/PopRT'], ...
    'OutPortSampleTime','1/30.72e6', 'Position',[240 1180 280 1200]);
add_line(loop, 'Transmitter/9', 'PopRT/1', 'autorouting','on');
add_block('built-in/Delay', [loop '/PopDly'], 'DelayLength','1', ...
    'Position',[300 1210 340 1230]);
add_block('built-in/Logic', [loop '/PopEdge'], 'Operator','XOR', 'Inputs','2', ...
    'Position',[360 1180 400 1210]);
add_line(loop, 'PopRT/1',  'PopDly/1',  'autorouting','on');
add_line(loop, 'PopRT/1',  'PopEdge/1', 'autorouting','on');
add_line(loop, 'PopDly/1', 'PopEdge/2', 'autorouting','on');

% ByteWordBuffer @30.72M -- MATLAB Function wrapping qpskByteWordBuffer (the
% unit-tested single source of truth, copied verbatim into this kit) with
% persistent state. The block emits readyNext (= state.readyReg AFTER the
% update); the explicit Delay below is the AXIS-mandated tready register, so
% byte_ready == the function's own registered ready, while keeping the
% byte_valid->byte_ready path free of direct feedthrough.
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [loop '/ByteWordBuffer'], 'Position',[430 1080 540 1200]);
bwbCh = sfroot().find('-isa','Stateflow.EMChart','Path',[loop '/ByteWordBuffer']);
assert(~isempty(bwbCh), 'ByteWordBuffer chart not found');
bwbCh.Script = strrep(sprintf([ ...
'function [word, avail, readyNext, wordFirst] = byteWordBufferBlk(dataIn, validIn, popReq, firstIn)\n' ...
'%% Block wrapper around BWB_FCN (unit-tested single source of\n' ...
'%% truth); persistent state only. readyNext = the post-update registered\n' ...
'%% ready; an external Delay (IC=1) turns it back into the AXIS tready.\n' ...
'%% firstIn/wordFirst carry the in-band first-word marker alongside data.\n' ...
'persistent state\n' ...
'if isempty(state)\n' ...
'    state = BWB_FCN();\n' ...
'end\n' ...
'[word, avail, ~, wordFirst, state] = BWB_FCN(state, uint64(dataIn), ...\n' ...
'    logical(validIn), logical(popReq), logical(firstIn));\n' ...
'readyNext = state.readyReg;\n']), 'BWB_FCN', bwbFcn);
add_line(loop, 'byte_data/1',  'ByteWordBuffer/1', 'autorouting','on');
add_line(loop, 'byte_valid/1', 'ByteWordBuffer/2', 'autorouting','on');
add_line(loop, 'PopEdge/1',    'ByteWordBuffer/3', 'autorouting','on');
add_line(loop, 'byte_first/1', 'ByteWordBuffer/4', 'autorouting','on');
add_block('built-in/Delay', [loop '/ReadyDly'], 'DelayLength','1', ...
    'InitialCondition','1', 'Position',[600 1080 640 1100]);
add_line(loop, 'ByteWordBuffer/3', 'ReadyDly/1',   'autorouting','on');
add_line(loop, 'ReadyDly/1',       'byte_ready/1', 'autorouting','on');

% head word/avail/first: 30.72M -> 15.36M into the Transmitter byte ports
add_block('built-in/RateTransition', [loop '/WordRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[600 1120 640 1140]);
add_block('built-in/RateTransition', [loop '/AvailRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[600 1160 640 1180]);
add_block('built-in/RateTransition', [loop '/FirstRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[600 1200 640 1220]);
add_line(loop, 'ByteWordBuffer/1', 'WordRT/1',  'autorouting','on');
add_line(loop, 'ByteWordBuffer/2', 'AvailRT/1', 'autorouting','on');
add_line(loop, 'ByteWordBuffer/4', 'FirstRT/1', 'autorouting','on');
add_line(loop, 'WordRT/1',  'Transmitter/5', 'autorouting','on');
add_line(loop, 'AvailRT/1', 'Transmitter/6', 'autorouting','on');
add_line(loop, 'FirstRT/1', 'Transmitter/8', 'autorouting','on');

% tx_data_source (uint32 AXI reg) -> boolean (u ~= 0) -> 15.36M -> extBitSel
add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [loop '/ByteSel'], 'relop','~=', 'const','0', 'Position',[240 1100 280 1130]);
add_block('built-in/RateTransition', [loop '/SelRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[300 1100 340 1130]);
add_line(loop, 'tx_data_source/1', 'ByteSel/1', 'autorouting','on');
add_line(loop, 'ByteSel/1', 'SelRT/1', 'autorouting','on');
add_line(loop, 'SelRT/1', 'Transmitter/7', 'autorouting','on');

% --- (1e) FPGA->host byte-RX path (Rx mirror of 1d) ---
add_block('built-in/Inport', [loop '/byte_rx_ready'], 'Port', num2str(nIn+5), ...
    'Position', [40 1280 70 1300]);
set_param([loop '/byte_rx_ready'], 'OutDataTypeStr','boolean', ...
    'SampleTime','1/30.72e6');
out_byte_rx = { 'byte_rx_data', nOut+2; 'byte_rx_valid', nOut+3; ...
                'byte_rx_last', nOut+4; 'byte_rx_user', nOut+5 };
for k = 1:size(out_byte_rx,1)
    add_block('built-in/Outport', [loop '/' out_byte_rx{k,1}], ...
        'Port', num2str(out_byte_rx{k,2}), 'Position', [980 1240+40*k 1010 1260+40*k]);
end

% ready: 30.72M -> 15.36M (fast->slow RT; the DMA tready is a level)
add_block('built-in/RateTransition', [loop '/RxReadyRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[160 1280 200 1300]);
add_line(loop, 'byte_rx_ready/1', 'RxReadyRT/1', 'autorouting','on');

% ByteSerializer @15.36M -- DELTA 1: WORDS_PER_PACKET = 16 (128 B of the 1084
% decoded info bits per frame; trailing 60 bits discarded at the start-reset)
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [loop '/ByteSerializer'], 'Position',[700 1240 820 1360]);
bsCh = sfroot().find('-isa','Stateflow.EMChart','Path',[loop '/ByteSerializer']);
assert(~isempty(bsCh), 'ByteSerializer chart not found');
bsCh.Script = strrep(sprintf([ ...
'function [word, wordTog, wordLast, wordFirst] = byteSerializerBlk(bitIn, bitValid, start, ready)\n' ...
'%% Block wrapper around qpskByteSerializer (unit-tested single source of\n' ...
'%% truth); persistent state only. word/wordLast are HELD stable between\n' ...
'%% emissions; wordTog flips once per emitted word so the slow->fast rate\n' ...
'%% crossing cannot drop or repeat it -- the 30.72M BeatGate edge-detects\n' ...
'%% it into exactly one accepted AXIS beat. Dropped words (ready low at\n' ...
'%% completion) do not toggle: drop means NO beat, never a stall.\n' ...
'%% K5 kit: WORDS_PER_PACKET words/frame = the first 64*WORDS_PER_PACKET of\n' ...
'%% the 1084 decoded info bits; the trailing 60 are dropped by start-reset.\n' ...
'persistent state tog heldWord heldLast heldFirst firstNext\n' ...
'if isempty(state)\n' ...
'    state = qpskByteSerializer();\n' ...
'    tog = false; heldWord = uint64(0); heldLast = false;\n' ...
'    heldFirst = true; firstNext = true;\n' ...
'end\n' ...
'%% presentation is decoupled from acceptance (ADI S2MM source style):\n' ...
'%% the offered beat must refresh on EVERY completed word or the DMA''s\n' ...
'%% SYNC_TRANSFER_START gate can wait forever on a frozen user flag /\n' ...
'%% accept a stale word. ready at the pin only decides acceptance, so\n' ...
'%% the core serializer runs with ready=true and unaccepted beats are\n' ...
'%% simply superseded.\n' ...
'[w, wv, wl, ~, state] = qpskByteSerializer(state, logical(bitIn), ...\n' ...
'    logical(bitValid), logical(start), true, uint16(WORDS_PER_PACKET));\n' ...
'if wv\n' ...
'    heldWord = w; heldLast = logical(wl); tog = ~tog;\n' ...
'    heldFirst = firstNext; firstNext = logical(wl);\n' ...
'end\n' ...
'word = heldWord; wordTog = tog; wordLast = heldLast; wordFirst = heldFirst;\n']), ...
    'WORDS_PER_PACKET', num2str(WPP));
add_line(loop, sprintf('Receiver/%d', recP.recBit),      'ByteSerializer/1', 'autorouting','on');
add_line(loop, sprintf('Receiver/%d', recP.recBitValid), 'ByteSerializer/2', 'autorouting','on');
add_line(loop, sprintf('Receiver/%d', recP.recStart),    'ByteSerializer/3', 'autorouting','on');
add_line(loop, 'RxReadyRT/1', 'ByteSerializer/4', 'autorouting','on');

% word/toggle/last/first: 15.36M -> 30.72M (slow->fast RT is safe)
add_block('built-in/RateTransition', [loop '/SerWordRT'], ...
    'OutPortSampleTime','1/30.72e6', 'Position',[860 1280 900 1300]);
add_block('built-in/RateTransition', [loop '/SerTogRT'], ...
    'OutPortSampleTime','1/30.72e6', 'Position',[860 1320 900 1340]);
add_block('built-in/RateTransition', [loop '/SerLastRT'], ...
    'OutPortSampleTime','1/30.72e6', 'Position',[860 1360 900 1380]);
add_block('built-in/RateTransition', [loop '/SerFirstRT'], ...
    'OutPortSampleTime','1/30.72e6', 'Position',[860 1400 900 1420]);
add_line(loop, 'ByteSerializer/1', 'SerWordRT/1', 'autorouting','on');
add_line(loop, 'ByteSerializer/2', 'SerTogRT/1',  'autorouting','on');
add_line(loop, 'ByteSerializer/3', 'SerLastRT/1', 'autorouting','on');
add_line(loop, 'ByteSerializer/4', 'SerFirstRT/1', 'autorouting','on');

% BeatGate @30.72M: toggle edge -> pend; hold valid until accepted beat
% (legacy k5 gate -- byte-identical HDL, G0)
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [loop '/ByteRxBeatGate'], 'Position',[920 1320 1000 1380]);
bgCh = sfroot().find('-isa','Stateflow.EMChart','Path',[loop '/ByteRxBeatGate']);
assert(~isempty(bgCh), 'ByteRxBeatGate chart not found');
bgCh.Script = sprintf([ ...
'function valid = byteRxBeatGate(tog, ready)\n' ...
'%% one ACCEPTED AXIS beat per serialized word: a toggle edge sets\n' ...
'%% pending; valid stays asserted until the beat is accepted\n' ...
'%% (valid && ready), then clears. Robust to momentary tready dips.\n' ...
'persistent prev pending\n' ...
'if isempty(prev)\n' ...
'    prev = false; pending = false;\n' ...
'end\n' ...
'if logical(tog) ~= prev\n' ...
'    pending = true;\n' ...
'end\n' ...
'prev = logical(tog);\n' ...
'valid = pending;\n' ...
'if pending && logical(ready)\n' ...
'    pending = false;\n' ...
'end\n']);
add_line(loop, 'SerTogRT/1',      'ByteRxBeatGate/1', 'autorouting','on');
add_line(loop, 'byte_rx_ready/1', 'ByteRxBeatGate/2', 'autorouting','on');

add_line(loop, 'SerWordRT/1',      'byte_rx_data/1',  'autorouting','on');
add_line(loop, 'ByteRxBeatGate/1', 'byte_rx_valid/1', 'autorouting','on');
add_line(loop, 'SerLastRT/1',      'byte_rx_last/1',  'autorouting','on');
add_line(loop, 'SerFirstRT/1',     'byte_rx_user/1',  'autorouting','on');

fprintf('byte_plumbing_overlay_k5: model edits done (byte inports %d..%d + %d, byte outports %d..%d, WPP=%d)\n', ...
    nIn+1, nIn+4, nIn+5, nOut+1, nOut+5, WPP);
else
    fprintf('byte_plumbing_overlay_k5: ByteWordBuffer already present -- model edits skipped\n');
end

% --- (3) patch the kit hdlworkflow_loopback.m: byte mappings + byte RD ---
% Donor loop-built tuple list, MINUS the verif host/debug tuples (already
% present in this kit's workflow from variant_pre.m), PLUS DELTA 2 (x"158").
addpath('/home/tcollins/dev/qpsk_ai/TransceiverToolbox/hdl/vendor/AnalogDevices');
hRDbyte = AnalogDevices.jupiter.plugin_rd_rxtx_byte();
rdName  = hRDbyte.ReferenceDesignName;
assert(strcmp(rdName, 'JUPITER (RX & TX, BYTE DMA)'), ...
    'unexpected byte RD name: %s', rdName);
wfFile = 'hdlworkflow_loopback.m';
wfTxt  = fileread(wfFile);
if ~contains(wfTxt, 'composite-byte mappings')
    assert(~contains(wfTxt, TXDS_ADDR), 'AXI %s already used in the workflow', TXDS_ADDR);
    assert(contains(wfTxt, 'x"11C"'), 'dbg_sentinel x"11C" mapping missing (unexpected base workflow)');
    maps = { ...
      % byte-TX path
      'byte_data',      'Byte Data IN [0:63]',   '[0:63]'; ...
      'byte_valid',     'Byte Valid IN',         '[0]'; ...
      'byte_ready',     'Byte Ready OUT',        '[0]'; ...
      'byte_first',     'Byte First IN',         '[0]'; ...
      'tx_data_source', 'AXI4-Lite',             TXDS_ADDR; ...   % DELTA 2 (0x11C = dbg_sentinel!)
      % byte-RX path
      'byte_rx_data',   'Byte Data OUT [0:63]',  '[0:63]'; ...
      'byte_rx_valid',  'Byte Valid OUT',        '[0]'; ...
      'byte_rx_last',   'Byte Last OUT',         '[0]'; ...
      'byte_rx_user',   'Byte User OUT',         '[0]'; ...
      'byte_rx_ready',  'Byte Ready IN',         '[0]'};
    L = ['% --- composite-byte mappings (tx_data_source at x"158": 0x11C = dbg_sentinel) ---' newline];
    for k = 1:size(maps,1)
        L = [L 'hdlset_param(''' sys '/TxRxComposite/' maps{k,1} ...
             ''', ''IOInterface'', ''' maps{k,2} ''');' newline]; %#ok<AGROW>
        L = [L 'hdlset_param(''' sys '/TxRxComposite/' maps{k,1} ...
             ''', ''IOInterfaceMapping'', ''' maps{k,3} ''');' newline]; %#ok<AGROW>
    end
    L = [L '% --- end composite-byte mappings ---' newline];
    anchor = ['hdlset_param(''' sys '/TxRxComposite/bit_errors_out'', ' ...
              '''IOInterfaceMapping'', ''x"108"'');'];
    idx = strfind(wfTxt, anchor); assert(~isempty(idx), 'bit_errors_out x"108" anchor not found');
    at = idx(1) + numel(anchor);
    if at <= numel(wfTxt) && wfTxt(at) == newline, at = at + 1; end
    wfTxt = [wfTxt(1:at-1) newline L wfTxt(at:end)];
    oldRD = ['hdlset_param(''' sys ''', ''ReferenceDesign'', ' ...
             '''JUPITER (RX & TX - RX IS FASTER OR HAS PRIORITY)'');'];
    newRD = ['hdlset_param(''' sys ''', ''ReferenceDesign'', ''' rdName ''');'];
    assert(contains(wfTxt, oldRD), 'ReferenceDesign line not found');
    wfTxt = strrep(wfTxt, oldRD, newRD);
    fid = fopen(wfFile, 'w');
    fwrite(fid, wfTxt); fclose(fid);
    fprintf('byte_plumbing_overlay_k5: hdlworkflow patched (RD=%s, tx_data_source=%s)\n', rdName, TXDS_ADDR);
else
    fprintf('byte_plumbing_overlay_k5: hdlworkflow already patched -- skipping\n');
end
fprintf('byte_plumbing_overlay_k5: DONE\n');
end
