function fec_insert_overlay_rxonly_k5(sys, base)
% fec_insert_overlay_rxonly_k5 -- RX-ONLY K=5 FEC insertion (jupiter_240k5).
%
% Copy of zed_fecrx/fec_insert_overlay_rxonly.m with the FEC constants migrated
% K=7 -> K=5 per the 240k/K5 contract (k5_240/PACKET_K5.txt):
%   trellis poly2trellis(7,[171 133]) -> poly2trellis(5,[35 23])
%   traceback 34 -> 25
%   info/tail 1080/6 -> 1084/4  =>  CODED 2172 -> 2176 (= 16 cols x 136 ROWS;
%   ROWS is computed as idivide(CODED,COLS) inside the FSM sources, so the
%   deinterleave perm c*ROWS+r becomes c*136+r automatically)
%
% Inserts ONLY the Rx-side decode chain (16-col deinterleaver + K=5 hard
% Viterbi TB=25 + RxAlign + FEC Decoder Wrapper) and OMITS the Tx-side FEC
% Encoder Wrapper: the jupiter_240k5 Tx bit source is the PRE-CODED msggen
% ROM (msggen_rom_overlay_k5.m) -- an in-FPGA encoder would double-encode the
% already-coded ROM payload (and is the proven-buggy path class).
%
% The Rx deinterleaver consumes the FIRST CODED(=2176) bits of the 2240-bit
% payload; the 64 filler bits at the end are never read (RxDeint reads pairs
% 0..NPAIR-1 = coded bits only; the write side stores the first 2176).
%
% Apply AFTER the model is loaded and BEFORE HDL codegen. Idempotent.

NL = char(10); %#ok<NASGU>
if nargin < 1, sys = bdroot; end
if nargin < 2 || isempty(base), base = sys; end
P = commhdlQPSKTxRxParameters();
assert(P.DataBitsPerPacket == 2240, 'unexpected DataBitsPerPacket');

TRELLIS_STR = 'poly2trellis(5, [35 23])';   % K=5 (was poly2trellis(7,[171 133]))
INFO_BITS   = 1084;                          % was 1080
TAIL_BITS   = 4;                             % K-1 (was 6)
CODED_BITS  = 2*(INFO_BITS + TAIL_BITS);     % = 2176 (was 2172); ROWS = 2176/16 = 136
INTERLEAVE_COLS = 16;
TB_DEPTH    = 25;                            % was 34
assert(CODED_BITS == 2176 && CODED_BITS/INTERLEAVE_COLS == 136, 'K5 contract mismatch');

% Marker: skip if the Rx decoder is already present.
if ~isempty(find_system(base,'LookUnderMasks','all','FollowLinks','on', ...
        'BlockType','SubSystem','Name','FEC Decoder Wrapper'))
    fprintf('fec_insert_overlay_rxonly_k5: FEC Decoder already present -- skipping\n');
    return;
end

load_system('commcnvcod2');

% ============================================================================
% (A) TX -- DELIBERATELY OMITTED (Rx-only, LUT-lean). The Tx path keeps its stock
%     Bit Packetizer -> HDL Data Scrambler wiring UNCHANGED (no FEC encoder).
% ============================================================================
fprintf('fec_insert_overlay_rxonly_k5: Tx FEC encoder OMITTED (Rx-only LUT-lean)\n');

% ============================================================================
% (B) RX -- insert FEC Decoder Wrapper between Descrambler and BIST (identical
%     to the shared overlay).
% ============================================================================
qrx = [base '/Receiver/QPSK Rx'];
dec = [qrx '/FEC Decoder Wrapper'];
build_rx_decoder_wrapper(dec, TRELLIS_STR, TB_DEPTH, INFO_BITS, CODED_BITS, INTERLEAVE_COLS);

delete_line(qrx, 'HDL Data Descrambler/1', 'dataOut/1');
delete_line(qrx, 'HDL Data Descrambler/2', 'Bus Creator1/1');
delete_line(qrx, 'HDL Data Descrambler/3', 'Bus Creator1/2');
delete_line(qrx, 'HDL Data Descrambler/4', 'Bus Creator1/3');
add_line(qrx, 'HDL Data Descrambler/1', 'FEC Decoder Wrapper/1', 'autorouting','on');
add_line(qrx, 'HDL Data Descrambler/2', 'FEC Decoder Wrapper/2', 'autorouting','on');
add_line(qrx, 'HDL Data Descrambler/3', 'FEC Decoder Wrapper/3', 'autorouting','on');
add_line(qrx, 'HDL Data Descrambler/4', 'FEC Decoder Wrapper/4', 'autorouting','on');
add_line(qrx, 'FEC Decoder Wrapper/1', 'dataOut/1', 'autorouting','on');
add_line(qrx, 'FEC Decoder Wrapper/2', 'Bus Creator1/1', 'autorouting','on');
add_line(qrx, 'FEC Decoder Wrapper/3', 'Bus Creator1/2', 'autorouting','on');
add_line(qrx, 'FEC Decoder Wrapper/4', 'Bus Creator1/3', 'autorouting','on');
fprintf('fec_insert_overlay_rxonly_k5: Rx FEC Decoder Wrapper inserted (deint+Viterbi+RxAlign)\n');
fprintf('fec_insert_overlay_rxonly_k5: DONE (trellis=%s, coded=%d cols=%d tb=%d)\n', ...
    TRELLIS_STR, CODED_BITS, INTERLEAVE_COLS, TB_DEPTH);
end

% ---- Rx decoder wrapper builder (copied bit-for-bit from fec_insert_overlay.m) ----
function build_rx_decoder_wrapper(dec, TRELLIS_STR, TB, INFO_BITS, CODED_BITS, COLS)
add_block('built-in/Subsystem', dec, 'Position',[700 380 820 480]);
for k=1:4, add_block('built-in/Inport',[dec '/' inn(k)],'Port',num2str(k),'Position',[20 40+40*k 50 60+40*k]); end
add_block('built-in/Inport',[dec '/skipCount'],'Port','5','Position',[20 40+40*5 50 60+40*5]);
set_param([dec '/skipCount'],'OutDataTypeStr','uint32','SampleTime','-1');
for k=1:4, add_block('built-in/Outport',[dec '/' onn(k)],'Port',num2str(k),'Position',[760 40+40*k 790 60+40*k]); end

add_block('simulink/User-Defined Functions/MATLAB Function',[dec '/RxDeint'],'Position',[120 60 260 200]);
set_fcn_script([dec '/RxDeint'],  fecRxDeint_src(CODED_BITS, COLS));

% RXROOT fix (2026-07-02): the Viterbi block MUST only advance one trellis step
% per valid deinterleaved pair. The deint holds codedPair between deintValid
% beats; an ungated Viterbi consumes each held pair ~5-6x and decodes garbage
% (proven in RTL replay of real air + iverilog unit bench, see k5_240/RXROOT.txt
% ROOT CAUSE #3). Wrap it in an ENABLED subsystem driven by deintValid.
vg = [dec '/VitGate'];
add_block('built-in/Subsystem', vg, 'Position',[320 60 440 160]);
add_block('built-in/Inport',[vg '/pairIn'],'Port','1','Position',[20 60 50 80]);
add_block('built-in/Inport',[vg '/rstIn'],'Port','2','Position',[20 120 50 140]);
add_block('built-in/EnablePort',[vg '/Enable'],'Position',[200 20 220 40]);
add_block('commcnvcod2/Viterbi Decoder',[vg '/Viterbi'],'Position',[120 70 230 140]);
set_param([vg '/Viterbi'],'trellis',TRELLIS_STR,'dectype','Hard decision', ...
    'tbdepth',num2str(TB),'opmode','Continuous','reset','on', ...
    'delayedResetAction','on','outDataType','boolean');
add_block('built-in/Outport',[vg '/decOut'],'Port','1','Position',[300 95 330 115]);
% Delay balancing cannot absorb the Viterbi's internal pipeline (16 cy) inside a
% conditional subsystem; it does not need to -- RxAlign's skip alignment absorbs
% ALL decoder latency (measured end-to-end: 37 deintValid beats, baked below).
hdlset_param(vg, 'BalanceDelays', 'off');
add_line(vg,'pairIn/1','Viterbi/1','autorouting','on');
add_line(vg,'rstIn/1','Viterbi/2','autorouting','on');
add_line(vg,'Viterbi/1','decOut/1','autorouting','on');

add_block('simulink/User-Defined Functions/MATLAB Function',[dec '/RxAlign'],'Position',[500 60 660 200]);
set_fcn_script([dec '/RxAlign'],  fecRxAlign_src(INFO_BITS, TB));

add_line(dec, [inn(1) '/1'], 'RxDeint/1', 'autorouting','on');
add_line(dec, [inn(2) '/1'], 'RxDeint/2', 'autorouting','on');
add_line(dec, [inn(3) '/1'], 'RxDeint/3', 'autorouting','on');
add_line(dec, [inn(4) '/1'], 'RxDeint/4', 'autorouting','on');
add_line(dec, 'RxDeint/1', 'VitGate/1', 'autorouting','on');
add_line(dec, 'RxDeint/2', 'VitGate/2', 'autorouting','on');
add_line(dec, 'RxDeint/3', 'VitGate/Enable', 'autorouting','on');
add_line(dec, 'VitGate/1', 'RxAlign/1', 'autorouting','on');
add_line(dec, 'RxDeint/3', 'RxAlign/2', 'autorouting','on');
add_line(dec, 'RxDeint/4', 'RxAlign/3', 'autorouting','on');
add_line(dec, 'RxDeint/5', 'RxAlign/4', 'autorouting','on');
add_line(dec, 'skipCount/1', 'RxAlign/5', 'autorouting','on');
add_line(dec, 'RxAlign/1', [onn(1) '/1'], 'autorouting','on');
add_line(dec, 'RxAlign/2', [onn(2) '/1'], 'autorouting','on');
add_line(dec, 'RxAlign/3', [onn(3) '/1'], 'autorouting','on');
add_line(dec, 'RxAlign/4', [onn(4) '/1'], 'autorouting','on');
end

function s = inn(k), names={'bitsIn','startIn','endIn','validIn'}; s=names{k}; end
function s = onn(k), names={'dataOut','startOut','endOut','validOut'}; s=names{k}; end
function set_fcn_script(blk, src)
rt = sfroot; chart = rt.find('-isa','Stateflow.EMChart','Path',blk); chart.Script = src;
end

function src = fecRxDeint_src(CODED, COLS)
% Sync-semantics compliant (RXROOT E11c): persistents are read into locals at
% the top, ALL reads precede ALL writes, outputs come from locals, persistents
% are written last. Bit-identical to the classic version (the read bank is
% always the opposite of the write bank).
src = sprintf([ ...
'function [codedPair, vitReset, deintValid, frameStart, frameEnd] = fecRxDeint(dataIn, startIn, endIn, validIn)\n' ...
'%%#codegen\n' ...
'persistent ramA ramB rdBank wptr pcnt hold0 hold1 rdGate;\n' ...
'CODED=uint16(%d); COLS=uint16(%d); ROWS=uint16(idivide(uint16(%d),uint16(%d)));\n' ...
'NPAIR=uint16(idivide(uint16(%d),uint16(2)));\n' ...
'if isempty(ramA), ramA=false(1,%d); ramB=false(1,%d); rdBank=false; wptr=uint16(0); pcnt=uint16(0); hold0=false; hold1=false; rdGate=false; end\n' ...
'rb=rdBank; w=wptr; pc=pcnt; g=rdGate; h0=hold0; h1=hold1;\n' ...
'pair0=h0; pair1=h1;\n' ...
'vitReset=false; deintValid=false; frameStart=false; frameEnd=false;\n' ...
'wrPos=uint16(65535); wrBit=false; wrBankA=false; doWr=false;\n' ...
'if validIn\n' ...
'  if startIn, w=uint16(0); pc=uint16(0); rb=~rb; g=true; end %% rdGate=TRUE: frame pair0 read COINCIDES with frameStart (RxAlign arms on that beat)\n' ...
'  %% ---- READ side first (opposite bank; RXROOT E8 isolated reads: 1 pair per 2 validIn beats) ----\n' ...
'  if g && (pc < NPAIR)\n' ...
'    rc0 = pc+pc;\n' ...
'    rc1 = rc0 + uint16(1);\n' ...
'    c0 = mod(rc0, COLS); r0 = idivide(rc0, COLS); perm0 = c0*ROWS + r0;\n' ...
'    c1 = mod(rc1, COLS); r1 = idivide(rc1, COLS); perm1 = c1*ROWS + r1;\n' ...
'    b0v = false; b1v = false;\n' ...
'    if perm0 < CODED\n' ...
'      if rb, b0v = ramB(double(perm0)+1); else b0v = ramA(double(perm0)+1); end\n' ...
'    end\n' ...
'    if perm1 < CODED\n' ...
'      if rb, b1v = ramB(double(perm1)+1); else b1v = ramA(double(perm1)+1); end\n' ...
'    end\n' ...
'    pair0 = b0v; pair1 = b1v; h0 = b0v; h1 = b1v;\n' ...
'    deintValid = true;\n' ...
'    if pc == uint16(0), vitReset = true; end\n' ...
'    pc = pc + 1;\n' ...
'  end\n' ...
'  %% ---- WRITE side after all reads ----\n' ...
'  if w < CODED\n' ...
'    wrPos = w; wrBit = logical(dataIn); wrBankA = rb; doWr = true;\n' ...
'    w = w + 1;\n' ...
'  end\n' ...
'  g = ~g;\n' ...
'  frameStart=startIn; frameEnd=endIn;\n' ...
'end\n' ...
'codedPair = fi([pair0; pair1], 0, 1, 0);\n' ...
'%% ---- persist state last ----\n' ...
'if doWr\n' ...
'  if wrBankA, ramA(double(wrPos)+1)=wrBit; else ramB(double(wrPos)+1)=wrBit; end\n' ...
'end\n' ...
'rdBank=rb; wptr=w; pcnt=pc; rdGate=g; hold0=h0; hold1=h1;\n'], CODED, COLS, CODED, COLS, CODED, CODED, CODED);
end

function src = fecRxAlign_src(INFO, TB) %#ok<INUSD>
% Sync-semantics compliant: locals in, outputs from locals, persist last.
src = sprintf([ ...
'function [dataOut, startOut, endOut, validOut] = fecRxAlign(decBit, deintValid, frameStart, frameEnd, skipCount)\n' ...
'%%#codegen\n' ...
'persistent oc started skip;\n' ...
'INFO=uint16(%d);\n' ...
'if isempty(oc), oc=uint16(0); started=false; skip=uint16(0); end\n' ...
'o=oc; st=started; sk=skip;\n' ...
'dataOut=false; startOut=false; endOut=false; validOut=false;\n' ...
'sc = uint16(skipCount);\n' ...
'if sc > INFO, sc = INFO; end\n' ...
'if deintValid\n' ...
'  if frameStart, o=uint16(0); st=true; sk=sc+uint16(41); end %% +41 = gated-Viterbi latency in deintValid beats incl. VitGate hold reg (RXROOT E8)\n' ...
'  if st\n' ...
'    if sk > uint16(0)\n' ...
'      sk = sk - uint16(1);\n' ...
'    elseif o < INFO\n' ...
'      dataOut = decBit;\n' ...
'      startOut = (o==uint16(0));\n' ...
'      endOut   = (o==(INFO-1));\n' ...
'      validOut = true;\n' ...
'      o = o + uint16(1);\n' ...
'    end\n' ...
'  end\n' ...
'end\n' ...
'oc=o; started=st; skip=sk;\n'], INFO);
end
