function framestat_overlay(sys, base)
% framestat_overlay -- ONE 64-bit per-frame RX status record, latched at the
% RX frame strobe and buffered in a 64-deep side FIFO exposed at UNMAPPED AXI
% offsets 0x1D0-0x1DC. The host reads a compact "which frame did this error
% hit, and was it transport or upstream" verdict per frame -- see
% FRAMESTAT_NOTES.md for the record layout, the AXI access protocol, the
% checksum/whitener contract and the host-side offsets qpsk_hw.h must add.
%
% G0 PRESERVATION: the ENTIRE body is env-gated. With QPSK_FRAMESTAT unset the
% function EARLY-RETURNS before touching a single block, so the assembled model
% is byte-identical to today (same idiom family as loop_gain's LEAN gate, but
% here the gate is an early return so the OFF path adds zero blocks/ports).
%
% COEXISTENCE with loop_gain_axi_overlay: framestat uses 0x1D0-0x1DC, which are
% free in BOTH the LEAN and the debug image (occupied through 0x1B0 shipped;
% loop_gain 0x170-0x184 LEAN-only; P1B census 0x1B4-0x1C8). No register
% collision either way, so framestat is orthogonal to the LEAN/debug split.
%
% ------------------------------------------------------------------ record
% 64-bit, latched at the recStart rising edge (= completion of the frame whose
% bits accumulated since the previous recStart):
%   [7:0]   frame_seq          low 8 bits of packets_out (0x104) host align tag
%   [8]     cs_reset_in_frame  rstcs_count (0x150) changed since last strobe
%   [9]     stall_in_frame     framestat_stallcnt (0x1C4) changed since last
%                              strobe = a byte_rx_valid&&!byte_rx_ready stall
%                              cycle occurred in this frame's delivery window
%                              (the DIRECT witness of inter-transfer DMAC
%                              backpressure -- FWD_SINGLES_ROOT_CAUSE.md)
%   [10]    txur_in_frame      framestat_txurcnt (0x1C8) changed since last
%                              strobe = the TX ByteBitShifter hit its underflow
%                              reload (modulator aired zeros) in the window
%   [11]    sync_low_margin    quantized Peak Search runningMax < CORR_FLOOR
%   [15:12] reserved (0)
%   [23:16] corr_strength      quantized Peak Search runningMax (MSB position)
%   [31:24] agc_level          adc_forensic levelLog (0x15C [31:24]); 0 in LEAN
%   [47:32] cfc_snapshot       cfc_est (0x154) top-16 slice at the strobe
%   [63:48] payload_checksum   16-bit sum of the bytes of the delivered RX
%                              64-bit words (ByteSerializer out) -- THE
%                              discriminator (see NOTES: deliberate deviation
%                              from "over recBit" -- 60 info bits are undelivered)
%
% ------------------------------------------------------------------ blocks
%   FrameStatChecksum  MLFB, 16-bit checksum over the delivered ByteSerializer
%                      words (adc_forensic persistent-accumulator idiom)
%   FrameStatProbe     MLFB, latches the 10 fields into the 64-bit record at the
%                      strobe (adc_forensic packed-snapshot latch idiom)
%   FrameStatFifo      MLFB, 64-deep circular FIFO of 64-bit records + overflow
%                      counter (modeled on byte_rxfifo_overlay's FIFO)
%   FrameStatWordCnt   MLFB, FREE-RUNNING 32-bit counter of accepted byte_rx
%                      words (byte_rx_valid && byte_rx_ready) -- checkpoint-1
%                      word COUNT (SEGMENTED_LOOPBACK_DESIGN.md); the cheapest
%                      wedge detector (frozen count is unambiguous)
%   FrameStatStallCnt  MLFB, FREE-RUNNING 32-bit counter of byte_rx STALL
%                      cycles (byte_rx_valid && ~byte_rx_ready) -- the direct
%                      backpressure witness (30.72M rail, same rails as the
%                      word counter)
%   FrameStatTxUrCnt   MLFB, FREE-RUNNING 32-bit counter of TX ByteBitShifter
%                      underflow-reload events (modulator starved mid-frame ->
%                      zeros aired; one event ~= one muted frame remainder)
%   framestat_head_lo/hi/stat  composite read outports  (0x1D0/0x1D4/0x1D8)
%   framestat_pop              composite write inport   (0x1DC, FIFO advance)
%   framestat_wordcnt          composite read outport   (0x1C0, word counter)
%   framestat_stallcnt         composite read outport   (0x1C4, stall counter)
%   framestat_txurcnt          composite read outport   (0x1C8, TX underrun)
%
% 0x1C0/0x1C4/0x1C8 COLLISION NOTE: 0x1C0 is p1b_pc_w1, 0x1C4 is p1b_pc_w2 and
% 0x1C8 is p1b_pa_w1 in NON-LEAN debug builds (p1b_decision_taps_overlay,
% census 0x1B4-0x1C8 -- verified the only claimants in hdlworkflow_loopback.m).
% The framestat instrument image is LEAN (p1b stripped), so all three offsets
% are free there; the single hard assert below (p1b_pc_w1 absent -- the p1b
% ports are added/stripped as one block) refuses a framestat+p1b combination
% rather than double-mapping any of them.
%
% CHECKSUM WIDTH: stays 16-bit. The design doc asks for 32-bit "if the record
% layout allows" -- it does not: the 64-bit record has only 4 reserved bits
% left ([15:12]; [10:9] = N2 witnesses), so a 32-bit checksum cannot fit without evicting another
% field. The 0x1C0 word counter covers the drop/wedge class; the 16-bit
% checksum retains 1-in-65536 corruption coverage per frame.
%
% Peak Search runningMax is reused from the p1c_runmax outport that
% p1d_pd_telemetry_overlay already surfaces on Peak Search, then surfaced up
% Preamble Detector -> FTS -> QPSK Rx -> Receiver following the p1d/iq_debug
% StatePairProbe surfacing idiom.
%
% Apply LATE in assemble, AFTER byte_rxfifo_overlay AND loop_gain_axi_overlay
% (so the composite port set + the p1d runningMax tap are stable), env-gated on
% QPSK_FRAMESTAT. Idempotent. Does NOT save.

if nargin < 1 || isempty(sys),  sys  = bdroot; end
if nargin < 2 || isempty(base), base = sys;    end
loop = base;

% ---- G0 gate: early return => byte-identical when off (no blocks touched) ----
if isempty(getenv('QPSK_FRAMESTAT'))
    return;
end

% ---- idempotency (every reference overlay guards this way) ----
if ~isempty(find_system(loop,'SearchDepth',1,'LookUnderMasks','all', ...
        'FollowLinks','on','Name','FrameStatFifo'))
    fprintf('framestat_overlay: already present -- skipping\n');
    return;
end

% ---- tunables (documented in FRAMESTAT_NOTES.md; on-air-refine later) ----
CORR_FLOOR = 20;    % MSB-position of runningMax below which sync_low_margin fires

rcv = [loop '/Receiver'];
qrx = [rcv '/QPSK Rx'];
fts = [qrx '/Frequency and Time Synchronizer'];
pd  = [fts '/Preamble Detector'];
ps  = [pd '/Peak Search'];

% ---- preconditions (assert, don't assume -- byte_rx_overlay warns numbering
%      drifted; every source is introspected, never hardcoded) ----
psRun = find_system(ps,'SearchDepth',1,'LookUnderMasks','all','FollowLinks','on', ...
    'BlockType','Outport','Name','p1c_runmax');
assert(~isempty(psRun), ...
    'framestat_overlay: Peak Search p1c_runmax missing -- apply after p1d_pd_telemetry_overlay');
% packets_out/rstcs_count/cfc_est ARE composite outports (search loop);
% recStart is a RECEIVER outport (byte_rx_overlay_k5 adds it there, never
% surfaced to composite -- byte_plumbing consumes it as Receiver/<port>).
for req = {'packets_out','rstcs_count','cfc_est'}
    assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Outport','Name',req{1})), ...
        'framestat_overlay: composite outport %s missing (apply after taps overlays)', req{1});
end
assert(~isempty(find_system(rcv,'SearchDepth',1,'LookUnderMasks','all','FollowLinks','on', ...
    'BlockType','Outport','Name','recStart')), ...
    'framestat_overlay: Receiver outport recStart missing -- apply after byte_rx_overlay_k5');
assert(~isempty(find_system(loop,'SearchDepth',1,'LookUnderMasks','all','FollowLinks','on', ...
    'Name','ByteSerializer')), ...
    'framestat_overlay: ByteSerializer missing -- apply after byte_plumbing_overlay_k5');
% 0x1C0 word counter vs p1b census: refuse the double-mapping instead of
% silently colliding (p1b_pc_w1 owns 0x1C0 in non-LEAN debug builds).
assert(isempty(find_system(loop,'SearchDepth',1,'BlockType','Outport','Name','p1b_pc_w1')), ...
    'framestat_overlay: p1b_pc_w1 present (non-LEAN) -- 0x1C0 collision; build framestat on LEAN');
% byte_rx handshake rails for the 0x1C0 word counter
assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Outport','Name','byte_rx_valid')), ...
    'framestat_overlay: composite outport byte_rx_valid missing -- apply after byte_rxfifo_overlay');
assert(~isempty(find_system(loop,'SearchDepth',1,'BlockType','Inport','Name','byte_rx_ready')), ...
    'framestat_overlay: composite inport byte_rx_ready missing -- apply after byte_plumbing_overlay_k5');
% TX byte plumbing (for the 0x1C8 TX-underrun witness)
idPath = [loop '/Transmitter/Input Data'];
assert(~isempty(find_system(idPath,'SearchDepth',1,'LookUnderMasks','all','FollowLinks','on', ...
    'Name','ByteBitShifter')), ...
    'framestat_overlay: ByteBitShifter missing -- apply after byte_tx_overlay_k5');

% ================================================================= (1) runMax
% Surface the p1c_runmax register (SI of sfix32_En26) up the hierarchy:
% Peak Search -> Preamble Detector -> FTS -> QPSK Rx -> Receiver. Same
% add-an-outport-per-level idiom as iq_debug_tap_overlay's state-pair surfacing.
psRunPort = str2double(get_param(psRun{1},'Port'));
chain = { pd, ps, 'Peak Search', psRunPort; ...
          fts, pd, 'Preamble Detector', []; ...
          qrx, fts, 'Frequency and Time Synchronizer', []; ...
          rcv, qrx, 'QPSK Rx', [] };
childPort = psRunPort;
for L = 1:size(chain,1)
    parent = chain{L,1};
    childName = chain{L,3};
    nOut = numel(find_system(parent,'SearchDepth',1,'LookUnderMasks','all', ...
        'BlockType','Outport'));
    thisPort = nOut + 1;
    add_block('built-in/Outport',[parent '/fs_runmax'],'Port',num2str(thisPort), ...
        'Position',[1500 1400+30*thisPort 1530 1416+30*thisPort]);
    add_line(parent, sprintf('%s/%d', childName, childPort), 'fs_runmax/1', ...
        'autorouting','on');
    childPort = thisPort;
end
rcvRunPort = childPort;   % Receiver outport carrying runningMax at composite
fprintf('framestat_overlay: runningMax surfaced to Receiver outport %d (from p1c_runmax)\n', rcvRunPort);

% ================================================================= helpers
    function spec = outSrc(name)
        % 'SrcName/port' string feeding the named composite Outport (to fan out
        % from). add_line branches automatically when the source already drives
        % a line. Source names are asserted newline-free (byte_rx_overlay warns
        % some block names contain newlines and must use handles instead).
        lh = get_param([loop '/' name],'LineHandles');
        assert(lh.Inport(1) ~= -1, 'framestat_overlay: %s outport unconnected', name);
        sph = get_param(lh.Inport(1),'SrcPortHandle');
        sName = get_param(get_param(sph,'Parent'),'Name');
        assert(isempty(strfind(sName, char(10))), ...
            'framestat_overlay: %s source name %s has a newline -- use a handle', name, sName);
        spec = sprintf('%s/%d', sName, get_param(sph,'PortNumber'));
    end
    function addSiDtc(nm, srcSpec, dstSpec, dtStr, ypos)
        % stored-integer reinterpret DTC (p1d siwire isolation): src -> DTC -> dst
        add_block('simulink/Signal Attributes/Data Type Conversion',[loop '/' nm], ...
            'OutDataTypeStr',dtStr,'ConvertRealWorld','Stored Integer (SI)', ...
            'Position',[300 ypos 340 ypos+16]);
        add_line(loop, srcSpec, [nm '/1'], 'autorouting','on');
        add_line(loop, [nm '/1'], dstSpec, 'autorouting','on');
    end

% ================================================================= (2) checksum
% 16-bit running checksum over the DELIVERED RX 64-bit words -- the actual bytes
% the host receives, tapped at the ByteSerializer output (word + wordTog).
%
% DELIBERATE DEVIATION from deliverable-1's "checksum over recBit", forced by
% primary-source evidence: the ByteSerializer delivers only the FIRST
% WordsPerPacketRx*64 (= 1024 in k5) of the 1084 decoded info bits -- the
% trailing 60 are dropped by start-reset. A checksum over ALL recBit would
% include 60 bits the host never receives, so it would MISMATCH on every clean
% frame and the discriminator would be worthless. Checksumming the delivered
% words instead (a) matches the record-layout prose verbatim ("over the
% delivered RX 64-bit words"), (b) is byte-order-agnostic (whole 64-bit words;
% the host sums the same received words), and (c) also catches ByteRxFifo drops
% as transport loss. recStart is the frame strobe (Receiver-level outport).
recStartB = find_system(rcv,'SearchDepth',1, ...
    'LookUnderMasks','all','FollowLinks','on', ...
    'BlockType','Outport','Name','recStart');
recStartP = str2double(get_param(recStartB{1},'Port'));

add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatChecksum'], ...
    'Position',[420 1300 540 1380]);
set_fcn_script([loop '/FrameStatChecksum'], sprintf([ ...
'function chk = frameStatChecksum(word, wordTog, strobe)\n' ...
'%%#codegen\n' ...
'%% 16-bit running checksum over the delivered RX 64-bit words. On each emitted\n' ...
'%% word (wordTog change), the eight bytes of the word are added into a 16-bit\n' ...
'%% modular accumulator. chk is COMBINATIONAL (= the accumulated sum of every\n' ...
'%% word delivered in the frame completed as of this cycle) so FrameStatProbe,\n' ...
'%% latching chk on the SAME strobe edge, captures THIS frame -- no register-to-\n' ...
'%% register race / off-by-one (see FRAMESTAT_NOTES.md). Host mirror: for each\n' ...
'%% received 64-bit word, add its 8 bytes mod 2^16.\n' ...
'persistent acc prevTog prevStr\n' ...
'if isempty(acc)\n' ...
'    acc = uint16(0); prevTog = false; prevStr = false;\n' ...
'end\n' ...
'chk = acc;\n' ...
'strobeEdge = strobe && ~prevStr;\n' ...
'prevStr = strobe;\n' ...
'if strobeEdge\n' ...
'    acc = uint16(0);\n' ...
'end\n' ...
'if logical(wordTog) ~= prevTog\n' ...
'    s = uint32(0);\n' ...
'    for bpos = 0:8:56\n' ...
'        s = s + uint32(bitand(bitshift(word, -bpos), uint64(255)));\n' ...
'    end\n' ...
'    acc = uint16(mod(uint32(acc) + s, uint32(65536)));\n' ...
'end\n' ...
'prevTog = logical(wordTog);\n']));
pin_types([loop '/FrameStatChecksum'], struct( ...
    'word','uint64','wordTog','boolean','strobe','boolean','chk','uint16'));
add_line(loop, 'ByteSerializer/1', 'FrameStatChecksum/1', 'autorouting','on');   % word (held)
add_line(loop, 'ByteSerializer/2', 'FrameStatChecksum/2', 'autorouting','on');   % wordTog
add_line(loop, sprintf('Receiver/%d', recStartP), 'FrameStatChecksum/3', 'autorouting','on');

% ================================================================= (3) probe
% Latch the 10 fields into the 64-bit record at the recStart strobe.
% adc_forensic packed-snapshot latch idiom (one uint32 -> here uint64).
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatProbe'], ...
    'Position',[600 1240 740 1420]);
set_fcn_script([loop '/FrameStatProbe'], sprintf([ ...
'function [rec, push] = frameStatProbe(pktCnt, rstcsCnt, runMax, adcFor, cfcEst, chk, strobe, stallCnt, txurCnt)\n' ...
'%%#codegen\n' ...
'%% Latch the 64-bit per-frame status record at the frame strobe. Bit layout:\n' ...
'%%   [7:0] frame_seq [8] cs_reset [9] stall_in_frame [10] txur_in_frame\n' ...
'%%   [11] sync_low [23:16] corr [31:24] agc [47:32] cfc [63:48] checksum.\n' ...
'%% [9]/[10] use the SAME changed-since-last-strobe idiom as cs_reset (the\n' ...
'%% free-running counters are the ground truth; comparing latched snapshots\n' ...
'%% avoids any cross-rate clear/latch race). See FRAMESTAT_NOTES.md.\n' ...
'persistent rec_r prevRst prevStr prevStall prevTxur\n' ...
'if isempty(rec_r)\n' ...
'    rec_r = uint64(0); prevRst = uint32(0); prevStr = false;\n' ...
'    prevStall = uint32(0); prevTxur = uint32(0);\n' ...
'end\n' ...
'push = false;\n' ...
'%% latch once per frame on the strobe rising edge (recStart pulse-or-hold safe)\n' ...
'strobeEdge = strobe && ~prevStr;\n' ...
'prevStr = strobe;\n' ...
'if strobeEdge\n' ...
'    frame_seq = uint64(bitand(pktCnt, uint32(255)));\n' ...
'    cs_reset  = uint64(rstcsCnt ~= prevRst);\n' ...
'    stall_b   = uint64(stallCnt ~= prevStall);\n' ...
'    txur_b    = uint64(txurCnt ~= prevTxur);\n' ...
'    %% corr_strength = MSB position (0..32) of the runningMax SI\n' ...
'    corrq = uint32(0);\n' ...
'    for k = 0:31\n' ...
'        if bitshift(runMax, -k) ~= uint32(0)\n' ...
'            corrq = uint32(k + 1);\n' ...
'        end\n' ...
'    end\n' ...
'    sync_low = uint64(corrq < uint32(%d));\n' ...
'    corr8 = uint64(bitand(corrq, uint32(255)));\n' ...
'    agc8  = uint64(bitand(bitshift(adcFor, -24), uint32(255)));\n' ...
'    cfc16 = uint64(bitand(bitshift(cfcEst, -5), uint32(65535)));\n' ...
'    chk16 = uint64(chk);\n' ...
'    rec_r = bitor(bitor(bitor(bitor(bitor(bitor(bitor(bitor( ...\n' ...
'        frame_seq, ...\n' ...
'        bitshift(cs_reset, 8)), ...\n' ...
'        bitshift(stall_b, 9)), ...\n' ...
'        bitshift(txur_b, 10)), ...\n' ...
'        bitshift(sync_low, 11)), ...\n' ...
'        bitshift(corr8, 16)), ...\n' ...
'        bitshift(agc8, 24)), ...\n' ...
'        bitshift(cfc16, 32)), ...\n' ...
'        bitshift(chk16, 48));\n' ...
'    prevRst = rstcsCnt;\n' ...
'    prevStall = stallCnt;\n' ...
'    prevTxur  = txurCnt;\n' ...
'    push = true;\n' ...
'end\n' ...
'rec = rec_r;\n'], CORR_FLOOR));
pin_types([loop '/FrameStatProbe'], struct( ...
    'pktCnt','uint32','rstcsCnt','uint32','runMax','uint32','adcFor','uint32', ...
    'cfcEst','uint32','chk','uint16','strobe','boolean','stallCnt','uint32', ...
    'txurCnt','uint32','rec','uint64','push','boolean'));

% probe inputs (fan out from the composite register lines; SI-isolate the
% fixed-point taps runMax + cfc_est to uint32 stored integers)
add_line(loop, outSrc('packets_out'),  'FrameStatProbe/1', 'autorouting','on');
add_line(loop, outSrc('rstcs_count'),  'FrameStatProbe/2', 'autorouting','on');
% SI-isolate the fixed-point taps (runMax sfix32_En26, cfc_est sfix21_En21) to
% uint32 stored integers before the probe (p1d siwire discipline).
addSiDtc('FsRunSi', sprintf('Receiver/%d', rcvRunPort), 'FrameStatProbe/3', 'fixdt(0,32,0)', 1440);
% agc_level: block-existence-guarded (adc_forensic is ~LEAN only). Present =>
% branch its levelLog word; absent (LEAN) => Constant 0 keeps the field valid.
% RATE FIX (N2 2026-08-12, first non-LEAN framestat build): AdcForensic runs at
% the FULL 30.72M rail ("full-rate like AdcCap"), while every other probe input
% is 15.36M -- feeding it directly makes the probe mixed-rate and model init
% dies with the multi-cause "Data integrity issue" checkhdl error. Isolate it
% through a fast->slow RateTransition (RxReadyRT idiom); it is a level word,
% so the 1-beat latency is irrelevant to the per-frame latch.
if ~isempty(find_system(loop,'SearchDepth',1,'BlockType','Outport','Name','adc_forensic'))
    add_block('built-in/RateTransition', [loop '/FsAgcRT'], ...
        'OutPortSampleTime','1/15.36e6', 'Position',[300 1470 340 1490]);
    add_line(loop, outSrc('adc_forensic'), 'FsAgcRT/1', 'autorouting','on');
    add_line(loop, 'FsAgcRT/1', 'FrameStatProbe/4', 'autorouting','on');
    fprintf('framestat_overlay: adc_forensic branched through FsAgcRT (30.72M -> 15.36M)\n');
else
    add_block('built-in/Constant',[loop '/FsAgcZero'],'Value','0', ...
        'OutDataTypeStr','uint32','Position',[300 1470 340 1490]);
    add_line(loop, 'FsAgcZero/1', 'FrameStatProbe/4', 'autorouting','on');
    fprintf('framestat_overlay: LEAN -- adc_forensic absent, agc_level pinned 0\n');
end
addSiDtc('FsCfcSi', outSrc('cfc_est'), 'FrameStatProbe/5', 'fixdt(0,32,0)', 1500);
add_line(loop, 'FrameStatChecksum/1', 'FrameStatProbe/6', 'autorouting','on');
add_line(loop, sprintf('Receiver/%d', recStartP), 'FrameStatProbe/7', 'autorouting','on');
% probe inputs 8 (stallCnt) and 9 (txurCnt) are wired in sections (7)/(8) below.

% ================================================================= (4) FIFO
% 64-deep circular FIFO of 64-bit records (byte_rxfifo REGISTERS, not RAM).
% push on the probe strobe; advance (pop) on a CHANGE of the framestat_pop
% token (the host writes a fresh value per record consumed -- the realizable
% stand-in for "0x1D4 read pops"; see NOTES). Drop-NEWEST + count on full so
% the oldest un-drained records survive for in-order host draining.
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatFifo'], ...
    'Position',[820 1260 960 1420]);
set_fcn_script([loop '/FrameStatFifo'], sprintf([ ...
'function [headLo, headHi, stat] = frameStatFifo(rec, push, popTok)\n' ...
'%%#codegen\n' ...
'%% 64-deep record FIFO. HEAD = mem(rd). Host: read 0x1D0 (lo), 0x1D4 (hi),\n' ...
'%% then write a changed token to 0x1DC to advance. STAT(0x1D8) =\n' ...
'%% {ovf[31:16] | level[15:0]}. Drop-newest on full.\n' ...
'persistent mem wr rd ovfCnt prevPop\n' ...
'if isempty(wr)\n' ...
'    mem = zeros(64,1,''uint64''); wr = uint16(0); rd = uint16(0);\n' ...
'    ovfCnt = uint16(0); prevPop = uint32(0);\n' ...
'end\n' ...
'if push\n' ...
'    nxt = uint16(mod(uint32(wr) + 1, 64));\n' ...
'    if nxt == rd\n' ...
'        if ovfCnt < uint16(65535), ovfCnt = ovfCnt + uint16(1); end\n' ...
'    else\n' ...
'        mem(uint32(wr)+1) = rec;\n' ...
'        wr = nxt;\n' ...
'    end\n' ...
'end\n' ...
'if popTok ~= prevPop\n' ...
'    if wr ~= rd, rd = uint16(mod(uint32(rd) + 1, 64)); end\n' ...
'end\n' ...
'prevPop = popTok;\n' ...
'head = mem(uint32(rd)+1);\n' ...
'headLo = uint32(bitand(head, uint64(4294967295)));\n' ...
'headHi = uint32(bitshift(head, -32));\n' ...
'level  = uint32(mod(uint32(wr) - uint32(rd) + 64, 64));\n' ...
'stat   = bitor(bitshift(uint32(ovfCnt), 16), level);\n']));
pin_types([loop '/FrameStatFifo'], struct( ...
    'rec','uint64','push','boolean','popTok','uint32', ...
    'headLo','uint32','headHi','uint32','stat','uint32'));
add_line(loop, 'FrameStatProbe/1', 'FrameStatFifo/1', 'autorouting','on');   % rec
add_line(loop, 'FrameStatProbe/2', 'FrameStatFifo/2', 'autorouting','on');   % push

% framestat_pop composite write inport (0x1DC). Wired to the FIFO so codegen
% cannot erase it (dangling inputs are erased -- iq_debug note).
nIn = numel(find_system(loop,'SearchDepth',1,'BlockType','Inport'));
add_block('built-in/Inport',[loop '/framestat_pop'],'Port',num2str(nIn+1), ...
    'Position',[40 1500 70 1516]);
set_param([loop '/framestat_pop'],'OutDataTypeStr','uint32','SampleTime','1/15.36e6');
add_line(loop, 'framestat_pop/1', 'FrameStatFifo/3', 'autorouting','on');

% ================================================================= (5) outports
nOut = numel(find_system(loop,'SearchDepth',1,'BlockType','Outport'));
outs = {'framestat_head_lo', 1; 'framestat_head_hi', 2; 'framestat_stat', 3};
for k = 1:size(outs,1)
    add_block('built-in/Outport',[loop '/' outs{k,1}],'Port',num2str(nOut+k), ...
        'Position',[1000 1260+40*k 1030 1276+40*k]);
    add_line(loop, sprintf('FrameStatFifo/%d', outs{k,2}), [outs{k,1} '/1'], ...
        'autorouting','on');
end

% ================================================================= (6) wordcnt
% Checkpoint-1 word COUNT (SEGMENTED_LOOPBACK_DESIGN.md): a FREE-RUNNING 32-bit
% counter of ACCEPTED byte_rx words -- byte_rx_valid && byte_rx_ready at the
% composite boundary, i.e. exactly the beats axi_dmac takes. Mapped 0x1C0
% (free in LEAN; p1b collision asserted above). Wrap-around by design; the host
% differences successive reads. Frozen count = wedge, unambiguous.
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatWordCnt'], ...
    'Position',[820 1460 960 1520]);
set_fcn_script([loop '/FrameStatWordCnt'], sprintf([ ...
'function cnt = frameStatWordCnt(vld, rdy)\n' ...
'%%#codegen\n' ...
'%% free-running 32-bit accepted-word counter (byte_rx_valid && byte_rx_ready).\n' ...
'%% Wraps mod 2^32 (uint32 native wrap is not guaranteed saturation-free in\n' ...
'%% MLFB codegen defaults, so wrap explicitly).\n' ...
'persistent c\n' ...
'if isempty(c)\n' ...
'    c = uint32(0);\n' ...
'end\n' ...
'cnt = c;\n' ...
'if vld && rdy\n' ...
'    if c == uint32(4294967295)\n' ...
'        c = uint32(0);\n' ...
'    else\n' ...
'        c = c + uint32(1);\n' ...
'    end\n' ...
'end\n']));
pin_types([loop '/FrameStatWordCnt'], struct( ...
    'vld','boolean','rdy','boolean','cnt','uint32'));
add_line(loop, outSrc('byte_rx_valid'), 'FrameStatWordCnt/1', 'autorouting','on');
add_line(loop, 'byte_rx_ready/1', 'FrameStatWordCnt/2', 'autorouting','on');
nOut2 = numel(find_system(loop,'SearchDepth',1,'BlockType','Outport'));
add_block('built-in/Outport',[loop '/framestat_wordcnt'],'Port',num2str(nOut2+1), ...
    'Position',[1000 1470 1030 1486]);
add_line(loop, 'FrameStatWordCnt/1', 'framestat_wordcnt/1', 'autorouting','on');

% ================================================================= (7) stallcnt
% DIRECT backpressure witness (FWD_SINGLES_ROOT_CAUSE.md): a FREE-RUNNING
% 32-bit counter of byte_rx STALL cycles -- byte_rx_valid && ~byte_rx_ready at
% the composite boundary = the DMAC holding tready low against an offered beat
% (the inter-transfer backpressure the mechanism predicts at boundaries).
% Same 30.72M rails + wrap idiom as FrameStatWordCnt. Mapped 0x1C4 (free in
% LEAN; p1b_pc_w2 owns it in non-LEAN debug -- the p1b assert above refuses
% that combination). The counter is also RT'd down to the 15.36M probe rail so
% FrameStatProbe latches stall_in_frame ([9]) as changed-since-last-strobe.
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatStallCnt'], ...
    'Position',[820 1560 960 1620]);
set_fcn_script([loop '/FrameStatStallCnt'], sprintf([ ...
'function cnt = frameStatStallCnt(vld, rdy)\n' ...
'%%#codegen\n' ...
'%% free-running 32-bit STALL-cycle counter (byte_rx_valid && ~byte_rx_ready):\n' ...
'%% each count is one cycle the DMAC backpressured an offered byte_rx beat.\n' ...
'%% Wraps mod 2^32 explicitly (same idiom as FrameStatWordCnt).\n' ...
'persistent c\n' ...
'if isempty(c)\n' ...
'    c = uint32(0);\n' ...
'end\n' ...
'cnt = c;\n' ...
'if vld && ~rdy\n' ...
'    if c == uint32(4294967295)\n' ...
'        c = uint32(0);\n' ...
'    else\n' ...
'        c = c + uint32(1);\n' ...
'    end\n' ...
'end\n']));
pin_types([loop '/FrameStatStallCnt'], struct( ...
    'vld','boolean','rdy','boolean','cnt','uint32'));
add_line(loop, outSrc('byte_rx_valid'), 'FrameStatStallCnt/1', 'autorouting','on');
add_line(loop, 'byte_rx_ready/1', 'FrameStatStallCnt/2', 'autorouting','on');
nOut3 = numel(find_system(loop,'SearchDepth',1,'BlockType','Outport'));
add_block('built-in/Outport',[loop '/framestat_stallcnt'],'Port',num2str(nOut3+1), ...
    'Position',[1000 1570 1030 1586]);
add_line(loop, 'FrameStatStallCnt/1', 'framestat_stallcnt/1', 'autorouting','on');
% 30.72M -> 15.36M into the probe (fast->slow RT of a level, RxReadyRT idiom;
% a stall in the RT-latency cycles at a frame edge lands in the next record --
% acceptable boundary skew, and the 0x1C4 counter itself is skew-free).
add_block('built-in/RateTransition', [loop '/FsStallRT'], ...
    'OutPortSampleTime','1/15.36e6', 'Position',[600 1570 640 1590]);
add_line(loop, 'FrameStatStallCnt/1', 'FsStallRT/1', 'autorouting','on');
add_line(loop, 'FsStallRT/1', 'FrameStatProbe/8', 'autorouting','on');

% ================================================================= (8) TX underrun
% TX-underrun witness (the ~72us TX-mute class + residual feeder gaps): the
% ByteBitShifter's UNDERFLOW RELOAD -- aligned, at a word boundary/frame start,
% with the TX byte FIFO empty -> it airs zeros and drops alignment
% (qpskByteBitShifterStrict.m). That branch is the ONLY aligned->unaligned
% transition WITHOUT a pop (the strict phase-error discard pops), so the
% wrapper detects it exactly: wasAligned && ~aligned && ~pop. One event ==
% the modulator starved mid-frame (zeros aired for the frame remainder).
% Surfaced Input Data -> Transmitter -> composite (fs_runmax surfacing idiom),
% counted FREE-RUNNING 32-bit at 0x1C8 (free in LEAN; p1b_pa_w1 owns it in
% non-LEAN debug -- p1b assert above), latched per-record as bit [10].
% The chart edit is env-gated with the whole overlay => G0 preserved.
bbsCh = sfroot().find('-isa','Stateflow.EMChart','Path',[idPath '/ByteBitShifter']);
assert(~isempty(bbsCh), 'framestat_overlay: ByteBitShifter chart not found');
bbsCh = bbsCh(1);
assert(contains(bbsCh.Script, 'function [bit, popToggle] = byteBitShifterBlk'), ...
    'framestat_overlay: ByteBitShifter wrapper signature drifted -- update section (8)');
if contains(bbsCh.Script, 'qpskByteBitShifterStrict')
    shifterFcn = 'qpskByteBitShifterStrict';
else
    shifterFcn = 'qpskByteBitShifter';
end
bbsCh.Script = strrep(sprintf([ ...
'function [bit, popToggle, txur] = byteBitShifterBlk(enable, reset, start, extWord, extWordAvail, extWordFirst)\n' ...
'%% Block wrapper around SHIFTER_FCN (the unit-tested single source\n' ...
'%% of truth). Persistent state only; the effective enable matches the\n' ...
'%% Message Generator chart''s active condition (enable && ~reset) so the\n' ...
'%% shifter emits bits on exactly the generator''s bit steps. pop is\n' ...
'%% exported as a toggle (one flip per word latch OR discard) to survive\n' ...
'%% the slow->fast rate crossing; upstream edge-detects it into a pulse.\n' ...
'%% txur (framestat TX-underrun witness): one-step pulse when the shifter\n' ...
'%% hit its UNDERFLOW reload -- the only aligned->unaligned transition\n' ...
'%% without a pop (the strict phase-error discard pops). Zeros air.\n' ...
'persistent state tog\n' ...
'if isempty(state)\n' ...
'    state = SHIFTER_FCN();\n' ...
'    tog = false;\n' ...
'end\n' ...
'en = logical(enable) && ~logical(reset);\n' ...
'wasAligned = state.aligned;\n' ...
'[bit, pop, state] = SHIFTER_FCN(state, en, logical(start), ...\n' ...
'    uint64(extWord), logical(extWordAvail), logical(extWordFirst));\n' ...
'if pop\n' ...
'    tog = ~tog;\n' ...
'end\n' ...
'popToggle = tog;\n' ...
'txur = wasAligned && ~state.aligned && ~pop;\n']), 'SHIFTER_FCN', shifterFcn);
% surface: Input Data outport -> Transmitter outport -> composite
tx = [loop '/Transmitter'];
nOutId = numel(find_system(idPath,'SearchDepth',1,'LookUnderMasks','all', ...
    'FollowLinks','on','BlockType','Outport'));
add_block('built-in/Outport',[idPath '/fs_txur'],'Port',num2str(nOutId+1), ...
    'Position',[620 540 650 556]);
add_line(idPath, 'ByteBitShifter/3', 'fs_txur/1', 'autorouting','on');
nOutTx = numel(find_system(tx,'SearchDepth',1,'LookUnderMasks','all', ...
    'FollowLinks','on','BlockType','Outport'));
add_block('built-in/Outport',[tx '/fs_txur'],'Port',num2str(nOutTx+1), ...
    'Position',[700 800 730 816]);
add_line(tx, sprintf('Input Data/%d', nOutId+1), 'fs_txur/1', 'autorouting','on');
fprintf('framestat_overlay: TX underrun surfaced (Input Data out %d -> Transmitter out %d, %s)\n', ...
    nOutId+1, nOutTx+1, shifterFcn);
% free-running event counter at the composite (15.36M rail, same as the probe)
add_block('simulink/User-Defined Functions/MATLAB Function',[loop '/FrameStatTxUrCnt'], ...
    'Position',[820 1660 960 1720]);
set_fcn_script([loop '/FrameStatTxUrCnt'], sprintf([ ...
'function cnt = frameStatTxUrCnt(ur)\n' ...
'%%#codegen\n' ...
'%% free-running 32-bit TX-underrun EVENT counter: one count per\n' ...
'%% ByteBitShifter underflow reload (modulator starved -> zeros aired for\n' ...
'%% the frame remainder). Wraps mod 2^32 explicitly (FrameStatWordCnt idiom).\n' ...
'persistent c\n' ...
'if isempty(c)\n' ...
'    c = uint32(0);\n' ...
'end\n' ...
'cnt = c;\n' ...
'if ur\n' ...
'    if c == uint32(4294967295)\n' ...
'        c = uint32(0);\n' ...
'    else\n' ...
'        c = c + uint32(1);\n' ...
'    end\n' ...
'end\n']));
pin_types([loop '/FrameStatTxUrCnt'], struct('ur','boolean','cnt','uint32'));
add_line(loop, sprintf('Transmitter/%d', nOutTx+1), 'FrameStatTxUrCnt/1', 'autorouting','on');
nOut4 = numel(find_system(loop,'SearchDepth',1,'BlockType','Outport'));
add_block('built-in/Outport',[loop '/framestat_txurcnt'],'Port',num2str(nOut4+1), ...
    'Position',[1000 1670 1030 1686]);
add_line(loop, 'FrameStatTxUrCnt/1', 'framestat_txurcnt/1', 'autorouting','on');
add_line(loop, 'FrameStatTxUrCnt/1', 'FrameStatProbe/9', 'autorouting','on');

fprintf('framestat_overlay: STALL witness -> 0x1C4 (byte_rx_valid && !byte_rx_ready cycles), record bit [9]\n');
fprintf('framestat_overlay: TXUR witness -> 0x1C8 (shifter underflow events), record bit [10]\n');
fprintf(['framestat_overlay: DONE -- FrameStat FIFO (64-deep) head_lo/hi/stat -> ' ...
    '0x1D0/0x1D4/0x1D8, pop <- 0x1DC, wordcnt -> 0x1C0, stallcnt -> 0x1C4, txurcnt -> 0x1C8\n']);
end

% ===================== helpers =====================
function set_fcn_script(blk, src)
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',blk);
chart.Script = src;
end

function pin_types(blk, spec)
ch = sfroot().find('-isa','Stateflow.EMChart','Path',blk);
for d = ch.getChildren()'
    if ~isa(d,'Stateflow.Data'), continue; end
    if isfield(spec, d.Name), d.DataType = spec.(d.Name); end
end
end
