function p1d_pd_telemetry_overlay(sys, base)
% p1d_pd_telemetry_overlay -- LOSS-FREE beat-exact Preamble Detector
% state+input telemetry (P1C rev 2). Three fixes over p1c, driven by the
% 20260716 hunt findings:
%   * 7-word burst (dead corr slot dropped) -> >=1 idle beat/symbol of
%     elastic slack -> the ~2.3% whole-record losses go to ~zero;
%   * STICKY pulse flags (done/newPk/thrEx/sync/vPop OR-accumulated across
%     the symbol's beats, cleared at snapshot) -> 1-beat pulses can no
%     longer alias away (p1c read them 0 at every strobe);
%   * 3-bit beat-phase field = beats since the previous strobe (saturating
%     at 7) -> the 7/8/9-beat symbol structure is recorded per record.
%
% Slot layout (tag 0xE distinguishes the 7-slot format from p1c's 0xD):
%   S0 {tag=0xE[31:28], tRef[27:17], tOff[16:6],
%       done,newPk,succ,thrEx,sync,armed[5:0]}   (done/newPk/thrEx/sync sticky)
%   S1 {dataI[31:16], dataQ[15:0]}       <-- the exact PD input symbol
%   S2 {taRef[31:21], accOff[20:10], fifoEnt[9:1], vPop_sticky[0]}
%   S3 tRefLong[31:0]
%   S4 runningMax[31:0]                  (SI of sfix32_En26)
%   S5 heldPeakTs[31:0]
%   S6 {0xA5[31:24], beat[23:21], symCtr[20:0]}
% Idle beats emit 0x00000000 (no tag; parser skips).
%
% Wiring identical to p1c minus the corr input (18 MLFB inputs). All ports
% pinned + DTC-SI isolated. LEAN debug-mux mode 4.

if nargin < 1 || isempty(sys),  sys  = bdroot; end
if nargin < 2 || isempty(base), base = sys;    end

rcv = [base '/Receiver'];
qrx = [rcv '/QPSK Rx'];
fts = [qrx '/Frequency and Time Synchronizer'];
pd  = [fts '/Preamble Detector'];
ps  = [pd '/Peak Search'];
ta  = [pd '/Timing Adjust'];

if ~isempty(find_system(pd,'SearchDepth',1,'LookUnderMasks','all', ...
        'FollowLinks','on','Name','PdTelemetry'))
    fprintf('p1d_pd_telemetry_overlay: already present -- skipping\n');
    return;
end

lo = 'LookUnderMasks';
nl = sprintf('\n');

% ---------- 1. surface Peak Search internals (inside the mask) ----------
nPs = numel(find_system(ps,'SearchDepth',1,lo,'all','BlockType','Outport'));
psAdd = { ...
    'timing Reference',                                'p1c_tref'; ...
    'timing Reference Long',                           'p1c_treflong'; ...
    ['Unit Delay Enabled Resettable' nl 'Synchronous'],'p1c_runmax'; ...
    ['Logical' nl 'Operator4'],                        'p1c_newpk'; ...
    ['Unit Delay Enabled' nl 'Synchronous1'],          'p1c_heldts'};
psPorts = zeros(1,size(psAdd,1));
for k = 1:size(psAdd,1)
    add_block('built-in/Outport',[ps '/' psAdd{k,2}],'Port',num2str(nPs+k), ...
        'Position',[1400 300+30*k 1430 316+30*k]);
    add_line(ps, [psAdd{k,1} '/1'], [psAdd{k,2} '/1'], 'autorouting','on');
    psPorts(k) = nPs+k;
end
fprintf('p1d: Peak Search internals surfaced (%d ports)\n', size(psAdd,1));

% ---------- 2. surface Timing Adjust internals ----------
nTa = numel(find_system(ta,'SearchDepth',1,lo,'all','BlockType','Outport'));
taAdd = { ...
    'State Register',                          'p1c_armed'; ...
    'timing Reference',                        'p1c_taref'; ...
    ['Unit Delay Enabled' nl 'Synchronous3'],  'p1c_accoff'};
taPorts = zeros(1,size(taAdd,1));
for k = 1:size(taAdd,1)
    add_block('built-in/Outport',[ta '/' taAdd{k,2}],'Port',num2str(nTa+k), ...
        'Position',[1400 300+30*k 1430 316+30*k]);
    add_line(ta, [taAdd{k,1} '/1'], [taAdd{k,2} '/1'], 'autorouting','on');
    taPorts(k) = nTa+k;
end
fprintf('p1d: Timing Adjust internals surfaced (%d ports)\n', size(taAdd,1));

% ---------- 3. the PD-level telemetry MLFB (7-slot, sticky, beat-phase) ----------
add_block('simulink/User-Defined Functions/MATLAB Function',[pd '/PdTelemetry'], ...
    'Position',[1500 700 1650 950]);
set_fcn_script([pd '/PdTelemetry'], sprintf([ ...
'function [telI, telQ] = pdTelemetry(validIn, dI, dQ, thrEx, tRef, tOff, ' ...
'done, newPk, succ, sync, armed, taRef, accOff, fifoEnt, vPop, tRefLong, runMax, heldTs)\n' ...
'%%#codegen\n' ...
'persistent slot symCtr beatCnt aDone aNewPk aThrEx aSync aVPop s0 s1 s2 s3 s4 s5 s6\n' ...
'if isempty(slot)\n' ...
'    slot = uint8(7); symCtr = uint32(0); beatCnt = uint8(0);\n' ...
'    aDone = false; aNewPk = false; aThrEx = false; aSync = false; aVPop = false;\n' ...
'    s0 = uint32(0); s1 = uint32(0); s2 = uint32(0); s3 = uint32(0);\n' ...
'    s4 = uint32(0); s5 = uint32(0); s6 = uint32(0);\n' ...
'end\n' ...
'aDone = aDone || done; aNewPk = aNewPk || newPk; aThrEx = aThrEx || thrEx;\n' ...
'aSync = aSync || sync; aVPop = aVPop || vPop;\n' ...
'if beatCnt < uint8(7), beatCnt = beatCnt + uint8(1); end\n' ...
'if validIn\n' ...
'    symCtr = symCtr + uint32(1);\n' ...
'    flags = uint32(aDone) + bitshift(uint32(aNewPk),1) + bitshift(uint32(succ),2) + ...\n' ...
'            bitshift(uint32(aThrEx),3) + bitshift(uint32(aSync),4) + bitshift(uint32(armed),5);\n' ...
'    s0 = bitor(bitor(bitor(bitshift(uint32(14),28), bitshift(uint32(bitand(tRef,uint16(2047))),17)), ...\n' ...
'         bitshift(uint32(bitand(tOff,uint16(2047))),6)), flags);\n' ...
'    s1 = bitor(bitshift(uint32(reinterpretcast(dI,numerictype(0,16,0))),16), ...\n' ...
'         uint32(reinterpretcast(dQ,numerictype(0,16,0))));\n' ...
'    s2 = bitor(bitor(bitor(bitshift(uint32(bitand(taRef,uint16(2047))),21), ...\n' ...
'         bitshift(uint32(bitand(accOff,uint16(2047))),10)), ...\n' ...
'         bitshift(uint32(bitand(fifoEnt,uint16(511))),1)), uint32(aVPop));\n' ...
'    s3 = tRefLong;\n' ...
'    s4 = runMax;\n' ...
'    s5 = heldTs;\n' ...
'    s6 = bitor(bitor(bitshift(uint32(165),24), bitshift(uint32(bitand(uint16(beatCnt),uint16(7))),21)), ...\n' ...
'         bitand(symCtr,uint32(2097151)));\n' ...
'    aDone = false; aNewPk = false; aThrEx = false; aSync = false; aVPop = false;\n' ...
'    beatCnt = uint8(0);\n' ...
'    slot = uint8(0);\n' ...
'end\n' ...
'switch slot\n' ...
'  case uint8(0), w = s0;\n' ...
'  case uint8(1), w = s1;\n' ...
'  case uint8(2), w = s2;\n' ...
'  case uint8(3), w = s3;\n' ...
'  case uint8(4), w = s4;\n' ...
'  case uint8(5), w = s5;\n' ...
'  case uint8(6), w = s6;\n' ...
'  otherwise,     w = uint32(0);\n' ...
'end\n' ...
'if slot < uint8(7), slot = slot + uint8(1); end\n' ...
'telI = reinterpretcast(uint16(bitshift(w, -16)), numerictype(1,16,0));\n' ...
'telQ = reinterpretcast(uint16(bitand(w, uint32(65535))), numerictype(1,16,0));\n']));
pin_types([pd '/PdTelemetry'], struct( ...
    'validIn','boolean','dI','int16','dQ','int16', ...
    'thrEx','boolean','tRef','uint16','tOff','uint16','done','boolean', ...
    'newPk','boolean','succ','boolean','sync','boolean','armed','boolean', ...
    'taRef','uint16','accOff','uint16','fifoEnt','uint16','vPop','boolean', ...
    'tRefLong','uint32','runMax','uint32','heldTs','uint32', ...
    'telI','fixdt(1,16,0)','telQ','fixdt(1,16,0)'));

% ---------- 4. wire the 18 inputs (DTC-SI isolation on non-boolean) ----------
    function siwire(srcSpec, dtcName, dtStr, dstPort)
        add_block('simulink/Signal Attributes/Data Type Conversion',[pd '/' dtcName], ...
            'OutDataTypeStr',dtStr,'ConvertRealWorld','Stored Integer (SI)', ...
            'Position',[1430 700+18*dstPort 1460 714+18*dstPort]);
        add_line(pd, srcSpec, [dtcName '/1'], 'autorouting','on');
        add_line(pd, [dtcName '/1'], sprintf('PdTelemetry/%d',dstPort), 'autorouting','on');
    end
% PD input pair + valid: trace the lines feeding the Correlator
lhC = get_param([pd '/Correlator'],'LineHandles');
srcD_re = get_param(lhC.Inport(1),'SrcPortHandle');
add_block('simulink/Math Operations/Complex to Real-Imag',[pd '/P1cSplit'], ...
    'Output','Real and imag','Position',[1380 660 1410 690]);
phSplit = get_param([pd '/P1cSplit'],'PortHandles');
add_line(pd, srcD_re, phSplit.Inport(1), 'autorouting','on');
for kk = 1:2
    dn = sprintf('P1cDSi%d', kk);
    add_block('simulink/Signal Attributes/Data Type Conversion',[pd '/' dn], ...
        'OutDataTypeStr','fixdt(1,16,0)','ConvertRealWorld','Stored Integer (SI)', ...
        'Position',[1420 655+20*kk 1450 669+20*kk]);
    add_line(pd, sprintf('P1cSplit/%d',kk), [dn '/1'], 'autorouting','on');
    add_line(pd, [dn '/1'], sprintf('PdTelemetry/%d',kk+1), 'autorouting','on');
end
% validIn = the Correlator's valid input
srcV = get_param(lhC.Inport(2),'SrcPortHandle');
phT = get_param([pd '/PdTelemetry'],'PortHandles');
add_line(pd, srcV, phT.Inport(1), 'autorouting','on');
% thresholdExceeded: Peak Search inport 2 line (corr slot dropped in p1d)
lhPS = get_param(ps,'LineHandles');
add_line(pd, get_param(lhPS.Inport(2),'SrcPortHandle'), phT.Inport(4), 'autorouting','on');
% Peak Search internals (surfaced above) + existing outputs
siwire(sprintf('Peak Search/%d', psPorts(1)), 'P1cTrefSi',   'fixdt(0,16,0)', 5);
siwire('Peak Search/1',                       'P1cToffSi',   'fixdt(0,16,0)', 6);
add_line(pd, 'Peak Search/2', 'PdTelemetry/7',  'autorouting','on');  % done
add_line(pd, sprintf('Peak Search/%d', psPorts(4)), 'PdTelemetry/8', 'autorouting','on'); % newPk
add_line(pd, 'Peak Search/3', 'PdTelemetry/9', 'autorouting','on');   % success
add_line(pd, 'Timing Adjust/3', 'PdTelemetry/10', 'autorouting','on');% sync
add_line(pd, sprintf('Timing Adjust/%d', taPorts(1)), 'PdTelemetry/11', 'autorouting','on'); % armed
siwire(sprintf('Timing Adjust/%d', taPorts(2)), 'P1cTaRefSi', 'fixdt(0,16,0)', 12);
siwire(sprintf('Timing Adjust/%d', taPorts(3)), 'P1cAccSi',   'fixdt(0,16,0)', 13);
siwire('FIFO/2',                                'P1cEntSi',   'fixdt(0,16,0)', 14);
add_line(pd, 'FIFO/3', 'PdTelemetry/15', 'autorouting','on');         % vPop
siwire(sprintf('Peak Search/%d', psPorts(2)), 'P1cTlongSi', 'fixdt(0,32,0)', 16);
siwire(sprintf('Peak Search/%d', psPorts(3)), 'P1cRmaxSi',  'fixdt(0,32,0)', 17);
siwire(sprintf('Peak Search/%d', psPorts(5)), 'P1cHeldSi',  'fixdt(0,32,0)', 18);

% ---------- 5. surface the stream + widen the debug mux ----------
gnames = {'p1c_telI','p1c_telQ'};
nPd = numel(find_system(pd,'SearchDepth',1,lo,'all','BlockType','Outport'));
for k = 1:2
    add_block('built-in/Outport',[pd '/' gnames{k}],'Port',num2str(nPd+k), ...
        'Position',[1700 700+30*k 1730 716+30*k]);
    add_line(pd, sprintf('PdTelemetry/%d',k), [gnames{k} '/1'], 'autorouting','on');
end
% surface PD -> FTS only; the mux lives at QRX and reads the FTS ports
pdTelPorts = [nPd+1, nPd+2];
nFts0 = numel(find_system(fts,'SearchDepth',1,lo,'all','BlockType','Outport'));
ftsPorts = [nFts0+1, nFts0+2];
for k = 1:2
    add_block('built-in/Outport',[fts '/' gnames{k}],'Port',num2str(ftsPorts(k)), ...
        'Position',[1700 1400+26*ftsPorts(k) 1730 1416+26*ftsPorts(k)]);
    add_line(fts, sprintf('Preamble Detector/%d', pdTelPorts(k)), [gnames{k} '/1'], 'autorouting','on');
end
mux = find_system(qrx,'SearchDepth',1,lo,'all','BlockType','MultiPortSwitch');
assert(numel(mux)==1, 'p1d: expected one debug MultiPortSwitch');
mux = mux{1};
nIn = str2double(get_param(mux,'Inputs'));
set_param(mux,'Inputs',num2str(nIn+1));
add_block('simulink/Math Operations/Real-Imag to Complex',[qrx '/P1cToCplx'], ...
    'Input','Real and imag','Position',[1450 1700 1490 1740]);
add_line(qrx, sprintf('Frequency and Time Synchronizer/%d', ftsPorts(1)), 'P1cToCplx/1', 'autorouting','on');
add_line(qrx, sprintf('Frequency and Time Synchronizer/%d', ftsPorts(2)), 'P1cToCplx/2', 'autorouting','on');
add_block('simulink/Signal Attributes/Data Type Conversion',[qrx '/P1cDtc'], ...
    'OutDataTypeStr','fixdt(1,16,14)','ConvertRealWorld','Stored Integer (SI)', ...
    'Position',[1510 1705 1550 1735]);
add_line(qrx, 'P1cToCplx/1', 'P1cDtc/1', 'autorouting','on');
add_line(qrx, 'P1cDtc/1', sprintf('%s/%d', get_param(mux,'Name'), nIn+2), 'autorouting','on');

fprintf('p1d_pd_telemetry_overlay: DONE (7-slot loss-free PD stream on debug-mux mode %d)\n', nIn);
end

% ===================== helpers =====================
function set_fcn_script(blk, src)
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',blk);
chart.Script = src;
end

function pin_types(blk, spec)
ch = sfroot().find('-isa','Stateflow.EMChart','Path',blk);
for d = ch.getChildren()'
    if ~isa(d,'Stateflow.Data'), continue; end
    if isfield(spec, d.Name), d.DataType = spec.(d.Name); end
end
end
