#!/bin/bash
# build_seqbist_gate.sh -- build the SEQ-BIST T0c full-loop sim gate harness
# (wrap_byte_seqbist.v + sim_byte_seqbist.cpp) against the FLASHED 148 lineage
# netlist snapshot rtl_sim/s1_rtl_txfix_F3/hdlsrc/commhdlQPSKTxRxLoopback
# (cadence 2 -- TxRxComposite.v:480 ties MUX_RxValid_out1=1).
#
# The three SEQ-BIST modules (rx_seq_checker.v, cnt_mux32.v,
# qpsk_traffic_gen_v2.v) live in rtl_sim/, not in the netlist, so the build
# needs BOTH -y directories.
#
# Runs under `systemd-run --user` (transient unit, survives an agent session;
# never a harness background task -- see MEMORY background-jobs-systemd-run) and
# logs to beat_runs/seqbist_build.log.  Re-exec into the unit is automatic.
#
#   ./build_seqbist_gate.sh            # launch the build unit and return
#   ./build_seqbist_gate.sh --wait     # launch and block until it finishes
#
# Stamps seqbist_build_stamp.h with the rx_seq_checker git sha and the interval
# UNITS the compiled RTL implements (seqdelta = emitted frames, per the
# 2026-09-03 operator ruling; received = the pre-fix contract).  The scorer
# refuses to score a run whose stamped units do not match the gate's
# expectation, so a stale rebuild cannot produce a wrong-unit PASS.
set -u -o pipefail
R=$(cd "$(dirname "$0")" && pwd)
VD=${SEQBIST_NETLIST:-$R/s1_rtl_txfix_F3/hdlsrc/commhdlQPSKTxRxLoopback}
TAG=${SEQBIST_TAG:-seqbist_gate}
LOG=$R/beat_runs/seqbist_build.log
UNIT=seqbist-build-$(date +%s)-$$

if [ "${SEQBIST_IN_UNIT:-0}" != "1" ]; then
  [ -f "$VD/TxRxComposite.v" ] || { echo "FATAL: no netlist at $VD" >&2; exit 1; }
  mkdir -p "$R/beat_runs"
  : > "$LOG"
  systemd-run --user --collect --unit="$UNIT" \
    --working-directory="$R" \
    -p StandardOutput=append:"$LOG" -p StandardError=append:"$LOG" \
    -E SEQBIST_IN_UNIT=1 -E SEQBIST_NETLIST="$VD" -E SEQBIST_TAG="$TAG" \
    /bin/bash "$R/build_seqbist_gate.sh" || exit 1
  echo "SEQBIST_BUILD_LAUNCHED unit=$UNIT log=$LOG"
  if [ "${1:-}" = "--wait" ]; then
    while systemctl --user is-active "$UNIT" >/dev/null 2>&1; do sleep 5; done
    tail -3 "$LOG"
  fi
  exit 0
fi

# ---------------- inside the transient unit ----------------
export PATH=/usr/local/bin:/usr/bin:/bin
cd "$R" || exit 1
echo "SEQBIST_BUILD_START $(date -Iseconds) netlist=$VD"

# --- build stamp: rx_seq_checker sha + the interval units it implements ---
SHA=$(git -C "$R" log -1 --format=%h -- rx_seq_checker.v 2>/dev/null)
[ -n "$SHA" ] || SHA=unknown
if grep -q 'prev_gap_seq' rx_seq_checker.v; then UNITS=seqdelta
elif grep -q 'prev_gap_mark' rx_seq_checker.v; then UNITS=received
else UNITS=unknown; fi
DIRTY=""
[ -z "$(git -C "$R" status --porcelain -- rx_seq_checker.v 2>/dev/null)" ] || DIRTY="+dirty"
cat > seqbist_build_stamp.h <<EOF
// generated by build_seqbist_gate.sh -- do not edit
#define SEQBIST_RTL_SHA   "${SHA}${DIRTY}"
#define SEQBIST_INT_UNITS "${UNITS}"
EOF
echo "SEQBIST_BUILD_STAMP rtl_sha=${SHA}${DIRTY} int_units=${UNITS}"

OBJ=obj_${TAG}
rm -rf "$OBJ"
T0=$(date +%s)
verilator -O2 -Wno-fatal --cc wrap_byte_seqbist.v -y "$VD" -y "$R" \
  --exe sim_byte_seqbist.cpp -CFLAGS "-I$R" \
  -Mdir "$OBJ" --top-module wrap_byte_seqbist || { echo "SEQBIST_BUILD_EXIT=1"; exit 1; }
make -s -C "$OBJ" -f Vwrap_byte_seqbist.mk Vwrap_byte_seqbist \
  || { echo "SEQBIST_BUILD_EXIT=2"; exit 2; }
T1=$(date +%s)
echo "SEQBIST_BUILD_DONE $R/$OBJ/Vwrap_byte_seqbist secs=$((T1-T0)) rtl_sha=${SHA}${DIRTY} int_units=${UNITS}"
echo "SEQBIST_BUILD_EXIT=0"
