#!/usr/bin/env python3
"""gen_inject_map.py <Vtop___024root.h> <out_header> [--prefixes p1,p2,...]

T8.7 state-injection map generator: scans the Verilated flat-root header for
register members under the given hierarchical prefixes (Verilator mangles
hierarchy as name__DOT__name) and emits a C++ header with a name->accessor
table (getter + setter, masked to declared width) usable by sim_byte_inject.

Default prefixes cover the synchronizer chain (the T8.7 capture scope);
shadow/canary instrumentation instances are excluded (they are re-derived,
not injected). Handles CData/SData/IData/QData members and 1-D VlUnpacked
arrays of them (emitted as name[i] entries). Wide (>64b) members are skipped
with a warning (none exist in the capture scope today).
"""
import sys, re

DEF_PREFIXES = [
    'u_Automatic_Gain_Control',
    'u_Symbol_Synchronizer',
    'u_Coarse_Frequency_Compensator',
    'u_Carrier_Synchronizer',
    'u_Preamble_Detector',
    'u_Phase_Ambiguity_Estimation_and_Correction',
    'u_Packet_Controller',
]
EXCLUDE = ['Shadow', 'ShadowScore', 'NcoCanary', 'Canary']

def main():
    hdr, out = sys.argv[1], sys.argv[2]
    prefixes = DEF_PREFIXES
    if len(sys.argv) > 3 and sys.argv[3] == '--prefixes':
        prefixes = sys.argv[4].split(',')
    # member decls look like:  CData/*0:0*/ name;  IData/*20:0*/ name;
    #   VlUnpacked<SData/*12:0*/, 2> name;
    rx_plain = re.compile(r'^\s*([CSIQ]Data)/\*(\d+):(\d+)\*/\s+(\w+);')
    rx_arr   = re.compile(r'^\s*VlUnpacked<([CSIQ]Data)/\*(\d+):(\d+)\*/,\s*(\d+)>\s+(\w+);')
    entries = []
    skipped = 0
    for line in open(hdr):
        m = rx_plain.match(line); a = rx_arr.match(line)
        name = m.group(4) if m else (a.group(5) if a else None)
        if not name: continue
        if '__DOT__' not in name: continue
        parts = name.split('__DOT__')
        if not any(p in parts for p in prefixes): continue
        if any(x in name for x in EXCLUDE): continue
        msb = int((m or a).group(2))
        if msb > 63: skipped += 1; continue
        mask = (1 << (msb + 1)) - 1
        typ=(m or a).group(1)
        if m:
            entries.append((name, mask, typ, None, 0))
        else:
            for i in range(int(a.group(4))):
                entries.append((f'{name}[{i}]', mask, typ, name, i))
    with open(out, 'w') as f:
        f.write('// generated by gen_inject_map.py -- do not edit\n')
        f.write('#include <cstdint>\n#include <cstddef>\n#include <cstring>\n')
        f.write('struct InjEntry { const char* name; uint64_t mask; size_t off; uint8_t width; };\n')
        f.write('static inline uint64_t inj_get(Vwrap_byte_taps___024root* r, const InjEntry& e){\n')
        f.write('  const char* p = reinterpret_cast<const char*>(r) + e.off;\n')
        f.write('  switch(e.width){ case 1: return *(const uint8_t*)p; case 2: return *(const uint16_t*)p;\n')
        f.write('    case 4: return *(const uint32_t*)p; default: return *(const uint64_t*)p; } }\n')
        f.write('static inline void inj_set(Vwrap_byte_taps___024root* r, const InjEntry& e, uint64_t v){\n')
        f.write('  char* p = reinterpret_cast<char*>(r) + e.off;\n')
        f.write('  switch(e.width){ case 1: *(uint8_t*)p = v; break; case 2: *(uint16_t*)p = v; break;\n')
        f.write('    case 4: *(uint32_t*)p = v; break; default: *(uint64_t*)p = v; break; } }\n')
        f.write('#pragma GCC diagnostic ignored "-Winvalid-offsetof"\n')
        f.write('static const InjEntry INJ_TABLE[] = {\n')
        W = {'CData':1,'SData':2,'IData':4,'QData':8}
        for name, mask, typ, arrbase, idx in entries:
            if arrbase is None:
                off = 'offsetof(Vwrap_byte_taps___024root, %s)' % name
            else:
                # VlUnpacked<T,N> stores a plain T m_storage[N] as its sole member
                off = 'offsetof(Vwrap_byte_taps___024root, %s) + %d*%d' % (arrbase, idx, W[typ])
            f.write('  {"%s", 0x%xULL, %s, %d},\n' % (name, mask, off, W[typ]))
        f.write('};\nstatic const int INJ_N = %d;\n' % len(entries))
    print(f'inject map: {len(entries)} entries ({skipped} wide skipped) -> {out}')

if __name__ == '__main__':
    main()
