// sim_byte_s2mm.cpp -- EGRESS reproduction harness (extends sim_byte.cpp).
//
// GOAL: reproduce (or refute) the on-silicon W0x5 byte-egress replication by
// driving the REAL generated byte-egress RTL (Serializer -> ByteRxFifo -> AXIS
// byte_rx_* pins, via wrap_byte.v) with a REALISTIC axi_dmac S2MM acceptance:
//   - descriptor-prime delay: byte_rx_ready held LOW for PRIME cycles at the
//     start of each frame transfer (emulates descriptor fetch before 1st ready)
//   - per-beat ready with GAP-cycle gaps between accepted beats
// (The shipped netlist gate tied byte_rx_ready=1 permanently -- it never modeled
//  S2MM backpressure. That omission is the reproduction key per BYTEPLANE.)
//
// It records TWO DDR-write models to localize the seam:
//   (A) CORRECT S2MM  : DDR write == accepted AXIS beat (valid && ready).
//   (B) HAZARD S2MM   : a *broken* DMA that issues a DDR write every cycle it is
//       "mid-transfer" sampling the held tdata, but only pulses tready every
//       (GAP+1) cycles. This is the write-before-accept decoupling BYTEPLANE
//       fingers. It is a HYPOTHESIS demonstrator, NOT the real IP.
//
// argv: tx_words.hex total_clks rot out_prefix [PRIME] [GAP]
#include "Vwrap_byte.h"
#include "verilated.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
int main(int argc, char** argv){
    Verilated::commandArgs(argc,argv);
    if(argc < 5){ fprintf(stderr,"usage: sim_byte_s2mm tx_words.hex total_clks rot out_prefix [PRIME] [GAP]\n"); return 2; }
    std::vector<unsigned long long> words;
    { FILE* f=fopen(argv[1],"r"); if(!f){ fprintf(stderr,"no %s\n",argv[1]); return 2; }
      char ln[128];
      while(fgets(ln,sizeof ln,f)){ if(ln[0]=='\n') continue;
          words.push_back(strtoull(ln,nullptr,16)); }
      fclose(f); }
    const unsigned NW = (unsigned)words.size();
    if(NW==0){ fprintf(stderr,"empty word file %s\n",argv[1]); return 2; }
    long total=atol(argv[2]); int rot=atoi(argv[3]);
    int PRIME = (argc>5)?atoi(argv[5]):5;   // descriptor-prime low cycles / frame
    int GAP   = (argc>6)?atoi(argv[6]):3;   // low cycles between accepted beats
    char fn[512];
    snprintf(fn,sizeof fn,"%s_rxw.txt",argv[4]); FILE* fr=fopen(fn,"w");   // accepted beats
    snprintf(fn,sizeof fn,"%s_ddrA.txt",argv[4]); FILE* fA=fopen(fn,"w");  // correct-DMA DDR
    snprintf(fn,sizeof fn,"%s_ddrB.txt",argv[4]); FILE* fB=fopen(fn,"w");  // hazard-DMA DDR
    Vwrap_byte* t=new Vwrap_byte;
    long clk=0; unsigned idx=(unsigned)rot;
    t->reset=1; t->adc_validIn=0; t->adc_dataInI=0; t->adc_dataInQ=0;
    t->rstCS=0; t->rx_input_select=0; t->skip_count=0;
    t->tx_data_source=1;
    t->byte_valid=1; t->byte_rx_ready=0;   // start with ready LOW (pre-prime)
    t->byte_data=words[idx]; t->byte_first=(idx==0);
    for(int i=0;i<100;i++){ t->clk=0; t->eval(); t->clk=1; t->eval(); clk++; }
    t->reset=0;
    long nrxw=0, nddrA=0, nddrB=0;
    // ---- S2MM ready model state ----
    int primeLeft = PRIME;      // start every frame with a descriptor prime
    int gapLeft   = 0;
    bool sawFirstThisXfer=false;
    while(clk<total){
        // AXIS byte source into the fabric (registered handshake, ready&&valid)
        if(t->byte_ready && t->byte_valid){ idx = (idx+1)%NW; }
        t->byte_data=words[idx]; t->byte_first=(idx==0); t->byte_valid=1;
        t->adc_validIn = (clk&1)?0:1;

        // ---- compute this cycle's byte_rx_ready from the S2MM model ----
        // A new frame's word0 waiting (valid && user) starts a descriptor prime.
        bool wordWaiting = t->byte_rx_valid;
        bool isFirst     = t->byte_rx_valid && t->byte_rx_user;
        if(isFirst && !sawFirstThisXfer){ primeLeft = PRIME; sawFirstThisXfer=true; }
        int ready;
        if(!wordWaiting){ ready=0; }
        else if(primeLeft>0){ ready=0; primeLeft--; }
        else if(gapLeft>0){ ready=0; gapLeft--; }
        else { ready=1; }
        t->byte_rx_ready = ready;

        // settle combinational outputs with this cycle's inputs (pre-edge)
        t->clk=0; t->eval();

        // ---- HAZARD DDR model (B): a broken DMA writes the held tdata EVERY
        // cycle it is mid-transfer (valid high) regardless of ready -> what WOULD
        // land in DDR if writes were decoupled from tready acceptance. ----
        if(t->byte_rx_valid){
            fprintf(fB,"%016llx,%d,%d\n",(unsigned long long)t->byte_rx_data,
                    (int)t->byte_rx_last,(int)t->byte_rx_user); nddrB++;
        }
        // ---- accepted AXIS beat: qualified valid && ready, SAMPLED PRE-EDGE
        // (the beat the FIFO's rd pointer will advance past on the coming posedge)
        // == CORRECT DMA DDR write (A). One record per accepted beat. ----
        bool accept = t->byte_rx_valid && t->byte_rx_ready;
        unsigned long long adata=t->byte_rx_data; int alast=t->byte_rx_last, auser=t->byte_rx_user;
        if(accept){
            fprintf(fr,"%016llx,%d,%d\n",adata,alast,auser); nrxw++;
            fprintf(fA,"%016llx,%d,%d\n",adata,alast,auser); nddrA++;
            gapLeft = GAP;                                 // space out next accept
            if(alast){ sawFirstThisXfer=false; }           // next frame re-primes
        }

        t->clk=1; t->eval(); clk++;   // posedge: rd/source advance
    }
    fclose(fr); fclose(fA); fclose(fB);
    printf("S2MM rot=%d PRIME=%d GAP=%d accepted=%ld ddrA=%ld ddrB(hazard)=%ld capout=%08x\n",
           rot,PRIME,GAP,nrxw,nddrA,nddrB,t->cap_out);
    delete t; return 0;
}
