#!/usr/bin/env python3
"""Generate beatila3_debug.xdc -- implementation-side debug-core insertion for the
BEATILA-3 on-silicon observability ILA (BEATILA3_DESIGN.md), written against net
names VERIFIED in build-1's routed DCP by beatila3_preflight.tcl (v2) on 2026-08-20.

The XDC is processed at opt_design (the standard Set-Up-Debug output form); it is
added used_in_synthesis=false so synthesis is untouched. If any net name misses in
the new build, insertion leaves an unconnected port and the post-impl gate
(BEATILA3_ILA_OK) hard-fails the build.

usage: gen_beatila3_xdc.py <out_xdc>
"""
import sys

P = "i_system_wrapper/system_i/TxRxCompo_ip_0/inst/u_TxRxCompo_ip_dut_inst/u_TxRxCompo_ip_src_TxRxComposite"
DEMOD = P + "/u_Receiver/u_QPSK_Rx/u_QPSK_Demodulator"
AVG   = P + "/u_Receiver/u_QPSK_Rx/u_Frequency_and_Time_Synchronizer/u_Phase_Ambiguity_Estimation_and_Correction/u_Average_Estimates"

# probe list: (comment, [net names]) -- ALL names verified in the routed DCP
PROBES = [
    ("trig (burst_det scheduled force)", ["i_system_wrapper/system_i/burst_det_trig"]),
    ("decision pair u0,u1 (Delay12)", [DEMOD + "/Delay12_out1_2[0]", DEMOD + "/Delay12_out1_2[1]"]),
    ("serializer phase counter", [DEMOD + "/u_Serializer/HDL_Counter_out1_reg_n_0"]),
    ("dataOut = coded-bit stream into FEC", ["@DATAOUT@"]),
    ("startOut (frame alignment)", [DEMOD + "/Delay10_out1_reg_1"]),
    ("validOut", [DEMOD + "/Delay9_out1_reg_0"]),
    ("avgEst_re top bits (resolution latch)", [AVG + "/Unit_Delay_Enabled_Synchronous_out1_re_reg[17]_0[%d]" % i for i in range(8)]),
    ("avgEst_im top bits (resolution latch)", [AVG + "/Unit_Delay_Enabled_Synchronous_out1_im_reg[17]_0[%d]" % i for i in range(8)]),
    ("gated rail copy A (Receiver)", [P + "/u_Receiver/enb_1_2_0_gated"]),
    ("gated rail copy B (RxAlign/FEC)", ["i_system_wrapper/system_i/TxRxCompo_ip_0/inst/u_TxRxCompo_ip_dut_inst/u_TxRxCompo_ip_src_TxRxComposite/u_QPSK_Rx/u_FEC_Decoder_Wrapper/u_RxAlign/enb_1_2_0_gated"]),
]
CLK = "i_system_wrapper/system_i/axi_adrv9001_adc_1_clk"

def main():
    out = sys.argv[1]
    dataout = sys.argv[2] if len(sys.argv) > 2 else None
    lines = []
    lines.append("# beatila3_debug.xdc -- generated by gen_beatila3_xdc.py; do not hand-edit.")
    lines.append("create_debug_core u_ila_beat3 ila")
    lines.append("set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_beat3]")
    lines.append("set_property C_TRIGIN_EN false [get_debug_cores u_ila_beat3]")
    lines.append("set_property C_TRIGOUT_EN false [get_debug_cores u_ila_beat3]")
    lines.append("set_property C_ADV_TRIGGER false [get_debug_cores u_ila_beat3]")
    lines.append("set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_beat3]")
    lines.append("set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_beat3]")
    lines.append("set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_beat3]")
    lines.append("set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_beat3]")
    lines.append("set_property port_width 1 [get_debug_ports u_ila_beat3/clk]")
    lines.append("connect_debug_port u_ila_beat3/clk [get_nets [list %s ]]" % CLK)
    for i, (cmt, nets) in enumerate(PROBES):
        nets = [dataout if n == "@DATAOUT@" else n for n in nets]
        if any(n is None for n in nets):
            print("FATAL: dataOut net not supplied"); sys.exit(1)
        port = "u_ila_beat3/probe%d" % i
        if i > 0:
            lines.append("create_debug_port u_ila_beat3 probe")
        lines.append("# probe%d: %s" % (i, cmt))
        lines.append("set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports %s]" % port)
        lines.append("set_property port_width %d [get_debug_ports %s]" % (len(nets), port))
        lines.append("connect_debug_port %s [get_nets [list %s ]]" % (port, " ".join("{%s}" % n for n in nets)))
    open(out, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d probes)" % (out, len(PROBES)))

if __name__ == "__main__":
    main()
