// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/BeatObs.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BeatObs
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/BeatObs
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BeatObs
          (dOut,
           sOut,
           vOut,
           decis_0,
           decis_1,
           rhc,
           pushc,
           popc,
           dbgI1,
           dbgQ1);


  input   [15:0] dOut;  // uint16
  input   [15:0] sOut;  // uint16
  input   [15:0] vOut;  // uint16
  input   [15:0] decis_0;  // uint16
  input   [15:0] decis_1;  // uint16
  input   [15:0] rhc;  // uint16
  input   [15:0] pushc;  // uint16
  input   [15:0] popc;  // uint16
  output  [15:0] dbgI1;  // uint16
  output  [15:0] dbgQ1;  // uint16


  wire [15:0] decis [0:1];  // uint16 [2]
  wire [31:0] fill8;  // uint32
  wire [31:0] acc;  // uint32
  wire [31:0] qcc;  // uint32
  wire [31:0] acc_1;  // uint32
  wire [31:0] acc_2;  // uint32
  wire [31:0] acc_3;  // uint32
  wire [31:0] acc_4;  // uint32
  wire [31:0] acc_5;  // uint32
  wire [31:0] acc_6;  // uint32
  wire signed [32:0] sub_temp;  // sfix33
  wire [31:0] cast;  // uint32
  wire [31:0] s;  // uint32
  wire [31:0] s_1;  // uint32
  wire [31:0] s_2;  // uint32
  wire [31:0] s_3;  // uint32
  wire [31:0] add_cast;  // uint32
  wire [63:0] add_cast_1;  // ufix64
  wire [31:0] add_cast_2;  // uint32
  wire [31:0] add_cast_3;  // uint32
  wire [31:0] s_4;  // uint32
  wire signed [32:0] s_5;  // sfix33
  wire [31:0] s_6;  // uint32
  wire signed [32:0] s_7;  // sfix33
  wire s_8;
  wire [31:0] s_9;  // uint32
  wire [63:0] mul_temp;  // ufix64
  wire [31:0] s_10;  // uint32
  wire [63:0] mul_temp_1;  // ufix64
  wire [31:0] s_11;  // uint32


  assign decis[0] = decis_0;
  assign decis[1] = decis_1;

  assign s_4 = {16'b0, pushc};
  assign s_5 = {1'b0, s_4};
  assign s_6 = {16'b0, popc};
  assign s_7 = {1'b0, s_6};
  assign sub_temp = s_5 - s_7;
  assign cast = (sub_temp[32] == 1'b1 ? 32'b00000000000000000000000000000000 :
              sub_temp[31:0]);
  assign fill8 = cast & 32'd255;
  assign s_8 = dOut != 16'd0;
  assign acc = {31'b0, s_8};
  assign s = (sOut != 16'd0 ? 32'd2 :
              32'd0);
  assign acc_1 = acc + s;
  assign s_1 = (vOut != 16'd0 ? 32'd4 :
              32'd0);
  assign acc_2 = acc_1 + s_1;
  assign s_2 = (decis[0] != 16'd0 ? 32'd8 :
              32'd0);
  assign acc_3 = acc_2 + s_2;
  assign s_3 = (decis[1] != 16'd0 ? 32'd16 :
              32'd0);
  assign acc_4 = acc_3 + s_3;
  assign s_9 = {16'b0, rhc};
  assign mul_temp = 32'd32 * (s_9 & 32'd3);
  assign add_cast = mul_temp[31:0];
  assign acc_5 = acc_4 + add_cast;
  assign add_cast_1 = {24'b0, {fill8, 8'b00000000}};
  assign add_cast_2 = add_cast_1[31:0];
  assign acc_6 = acc_5 + add_cast_2;
  assign s_10 = {16'b0, popc};
  assign mul_temp_1 = 32'd256 * (s_10 & 32'd255);
  assign add_cast_3 = mul_temp_1[31:0];
  assign s_11 = {16'b0, pushc};
  assign qcc = (s_11 & 32'd255) + add_cast_3;
  assign dbgI1 = acc_6[15:0];
  assign dbgQ1 = qcc[15:0];

endmodule  // BeatObs

