// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/BfSerMux.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BfSerMux
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/QPSK Demodulator/Serializer/BfSerMux
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BfSerMux
          (c,
           anchor,
           y);


  input   c;  // ufix1
  input   anchor;
  output  [7:0] y;  // uint8




  assign y = (anchor ? 8'd0 :
              {7'b0, c});

endmodule  // BfSerMux

