// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/BfTagGen.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BfTagGen
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/BfTagGen
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BfTagGen
          (clk,
           reset,
           enb_1_2_0,
           vin,
           sin,
           tag);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   vin;
  input   sin;
  output  [15:0] tag;  // uint16


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg [15:0] tag_1;  // uint16
  reg [15:0] t;  // uint16
  reg [15:0] t_next;  // uint16
  reg [15:0] tag_last_value;  // uint16
  reg [15:0] t_temp;  // uint16
  reg [16:0] add_temp;  // ufix17
  reg [16:0] t_0;  // ufix17


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : BfTagGen_process
      if (reset == 1'b1) begin
        t <= 16'd0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          t <= t_next;
        end
      end
    end

  always @(sin, t, vin) begin
    add_temp = 17'b00000000000000000;
    t_0 = 17'b00000000000000000;
    t_temp = t;
    if (vin) begin
      if (sin) begin
        t_temp = 16'd0;
      end
      else if (t >= 16'd12319) begin
        t_temp = 16'd0;
      end
      else begin
        t_0 = {1'b0, t};
        add_temp = t_0 + 17'b00000000000000001;
        if (add_temp[16] != 1'b0) begin
          t_temp = 16'b1111111111111111;
        end
        else begin
          t_temp = add_temp[15:0];
        end
      end
    end
    tag_1 = t_temp;
    t_next = t_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        tag_last_value <= 16'b0000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          tag_last_value <= tag;
        end
      end
    end

  assign tag = (stateControl_2 == 1'b0 ? tag_last_value :
              tag_1);

endmodule  // BfTagGen

