// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Bit_Packetizer.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Bit_Packetizer
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/Bit Packetizer
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Bit_Packetizer
          (clk,
           reset,
           enb_1_2_0,
           dataIn,
           validIn,
           bitsOut,
           dataStart,
           dataEnd,
           bitsValid,
           dataReady);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   dataIn;
  input   validIn;
  output  bitsOut;
  output  dataStart;
  output  dataEnd;
  output  bitsValid;
  output  dataReady;


  wire Data_Bits_FIFO_dataOut;
  wire Data_Bits_FIFO_activeFrame;
  wire [14:0] Data_Bits_FIFO_sampleCount;  // ufix15
  wire Data_Bits_FIFO_sampleCountValid;
  wire Data_Bits_FIFO_fullRAM;
  wire Compare_To_Constant2_y;
  reg  Compare_To_Constant2_y_1;
  wire Preamble_Bits_Generator_preambleBits;
  reg  Preamble_Bits_Generator_preambleBits_1;
  wire Switch_out1;
  wire Compare_To_Constant_y;
  wire Logical_Operator_out1;
  wire Compare_To_Constant1_y;
  wire Logical_Operator1_out1;
  wire Logical_Operator2_out1;
  wire count_step;  // ufix1
  wire count_from;  // ufix1
  reg  HDL_Counter_out1;  // ufix1
  wire count;  // ufix1
  wire need_to_wrap;
  wire count_value;  // ufix1
  wire count_1;  // ufix1
  wire DataReadyPaceCmp_out1;


  Data_Bits_FIFO u_Data_Bits_FIFO (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .data(dataIn),
                                                    .push(validIn),
                                                    .dataOut(Data_Bits_FIFO_dataOut),
                                                    .activeFrame(Data_Bits_FIFO_activeFrame),
                                                    .sampleCount(Data_Bits_FIFO_sampleCount),  // ufix15
                                                    .sampleCountValid(Data_Bits_FIFO_sampleCountValid),
                                                    .fullRAM(Data_Bits_FIFO_fullRAM)
                                                    );

  Compare_To_Constant2 u_Compare_To_Constant2 (.u(Data_Bits_FIFO_sampleCount),  // ufix15
                                                                .y(Compare_To_Constant2_y)
                                                                );

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        Compare_To_Constant2_y_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Compare_To_Constant2_y_1 <= Compare_To_Constant2_y;
        end
      end
    end

  Preamble_Bits_Generator u_Preamble_Bits_Generator (.clk(clk),
                                                                      .reset(reset),
                                                                      .enb_1_2_0(enb_1_2_0),
                                                                      .activeFrame(Data_Bits_FIFO_activeFrame),
                                                                      .sampleCount(Data_Bits_FIFO_sampleCount),  // ufix15
                                                                      .sampleCountValid(Data_Bits_FIFO_sampleCountValid),
                                                                      .preambleBits(Preamble_Bits_Generator_preambleBits)
                                                                      );

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        Preamble_Bits_Generator_preambleBits_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Preamble_Bits_Generator_preambleBits_1 <= Preamble_Bits_Generator_preambleBits;
        end
      end
    end

  assign Switch_out1 = (Compare_To_Constant2_y_1 == 1'b0 ? Preamble_Bits_Generator_preambleBits_1 :
              Data_Bits_FIFO_dataOut);

  assign bitsOut = Switch_out1;

  Compare_To_Constant_block1 u_Compare_To_Constant (.u(Data_Bits_FIFO_sampleCount),  // ufix15
                                                                     .y(Compare_To_Constant_y)
                                                                     );

  assign Logical_Operator_out1 = Compare_To_Constant_y & Data_Bits_FIFO_sampleCountValid;

  assign dataStart = Logical_Operator_out1;

  Compare_To_Constant1_block1 u_Compare_To_Constant1 (.u(Data_Bits_FIFO_sampleCount),  // ufix15
                                                                       .y(Compare_To_Constant1_y)
                                                                       );

  assign Logical_Operator1_out1 = Data_Bits_FIFO_sampleCountValid & Compare_To_Constant1_y;

  assign dataEnd = Logical_Operator1_out1;

  assign bitsValid = Data_Bits_FIFO_sampleCountValid;

  assign Logical_Operator2_out1 =  ~ Data_Bits_FIFO_fullRAM;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  assign count_step = 1'b1;

  assign count_from = 1'b0;

  assign count = HDL_Counter_out1 ^ count_step;

  assign need_to_wrap = HDL_Counter_out1 == 1'b1;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (Logical_Operator2_out1 == 1'b0 ? HDL_Counter_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end

  assign DataReadyPaceCmp_out1 = HDL_Counter_out1 == 1'b1;

  assign dataReady = DataReadyPaceCmp_out1;

endmodule  // Bit_Packetizer

