// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/ByteBitShifter.v
// Created: 2026-08-21 23:31:06
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ByteBitShifter
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/Input Data/ByteBitShifter
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ByteBitShifter
          (clk,
           reset,
           enb_1_2_0,
           enable,
           reset_1,
           start,
           extWord,
           extWordAvail,
           extWordFirst,
           bit_rsvd,
           popToggle);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   enable;
  input   reset_1;
  input   start;
  input   [63:0] extWord;  // ufix64
  input   extWordAvail;
  input   extWordFirst;
  output  bit_rsvd;
  output  popToggle;


  reg  bit_rsvd_1;
  reg  popToggle_1;
  reg [63:0] state_shiftWord;  // uint64
  reg [7:0] state_bitIdx;  // uint8
  reg  state_aligned;
  reg  tog;
  reg [63:0] state_shiftWord_next;  // uint64
  reg [7:0] state_bitIdx_next;  // uint8
  reg  state_aligned_next;
  reg  tog_next;
  reg  pop;
  reg  state_aligned_1;
  reg  en;
  reg [7:0] byteIdx;  // uint8
  reg [7:0] bitInByte;  // uint8
  reg [63:0] byteVal;  // uint64
  reg signed [31:0] y;  // int32
  reg [7:0] a1;  // uint8
  reg [63:0] a1_0;  // uint64
  reg signed [31:0] absk1;  // int32
  reg [63:0] bm1;  // uint64
  reg  tog_temp;
  reg [63:0] c;  // uint64
  reg signed [31:0] a1_1;  // int32
  reg signed [31:0] a1_2;  // int32
  reg signed [40:0] mul_temp;  // sfix41
  reg signed [32:0] y_0;  // sfix33
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_1;  // int32
  reg signed [8:0] t_2;  // sfix9
  reg [63:0] t_3;  // uint64
  reg signed [32:0] t_4;  // sfix33
  reg signed [40:0] t_5;  // sfix41


  always @(posedge clk or posedge reset)
    begin : ByteBitShifter_process
      if (reset == 1'b1) begin
        state_shiftWord <= 64'd0;
        state_bitIdx <= 8'd64;
        state_aligned <= 1'b0;
        tog <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          state_shiftWord <= state_shiftWord_next;
          state_bitIdx <= state_bitIdx_next;
          state_aligned <= state_aligned_next;
          tog <= tog_next;
        end
      end
    end

  always @(enable, extWord, extWordAvail, extWordFirst, reset_1, start, state_aligned,
       state_bitIdx, state_shiftWord, tog) begin
    c = 64'd0;
    bm1 = 64'd0;
    byteVal = 64'd0;
    a1_1 = 32'sd0;
    a1_2 = 32'sd0;
    mul_temp = 41'sh00000000000;
    y_0 = 33'sh000000000;
    t_0 = 32'sd0;
    t_1 = 32'sd0;
    t_2 = 9'sb000000000;
    y = 32'sd0;
    t_3 = 64'd0;
    t_4 = 33'sh000000000;
    absk1 = 32'sd0;
    byteIdx = 8'd0;
    bitInByte = 8'd0;
    t_5 = 41'sh00000000000;
    tog_temp = tog;
    // Block wrapper around qpskByteBitShifterStrict (the unit-tested single source
    // of truth). Persistent state only; the effective enable matches the
    // Message Generator chart's active condition (enable && ~reset) so the
    // shifter emits bits on exactly the generator's bit steps. pop is
    // exported as a toggle (one flip per word latch OR discard) to survive
    // the slow->fast rate crossing; upstream edge-detects it into a pulse.
    en = enable && ( ! reset_1);
    a1_0 = state_shiftWord;
    a1 = state_bitIdx;
    state_aligned_1 = state_aligned;
    // qpskByteBitShifterStrict -- f1536 variant of qpskByteBitShifter with a
    // START-BEAT MARKER RE-CHECK (TXMUX task 2026-07-25).
    //
    // DEFECT FIXED (aggravator of the R0 f1536 byte-plane failure): the legacy
    // shifter validates wordFirst only while UNALIGNED. Once aligned, it latches
    // blindly at every start; because steady-state consumption (PayloadWords64
    // words/frame) exactly equals the host supply, ANY acquired word-phase error
    // (e.g. the ingress idle-exit drop, see qpskByteWordBufferSkid.m) persists
    // FOREVER -- the silicon "+4 words forever" signature. The k5 cadence
    // underflowed often enough to keep realigning; the f1536 gapless keepalive
    // queue never does.
    //
    // FIX: at an aligned `start` beat, the head word MUST carry the first-word
    // marker (the host sends one transfer per air frame, tlast-delimited, so
    // frame boundary == transfer boundary). If the head is unmarked at start,
    // the phase is wrong: discard it and drop to the realign sequence instead of
    // latching. Self-heals any offset within <= 1 frame (that frame emits zeros,
    // exactly like the legacy underflow path). All other behavior is IDENTICAL
    // to qpskByteBitShifter (same state fields, same emission order, same
    // mid-frame reload/underflow semantics).
    //
    // k5-G0 NOTE: NEW function, used only by the f1536 overlay wrapper
    // (byte_tx_overlay_k5.m, cfg-gated); qpskByteBitShifter.m and the k5
    // generated HDL are untouched (byte-identical).
    bit_rsvd_1 = 1'b0;
    pop = 1'b0;
    if (en) begin
      if ( ! state_aligned) begin
        if ((start && extWordAvail) && extWordFirst) begin
          // packet boundary with the first-marked word at the head:
          // latch it and lock alignment
          a1_0 = extWord;
          pop = 1'b1;
          a1 = 8'd0;
          state_aligned_1 = 1'b1;
        end
        else if (extWordAvail && ( ! extWordFirst)) begin
          // discard toward the first-marked word (one per enabled step)
          pop = 1'b1;
          a1_0 = 64'd0;
          a1 = 8'd64;
        end
        else begin
          // head is first-marked (hold for the next start) or FIFO empty
          a1_0 = 64'd0;
          a1 = 8'd64;
        end
      end
      else if (start || (state_bitIdx >= 8'd64)) begin
        if ((start && extWordAvail) && ( ! extWordFirst)) begin
          // STRICT: frame boundary but the head is NOT a transfer head --
          // word-phase error. Discard and re-run the alignment sequence
          // (zeros this frame; locks to the marker at the next start).
          pop = 1'b1;
          a1_0 = 64'd0;
          a1 = 8'd64;
          state_aligned_1 = 1'b0;
        end
        else if (extWordAvail) begin
          a1_0 = extWord;
          pop = 1'b1;
          a1 = 8'd0;
        end
        else begin
          // underflow: emit zeros and re-run the alignment sequence
          a1_0 = 64'd0;
          a1 = 8'd64;
          state_aligned_1 = 1'b0;
        end
      end
      if (state_aligned_1) begin
        t_0 = {24'b0, a1};
        a1_1 = t_0 >>> 32'sd3;
        byteIdx = a1_1[7:0];
        // floor(bitIdx/8)
        t_1 = {24'b0, a1};
        a1_2 = t_1 & 32'sd7;
        bitInByte = a1_2[7:0];
        // mod(bitIdx,8)
        t_2 = {1'b0, byteIdx};
        // CSD Encoding (8) : 1000; Cost (Adders) = 0
        t_5 = {{29{t_2[8]}}, {t_2, 3'b000}};
        mul_temp =  - (t_5);
        y = mul_temp[31:0];
        if (y >= 32'sd0) begin
          c = a1_0;
        end
        else if (y >= -32'sd63) begin
          t_4 = {y[31], y};
          y_0 =  - (t_4);
          absk1 = y_0[31:0];
          c = a1_0 >> absk1;
        end
        else begin
          c = 64'd0;
        end
        byteVal = c & 64'd255;
        t_3 = {56'b0, bitInByte};
        bm1 = 64'd7 - t_3;
        bit_rsvd_1 = byteVal[bm1] != 1'b0;
        a1 = a1 + 8'd1;
      end
    end
    state_shiftWord_next = a1_0;
    state_bitIdx_next = a1;
    state_aligned_next = state_aligned_1;
    if (pop) begin
      tog_temp =  ! tog;
    end
    popToggle_1 = tog_temp;
    tog_next = tog_temp;
  end

  assign bit_rsvd = bit_rsvd_1;

  assign popToggle = popToggle_1;

endmodule  // ByteBitShifter

