// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/ByteSerializer.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ByteSerializer
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/ByteSerializer
// Hierarchy Level: 1
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ByteSerializer
          (clk,
           reset,
           enb_1_2_0,
           bitIn,
           bitValid,
           start,
           ready,
           word,
           wordTog,
           wordLast,
           wordFirst);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   bitIn;
  input   bitValid;
  input   start;
  input   ready;
  output  [63:0] word;  // ufix64
  output  wordTog;
  output  wordLast;
  output  wordFirst;


  wire stateControl_1;
  reg  [1:0] delayMatch1_reg;  // ufix1 [2]
  wire stateControl_2;
  wire enb_1_2_0_gated;
  reg  [1:0] delayMatch_reg;  // ufix1 [2]
  wire ready_1;
  reg [63:0] word_1;  // ufix64
  reg  wordTog_1;
  reg  wordLast_1;
  reg  wordFirst_1;
  reg [63:0] state_acc;  // uint64
  reg [7:0] state_bitIdx;  // uint8
  reg [15:0] state_wordCnt;  // uint16
  reg  tog;
  reg [63:0] heldWord;  // uint64
  reg  heldLast;
  reg  heldFirst;
  reg  firstNext;
  reg [63:0] state_acc_next;  // uint64
  reg [7:0] state_bitIdx_next;  // uint8
  reg [15:0] state_wordCnt_next;  // uint16
  reg  tog_next;
  reg [63:0] heldWord_next;  // uint64
  reg  heldLast_next;
  reg  heldFirst_next;
  reg  firstNext_next;
  reg [63:0] word_last_value;  // ufix64
  reg  wordTog_last_value;
  reg  wordLast_last_value;
  reg  wordFirst_last_value;
  reg [63:0] w;  // uint64
  reg  wv;
  reg  wl;
  reg [63:0] state_acc_1;  // uint64
  reg [15:0] state_wordCnt_1;  // uint16
  reg [7:0] byteIdx;  // uint8
  reg [7:0] bitInByte;  // uint8
  reg [31:0] pos;  // uint32
  reg [7:0] a1;  // uint8
  reg  tog_temp;
  reg [63:0] heldWord_temp;  // uint64
  reg  heldLast_temp;
  reg  heldFirst_temp;
  reg [63:0] c;  // uint64
  reg signed [31:0] a1_0;  // int32
  reg [8:0] add_temp;  // ufix9
  reg signed [31:0] a1_1;  // int32
  reg [16:0] add_temp_0;  // ufix17
  reg [39:0] sub_cast;  // ufix40
  reg [31:0] sub_cast_0;  // uint32
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_1;  // int32
  reg [31:0] t_2;  // uint32
  reg [8:0] t_3;  // ufix9
  reg [16:0] t_4;  // ufix17


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[1] <= delayMatch1_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[1];

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          delayMatch_reg[0] <= ready;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign ready_1 = delayMatch_reg[1];

  always @(posedge clk or posedge reset)
    begin : ByteSerializer_process
      if (reset == 1'b1) begin
        state_acc <= 64'd0;
        state_bitIdx <= 8'd0;
        state_wordCnt <= 16'd0;
        tog <= 1'b0;
        heldWord <= 64'd0;
        heldLast <= 1'b0;
        heldFirst <= 1'b1;
        firstNext <= 1'b1;
      end
      else begin
        if (enb_1_2_0_gated) begin
          state_acc <= state_acc_next;
          state_bitIdx <= state_bitIdx_next;
          state_wordCnt <= state_wordCnt_next;
          tog <= tog_next;
          heldWord <= heldWord_next;
          heldLast <= heldLast_next;
          heldFirst <= heldFirst_next;
          firstNext <= firstNext_next;
        end
      end
    end

  always @(bitIn, bitValid, firstNext, heldFirst, heldLast, heldWord, start, state_acc,
       state_bitIdx, state_wordCnt, tog) begin
    pos = 32'd0;
    c = 64'd0;
    a1_0 = 32'sd0;
    add_temp = 9'b000000000;
    a1_1 = 32'sd0;
    add_temp_0 = 17'b00000000000000000;
    t_0 = 32'sd0;
    t_1 = 32'sd0;
    sub_cast = 40'h0000000000;
    sub_cast_0 = 32'd0;
    t_2 = 32'd0;
    t_3 = 9'b000000000;
    t_4 = 17'b00000000000000000;
    byteIdx = 8'd0;
    bitInByte = 8'd0;
    tog_temp = tog;
    heldWord_temp = heldWord;
    heldLast_temp = heldLast;
    heldFirst_temp = heldFirst;
    firstNext_next = firstNext;
    // Block wrapper around qpskByteSerializer (unit-tested single source of
    // truth); persistent state only. word/wordLast are HELD stable between
    // emissions; wordTog flips once per emitted word so the slow->fast rate
    // crossing cannot drop or repeat it -- the 30.72M BeatGate edge-detects
    // it into exactly one accepted AXIS beat. Dropped words (ready low at
    // completion) do not toggle: drop means NO beat, never a stall.
    // K5 kit: 191 words/frame = the first 64*191 of
    // the 1084 decoded info bits; the trailing 60 are dropped by start-reset.
    // presentation is decoupled from acceptance (ADI S2MM source style):
    // the offered beat must refresh on EVERY completed word or the DMA's
    // SYNC_TRANSFER_START gate can wait forever on a frozen user flag /
    // accept a stale word. ready at the pin only decides acceptance, so
    // the core serializer runs with ready=true and unaccepted beats are
    // simply superseded.
    state_acc_1 = state_acc;
    a1 = state_bitIdx;
    state_wordCnt_1 = state_wordCnt;
    // qpskByteSerializer -- recovered payload bit -> 64-bit word serializer for
    // the byte-RX path (the EXACT inverse of qpskByteBitShifter: byte-0-first,
    // MSB-first within each byte, so shifter(pack(bytes)) bits fed in here
    // reproduce pack(bytes) words and the host unpacks them little-endian).
    //
    //   state = qpskByteSerializer()                            -- initial state
    //   [word, wordValid, wordLast, drop, state] = ...
    //       qpskByteSerializer(state, bitIn, bitValid, start, ready)
    //
    // Collects bitValid-gated payload bits into a 64-bit word. `start` (the Rx
    // packet-boundary flag, asserted with the packet's first payload bit) resets
    // the bit position AND the word counter -- a start arriving mid-word
    // DISCARDS the partial word, so word/packet alignment self-heals at every
    // packet boundary. When the 64th bit lands the word completes in the SAME
    // step:
    //   * ready true  -> wordValid asserted for this one step, with wordLast on
    //     the 35th word of the packet (2240 bits = exactly 35 words);
    //   * ready false -> the word is flagged via `drop` and DISCARDED -- the
    //     serializer NEVER stalls the Receiver (the recovered bit stream cannot
    //     be backpressured). The word-position counter still advances, so
    //     wordLast keeps marking the word that completes the packet.
    //
    // This function is the unit-tested single source of truth for the logic
    // inside the composite overlay's ByteSerializer MATLAB Function block.
    w = 64'd0;
    wv = 1'b0;
    wl = 1'b0;
    if (start) begin
      // packet boundary: discard any partial word, restart word counting
      state_acc_1 = 64'd0;
      a1 = 8'd0;
      state_wordCnt_1 = 16'd0;
    end
    if (bitValid) begin
      if (bitIn) begin
        t_0 = {24'b0, a1};
        a1_0 = t_0 >>> 32'sd3;
        byteIdx = a1_0[7:0];
        // floor(bitIdx/8)
        t_1 = {24'b0, a1};
        a1_1 = t_1 & 32'sd7;
        bitInByte = a1_1[7:0];
        // mod(bitIdx,8)
        // global 0-based bit position: MSB-first within the byteIdx-th byte
        sub_cast = {29'b0, {byteIdx, 3'b000}};
        sub_cast_0 = sub_cast[31:0];
        t_2 = {24'b0, bitInByte};
        pos = (sub_cast_0 - t_2) + 32'd7;
        if (pos <= 32'd63) begin
          c = 64'd1 <<< pos;
        end
        else begin
          c = 64'd0;
        end
        state_acc_1 = state_acc_1 | c;
      end
      t_3 = {1'b0, a1};
      add_temp = t_3 + 9'b000000001;
      if (add_temp[8] != 1'b0) begin
        a1 = 8'b11111111;
      end
      else begin
        a1 = add_temp[7:0];
      end
      if (a1 >= 8'd64) begin
        // word complete this step
        t_4 = {1'b0, state_wordCnt_1};
        add_temp_0 = t_4 + 17'b00000000000000001;
        if (add_temp_0[16] != 1'b0) begin
          state_wordCnt_1 = 16'b1111111111111111;
        end
        else begin
          state_wordCnt_1 = add_temp_0[15:0];
        end
        w = state_acc_1;
        wv = 1'b1;
        wl = state_wordCnt_1 >= 16'd191;
        if (state_wordCnt_1 >= 16'd191) begin
          state_wordCnt_1 = 16'd0;
        end
        state_acc_1 = 64'd0;
        a1 = 8'd0;
      end
    end
    state_acc_next = state_acc_1;
    state_bitIdx_next = a1;
    state_wordCnt_next = state_wordCnt_1;
    if (wv) begin
      heldWord_temp = w;
      heldLast_temp = wl;
      tog_temp =  ! tog;
      heldFirst_temp = firstNext;
      firstNext_next = wl;
    end
    word_1 = heldWord_temp;
    wordTog_1 = tog_temp;
    wordLast_1 = heldLast_temp;
    wordFirst_1 = heldFirst_temp;
    tog_next = tog_temp;
    heldWord_next = heldWord_temp;
    heldLast_next = heldLast_temp;
    heldFirst_next = heldFirst_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        word_last_value <= 64'h0000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          word_last_value <= word;
        end
      end
    end

  assign word = (stateControl_2 == 1'b0 ? word_last_value :
              word_1);

  always @(posedge clk or posedge reset)
    begin : out1_bypass_process
      if (reset == 1'b1) begin
        wordTog_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          wordTog_last_value <= wordTog;
        end
      end
    end

  assign wordTog = (stateControl_2 == 1'b0 ? wordTog_last_value :
              wordTog_1);

  always @(posedge clk or posedge reset)
    begin : out2_bypass_process
      if (reset == 1'b1) begin
        wordLast_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          wordLast_last_value <= wordLast;
        end
      end
    end

  assign wordLast = (stateControl_2 == 1'b0 ? wordLast_last_value :
              wordLast_1);

  always @(posedge clk or posedge reset)
    begin : out3_bypass_process
      if (reset == 1'b1) begin
        wordFirst_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          wordFirst_last_value <= wordFirst;
        end
      end
    end

  assign wordFirst = (stateControl_2 == 1'b0 ? wordFirst_last_value :
              wordFirst_1);

endmodule  // ByteSerializer

