// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Capture_Data_Bits.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Capture_Data_Bits
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/Capture Data Bits
// Hierarchy Level: 2
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Capture_Data_Bits
          (clk,
           reset,
           enb_1_2_0,
           dataOut,
           dataSrt,
           valid,
           count_out,
           packets_out,
           bit_errors_out);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   dataOut;
  input   dataSrt;
  input   valid;
  output  [31:0] count_out;  // uint32
  output  [31:0] packets_out;  // uint32
  output  [31:0] bit_errors_out;  // uint32


  wire stateControl_1;
  reg  [1:0] delayMatch_reg;  // ufix1 [2]
  wire stateControl_2;
  wire enb_1_2_0_gated;
  wire [31:0] count_out_1;  // uint32
  wire [31:0] packets_out_1;  // uint32
  wire [31:0] bit_errors_out_1;  // uint32
  reg [31:0] count_out_last_value;  // uint32
  reg [31:0] packets_out_last_value;  // uint32
  reg [31:0] bit_errors_out_last_value;  // uint32


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          delayMatch_reg[0] <= stateControl_1;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch_reg[1];

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  MATLAB_Function u_MATLAB_Function (.clk(clk),
                                                      .reset(reset),
                                                      .enb_1_2_0(enb_1_2_0_gated),
                                                      .valid(valid),
                                                      .datain(dataOut),
                                                      .start(dataSrt),
                                                      .count_out(count_out_1),  // uint32
                                                      .packets_out(packets_out_1),  // uint32
                                                      .bit_errors_out(bit_errors_out_1)  // uint32
                                                      );

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        count_out_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          count_out_last_value <= count_out;
        end
      end
    end

  assign count_out = (stateControl_2 == 1'b0 ? count_out_last_value :
              count_out_1);

  always @(posedge clk or posedge reset)
    begin : out1_bypass_process
      if (reset == 1'b1) begin
        packets_out_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          packets_out_last_value <= packets_out;
        end
      end
    end

  assign packets_out = (stateControl_2 == 1'b0 ? packets_out_last_value :
              packets_out_1);

  always @(posedge clk or posedge reset)
    begin : out2_bypass_process
      if (reset == 1'b1) begin
        bit_errors_out_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          bit_errors_out_last_value <= bit_errors_out;
        end
      end
    end

  assign bit_errors_out = (stateControl_2 == 1'b0 ? bit_errors_out_last_value :
              bit_errors_out_1);

endmodule  // Capture_Data_Bits

