// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/CFO_step_change_detector.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CFO_step_change_detector
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency 
// Compensator/CFO step change detecto
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CFO_step_change_detector
          (clk,
           reset,
           enb_1_2_0,
           In1,
           cfo_threshold,
           Out1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [20:0] In1;  // sfix21_En21
  input   [31:0] cfo_threshold;  // uint32
  output  Out1;


  reg signed [20:0] Delay1_out1;  // sfix21_En21
  wire signed [21:0] Add_sub_cast;  // sfix22_En21
  wire signed [21:0] Add_sub_cast_1;  // sfix22_En21
  wire signed [21:0] Add_out1;  // sfix22_En21
  wire firePos;
  wire fireNeg;
  wire nz;
  wire Compare_To_Constant_out1;
  wire LGSw_cfo_threshold_1_out1;
  wire Compare_To_Constant1_out1;
  wire LGSw_cfo_threshold_2_out1;
  wire Logical_Operator_out1;
  reg  [5:0] Delay_reg;  // ufix1 [6]
  wire Delay_out1;

  // fixed point precision loss warning supressed for this subsystem


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 21'sb000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= In1;
        end
      end
    end

  assign Add_sub_cast = {In1[20], In1};
  assign Add_sub_cast_1 = {Delay1_out1[20], Delay1_out1};
  assign Add_out1 = Add_sub_cast - Add_sub_cast_1;

  LGMux_cfo_threshold u_LGMux_cfo_threshold (.clk(clk),
                                                              .reset(reset),
                                                              .enb_1_2_0(enb_1_2_0),
                                                              .axi(cfo_threshold),  // uint32
                                                              .x(Add_out1),  // sfix22_En21
                                                              .firePos(firePos),
                                                              .fireNeg(fireNeg),
                                                              .nz(nz)
                                                              );

  assign Compare_To_Constant_out1 = Add_out1 > 22'sb0000000110011001100110;

  assign LGSw_cfo_threshold_1_out1 = (nz == 1'b0 ? Compare_To_Constant_out1 :
              firePos);

  assign Compare_To_Constant1_out1 = Add_out1 < 22'sb1111111001100110011010;

  assign LGSw_cfo_threshold_2_out1 = (nz == 1'b0 ? Compare_To_Constant1_out1 :
              fireNeg);

  assign Logical_Operator_out1 = LGSw_cfo_threshold_1_out1 | LGSw_cfo_threshold_2_out1;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_reg <= {6{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay_reg[0] <= Logical_Operator_out1;
          Delay_reg[32'sd5:32'sd1] <= Delay_reg[32'sd4:32'sd0];
        end
      end
    end

  assign Delay_out1 = Delay_reg[5];

  assign Out1 = Delay_out1;

endmodule  // CFO_step_change_detector

