// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Compare_To_Constant1.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Compare_To_Constant1
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/FIFO/Validate 
// Input Push Pop/Compare To Constant
// Hierarchy Level: 7
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Compare_To_Constant1
          (u,
           y);


  input   [13:0] u;  // ufix14
  output  y;


  wire [13:0] Constant_out1;  // ufix14
  wire Compare_out1;


  assign Constant_out1 = 14'b11000000101101;

  assign Compare_out1 = u == Constant_out1;

  assign y = Compare_out1;

endmodule  // Compare_To_Constant1

