// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Compare_To_Constant_block.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Compare_To_Constant_block
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate 
// Handle/FIFO/Validate Input Push Pop/Compare To Constan
// Hierarchy Level: 8
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Compare_To_Constant_block
          (u,
           y);


  input   [5:0] u;  // ufix6
  output  y;


  wire [5:0] Constant_out1;  // ufix6
  wire Compare_out1;


  assign Constant_out1 = 6'b000000;

  assign Compare_out1 = u == Constant_out1;

  assign y = Compare_out1;

endmodule  // Compare_To_Constant_block

