// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/ConvEncK5.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ConvEncK5
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/Input Data/FEC Tx Encoder K5/ConvEncK5
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ConvEncK5
          (clk,
           reset,
           enb_1_2_0,
           infoBit,
           encReset,
           infoValid,
           codedPair_0,
           codedPair_1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   infoBit;
  input   encReset;
  input   infoValid;
  output  codedPair_0;  // boolean
  output  codedPair_1;  // boolean


  reg  [1:0] codedPair;  // boolean [2]
  reg  [3:0] sr;  // boolean [4]
  reg  [3:0] sr_next;  // boolean [4]
  reg  [3:0] srUse;  // boolean [4]
  reg  s1;
  reg  s2;
  reg  s3;
  reg  s4;
  reg  g0;
  reg  g1;
  reg  [1:0] g0_0;  // boolean [2]
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_1;  // int32
  reg signed [31:0] t_2;  // int32
  reg signed [31:0] t_3;  // int32
  reg signed [31:0] t_4;  // int32
  reg signed [31:0] t_0_0;  // int32
  reg signed [31:0] t_1_0;  // int32


  always @(posedge clk or posedge reset)
    begin : ConvEncK5_process
      if (reset == 1'b1) begin
        for(t_1_0 = 32'sd0; t_1_0 <= 32'sd3; t_1_0 = t_1_0 + 32'sd1) begin
          sr[t_1_0] <= 1'b0;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(t_0_0 = 32'sd0; t_0_0 <= 32'sd3; t_0_0 = t_0_0 + 32'sd1) begin
            sr[t_0_0] <= sr_next[t_0_0];
          end
        end
      end
    end

  always @* begin

    for(t_0 = 32'sd0; t_0 <= 32'sd3; t_0 = t_0 + 32'sd1) begin
      sr_next[t_0] = sr[t_0];
      srUse[t_0] = sr[t_0];
    end

    if (encReset) begin
      for(t_1 = 32'sd0; t_1 <= 32'sd3; t_1 = t_1 + 32'sd1) begin
        srUse[t_1] = 1'b0;
      end
    end
    // reset-then-advance (zero frame state)
    s1 = srUse[0];
    s2 = srUse[1];
    s3 = srUse[2];
    s4 = srUse[3];
    g0 = infoBit ^ (s1 ^ (s2 ^ s4));
    // poly 35 oct = 11101
    g1 = infoBit ^ (s3 ^ s4);
    // poly 23 oct = 10011
    // state update: advance ONLY on infoValid, else HOLD (anti-zero-stuff gate)
    if (infoValid) begin
      sr_next[0] = infoBit;

      for(t_3 = 32'sd0; t_3 <= 32'sd2; t_3 = t_3 + 32'sd1) begin
        sr_next[t_3 + 32'sd1] = srUse[t_3];
      end

    end
    else begin
      for(t_2 = 32'sd0; t_2 <= 32'sd3; t_2 = t_2 + 32'sd1) begin
        sr_next[t_2] = srUse[t_2];
      end
    end
    g0_0[0] = g0;
    g0_0[1] = g1;

    for(t_4 = 32'sd0; t_4 <= 32'sd1; t_4 = t_4 + 32'sd1) begin
      codedPair[t_4] = g0_0[t_4];
    end

  end

  assign codedPair_0 = codedPair[0];

  assign codedPair_1 = codedPair[1];

endmodule  // ConvEncK5

