// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/FecCaptureCadence.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FecCaptureCadence
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/FecCaptureCadence
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FecCaptureCadence
          (clk,
           reset,
           enb_1_2_0,
           startIn,
           validIn,
           capCad);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   startIn;
  input   validIn;
  output  [31:0] capCad;  // uint32


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg [31:0] capCad_1;  // uint32
  reg [7:0] sCnt;  // uint8
  reg [7:0] gap;  // uint8
  reg [7:0] snv;  // uint8
  reg [7:0] vrun;  // uint8
  reg  seenStart;
  reg  sawValid;
  reg  measuring;
  reg [7:0] sCnt_next;  // uint8
  reg [7:0] gap_next;  // uint8
  reg [7:0] snv_next;  // uint8
  reg [7:0] vrun_next;  // uint8
  reg  seenStart_next;
  reg  sawValid_next;
  reg  measuring_next;
  reg [31:0] capCad_last_value;  // uint32
  reg [7:0] sC;  // uint8
  reg [7:0] gp;  // uint8
  reg [7:0] sv;  // uint8
  reg [7:0] vr;  // uint8
  reg  seen;
  reg  saw;
  reg  mea;
  reg [31:0] a1;  // uint32
  reg [31:0] a1_0;  // uint32
  reg [31:0] a1_1;  // uint32
  reg [8:0] add_temp;  // ufix9
  reg [8:0] add_temp_0;  // ufix9
  reg [8:0] t_0;  // ufix9
  reg [8:0] t_1;  // ufix9
  reg [31:0] t_2;  // uint32


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : FecCaptureCadence_process
      if (reset == 1'b1) begin
        sCnt <= 8'd0;
        gap <= 8'd0;
        snv <= 8'd0;
        vrun <= 8'd0;
        seenStart <= 1'b0;
        sawValid <= 1'b0;
        measuring <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          sCnt <= sCnt_next;
          gap <= gap_next;
          snv <= snv_next;
          vrun <= vrun_next;
          seenStart <= seenStart_next;
          sawValid <= sawValid_next;
          measuring <= measuring_next;
        end
      end
    end

  always @(gap, measuring, sCnt, sawValid, seenStart, snv, startIn, validIn, vrun) begin
    add_temp = 9'b000000000;
    add_temp_0 = 9'b000000000;
    t_0 = 9'b000000000;
    t_1 = 9'b000000000;
    // sync-semantics compliant (RXROOT E11c): locals, persist last.
    sC = sCnt;
    gp = gap;
    sv = snv;
    vr = vrun;
    seen = seenStart;
    saw = sawValid;
    mea = measuring;
    if (startIn) begin
      if (sCnt < 8'd255) begin
        t_0 = {1'b0, sCnt};
        add_temp = t_0 + 9'b000000001;
        if (add_temp[8] != 1'b0) begin
          sC = 8'b11111111;
        end
        else begin
          sC = add_temp[7:0];
        end
      end
      if ( ! validIn && (snv < 8'd255)) begin
        t_1 = {1'b0, snv};
        add_temp_0 = t_1 + 9'b000000001;
        if (add_temp_0[8] != 1'b0) begin
          sv = 8'b11111111;
        end
        else begin
          sv = add_temp_0[7:0];
        end
      end
      if ( ! seenStart) begin
        seen = 1'b1;
        mea = 1'b1;
        gp = 8'd0;
        saw = 1'b0;
        vr = 8'd0;
      end
    end
    if (mea && ( ! saw)) begin
      if (validIn) begin
        saw = 1'b1;
      end
      else if (gp < 8'd255) begin
        gp = gp + 8'd1;
      end
    end
    if ((seen && validIn) && (vr < 8'd255)) begin
      vr = vr + 8'd1;
    end
    a1 = {24'b0, gp};
    a1_0 = {24'b0, sv};
    a1_1 = {24'b0, vr};
    sCnt_next = sC;
    gap_next = gp;
    snv_next = sv;
    vrun_next = vr;
    seenStart_next = seen;
    sawValid_next = saw;
    measuring_next = mea;
    t_2 = {24'b0, sC};
    capCad_1 = (t_2 | (a1 <<< 32'sd8)) | ((a1_0 <<< 32'sd16) | (a1_1 <<< 32'sd24));
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        capCad_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          capCad_last_value <= capCad;
        end
      end
    end

  assign capCad = (stateControl_2 == 1'b0 ? capCad_last_value :
              capCad_1);

endmodule  // FecCaptureCadence

