// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/FIFO.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIFO
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/FIFO
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIFO
          (clk,
           reset,
           enb_1_2_0,
           in_re,
           in_im,
           push,
           pop,
           reset_1,
           enSlack,
           out_re,
           out_im,
           numEntries,
           validPop,
           witA,
           witB);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] in_re;  // sfix16_En14
  input   signed [15:0] in_im;  // sfix16_En14
  input   push;
  input   pop;
  input   reset_1;
  input   enSlack;
  output  signed [15:0] out_re;  // sfix16_En14
  output  signed [15:0] out_im;  // sfix16_En14
  output  [13:0] numEntries;  // ufix14
  output  validPop;
  output  [31:0] witA;  // uint32
  output  [31:0] witB;  // uint32


  reg  Delay1_out1;
  reg  Delay1_out1_1;
  wire Validate_Input_Push_Pop_valid_push;
  wire Validate_Input_Push_Pop_valid_pop;
  wire [13:0] Validate_Input_Push_Pop_numEntries;  // ufix14
  wire Validate_Input_Push_Pop_pushOnFullRaw;
  wire [13:0] count_step;  // ufix14
  wire [13:0] count_from;  // ufix14
  wire [13:0] count_reset;  // ufix14
  reg [13:0] Push_Counter_out1;  // ufix14
  wire [13:0] count;  // ufix14
  wire need_to_wrap;
  wire [13:0] count_value;  // ufix14
  wire [13:0] count_1;  // ufix14
  wire [13:0] count_2;  // ufix14
  wire [13:0] count_step_1;  // ufix14
  wire [13:0] count_from_1;  // ufix14
  wire [13:0] count_reset_1;  // ufix14
  reg [13:0] Pop_Counter_out1;  // ufix14
  wire [13:0] count_3;  // ufix14
  wire need_to_wrap_1;
  wire [13:0] count_value_1;  // ufix14
  wire [13:0] count_4;  // ufix14
  wire [13:0] count_5;  // ufix14
  wire signed [15:0] Simple_Dual_Port_RAM_out1_re;  // sfix16_En14
  wire signed [15:0] Simple_Dual_Port_RAM_out1_im;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= reset_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        Delay1_out1_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_1 <= Delay1_out1;
        end
      end
    end

  Validate_Input_Push_Pop u_Validate_Input_Push_Pop (.clk(clk),
                                                                      .reset(reset),
                                                                      .enb_1_2_0(enb_1_2_0),
                                                                      .rst(reset_1),
                                                                      .push(push),
                                                                      .pop(pop),
                                                                      .valid_push(Validate_Input_Push_Pop_valid_push),
                                                                      .valid_pop(Validate_Input_Push_Pop_valid_pop),
                                                                      .numEntries(Validate_Input_Push_Pop_numEntries),  // ufix14
                                                                      .enSlack(enSlack),
                                                                      .pushOnFullRaw(Validate_Input_Push_Pop_pushOnFullRaw)
                                                                      );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 12332
  assign count_step = 14'b00000000000001;

  assign count_from = 14'b00000000000000;

  assign count_reset = 14'b00000000000000;

  assign count = Push_Counter_out1 + count_step;

  assign need_to_wrap = Push_Counter_out1 == 14'b11000000101100;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (Validate_Input_Push_Pop_valid_push == 1'b0 ? Push_Counter_out1 :
              count_value);

  assign count_2 = (Delay1_out1_1 == 1'b0 ? count_1 :
              count_reset);

  always @(posedge clk or posedge reset)
    begin : Push_Counter_process
      if (reset == 1'b1) begin
        Push_Counter_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Push_Counter_out1 <= count_2;
        end
      end
    end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 12332
  assign count_step_1 = 14'b00000000000001;

  assign count_from_1 = 14'b00000000000000;

  assign count_reset_1 = 14'b00000000000000;

  assign count_3 = Pop_Counter_out1 + count_step_1;

  assign need_to_wrap_1 = Pop_Counter_out1 == 14'b11000000101100;

  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_3 :
              count_from_1);

  assign count_4 = (Validate_Input_Push_Pop_valid_pop == 1'b0 ? Pop_Counter_out1 :
              count_value_1);

  assign count_5 = (Delay1_out1_1 == 1'b0 ? count_4 :
              count_reset_1);

  always @(posedge clk or posedge reset)
    begin : Pop_Counter_process
      if (reset == 1'b1) begin
        Pop_Counter_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Pop_Counter_out1 <= count_5;
        end
      end
    end

  SimpleDualPortRAM_generic #(.AddrWidth(14),
                                               .DataWidth(16)
                                               )
                                             u_Simple_Dual_Port_RAM (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .wr_din_re(in_re),
                                                                     .wr_din_im(in_im),
                                                                     .wr_addr(Push_Counter_out1),
                                                                     .wr_en(Validate_Input_Push_Pop_valid_push),
                                                                     .rd_addr(Pop_Counter_out1),
                                                                     .dout_re(Simple_Dual_Port_RAM_out1_re),
                                                                     .dout_im(Simple_Dual_Port_RAM_out1_im)
                                                                     );

  assign out_re = Simple_Dual_Port_RAM_out1_re;

  assign out_im = Simple_Dual_Port_RAM_out1_im;

  assign numEntries = Validate_Input_Push_Pop_numEntries;

  assign validPop = Validate_Input_Push_Pop_valid_pop;

  // ---- beat witness (2026-08-29, v5; v1-v4 each vetoed by the pre-build gates, log in SINGLES_CAMPAIGN).
  // Established by those vetoes: (push-pop) oscillates 0<->1 every symbol in a HEALTHY fifo (v1), the
  // occupancy counter is pipelined differently so comparing them is noisy (v2), the "settled" qualifier does
  // not remove the oscillation (v3), and during the initial FILL the difference legitimately sweeps 0..12332
  // so any range test fires on a clean run (v4).
  // What every run DID show clean: the difference sampled once per FRAME -- 0 on every healthy run, 1 while
  // displaced. v5 therefore builds its own frame strobe (a mod-12333 count of accepted pops), samples the
  // difference there, ignores the first 4 frames (fill), and counts changes of that per-frame sample.
  //   witA = {2'b0, numEntries[13:0], per_frame_addr_diff[13:0], 2'b0}
  //   witB = {push_on_full_count[15:0], displacement_events[7:0], max_per_frame_diff[7:0]}
  wire [14:0] wit_diff_raw = {1'b0, Push_Counter_out1} + 15'd12333 - {1'b0, Pop_Counter_out1};
  wire [13:0] wit_addr_diff = (wit_diff_raw >= 15'd12333) ? (wit_diff_raw - 15'd12333) : wit_diff_raw[13:0];
  reg  [13:0] wit_popctr;
  wire        wit_frame = (wit_popctr == 14'd12332) & Validate_Input_Push_Pop_valid_pop;
  reg  [13:0] wit_sample;
  reg  [2:0]  wit_armctr;
  reg  [7:0]  wit_events;
  reg  [7:0]  wit_max;
  reg  [15:0] wit_pof_count;
  always @(posedge clk or posedge reset) begin
    if (reset == 1'b1) begin
      wit_popctr <= 14'd0; wit_sample <= 14'd0; wit_armctr <= 3'd0;
      wit_events <= 8'd0; wit_max <= 8'd0; wit_pof_count <= 16'd0;
    end else if (enb_1_2_0) begin
      if (Validate_Input_Push_Pop_valid_pop)
        wit_popctr <= (wit_popctr == 14'd12332) ? 14'd0 : (wit_popctr + 14'd1);
      if (wit_frame) begin
        wit_sample <= wit_addr_diff;
        if (wit_armctr != 3'd7) wit_armctr <= wit_armctr + 3'd1;
        if (wit_armctr >= 3'd4) begin
          if (wit_addr_diff != wit_sample && wit_events != 8'hFF) wit_events <= wit_events + 8'd1;
          if (wit_addr_diff < 14'd256 && wit_addr_diff[7:0] > wit_max) wit_max <= wit_addr_diff[7:0];
        end
      end
      if (Validate_Input_Push_Pop_pushOnFullRaw && wit_pof_count != 16'hFFFF) wit_pof_count <= wit_pof_count + 16'd1;
    end
  end
  assign witA = {2'b00, Validate_Input_Push_Pop_numEntries, wit_sample, 2'b00};
  assign witB = {wit_pof_count, wit_events, wit_max};

endmodule  // FIFO

