// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/FilterTapSystolicPreAddWvlIn_block.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAddWvlIn_block
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/RRC Transmit Filter/RRC Filter/Filter/subFilter/FilterTapSystolicPreAddWvlIn
// Hierarchy Level: 7
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAddWvlIn_block
          (clk,
           enb_1_2_0,
           dinReg2_0_re,
           dinPreAdd,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   enb_1_2_0;
  input   signed [16:0] dinReg2_0_re;  // sfix17_En16
  input   signed [16:0] dinPreAdd;  // sfix17_En16
  input   signed [16:0] coefIn_0;  // sfix17_En16
  input   signed [47:0] addin;  // sfix48_En32
  input   dinRegVld;
  input   syncReset;
  output  signed [16:0] dinDly2;  // sfix17_En16
  output  signed [47:0] tapout;  // sfix48_En32


  reg signed [34:0] fTap_mult_reg;  // sfix35
  reg signed [16:0] fTap_din1_reg1;  // sfix17
  reg signed [16:0] fTap_din1_reg2;  // sfix17
  reg signed [16:0] fTap_din2_reg1;  // sfix17
  reg signed [17:0] fTap_preAdd_reg;  // sfix18
  reg signed [47:0] fTap_addout_reg;  // sfix48
  reg signed [16:0] fTap_coef_reg1;  // sfix17
  reg signed [16:0] fTap_coef_reg2;  // sfix17
  reg signed [34:0] fTap_mult_reg_next;  // sfix35_En32
  reg signed [16:0] fTap_din1_reg1_next;  // sfix17_En16
  reg signed [16:0] fTap_din1_reg2_next;  // sfix17_En16
  reg signed [16:0] fTap_din2_reg1_next;  // sfix17_En16
  reg signed [17:0] fTap_preAdd_reg_next;  // sfix18_En16
  reg signed [47:0] fTap_addout_reg_next;  // sfix48_En32
  reg signed [16:0] fTap_coef_reg1_next;  // sfix17_En16
  reg signed [16:0] fTap_coef_reg2_next;  // sfix17_En16
  reg signed [16:0] dinDly2_1;  // sfix17_En16
  reg signed [47:0] tapout_1;  // sfix48_En32
  reg signed [47:0] fTap_add_cast;  // sfix48_En32
  reg signed [17:0] fTap_add_cast_0;  // sfix18_En16
  reg signed [17:0] fTap_add_cast_1;  // sfix18_En16

  initial begin
    fTap_din1_reg1 = 17'sb00000000000000000;
    fTap_din1_reg2 = 17'sb00000000000000000;
    fTap_din2_reg1 = 17'sb00000000000000000;
    fTap_preAdd_reg = 18'sb000000000000000000;
    fTap_coef_reg1 = 17'sb00000000000000000;
    fTap_coef_reg2 = 17'sb00000000000000000;
    fTap_mult_reg = 35'sh000000000;
    fTap_addout_reg = 48'sh000000000000;
  end

  // FilterTapSystolicPreAddWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb_1_2_0) begin
        if (syncReset == 1'b1) begin
          fTap_din1_reg1 <= 17'sb00000000000000000;
          fTap_din1_reg2 <= 17'sb00000000000000000;
          fTap_din2_reg1 <= 17'sb00000000000000000;
          fTap_preAdd_reg <= 18'sb000000000000000000;
          fTap_coef_reg1 <= 17'sb00000000000000000;
          fTap_coef_reg2 <= 17'sb00000000000000000;
          fTap_mult_reg <= 35'sh000000000;
          fTap_addout_reg <= 48'sh000000000000;
        end
        else begin
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_din2_reg1 <= fTap_din2_reg1_next;
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
        end
      end
    end

  always @(addin, coefIn_0, dinPreAdd, dinReg2_0_re, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din1_reg1, fTap_din1_reg2,
       fTap_din2_reg1, fTap_mult_reg, fTap_preAdd_reg) begin
    fTap_add_cast = 48'sh000000000000;
    fTap_add_cast_0 = 18'sb000000000000000000;
    fTap_add_cast_1 = 18'sb000000000000000000;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_din2_reg1_next = fTap_din2_reg1;
    fTap_preAdd_reg_next = fTap_preAdd_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_coef_reg2_next = fTap_coef_reg2;
    if (dinRegVld) begin
      fTap_add_cast = {{13{fTap_mult_reg[34]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
      fTap_add_cast_0 = {fTap_din1_reg2[16], fTap_din1_reg2};
      fTap_add_cast_1 = {fTap_din2_reg1[16], fTap_din2_reg1};
      fTap_preAdd_reg_next = fTap_add_cast_0 + fTap_add_cast_1;
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
      fTap_din2_reg1_next = dinPreAdd;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end

  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicPreAddWvlIn_block

