// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/FixCtlDec.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FixCtlDec
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/FixCtlDec
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FixCtlDec
          (ctl,
           enContract,
           enSerAnchor,
           enGridPace,
           enSlack,
           enSpurStart);


  input   [31:0] ctl;  // uint32
  output  enContract;
  output  enSerAnchor;
  output  enGridPace;
  output  enSlack;
  output  enSpurStart;  // 2026-08-30 fixctl bit4: inject ONE spurious FEC start pulse on each rising edge   // 2026-08-29 fixctl bit3: delay-FIFO slack (beat trigger-removal arm)




  assign enContract = (ctl & 32'd1) != 32'd0;
  assign enSerAnchor = (ctl & 32'd2) != 32'd0;
  assign enGridPace = (ctl & 32'd4) != 32'd0;
  assign enSlack = (ctl & 32'd8) != 32'd0;
  assign enSpurStart = (ctl & 32'd16) != 32'd0;

endmodule  // FixCtlDec

