// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/FrameStatFifo.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FrameStatFifo
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/FrameStatFifo
// Hierarchy Level: 1
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FrameStatFifo
          (clk,
           reset,
           enb_1_2_0,
           rec,
           push,
           popTok,
           headLo,
           headHi,
           stat);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   [63:0] rec;  // ufix64
  input   push;
  input   [31:0] popTok;  // uint32
  output  [31:0] headLo;  // uint32
  output  [31:0] headHi;  // uint32
  output  [31:0] stat;  // uint32


  wire stateControl_1;
  reg  [1:0] delayMatch1_reg;  // ufix1 [2]
  wire stateControl_2;
  wire enb_1_2_0_gated;
  reg [31:0] delayMatch_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch_reg_next [0:1];  // ufix32 [2]
  wire [31:0] popTok_1;  // uint32
  reg [31:0] headLo_1;  // uint32
  reg [31:0] headHi_1;  // uint32
  reg [31:0] stat_1;  // uint32
  reg [63:0] mem [0:63];  // uint64 [64]
  reg [15:0] wr;  // uint16
  reg [15:0] rd;  // uint16
  reg [15:0] ovfCnt;  // uint16
  reg [31:0] prevPop;  // uint32
  reg [63:0] mem_next [0:63];  // uint64 [64]
  reg [15:0] wr_next;  // uint16
  reg [15:0] rd_next;  // uint16
  reg [15:0] ovfCnt_next;  // uint16
  reg [31:0] prevPop_next;  // uint32
  reg [31:0] headLo_last_value;  // uint32
  reg [31:0] headHi_last_value;  // uint32
  reg [31:0] stat_last_value;  // uint32
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32
  reg [15:0] nxt;  // uint16
  reg [63:0] head;  // uint64
  reg [31:0] level;  // uint32
  reg [31:0] x;  // uint32
  reg [31:0] a1;  // uint32
  reg [31:0] t;  // uint32
  reg [31:0] t_0;  // uint32
  reg [31:0] t_1;  // uint32
  reg [63:0] mem_temp [0:63];  // uint64 [64]
  reg [15:0] wr_temp;  // uint16
  reg [15:0] rd_temp;  // uint16
  reg [15:0] ovfCnt_temp;  // uint16
  reg [31:0] t_2;  // uint32
  reg [31:0] t_3;  // uint32
  reg [31:0] t_4;  // uint32
  reg signed [31:0] t_5;  // int32
  reg signed [31:0] t_6;  // int32
  reg [63:0] cast;  // ufix64
  reg [31:0] add_temp;  // uint32
  reg [63:0] cast_0;  // ufix64
  reg [31:0] add_temp_0;  // uint32
  reg signed [32:0] sub_temp;  // sfix33
  reg [31:0] add_cast;  // uint32
  reg [32:0] add_cast_0;  // ufix33
  reg [32:0] add_temp_1;  // ufix33
  reg [16:0] add_temp_2;  // ufix17
  reg [63:0] cast_1;  // ufix64
  reg [63:0] head_0;  // uint64
  reg [63:0] head_1;  // uint64
  reg [31:0] t_7;  // uint32
  reg [31:0] t_8;  // uint32
  reg [16:0] t_9;  // ufix17
  reg [31:0] t_10;  // uint32
  reg [31:0] t_11;  // uint32
  reg [31:0] t_12;  // uint32
  reg signed [32:0] t_13;  // sfix33
  reg [31:0] t_14;  // uint32
  reg signed [32:0] t_15;  // sfix33
  reg signed [31:0] t_0_0;  // int32
  reg signed [31:0] t_1_0;  // int32


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[1] <= delayMatch1_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[1];

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd1; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg[delayMatch_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd1; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
            delayMatch_reg[delayMatch_t_0_0] <= delayMatch_reg_next[delayMatch_t_0_0];
          end
        end
      end
    end

  assign popTok_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = popTok;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];

  always @(posedge clk or posedge reset)
    begin : FrameStatFifo_process
      if (reset == 1'b1) begin

        for(t_1_0 = 32'sd0; t_1_0 <= 32'sd63; t_1_0 = t_1_0 + 32'sd1) begin
          mem[t_1_0] <= 64'd0;
        end

        wr <= 16'd0;
        rd <= 16'd0;
        ovfCnt <= 16'd0;
        prevPop <= 32'd0;
      end
      else begin
        if (enb_1_2_0_gated) begin

          for(t_0_0 = 32'sd0; t_0_0 <= 32'sd63; t_0_0 = t_0_0 + 32'sd1) begin
            mem[t_0_0] <= mem_next[t_0_0];
          end

          wr <= wr_next;
          rd <= rd_next;
          ovfCnt <= ovfCnt_next;
          prevPop <= prevPop_next;
        end
      end
    end

  always @* begin
    t_0 = 32'd0;
    t = 32'd0;
    add_temp = 32'd0;
    add_temp_0 = 32'd0;
    add_temp_2 = 17'b00000000000000000;
    t_7 = 32'd0;
    cast = 64'h0000000000000000;
    t_2 = 32'd0;
    t_8 = 32'd0;
    nxt = 16'd0;
    t_9 = 17'b00000000000000000;
    t_10 = 32'd0;
    cast_0 = 64'h0000000000000000;
    t_3 = 32'd0;
    t_11 = 32'd0;

    for(t_5 = 32'sd0; t_5 <= 32'sd63; t_5 = t_5 + 32'sd1) begin
      mem_temp[t_5] = mem[t_5];
    end

    wr_temp = wr;
    rd_temp = rd;
    ovfCnt_temp = ovfCnt;
    // 64-deep record FIFO. HEAD = mem(rd). Host: read 0x1D0 (lo), 0x1D4 (hi),
    // then write a changed token to 0x1DC to advance. STAT(0x1D8) =
    // {ovf[31:16] | level[15:0]}. Drop-newest on full.
    if (push) begin
      t_7 = {16'b0, wr};
      t = (t_7 + 32'd1) + 0  >> 32'd6;
      cast = {26'b0, {t, 6'b000000}};
      t_2 = cast[31:0];
      t_8 = {16'b0, wr};
      add_temp = (t_8 - t_2) + 32'd1;
      if (add_temp[31:16] != 16'b0000000000000000) begin
        nxt = 16'b1111111111111111;
      end
      else begin
        nxt = add_temp[15:0];
      end
      if (nxt == rd) begin
        if (ovfCnt < 16'd65535) begin
          t_9 = {1'b0, ovfCnt};
          add_temp_2 = t_9 + 17'b00000000000000001;
          if (add_temp_2[16] != 1'b0) begin
            ovfCnt_temp = 16'b1111111111111111;
          end
          else begin
            ovfCnt_temp = add_temp_2[15:0];
          end
        end
      end
      else begin
        mem_temp[wr] = rec;
        wr_temp = nxt;
      end
    end
    if ((popTok_1 != prevPop) && (wr_temp != rd)) begin
      t_10 = {16'b0, rd};
      t_0 = (t_10 + 32'd1) + 0  >> 32'd6;
      cast_0 = {26'b0, {t_0, 6'b000000}};
      t_3 = cast_0[31:0];
      t_11 = {16'b0, rd};
      add_temp_0 = (t_11 - t_3) + 32'd1;
      if (add_temp_0[31:16] != 16'b0000000000000000) begin
        rd_temp = 16'b1111111111111111;
      end
      else begin
        rd_temp = add_temp_0[15:0];
      end
    end
    prevPop_next = popTok_1;
    head = mem_temp[rd_temp];
    t_12 = {16'b0, wr_temp};
    t_13 = {1'b0, t_12};
    t_14 = {16'b0, rd_temp};
    t_15 = {1'b0, t_14};
    sub_temp = t_13 - t_15;
    if (sub_temp[32] == 1'b1) begin
      add_cast = 32'b00000000000000000000000000000000;
    end
    else begin
      add_cast = sub_temp[31:0];
    end
    add_cast_0 = {1'b0, add_cast};
    add_temp_1 = add_cast_0 + 33'h000000040;
    if (add_temp_1[32] != 1'b0) begin
      x = 32'b11111111111111111111111111111111;
    end
    else begin
      x = add_temp_1[31:0];
    end
    t_1 = x >> 32'd6;
    cast_1 = {26'b0, {t_1, 6'b000000}};
    t_4 = cast_1[31:0];
    level = x - t_4;
    a1 = {16'b0, ovfCnt_temp};
    head_0 = head & 64'd4294967295;
    headLo_1 = head_0[31:0];
    head_1 = head >> 8'd32;
    if (head_1[63:32] != 32'b00000000000000000000000000000000) begin
      headHi_1 = 32'b11111111111111111111111111111111;
    end
    else begin
      headHi_1 = head_1[31:0];
    end
    stat_1 = (a1 <<< 32'sd16) | level;

    for(t_6 = 32'sd0; t_6 <= 32'sd63; t_6 = t_6 + 32'sd1) begin
      mem_next[t_6] = mem_temp[t_6];
    end

    wr_next = wr_temp;
    rd_next = rd_temp;
    ovfCnt_next = ovfCnt_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        headLo_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          headLo_last_value <= headLo;
        end
      end
    end

  assign headLo = (stateControl_2 == 1'b0 ? headLo_last_value :
              headLo_1);

  always @(posedge clk or posedge reset)
    begin : out1_bypass_process
      if (reset == 1'b1) begin
        headHi_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          headHi_last_value <= headHi;
        end
      end
    end

  assign headHi = (stateControl_2 == 1'b0 ? headHi_last_value :
              headHi_1);

  always @(posedge clk or posedge reset)
    begin : out2_bypass_process
      if (reset == 1'b1) begin
        stat_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          stat_last_value <= stat;
        end
      end
    end

  assign stat = (stateControl_2 == 1'b0 ? stat_last_value :
              stat_1);

endmodule  // FrameStatFifo

