// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Frequency_and_Time_Synchronizer.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Frequency_and_Time_Synchronizer
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Frequency_and_Time_Synchronizer
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           rstCS,
           cs_prop_gain,
           cs_integ_gain,
           ss_prop_gain,
           ss_integ_gain,
           cfo_threshold,
           bfGridEn,
           dataOut_re,
           dataOut_im,
           startOut,
           endOut,
           validOut,
           postSymbolSync_re,
           postSymbolSync_im,
           postCarrierSync_re,
           postCarrierSync_im,
           normCoarseFreqEst,
           rstcsDet,
           p1c_telI,
           p1c_telQ,
           fs_runmax,
           beatobsRhCtr,
           beatobsPush,
           beatobsPop,
           enSlack,
           pdWitA,
           pdWitB);


  input   clk;
  input   enSlack;
  output  [31:0] pdWitA;  // uint32
  output  [31:0] pdWitB;  // uint32
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En12
  input   signed [15:0] dataIn_im;  // sfix16_En12
  input   validIn;
  input   rstCS;
  input   [31:0] cs_prop_gain;  // uint32
  input   [31:0] cs_integ_gain;  // uint32
  input   [31:0] ss_prop_gain;  // uint32
  input   [31:0] ss_integ_gain;  // uint32
  input   [31:0] cfo_threshold;  // uint32
  input   bfGridEn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  startOut;
  output  endOut;
  output  validOut;
  output  signed [15:0] postSymbolSync_re;  // sfix16_En14
  output  signed [15:0] postSymbolSync_im;  // sfix16_En14
  output  signed [15:0] postCarrierSync_re;  // sfix16_En14
  output  signed [15:0] postCarrierSync_im;  // sfix16_En14
  output  signed [20:0] normCoarseFreqEst;  // sfix21_En21
  output  rstcsDet;
  output  signed [15:0] p1c_telI;  // int16
  output  signed [15:0] p1c_telQ;  // int16
  output  signed [31:0] fs_runmax;  // sfix32_En26
  output  [7:0] beatobsRhCtr;  // uint8
  output  [4:0] beatobsPush;  // ufix5
  output  [4:0] beatobsPop;  // ufix5


  wire signed [15:0] Symbol_Synchronizer_dataOut_re;  // sfix16_En14
  wire signed [15:0] Symbol_Synchronizer_dataOut_im;  // sfix16_En14
  wire Symbol_Synchronizer_validOut;
  wire [7:0] Symbol_Synchronizer_beatobsRhCtr;  // uint8
  wire [4:0] Symbol_Synchronizer_beatobsPush;  // ufix5
  wire [4:0] Symbol_Synchronizer_beatobsPop;  // ufix5
  wire signed [15:0] Coarse_Frequency_Compensator_dataOut_re;  // sfix16_En14
  wire signed [15:0] Coarse_Frequency_Compensator_dataOut_im;  // sfix16_En14
  wire Coarse_Frequency_Compensator_rstCS;
  wire Coarse_Frequency_Compensator_validOut;
  wire signed [20:0] Coarse_Frequency_Compensator_normalizedFreqEst;  // sfix21_En21
  wire signed [15:0] Carrier_Synchronizer_dataOut_re;  // sfix16_En14
  wire signed [15:0] Carrier_Synchronizer_dataOut_im;  // sfix16_En14
  wire Carrier_Synchronizer_validOut;
  wire signed [15:0] Preamble_Detector_dataOut_re;  // sfix16_En14
  wire signed [15:0] Preamble_Detector_dataOut_im;  // sfix16_En14
  wire Preamble_Detector_syncPulse;
  wire Preamble_Detector_validOut;
  wire signed [15:0] Preamble_Detector_p1c_telI;  // int16
  wire signed [15:0] Preamble_Detector_p1c_telQ;  // int16
  wire signed [31:0] Preamble_Detector_fs_runmax;  // sfix32_En26
  wire signed [15:0] Phase_Ambiguity_Estimation_and_Correction_dataOut_re;  // sfix16_En14
  wire signed [15:0] Phase_Ambiguity_Estimation_and_Correction_dataOut_im;  // sfix16_En14
  wire Phase_Ambiguity_Estimation_and_Correction_syncPulseOut;
  wire Phase_Ambiguity_Estimation_and_Correction_validOut;
  wire signed [15:0] Packet_Controller_dataOut_re;  // sfix16_En14
  wire signed [15:0] Packet_Controller_dataOut_im;  // sfix16_En14
  wire Packet_Controller_startOut;
  wire Packet_Controller_endOut;
  wire Packet_Controller_validOut;


  Symbol_Synchronizer u_Symbol_Synchronizer (.clk(clk),
                                                              .reset(reset),
                                                              .enb_1_2_0(enb_1_2_0),
                                                              .dataIn_re(dataIn_re),  // sfix16_En12
                                                              .dataIn_im(dataIn_im),  // sfix16_En12
                                                              .validIn(validIn),
                                                              .ss_prop_gain(ss_prop_gain),  // uint32
                                                              .ss_integ_gain(ss_integ_gain),  // uint32
                                                              .bfGridEn(bfGridEn),
                                                              .dataOut_re(Symbol_Synchronizer_dataOut_re),  // sfix16_En14
                                                              .dataOut_im(Symbol_Synchronizer_dataOut_im),  // sfix16_En14
                                                              .validOut(Symbol_Synchronizer_validOut),
                                                              .beatobsRhCtr(Symbol_Synchronizer_beatobsRhCtr),  // uint8
                                                              .beatobsPush(Symbol_Synchronizer_beatobsPush),  // ufix5
                                                              .beatobsPop(Symbol_Synchronizer_beatobsPop)  // ufix5
                                                              );

  Coarse_Frequency_Compensator u_Coarse_Frequency_Compensator (.clk(clk),
                                                                                .reset(reset),
                                                                                .enb_1_2_0(enb_1_2_0),
                                                                                .dataIn_re(Symbol_Synchronizer_dataOut_re),  // sfix16_En14
                                                                                .dataIn_im(Symbol_Synchronizer_dataOut_im),  // sfix16_En14
                                                                                .validIn(Symbol_Synchronizer_validOut),
                                                                                .cfo_threshold(cfo_threshold),  // uint32
                                                                                .dataOut_re(Coarse_Frequency_Compensator_dataOut_re),  // sfix16_En14
                                                                                .dataOut_im(Coarse_Frequency_Compensator_dataOut_im),  // sfix16_En14
                                                                                .rstCS(Coarse_Frequency_Compensator_rstCS),
                                                                                .validOut(Coarse_Frequency_Compensator_validOut),
                                                                                .normalizedFreqEst(Coarse_Frequency_Compensator_normalizedFreqEst)  // sfix21_En21
                                                                                );

  Carrier_Synchronizer u_Carrier_Synchronizer (.clk(clk),
                                                                .reset(reset),
                                                                .enb_1_2_0(enb_1_2_0),
                                                                .dataIn_re(Coarse_Frequency_Compensator_dataOut_re),  // sfix16_En14
                                                                .dataIn_im(Coarse_Frequency_Compensator_dataOut_im),  // sfix16_En14
                                                                .internalRst(Coarse_Frequency_Compensator_rstCS),
                                                                .validIn(Coarse_Frequency_Compensator_validOut),
                                                                .manualRst(rstCS),
                                                                .cs_prop_gain(cs_prop_gain),  // uint32
                                                                .cs_integ_gain(cs_integ_gain),  // uint32
                                                                .dataOut_re(Carrier_Synchronizer_dataOut_re),  // sfix16_En14
                                                                .dataOut_im(Carrier_Synchronizer_dataOut_im),  // sfix16_En14
                                                                .validOut(Carrier_Synchronizer_validOut)
                                                                );

  Preamble_Detector u_Preamble_Detector (.clk(clk),
                                                          .reset(reset),
                                                          .enb_1_2_0(enb_1_2_0),
                                                          .dataIn_re(Carrier_Synchronizer_dataOut_re),  // sfix16_En14
                                                          .dataIn_im(Carrier_Synchronizer_dataOut_im),  // sfix16_En14
                                                          .validIn(Carrier_Synchronizer_validOut),
                                                          .dataOut_re(Preamble_Detector_dataOut_re),  // sfix16_En14
                                                          .dataOut_im(Preamble_Detector_dataOut_im),  // sfix16_En14
                                                          .syncPulse(Preamble_Detector_syncPulse),
                                                          .validOut(Preamble_Detector_validOut),
                                                          .p1c_telI(Preamble_Detector_p1c_telI),  // int16
                                                          .p1c_telQ(Preamble_Detector_p1c_telQ),  // int16
                                                          .fs_runmax(Preamble_Detector_fs_runmax),  // sfix32_En26
                                        .enSlack(enSlack),
                                        .pdWitA(pdWitA),
                                        .pdWitB(pdWitB));

  Phase_Ambiguity_Estimation_and_Correction u_Phase_Ambiguity_Estimation_and_Correction (.clk(clk),
                                                                                                          .reset(reset),
                                                                                                          .enb_1_2_0(enb_1_2_0),
                                                                                                          .dataIn_re(Preamble_Detector_dataOut_re),  // sfix16_En14
                                                                                                          .dataIn_im(Preamble_Detector_dataOut_im),  // sfix16_En14
                                                                                                          .syncPulseIn(Preamble_Detector_syncPulse),
                                                                                                          .validIn(Preamble_Detector_validOut),
                                                                                                          .dataOut_re(Phase_Ambiguity_Estimation_and_Correction_dataOut_re),  // sfix16_En14
                                                                                                          .dataOut_im(Phase_Ambiguity_Estimation_and_Correction_dataOut_im),  // sfix16_En14
                                                                                                          .syncPulseOut(Phase_Ambiguity_Estimation_and_Correction_syncPulseOut),
                                                                                                          .validOut(Phase_Ambiguity_Estimation_and_Correction_validOut)
                                                                                                          );

  Packet_Controller u_Packet_Controller (.clk(clk),
                                                          .reset(reset),
                                                          .enb_1_2_0(enb_1_2_0),
                                                          .dataIn_re(Phase_Ambiguity_Estimation_and_Correction_dataOut_re),  // sfix16_En14
                                                          .dataIn_im(Phase_Ambiguity_Estimation_and_Correction_dataOut_im),  // sfix16_En14
                                                          .syncPulse(Phase_Ambiguity_Estimation_and_Correction_syncPulseOut),
                                                          .validIn(Phase_Ambiguity_Estimation_and_Correction_validOut),
                                                          .dataOut_re(Packet_Controller_dataOut_re),  // sfix16_En14
                                                          .dataOut_im(Packet_Controller_dataOut_im),  // sfix16_En14
                                                          .startOut(Packet_Controller_startOut),
                                                          .endOut(Packet_Controller_endOut),
                                                          .validOut(Packet_Controller_validOut)
                                                          );

  assign dataOut_re = Packet_Controller_dataOut_re;

  assign dataOut_im = Packet_Controller_dataOut_im;

  assign startOut = Packet_Controller_startOut;

  assign endOut = Packet_Controller_endOut;

  assign validOut = Packet_Controller_validOut;

  assign postSymbolSync_re = Symbol_Synchronizer_dataOut_re;

  assign postSymbolSync_im = Symbol_Synchronizer_dataOut_im;

  assign postCarrierSync_re = Carrier_Synchronizer_dataOut_re;

  assign postCarrierSync_im = Carrier_Synchronizer_dataOut_im;

  assign normCoarseFreqEst = Coarse_Frequency_Compensator_normalizedFreqEst;

  assign rstcsDet = Coarse_Frequency_Compensator_rstCS;

  assign p1c_telI = Preamble_Detector_p1c_telI;

  assign p1c_telQ = Preamble_Detector_p1c_telQ;

  assign fs_runmax = Preamble_Detector_fs_runmax;

  assign beatobsRhCtr = Symbol_Synchronizer_beatobsRhCtr;

  assign beatobsPush = Symbol_Synchronizer_beatobsPush;

  assign beatobsPop = Symbol_Synchronizer_beatobsPop;

endmodule  // Frequency_and_Time_Synchronizer

