// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/GTED.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: GTED
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Gardner 
// TED/GTE
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module GTED
          (clk,
           reset,
           enb_1_2_0,
           In1_re,
           In1_im,
           Out1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [18:0] In1_re;  // sfix19_En12
  input   signed [18:0] In1_im;  // sfix19_En12
  output  signed [39:0] Out1;  // sfix40_En24


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg signed [18:0] Delay_out1;  // sfix19_En12
  wire stateControl_3;
  reg  stateControl_4;
  wire enb_1_2_0_gated_1;
  reg signed [18:0] Delay1_out1;  // sfix19_En12
  wire stateControl_5;
  reg  stateControl_6;
  wire enb_1_2_0_gated_2;
  reg signed [18:0] Delay8_reg [0:1];  // sfix19 [2]
  wire signed [18:0] Delay8_reg_next [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay8_out1;  // sfix19_En12
  wire stateControl_7;
  reg  stateControl_8;
  wire enb_1_2_0_gated_3;
  reg signed [18:0] Delay2_out1;  // sfix19_En12
  wire stateControl_9;
  reg  stateControl_10;
  wire enb_1_2_0_gated_4;
  reg signed [18:0] Delay3_out1;  // sfix19_En12
  wire signed [19:0] Add1_sub_cast;  // sfix20_En12
  wire signed [19:0] Add1_sub_cast_1;  // sfix20_En12
  wire signed [19:0] Add1_out1;  // sfix20_En12
  wire stateControl_11;
  reg  stateControl_12;
  wire enb_1_2_0_gated_5;
  reg signed [19:0] Delay9_reg [0:1];  // sfix20 [2]
  wire signed [19:0] Delay9_reg_next [0:1];  // sfix20_En12 [2]
  wire signed [19:0] Delay9_out1;  // sfix20_En12
  wire signed [38:0] Product_out1;  // sfix39_En24
  wire stateControl_13;
  reg  stateControl_14;
  wire enb_1_2_0_gated_6;
  reg signed [38:0] Delay10_reg [0:1];  // sfix39 [2]
  wire signed [38:0] Delay10_reg_next [0:1];  // sfix39_En24 [2]
  wire signed [38:0] Delay10_out1;  // sfix39_En24
  wire stateControl_15;
  reg  stateControl_16;
  wire enb_1_2_0_gated_7;
  reg signed [18:0] Delay4_out1;  // sfix19_En12
  wire stateControl_17;
  reg  stateControl_18;
  wire enb_1_2_0_gated_8;
  reg signed [18:0] Delay5_out1;  // sfix19_En12
  wire stateControl_19;
  reg  stateControl_20;
  wire enb_1_2_0_gated_9;
  reg signed [18:0] Delay11_reg [0:1];  // sfix19 [2]
  wire signed [18:0] Delay11_reg_next [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay11_out1;  // sfix19_En12
  wire stateControl_21;
  reg  stateControl_22;
  wire enb_1_2_0_gated_10;
  reg signed [18:0] Delay6_out1;  // sfix19_En12
  wire stateControl_23;
  reg  stateControl_24;
  wire enb_1_2_0_gated_11;
  reg signed [18:0] Delay7_out1;  // sfix19_En12
  wire signed [19:0] Add2_sub_cast;  // sfix20_En12
  wire signed [19:0] Add2_sub_cast_1;  // sfix20_En12
  wire signed [19:0] Add2_out1;  // sfix20_En12
  wire stateControl_25;
  reg  stateControl_26;
  wire enb_1_2_0_gated_12;
  reg signed [19:0] Delay12_reg [0:1];  // sfix20 [2]
  wire signed [19:0] Delay12_reg_next [0:1];  // sfix20_En12 [2]
  wire signed [19:0] Delay12_out1;  // sfix20_En12
  wire signed [38:0] Product1_out1;  // sfix39_En24
  wire stateControl_27;
  reg  stateControl_28;
  wire enb_1_2_0_gated_13;
  reg signed [38:0] Delay13_reg [0:1];  // sfix39 [2]
  wire signed [38:0] Delay13_reg_next [0:1];  // sfix39_En24 [2]
  wire signed [38:0] Delay13_out1;  // sfix39_En24
  wire signed [39:0] Add_add_cast;  // sfix40_En24
  wire signed [39:0] Add_add_cast_1;  // sfix40_En24
  wire signed [39:0] Add_out1;  // sfix40_En24
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_1;  // int32
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32
  reg signed [31:0] Delay10_t_0_0;  // int32
  reg signed [31:0] Delay10_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_1;  // int32


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          Delay_out1 <= In1_re;
        end
      end
    end

  assign stateControl_3 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        stateControl_4 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_4 <= stateControl_3;
        end
      end
    end

  assign enb_1_2_0_gated_1 = stateControl_4 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_1) begin
          Delay1_out1 <= Delay_out1;
        end
      end
    end

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch12_process
      if (reset == 1'b1) begin
        stateControl_6 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_6 <= stateControl_5;
        end
      end
    end

  assign enb_1_2_0_gated_2 = stateControl_6 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd1; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg[Delay8_t_1] <= 19'sb0000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_2) begin
          for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd1; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
            Delay8_reg[Delay8_t_0_0] <= Delay8_reg_next[Delay8_t_0_0];
          end
        end
      end
    end

  assign Delay8_out1 = Delay8_reg[1];
  assign Delay8_reg_next[0] = Delay1_out1;
  assign Delay8_reg_next[1] = Delay8_reg[0];

  assign stateControl_7 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        stateControl_8 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_8 <= stateControl_7;
        end
      end
    end

  assign enb_1_2_0_gated_3 = stateControl_8 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_3) begin
          Delay2_out1 <= Delay1_out1;
        end
      end
    end

  assign stateControl_9 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        stateControl_10 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_10 <= stateControl_9;
        end
      end
    end

  assign enb_1_2_0_gated_4 = stateControl_10 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_4) begin
          Delay3_out1 <= Delay2_out1;
        end
      end
    end

  assign Add1_sub_cast = {Delay3_out1[18], Delay3_out1};
  assign Add1_sub_cast_1 = {In1_re[18], In1_re};
  assign Add1_out1 = Add1_sub_cast - Add1_sub_cast_1;

  assign stateControl_11 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch13_process
      if (reset == 1'b1) begin
        stateControl_12 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_12 <= stateControl_11;
        end
      end
    end

  assign enb_1_2_0_gated_5 = stateControl_12 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
          Delay9_reg[Delay9_t_1] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_5) begin
          for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
            Delay9_reg[Delay9_t_0_0] <= Delay9_reg_next[Delay9_t_0_0];
          end
        end
      end
    end

  assign Delay9_out1 = Delay9_reg[1];
  assign Delay9_reg_next[0] = Add1_out1;
  assign Delay9_reg_next[1] = Delay9_reg[0];

  assign Product_out1 = Delay8_out1 * Delay9_out1;

  assign stateControl_13 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        stateControl_14 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_14 <= stateControl_13;
        end
      end
    end

  assign enb_1_2_0_gated_6 = stateControl_14 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        for(Delay10_t_1 = 32'sd0; Delay10_t_1 <= 32'sd1; Delay10_t_1 = Delay10_t_1 + 32'sd1) begin
          Delay10_reg[Delay10_t_1] <= 39'sh0000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_6) begin
          for(Delay10_t_0_0 = 32'sd0; Delay10_t_0_0 <= 32'sd1; Delay10_t_0_0 = Delay10_t_0_0 + 32'sd1) begin
            Delay10_reg[Delay10_t_0_0] <= Delay10_reg_next[Delay10_t_0_0];
          end
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[1];
  assign Delay10_reg_next[0] = Product_out1;
  assign Delay10_reg_next[1] = Delay10_reg[0];

  assign stateControl_15 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch8_process
      if (reset == 1'b1) begin
        stateControl_16 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_16 <= stateControl_15;
        end
      end
    end

  assign enb_1_2_0_gated_7 = stateControl_16 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_7) begin
          Delay4_out1 <= In1_im;
        end
      end
    end

  assign stateControl_17 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch9_process
      if (reset == 1'b1) begin
        stateControl_18 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_18 <= stateControl_17;
        end
      end
    end

  assign enb_1_2_0_gated_8 = stateControl_18 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_8) begin
          Delay5_out1 <= Delay4_out1;
        end
      end
    end

  assign stateControl_19 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        stateControl_20 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_20 <= stateControl_19;
        end
      end
    end

  assign enb_1_2_0_gated_9 = stateControl_20 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd1; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg[Delay11_t_1] <= 19'sb0000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_9) begin
          for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
            Delay11_reg[Delay11_t_0_0] <= Delay11_reg_next[Delay11_t_0_0];
          end
        end
      end
    end

  assign Delay11_out1 = Delay11_reg[1];
  assign Delay11_reg_next[0] = Delay5_out1;
  assign Delay11_reg_next[1] = Delay11_reg[0];

  assign stateControl_21 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch10_process
      if (reset == 1'b1) begin
        stateControl_22 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_22 <= stateControl_21;
        end
      end
    end

  assign enb_1_2_0_gated_10 = stateControl_22 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_10) begin
          Delay6_out1 <= Delay5_out1;
        end
      end
    end

  assign stateControl_23 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch11_process
      if (reset == 1'b1) begin
        stateControl_24 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_24 <= stateControl_23;
        end
      end
    end

  assign enb_1_2_0_gated_11 = stateControl_24 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_11) begin
          Delay7_out1 <= Delay6_out1;
        end
      end
    end

  assign Add2_sub_cast = {Delay7_out1[18], Delay7_out1};
  assign Add2_sub_cast_1 = {In1_im[18], In1_im};
  assign Add2_out1 = Add2_sub_cast - Add2_sub_cast_1;

  assign stateControl_25 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        stateControl_26 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_26 <= stateControl_25;
        end
      end
    end

  assign enb_1_2_0_gated_12 = stateControl_26 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd1; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg[Delay12_t_1] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_12) begin
          for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
            Delay12_reg[Delay12_t_0_0] <= Delay12_reg_next[Delay12_t_0_0];
          end
        end
      end
    end

  assign Delay12_out1 = Delay12_reg[1];
  assign Delay12_reg_next[0] = Add2_out1;
  assign Delay12_reg_next[1] = Delay12_reg[0];

  assign Product1_out1 = Delay11_out1 * Delay12_out1;

  assign stateControl_27 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        stateControl_28 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_28 <= stateControl_27;
        end
      end
    end

  assign enb_1_2_0_gated_13 = stateControl_28 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg[Delay13_t_1] <= 39'sh0000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_13) begin
          for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
            Delay13_reg[Delay13_t_0_0] <= Delay13_reg_next[Delay13_t_0_0];
          end
        end
      end
    end

  assign Delay13_out1 = Delay13_reg[1];
  assign Delay13_reg_next[0] = Product1_out1;
  assign Delay13_reg_next[1] = Delay13_reg[0];

  assign Add_add_cast = {Delay10_out1[38], Delay10_out1};
  assign Add_add_cast_1 = {Delay13_out1[38], Delay13_out1};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;

  assign Out1 = Add_out1;

endmodule  // GTED

