// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Input_Data.v
// Created: 2026-08-21 23:31:06
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Input_Data
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/Input Data
// Hierarchy Level: 2
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Input_Data
          (clk,
           reset,
           enb,
           enb_1_2_1,
           enb_1_2_0,
           enb_1,
           extWord,
           extWordAvail,
           extBitSel,
           extWordFirst,
           txData,
           txValid,
           extWordPop);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_2_1;
  input   enb_1_2_0;
  input   enb_1;
  input   [63:0] extWord;  // ufix64
  input   extWordAvail;
  input   extBitSel;
  input   extWordFirst;
  output  txData;
  output  txValid;
  output  extWordPop;


  reg  extBitSel_1;
  wire Message_Generator_stop;
  reg  Delay_out1;
  wire Message_Generator_out;
  wire Message_Generator_start;
  wire Message_Generator_valid;
  reg  Message_Generator_out_1;
  wire bit_rsvd;
  wire popToggle;
  wire FEC_Tx_Encoder_K5_encBit;
  wire BitMux_out1;


  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        extBitSel_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          extBitSel_1 <= extBitSel;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= Message_Generator_stop;
        end
      end
    end

  Message_Generator u_Message_Generator (.clk(clk),
                                                          .reset(reset),
                                                          .enb_1_2_0(enb_1_2_0),
                                                          .reset_1(Delay_out1),
                                                          .enable(enb_1),
                                                          .out(Message_Generator_out),
                                                          .stop(Message_Generator_stop),
                                                          .start(Message_Generator_start),
                                                          .valid(Message_Generator_valid)
                                                          );

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        Message_Generator_out_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Message_Generator_out_1 <= Message_Generator_out;
        end
      end
    end

  ByteBitShifter u_ByteBitShifter (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .enable(enb_1),
                                                    .reset_1(Delay_out1),
                                                    .start(Message_Generator_start),
                                                    .extWord(extWord),  // ufix64
                                                    .extWordAvail(extWordAvail),
                                                    .extWordFirst(extWordFirst),
                                                    .bit_rsvd(bit_rsvd),
                                                    .popToggle(popToggle)
                                                    );

  FEC_Tx_Encoder_K5 u_FEC_Tx_Encoder_K5 (.clk(clk),
                                                          .reset(reset),
                                                          .enb(enb),
                                                          .enb_1_2_1(enb_1_2_1),
                                                          .enb_1_2_0(enb_1_2_0),
                                                          .bitIn(bit_rsvd),
                                                          .enable(enb_1),
                                                          .reset_1(Delay_out1),
                                                          .start(Message_Generator_start),
                                                          .encBit(FEC_Tx_Encoder_K5_encBit)
                                                          );

  assign BitMux_out1 = (extBitSel_1 == 1'b0 ? Message_Generator_out_1 :
              FEC_Tx_Encoder_K5_encBit);

  assign txData = BitMux_out1;

  assign txValid = Message_Generator_valid;

  assign extWordPop = popToggle;

endmodule  // Input_Data

