// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/LGMux_cs_prop_gain.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LGMux_cs_prop_gain
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Carrier Synchronizer/Loop 
// Filter/LGMux_cs_prop_gai
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LGMux_cs_prop_gain
          (axi,
           coeff,
           nz);


  input   [31:0] axi;  // uint32
  output  [15:0] coeff;  // ufix16_En16
  output  nz;


  wire [15:0] si;  // ufix16


  assign si = axi[15:0];
  assign coeff = si;
  assign nz = axi != 32'd0;

endmodule  // LGMux_cs_prop_gain

