// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/LGMux_ss_prop_gain.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LGMux_ss_prop_gain
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Loop 
// Filter/LGMux_ss_prop_gai
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LGMux_ss_prop_gain
          (axi,
           coeff,
           nz);


  input   [31:0] axi;  // uint32
  output  signed [23:0] coeff;  // sfix24_En24
  output  nz;


  wire [23:0] si;  // ufix24
  wire signed [23:0] yfi_trivial_scaling;  // sfix24


  assign si = axi[23:0];
  assign yfi_trivial_scaling = si;
  assign coeff = yfi_trivial_scaling;
  assign nz = axi != 32'd0;

endmodule  // LGMux_ss_prop_gain

