// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Loop_Filter_block1.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Loop_Filter_block1
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Loop 
// Filte
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Loop_Filter_block1
          (clk,
           reset,
           enb_1_2_0,
           e,
           ss_prop_gain,
           ss_integ_gain,
           v);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [39:0] e;  // sfix40_En24
  input   [31:0] ss_prop_gain;  // uint32
  input   [31:0] ss_integ_gain;  // uint32
  output  signed [10:0] v;  // sfix11_En10


  wire signed [23:0] coeff;  // sfix24_En24
  wire nz;
  wire stateControl;
  reg  stateControl_1;
  wire enb_1_2_0_gated;
  reg signed [39:0] Delay2_reg [0:1];  // sfix40 [2]
  wire signed [39:0] Delay2_reg_next [0:1];  // sfix40_En24 [2]
  wire signed [39:0] Delay2_out1;  // sfix40_En24
  wire signed [63:0] K1_mul_temp;  // sfix64_En48
  wire signed [29:0] K1_out1;  // sfix30_En23
  wire signed [63:0] LGProd_ss_prop_gain_mul_temp;  // sfix64_En48
  wire signed [29:0] LGProd_ss_prop_gain_out1;  // sfix30_En23
  wire signed [29:0] LGSw_ss_prop_gain_out1;  // sfix30_En23
  wire stateControl_2;
  reg  stateControl_3;
  wire enb_1_2_0_gated_1;
  reg signed [29:0] Delay3_reg [0:1];  // sfix30 [2]
  wire signed [29:0] Delay3_reg_next [0:1];  // sfix30_En23 [2]
  wire signed [29:0] Delay3_out1;  // sfix30_En23
  wire stateControl_4;
  reg  stateControl_5;
  wire enb_1_2_0_gated_2;
  reg signed [29:0] Delay1_out1;  // sfix30_En23
  wire signed [23:0] coeff_1;  // sfix24_En24
  wire nz_1;
  wire signed [63:0] K2_mul_temp;  // sfix64_En48
  wire signed [29:0] K2_out1;  // sfix30_En23
  wire signed [63:0] LGProd_ss_integ_gain_mul_temp;  // sfix64_En48
  wire signed [29:0] LGProd_ss_integ_gain_out1;  // sfix30_En23
  wire signed [29:0] LGSw_ss_integ_gain_out1;  // sfix30_En23
  wire stateControl_6;
  reg  stateControl_7;
  wire enb_1_2_0_gated_3;
  reg signed [29:0] Delay5_reg [0:1];  // sfix30 [2]
  wire signed [29:0] Delay5_reg_next [0:1];  // sfix30_En23 [2]
  wire signed [29:0] Delay5_out1;  // sfix30_En23
  wire stateControl_8;
  reg  stateControl_9;
  wire enb_1_2_0_gated_4;
  reg signed [29:0] Delay6_out1;  // sfix30_En23
  wire stateControl_11;
  reg  stateControl_12;
  wire enb_1_2_0_gated_5;
  wire signed [29:0] IntegClamp_out1;  // sfix30_En23
  reg signed [29:0] Delay_out1;  // sfix30_En23
  wire signed [29:0] Add2_out1;  // sfix30_En23
  wire stateControl_13;
  reg  stateControl_14;
  wire enb_1_2_0_gated_6;
  reg signed [29:0] Delay4_out1;  // sfix30_En23
  wire signed [30:0] Add_add_cast;  // sfix31_En23
  wire signed [30:0] Add_add_cast_1;  // sfix31_En23
  wire signed [30:0] Add_out1;  // sfix31_En23
  wire signed [10:0] Data_Type_Conversion17_out1;  // sfix11_En10
  reg signed [31:0] Delay2_t_0_0;  // int32
  reg signed [31:0] Delay2_t_1;  // int32
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay5_t_0_0;  // int32
  reg signed [31:0] Delay5_t_1;  // int32

  // Proportional-Plus-Integrator Loop Filter,
  // Infinite DC Response to guarantee convergence


  LGMux_ss_prop_gain u_LGMux_ss_prop_gain (.axi(ss_prop_gain),  // uint32
                                                            .coeff(coeff),  // sfix24_En24
                                                            .nz(nz)
                                                            );

  assign stateControl = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        stateControl_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_1 <= stateControl;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_1 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        for(Delay2_t_1 = 32'sd0; Delay2_t_1 <= 32'sd1; Delay2_t_1 = Delay2_t_1 + 32'sd1) begin
          Delay2_reg[Delay2_t_1] <= 40'sh0000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated) begin
          for(Delay2_t_0_0 = 32'sd0; Delay2_t_0_0 <= 32'sd1; Delay2_t_0_0 = Delay2_t_0_0 + 32'sd1) begin
            Delay2_reg[Delay2_t_0_0] <= Delay2_reg_next[Delay2_t_0_0];
          end
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[1];
  assign Delay2_reg_next[0] = e;
  assign Delay2_reg_next[1] = Delay2_reg[0];

  assign K1_mul_temp = 24'sb111111011000000101001110 * Delay2_out1;
  assign K1_out1 = K1_mul_temp[54:25];

  assign LGProd_ss_prop_gain_mul_temp = Delay2_out1 * coeff;
  assign LGProd_ss_prop_gain_out1 = LGProd_ss_prop_gain_mul_temp[54:25];

  assign LGSw_ss_prop_gain_out1 = (nz == 1'b0 ? K1_out1 :
              LGProd_ss_prop_gain_out1);

  assign stateControl_2 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        stateControl_3 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_3 <= stateControl_2;
        end
      end
    end

  assign enb_1_2_0_gated_1 = stateControl_3 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd1; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg[Delay3_t_1] <= 30'sb000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_1) begin
          for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd1; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
            Delay3_reg[Delay3_t_0_0] <= Delay3_reg_next[Delay3_t_0_0];
          end
        end
      end
    end

  assign Delay3_out1 = Delay3_reg[1];
  assign Delay3_reg_next[0] = LGSw_ss_prop_gain_out1;
  assign Delay3_reg_next[1] = Delay3_reg[0];

  assign stateControl_4 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        stateControl_5 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_5 <= stateControl_4;
        end
      end
    end

  assign enb_1_2_0_gated_2 = stateControl_5 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_2) begin
          Delay1_out1 <= Delay3_out1;
        end
      end
    end

  LGMux_ss_integ_gain u_LGMux_ss_integ_gain (.axi(ss_integ_gain),  // uint32
                                                              .coeff(coeff_1),  // sfix24_En24
                                                              .nz(nz_1)
                                                              );

  assign K2_mul_temp = 24'sb111111111111011101111100 * Delay2_out1;
  assign K2_out1 = K2_mul_temp[54:25];

  assign LGProd_ss_integ_gain_mul_temp = Delay2_out1 * coeff_1;
  assign LGProd_ss_integ_gain_out1 = LGProd_ss_integ_gain_mul_temp[54:25];

  assign LGSw_ss_integ_gain_out1 = (nz_1 == 1'b0 ? K2_out1 :
              LGProd_ss_integ_gain_out1);

  assign stateControl_6 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        stateControl_7 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_7 <= stateControl_6;
        end
      end
    end

  assign enb_1_2_0_gated_3 = stateControl_7 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        for(Delay5_t_1 = 32'sd0; Delay5_t_1 <= 32'sd1; Delay5_t_1 = Delay5_t_1 + 32'sd1) begin
          Delay5_reg[Delay5_t_1] <= 30'sb000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_3) begin
          for(Delay5_t_0_0 = 32'sd0; Delay5_t_0_0 <= 32'sd1; Delay5_t_0_0 = Delay5_t_0_0 + 32'sd1) begin
            Delay5_reg[Delay5_t_0_0] <= Delay5_reg_next[Delay5_t_0_0];
          end
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[1];
  assign Delay5_reg_next[0] = LGSw_ss_integ_gain_out1;
  assign Delay5_reg_next[1] = Delay5_reg[0];

  assign stateControl_8 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        stateControl_9 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_9 <= stateControl_8;
        end
      end
    end

  assign enb_1_2_0_gated_4 = stateControl_9 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_4) begin
          Delay6_out1 <= Delay5_out1;
        end
      end
    end

  assign stateControl_11 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_12 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_12 <= stateControl_11;
        end
      end
    end

  assign enb_1_2_0_gated_5 = stateControl_12 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_5) begin
          Delay_out1 <= IntegClamp_out1;
        end
      end
    end

  assign Add2_out1 = Delay6_out1 + Delay_out1;

  assign IntegClamp_out1 = (Add2_out1 > 30'sb000000000001111010111000010100 ? 30'sb000000000001111010111000010100 :
              (Add2_out1 < 30'sb111111111110000101000111101100 ? 30'sb111111111110000101000111101100 :
              Add2_out1));

  assign stateControl_13 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        stateControl_14 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_14 <= stateControl_13;
        end
      end
    end

  assign enb_1_2_0_gated_6 = stateControl_14 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated_6) begin
          Delay4_out1 <= IntegClamp_out1;
        end
      end
    end

  assign Add_add_cast = {Delay1_out1[29], Delay1_out1};
  assign Add_add_cast_1 = {Delay4_out1[29], Delay4_out1};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;

  assign Data_Type_Conversion17_out1 = ((Add_out1[30] == 1'b0) && (Add_out1[29:23] != 7'b0000000) ? 11'sb01111111111 :
              ((Add_out1[30] == 1'b1) && (Add_out1[29:23] != 7'b1111111) ? 11'sb10000000000 :
              $signed(Add_out1[23:13])));

  assign v = Data_Type_Conversion17_out1;

endmodule  // Loop_Filter_block1

