// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Loop_Filter.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Loop_Filter
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Automatic Gain Control/Loop Filter
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Loop_Filter
          (clk,
           reset,
           enb_1_2_0,
           err_re,
           err_im,
           agc_loop_gain,
           gain_re,
           gain_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [32:0] err_re;  // sfix33_En28
  input   signed [32:0] err_im;  // sfix33_En28
  input   [31:0] agc_loop_gain;  // uint32
  output  signed [33:0] gain_re;  // sfix34_En28
  output  signed [33:0] gain_im;  // sfix34_En28


  wire [31:0] coeff_re;  // ufix32_En31
  wire [31:0] coeff_im;  // ufix32_En31
  wire nz;
  wire stateControl;
  reg  stateControl_1;
  wire enb_1_2_0_gated;
  reg signed [32:0] Delay3_reg_re [0:1];  // sfix33_En28 [2]
  reg signed [32:0] Delay3_reg_im [0:1];  // sfix33_En28 [2]
  wire signed [32:0] Delay3_reg_next_re [0:1];  // sfix33_En28 [2]
  wire signed [32:0] Delay3_reg_next_im [0:1];  // sfix33_En28 [2]
  wire signed [32:0] Delay3_out1_re;  // sfix33_En28
  wire signed [32:0] Delay3_out1_im;  // sfix33_En28
  wire signed [65:0] Gain1_mul_temp;  // sfix66_En68
  wire signed [65:0] Gain1_mul_temp_1;  // sfix66_En68
  wire signed [33:0] Gain1_out1_re;  // sfix34_En28
  wire signed [33:0] Gain1_out1_im;  // sfix34_En28
  wire signed [32:0] LGProd_agc_loop_gain_cast;  // sfix33_En31
  wire signed [65:0] LGProd_agc_loop_gain_mul_temp;  // sfix66_En59
  wire signed [64:0] LGProd_agc_loop_gain_sub_cast;  // sfix65_En59
  wire signed [33:0] LGProd_agc_loop_gain_sub_cast_1;  // sfix34_En28
  wire signed [32:0] LGProd_agc_loop_gain_cast_1;  // sfix33_En31
  wire signed [65:0] LGProd_agc_loop_gain_mul_temp_1;  // sfix66_En59
  wire signed [64:0] LGProd_agc_loop_gain_sub_cast_2;  // sfix65_En59
  wire signed [33:0] LGProd_agc_loop_gain_sub_cast_3;  // sfix34_En28
  wire signed [32:0] LGProd_agc_loop_gain_cast_2;  // sfix33_En31
  wire signed [65:0] LGProd_agc_loop_gain_mul_temp_2;  // sfix66_En59
  wire signed [64:0] LGProd_agc_loop_gain_add_cast;  // sfix65_En59
  wire signed [33:0] LGProd_agc_loop_gain_add_cast_1;  // sfix34_En28
  wire signed [32:0] LGProd_agc_loop_gain_cast_3;  // sfix33_En31
  wire signed [65:0] LGProd_agc_loop_gain_mul_temp_3;  // sfix66_En59
  wire signed [64:0] LGProd_agc_loop_gain_add_cast_2;  // sfix65_En59
  wire signed [33:0] LGProd_agc_loop_gain_add_cast_3;  // sfix34_En28
  wire signed [33:0] LGProd_agc_loop_gain_out1_re;  // sfix34_En28
  wire signed [33:0] LGProd_agc_loop_gain_out1_im;  // sfix34_En28
  wire signed [33:0] LGSw_agc_loop_gain_out1_re;  // sfix34_En28
  wire signed [33:0] LGSw_agc_loop_gain_out1_im;  // sfix34_En28
  wire stateControl_2;
  reg  stateControl_3;
  wire enb_1_2_0_gated_1;
  reg signed [33:0] Delay2_reg_re [0:1];  // sfix34_En28 [2]
  reg signed [33:0] Delay2_reg_im [0:1];  // sfix34_En28 [2]
  wire signed [33:0] Delay2_reg_next_re [0:1];  // sfix34_En28 [2]
  wire signed [33:0] Delay2_reg_next_im [0:1];  // sfix34_En28 [2]
  wire signed [33:0] Delay2_out1_re;  // sfix34_En28
  wire signed [33:0] Delay2_out1_im;  // sfix34_En28
  wire stateControl_5;
  reg  stateControl_6;
  wire enb_1_2_0_gated_2;
  reg signed [33:0] Delay1_out1_re;  // sfix34_En28
  reg signed [33:0] Delay1_out1_im;  // sfix34_En28
  wire signed [33:0] Add_out1_re;  // sfix34_En28
  wire signed [33:0] Add_out1_im;  // sfix34_En28
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay2_t_0_0;  // int32
  reg signed [31:0] Delay2_t_1;  // int32

  // Fixed point precision loss warnings
  // are supressed in Mask Init Callback


  LGMux_agc_loop_gain u_LGMux_agc_loop_gain (.axi(agc_loop_gain),  // uint32
                                                              .coeff_re(coeff_re),  // ufix32_En31
                                                              .coeff_im(coeff_im),  // ufix32_En31
                                                              .nz(nz)
                                                              );

  assign stateControl = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        stateControl_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_1 <= stateControl;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_1 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd1; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg_re[Delay3_t_1] <= 33'sh000000000;
          Delay3_reg_im[Delay3_t_1] <= 33'sh000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated) begin
          for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd1; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
            Delay3_reg_re[Delay3_t_0_0] <= Delay3_reg_next_re[Delay3_t_0_0];
            Delay3_reg_im[Delay3_t_0_0] <= Delay3_reg_next_im[Delay3_t_0_0];
          end
        end
      end
    end

  assign Delay3_out1_re = Delay3_reg_re[1];
  assign Delay3_out1_im = Delay3_reg_im[1];
  assign Delay3_reg_next_re[0] = err_re;
  assign Delay3_reg_next_im[0] = err_im;
  assign Delay3_reg_next_re[1] = Delay3_reg_re[0];
  assign Delay3_reg_next_im[1] = Delay3_reg_im[0];

  assign Gain1_mul_temp = 33'sh083126E98 * Delay3_out1_re;
  assign Gain1_out1_re = {{8{Gain1_mul_temp[65]}}, Gain1_mul_temp[65:40]};
  assign Gain1_mul_temp_1 = 33'sh083126E98 * Delay3_out1_im;
  assign Gain1_out1_im = {{8{Gain1_mul_temp_1[65]}}, Gain1_mul_temp_1[65:40]};

  assign LGProd_agc_loop_gain_cast = {1'b0, coeff_re};
  assign LGProd_agc_loop_gain_mul_temp = Delay3_out1_re * LGProd_agc_loop_gain_cast;
  assign LGProd_agc_loop_gain_sub_cast = LGProd_agc_loop_gain_mul_temp[64:0];
  assign LGProd_agc_loop_gain_sub_cast_1 = LGProd_agc_loop_gain_sub_cast[64:31];
  assign LGProd_agc_loop_gain_cast_1 = {1'b0, coeff_im};
  assign LGProd_agc_loop_gain_mul_temp_1 = Delay3_out1_im * LGProd_agc_loop_gain_cast_1;
  assign LGProd_agc_loop_gain_sub_cast_2 = LGProd_agc_loop_gain_mul_temp_1[64:0];
  assign LGProd_agc_loop_gain_sub_cast_3 = LGProd_agc_loop_gain_sub_cast_2[64:31];
  assign LGProd_agc_loop_gain_out1_re = LGProd_agc_loop_gain_sub_cast_1 - LGProd_agc_loop_gain_sub_cast_3;
  assign LGProd_agc_loop_gain_cast_2 = {1'b0, coeff_re};
  assign LGProd_agc_loop_gain_mul_temp_2 = Delay3_out1_im * LGProd_agc_loop_gain_cast_2;
  assign LGProd_agc_loop_gain_add_cast = LGProd_agc_loop_gain_mul_temp_2[64:0];
  assign LGProd_agc_loop_gain_add_cast_1 = LGProd_agc_loop_gain_add_cast[64:31];
  assign LGProd_agc_loop_gain_cast_3 = {1'b0, coeff_im};
  assign LGProd_agc_loop_gain_mul_temp_3 = Delay3_out1_re * LGProd_agc_loop_gain_cast_3;
  assign LGProd_agc_loop_gain_add_cast_2 = LGProd_agc_loop_gain_mul_temp_3[64:0];
  assign LGProd_agc_loop_gain_add_cast_3 = LGProd_agc_loop_gain_add_cast_2[64:31];
  assign LGProd_agc_loop_gain_out1_im = LGProd_agc_loop_gain_add_cast_1 + LGProd_agc_loop_gain_add_cast_3;

  assign LGSw_agc_loop_gain_out1_re = (nz == 1'b0 ? Gain1_out1_re :
              LGProd_agc_loop_gain_out1_re);
  assign LGSw_agc_loop_gain_out1_im = (nz == 1'b0 ? Gain1_out1_im :
              LGProd_agc_loop_gain_out1_im);

  assign stateControl_2 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        stateControl_3 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_3 <= stateControl_2;
        end
      end
    end

  assign enb_1_2_0_gated_1 = stateControl_3 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        for(Delay2_t_1 = 32'sd0; Delay2_t_1 <= 32'sd1; Delay2_t_1 = Delay2_t_1 + 32'sd1) begin
          Delay2_reg_re[Delay2_t_1] <= 34'sh000000000;
          Delay2_reg_im[Delay2_t_1] <= 34'sh000000000;
        end
      end
      else begin
        if (enb_1_2_0_gated_1) begin
          for(Delay2_t_0_0 = 32'sd0; Delay2_t_0_0 <= 32'sd1; Delay2_t_0_0 = Delay2_t_0_0 + 32'sd1) begin
            Delay2_reg_re[Delay2_t_0_0] <= Delay2_reg_next_re[Delay2_t_0_0];
            Delay2_reg_im[Delay2_t_0_0] <= Delay2_reg_next_im[Delay2_t_0_0];
          end
        end
      end
    end

  assign Delay2_out1_re = Delay2_reg_re[1];
  assign Delay2_out1_im = Delay2_reg_im[1];
  assign Delay2_reg_next_re[0] = LGSw_agc_loop_gain_out1_re;
  assign Delay2_reg_next_im[0] = LGSw_agc_loop_gain_out1_im;
  assign Delay2_reg_next_re[1] = Delay2_reg_re[0];
  assign Delay2_reg_next_im[1] = Delay2_reg_im[0];

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_6 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_6 <= stateControl_5;
        end
      end
    end

  assign enb_1_2_0_gated_2 = stateControl_6 && enb_1_2_0;

  assign Add_out1_re = Delay2_out1_re + Delay1_out1_re;
  assign Add_out1_im = Delay2_out1_im + Delay1_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 34'sh000000000;
        Delay1_out1_im <= 34'sh000000000;
      end
      else begin
        if (enb_1_2_0_gated_2) begin
          Delay1_out1_re <= Add_out1_re;
          Delay1_out1_im <= Add_out1_im;
        end
      end
    end

  assign gain_re = Delay1_out1_re;

  assign gain_im = Delay1_out1_im;

endmodule  // Loop_Filter

