// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/MATLAB_Function_block.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function_block
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Packet Controller/MATLAB 
// Functio
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function_block
          (clk,
           reset,
           enb_1_2_0,
           valid,
           syncPulse,
           out);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   valid;
  input   syncPulse;
  output  out;


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg  out_1;
  reg  Reg_rsvd;
  reg  Reg_next;
  reg  out_last_value;


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : MATLAB_Function_process
      if (reset == 1'b1) begin
        Reg_rsvd <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          Reg_rsvd <= Reg_next;
        end
      end
    end

  always @(Reg_rsvd, syncPulse, valid) begin
    Reg_next = Reg_rsvd;
    if (Reg_rsvd && valid) begin
      Reg_next = 1'b0;
    end
    if (syncPulse) begin
      Reg_next = 1'b1;
    end
    out_1 = Reg_rsvd;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        out_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          out_last_value <= out;
        end
      end
    end

  assign out = (stateControl_2 == 1'b0 ? out_last_value :
              out_1);

endmodule  // MATLAB_Function_block

