// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/MATLAB_Function1.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function1
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/Bit Packetizer/Data Bits FIFO/MATLAB Function1
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function1
          (clk,
           reset,
           enb_1_2_0,
           wr,
           rd,
           full);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   wr;
  input   rd;
  output  full;


  reg  full_1;
  reg [15:0] count;  // ufix16
  reg [15:0] count_next;  // ufix16
  reg [15:0] count_temp;  // ufix16


  always @(posedge clk or posedge reset)
    begin : MATLAB_Function1_process
      if (reset == 1'b1) begin
        count <= 16'b0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          count <= count_next;
        end
      end
    end

  always @(count, rd, wr) begin
    count_temp = count;
    if (wr) begin
      count_temp = count + 16'b0000000000000001;
    end
    if (rd) begin
      count_temp = count_temp - 16'b0000000000000001;
    end
    full_1 = count_temp > 16'b1100000001111111;
    count_next = count_temp;
  end

  assign full = full_1;

endmodule  // MATLAB_Function1

