// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/MATLAB_Function_block2.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function_block2
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate 
// Handle/FIFO/Validate Input Push Pop/MATLAB Functio
// Hierarchy Level: 8
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function_block2
          (clk,
           reset,
           enb_1_2_0,
           rst,
           enb_1,
           dir,
           count);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   rst;
  input   enb_1;
  input   dir;
  output  [5:0] count;  // ufix6


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg [5:0] count_1;  // ufix6
  reg [5:0] countReg;  // ufix6
  reg [5:0] countReg_next;  // ufix6
  reg [5:0] count_last_value;  // ufix6
  reg [5:0] countReg_temp;  // ufix6
  reg signed [7:0] sub_temp;  // sfix8
  reg [6:0] cast;  // ufix7
  reg [6:0] add_temp;  // ufix7
  reg [6:0] t_0;  // ufix7
  reg [6:0] t_1;  // ufix7
  reg signed [7:0] t_2;  // sfix8


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : MATLAB_Function_process
      if (reset == 1'b1) begin
        countReg <= 6'b000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          countReg <= countReg_next;
        end
      end
    end

  always @(countReg, dir, enb_1, rst) begin
    sub_temp = 8'sb00000000;
    add_temp = 7'b0000000;
    t_0 = 7'b0000000;
    t_1 = 7'b0000000;
    t_2 = 8'sb00000000;
    cast = 7'b0000000;
    countReg_temp = countReg;
    if (rst) begin
      countReg_temp = 6'b000000;
    end
    else if (enb_1) begin
      if (dir) begin
        if (countReg == 6'b100000) begin
          countReg_temp = 6'b000000;
        end
        else begin
          t_0 = {1'b0, countReg};
          add_temp = t_0 + 7'b0000001;
          if (add_temp[6] != 1'b0) begin
            countReg_temp = 6'b111111;
          end
          else begin
            countReg_temp = add_temp[5:0];
          end
        end
      end
      else if (countReg == 6'b000000) begin
        countReg_temp = 6'b100000;
      end
      else begin
        t_1 = {1'b0, countReg};
        t_2 = {1'b0, t_1};
        sub_temp = t_2 - 8'sb00000001;
        if (sub_temp[7] == 1'b1) begin
          cast = 7'b0000000;
        end
        else begin
          cast = sub_temp[6:0];
        end
        if (cast[6] != 1'b0) begin
          countReg_temp = 6'b111111;
        end
        else begin
          countReg_temp = cast[5:0];
        end
      end
    end
    count_1 = countReg_temp;
    countReg_next = countReg_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        count_last_value <= 6'b000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          count_last_value <= count;
        end
      end
    end

  assign count = (stateControl_2 == 1'b0 ? count_last_value :
              count_1);

endmodule  // MATLAB_Function_block2

