// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/PdTelemetry.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PdTelemetry
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/PdTelemetry
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PdTelemetry
          (clk,
           reset,
           enb_1_2_0,
           validIn,
           dI,
           dQ,
           thrEx,
           tRef,
           tOff,
           done,
           newPk,
           succ,
           sync,
           armed,
           taRef,
           accOff,
           fifoEnt,
           vPop,
           tRefLong,
           runMax,
           heldTs,
           telI,
           telQ);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   validIn;
  input   signed [15:0] dI;  // int16
  input   signed [15:0] dQ;  // int16
  input   thrEx;
  input   [15:0] tRef;  // uint16
  input   [15:0] tOff;  // uint16
  input   done;
  input   newPk;
  input   succ;
  input   sync;
  input   armed;
  input   [15:0] taRef;  // uint16
  input   [15:0] accOff;  // uint16
  input   [15:0] fifoEnt;  // uint16
  input   vPop;
  input   [31:0] tRefLong;  // uint32
  input   [31:0] runMax;  // uint32
  input   [31:0] heldTs;  // uint32
  output  signed [15:0] telI;  // int16
  output  signed [15:0] telQ;  // int16


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg signed [15:0] telI_1;  // int16
  reg signed [15:0] telQ_1;  // int16
  reg [7:0] slot;  // uint8
  reg [31:0] symCtr;  // uint32
  reg [7:0] beatCnt;  // uint8
  reg  aDone;
  reg  aNewPk;
  reg  aThrEx;
  reg  aSync;
  reg  aVPop;
  reg [31:0] s0;  // uint32
  reg [31:0] s1;  // uint32
  reg [31:0] s2;  // uint32
  reg [31:0] s3;  // uint32
  reg [31:0] s4;  // uint32
  reg [31:0] s5;  // uint32
  reg [31:0] s6;  // uint32
  reg [7:0] slot_next;  // uint8
  reg [31:0] symCtr_next;  // uint32
  reg [7:0] beatCnt_next;  // uint8
  reg  aDone_next;
  reg  aNewPk_next;
  reg  aThrEx_next;
  reg  aSync_next;
  reg  aVPop_next;
  reg [31:0] s0_next;  // uint32
  reg [31:0] s1_next;  // uint32
  reg [31:0] s2_next;  // uint32
  reg [31:0] s3_next;  // uint32
  reg [31:0] s4_next;  // uint32
  reg [31:0] s5_next;  // uint32
  reg [31:0] s6_next;  // uint32
  reg signed [15:0] telI_last_value;  // int16
  reg signed [15:0] telQ_last_value;  // int16
  reg [31:0] flags;  // uint32
  reg [31:0] w;  // uint32
  reg  aDone_1;
  reg  aNewPk_1;
  reg  aThrEx_1;
  reg  aSync_1;
  reg  aVPop_1;
  reg signed [15:0] temp;  // sfix16
  reg signed [15:0] temp_0;  // sfix16
  reg [15:0] temp_1;  // ufix16
  reg [15:0] temp_2;  // ufix16
  reg [31:0] a1;  // uint32
  reg [31:0] a1_0;  // uint32
  reg [31:0] a1_1;  // uint32
  reg [31:0] a1_2;  // uint32
  reg [31:0] a1_3;  // uint32
  reg [31:0] a1_4;  // uint32
  reg [31:0] a1_5;  // uint32
  reg [31:0] a1_6;  // uint32
  reg [31:0] a1_7;  // uint32
  reg [31:0] a1_8;  // uint32
  reg [31:0] a1_9;  // uint32
  reg [31:0] a1_10;  // uint32
  reg [15:0] yfi_trivial_scaling;  // ufix16
  reg [15:0] yfi_trivial_scaling_0;  // ufix16
  reg [7:0] slot_temp;  // uint8
  reg [31:0] symCtr_temp;  // uint32
  reg [7:0] beatCnt_temp;  // uint8
  reg [31:0] s0_temp;  // uint32
  reg [31:0] s1_temp;  // uint32
  reg [31:0] s2_temp;  // uint32
  reg [31:0] s3_temp;  // uint32
  reg [31:0] s4_temp;  // uint32
  reg [31:0] s5_temp;  // uint32
  reg [31:0] s6_temp;  // uint32
  reg [8:0] add_temp;  // ufix9
  reg [32:0] add_temp_0;  // ufix33
  reg [8:0] add_temp_1;  // ufix9
  reg [31:0] w_0;  // uint32
  reg [15:0] cast;  // uint16
  reg [31:0] w_1;  // uint32
  reg [15:0] cast_0;  // uint16
  reg [15:0] cast_1;  // uint16
  reg [15:0] cast_2;  // uint16
  reg [15:0] cast_3;  // uint16
  reg [15:0] cast_4;  // uint16
  reg [8:0] t_0;  // ufix9
  reg [32:0] t_1;  // ufix33
  reg [31:0] t_2;  // uint32
  reg signed [31:0] t_3;  // int32
  reg signed [31:0] t_4;  // int32
  reg signed [31:0] t_5;  // int32
  reg signed [31:0] t_6;  // int32
  reg [31:0] t_7;  // uint32
  reg signed [31:0] t_8;  // int32
  reg signed [31:0] t_9;  // int32
  reg signed [31:0] t_10;  // int32
  reg signed [31:0] t_11;  // int32
  reg signed [31:0] t_12;  // int32
  reg signed [31:0] t_13;  // int32
  reg [31:0] t_14;  // uint32
  reg signed [31:0] t_15;  // int32
  reg signed [31:0] t_16;  // int32
  reg [8:0] t_17;  // ufix9


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : PdTelemetry_process
      if (reset == 1'b1) begin
        slot <= 8'd7;
        symCtr <= 32'd0;
        beatCnt <= 8'd0;
        aDone <= 1'b0;
        aNewPk <= 1'b0;
        aThrEx <= 1'b0;
        aSync <= 1'b0;
        aVPop <= 1'b0;
        s0 <= 32'd0;
        s1 <= 32'd0;
        s2 <= 32'd0;
        s3 <= 32'd0;
        s4 <= 32'd0;
        s5 <= 32'd0;
        s6 <= 32'd0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          slot <= slot_next;
          symCtr <= symCtr_next;
          beatCnt <= beatCnt_next;
          aDone <= aDone_next;
          aNewPk <= aNewPk_next;
          aThrEx <= aThrEx_next;
          aSync <= aSync_next;
          aVPop <= aVPop_next;
          s0 <= s0_next;
          s1 <= s1_next;
          s2 <= s2_next;
          s3 <= s3_next;
          s4 <= s4_next;
          s5 <= s5_next;
          s6 <= s6_next;
        end
      end
    end

  always @(aDone, aNewPk, aSync, aThrEx, aVPop, accOff, armed, beatCnt, dI, dQ, done,
       fifoEnt, heldTs, newPk, runMax, s0, s1, s2, s3, s4, s5, s6, slot, succ,
       symCtr, sync, tOff, tRef, tRefLong, taRef, thrEx, vPop, validIn) begin
    temp_0 = 16'sb0000000000000000;
    temp = 16'sb0000000000000000;
    flags = 32'd0;
    add_temp = 9'b000000000;
    add_temp_0 = 33'h000000000;
    add_temp_1 = 9'b000000000;
    t_4 = 32'sd0;
    t_6 = 32'sd0;
    t_9 = 32'sd0;
    t_11 = 32'sd0;
    t_13 = 32'sd0;
    t_16 = 32'sd0;
    t_0 = 9'b000000000;
    t_1 = 33'h000000000;
    a1 = 32'd0;
    a1_0 = 32'd0;
    a1_1 = 32'd0;
    a1_2 = 32'd0;
    a1_3 = 32'd0;
    t_2 = 32'd0;
    t_3 = 32'sd0;
    a1_4 = 32'd0;
    t_5 = 32'sd0;
    a1_5 = 32'd0;
    a1_6 = 32'd0;
    t_7 = 32'd0;
    t_8 = 32'sd0;
    a1_7 = 32'd0;
    t_10 = 32'sd0;
    a1_8 = 32'd0;
    t_12 = 32'sd0;
    a1_9 = 32'd0;
    t_14 = 32'd0;
    t_15 = 32'sd0;
    a1_10 = 32'd0;
    t_17 = 9'b000000000;
    cast = 16'd0;
    cast_0 = 16'd0;
    yfi_trivial_scaling = 16'b0000000000000000;
    yfi_trivial_scaling_0 = 16'b0000000000000000;
    cast_1 = 16'd0;
    cast_2 = 16'd0;
    cast_3 = 16'd0;
    cast_4 = 16'd0;
    slot_temp = slot;
    symCtr_temp = symCtr;
    beatCnt_temp = beatCnt;
    s0_temp = s0;
    s1_temp = s1;
    s2_temp = s2;
    s3_temp = s3;
    s4_temp = s4;
    s5_temp = s5;
    s6_temp = s6;
    aDone_1 = aDone || done;
    aNewPk_1 = aNewPk || newPk;
    aThrEx_1 = aThrEx || thrEx;
    aSync_1 = aSync || sync;
    aVPop_1 = aVPop || vPop;
    if (beatCnt < 8'd7) begin
      t_0 = {1'b0, beatCnt};
      add_temp = t_0 + 9'b000000001;
      if (add_temp[8] != 1'b0) begin
        beatCnt_temp = 8'b11111111;
      end
      else begin
        beatCnt_temp = add_temp[7:0];
      end
    end
    if (validIn) begin
      t_1 = {1'b0, symCtr};
      add_temp_0 = t_1 + 33'h000000001;
      if (add_temp_0[32] != 1'b0) begin
        symCtr_temp = 32'b11111111111111111111111111111111;
      end
      else begin
        symCtr_temp = add_temp_0[31:0];
      end
      a1 = {31'b0, aNewPk_1};
      a1_0 = {31'b0, succ};
      a1_1 = {31'b0, aThrEx_1};
      a1_2 = {31'b0, aSync_1};
      a1_3 = {31'b0, armed};
      t_2 = {31'b0, aDone_1};
      flags = ((((t_2 + (a1 <<< 32'sd1)) + (a1_0 <<< 32'sd2)) + (a1_1 <<< 32'sd3)) + (a1_2 <<< 32'sd4)) + (a1_3 <<< 32'sd5);
      t_3 = {16'b0, tRef};
      t_4 = t_3 & 32'sd2047;
      cast = t_4[15:0];
      a1_4 = {16'b0, cast};
      t_5 = {16'b0, tOff};
      t_6 = t_5 & 32'sd2047;
      cast_0 = t_6[15:0];
      a1_5 = {16'b0, cast_0};
      s0_temp = (((a1_4 <<< 32'sd17) | 32'd3758096384) | (a1_5 <<< 32'sd6)) | flags;
      temp = dI;
      yfi_trivial_scaling = temp;
      a1_6 = {16'b0, yfi_trivial_scaling};
      temp_0 = dQ;
      yfi_trivial_scaling_0 = temp_0;
      t_7 = {16'b0, yfi_trivial_scaling_0};
      s1_temp = (a1_6 <<< 32'sd16) | t_7;
      t_8 = {16'b0, taRef};
      t_9 = t_8 & 32'sd2047;
      cast_1 = t_9[15:0];
      a1_7 = {16'b0, cast_1};
      t_10 = {16'b0, accOff};
      t_11 = t_10 & 32'sd2047;
      cast_2 = t_11[15:0];
      a1_8 = {16'b0, cast_2};
      t_12 = {16'b0, fifoEnt};
      t_13 = t_12 & 32'sd511;
      cast_3 = t_13[15:0];
      a1_9 = {16'b0, cast_3};
      t_14 = {31'b0, aVPop_1};
      s2_temp = (((a1_7 <<< 32'sd21) | (a1_8 <<< 32'sd10)) | (a1_9 <<< 32'sd1)) | t_14;
      s3_temp = tRefLong;
      s4_temp = runMax;
      s5_temp = heldTs;
      t_15 = {24'b0, beatCnt_temp};
      t_16 = t_15 & 32'sd7;
      cast_4 = t_16[15:0];
      a1_10 = {16'b0, cast_4};
      s6_temp = ((a1_10 <<< 32'sd21) | 32'd2768240640) | (symCtr_temp & 32'd2097151);
      aDone_1 = 1'b0;
      aNewPk_1 = 1'b0;
      aThrEx_1 = 1'b0;
      aSync_1 = 1'b0;
      aVPop_1 = 1'b0;
      beatCnt_temp = 8'd0;
      slot_temp = 8'd0;
    end
    case ( slot_temp)
      8'd0 :
        begin
          w = s0_temp;
        end
      8'd1 :
        begin
          w = s1_temp;
        end
      8'd2 :
        begin
          w = s2_temp;
        end
      8'd3 :
        begin
          w = s3_temp;
        end
      8'd4 :
        begin
          w = s4_temp;
        end
      8'd5 :
        begin
          w = s5_temp;
        end
      8'd6 :
        begin
          w = s6_temp;
        end
      default :
        begin
          w = 32'd0;
        end
    endcase
    if (slot_temp < 8'd7) begin
      t_17 = {1'b0, slot_temp};
      add_temp_1 = t_17 + 9'b000000001;
      if (add_temp_1[8] != 1'b0) begin
        slot_temp = 8'b11111111;
      end
      else begin
        slot_temp = add_temp_1[7:0];
      end
    end
    w_0 = w >> 32'sd16;
    temp_1 = w_0[15:0];
    telI_1 = temp_1;
    w_1 = w & 32'd65535;
    temp_2 = w_1[15:0];
    telQ_1 = temp_2;
    slot_next = slot_temp;
    symCtr_next = symCtr_temp;
    beatCnt_next = beatCnt_temp;
    aDone_next = aDone_1;
    aNewPk_next = aNewPk_1;
    aThrEx_next = aThrEx_1;
    aSync_next = aSync_1;
    aVPop_next = aVPop_1;
    s0_next = s0_temp;
    s1_next = s1_temp;
    s2_next = s2_temp;
    s3_next = s3_temp;
    s4_next = s4_temp;
    s5_next = s5_temp;
    s6_next = s6_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        telI_last_value <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          telI_last_value <= telI;
        end
      end
    end

  assign telI = (stateControl_2 == 1'b0 ? telI_last_value :
              telI_1);

  always @(posedge clk or posedge reset)
    begin : out1_bypass_process
      if (reset == 1'b1) begin
        telQ_last_value <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          telQ_last_value <= telQ;
        end
      end
    end

  assign telQ = (stateControl_2 == 1'b0 ? telQ_last_value :
              telQ_1);

endmodule  // PdTelemetry

