// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Preamble_Bits_Store.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Preamble_Bits_Store
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/Bit Packetizer/Preamble Bits Generator/Preamble 
// Bits Stor
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Preamble_Bits_Store
          (actualPreamble,
           sampleCount,
           preamble);


  input   actualPreamble;
  input   [14:0] sampleCount;  // ufix15
  output  preamble;


  wire Constant_out1;
  wire [4:0] Extract_Bits_out1;  // ufix5
  wire [31:0] Preamble_table_data;  // ufix1 [32]
  wire Preamble_out1;
  wire Switch_out1;

  // The Preamble is padded with zeros in the LUT such that
  // the length is the 2^nextpow2(length(Preamble)) for 
  // efficient resource mapping to RAM


  assign Constant_out1 = 1'b1;

  assign Extract_Bits_out1 = sampleCount[4:0];

  assign Preamble_table_data[0] = 1'b1;
  assign Preamble_table_data[1] = 1'b1;
  assign Preamble_table_data[2] = 1'b1;
  assign Preamble_table_data[3] = 1'b1;
  assign Preamble_table_data[4] = 1'b1;
  assign Preamble_table_data[5] = 1'b1;
  assign Preamble_table_data[6] = 1'b1;
  assign Preamble_table_data[7] = 1'b1;
  assign Preamble_table_data[8] = 1'b1;
  assign Preamble_table_data[9] = 1'b1;
  assign Preamble_table_data[10] = 1'b0;
  assign Preamble_table_data[11] = 1'b0;
  assign Preamble_table_data[12] = 1'b0;
  assign Preamble_table_data[13] = 1'b0;
  assign Preamble_table_data[14] = 1'b1;
  assign Preamble_table_data[15] = 1'b1;
  assign Preamble_table_data[16] = 1'b1;
  assign Preamble_table_data[17] = 1'b1;
  assign Preamble_table_data[18] = 1'b0;
  assign Preamble_table_data[19] = 1'b0;
  assign Preamble_table_data[20] = 1'b1;
  assign Preamble_table_data[21] = 1'b1;
  assign Preamble_table_data[22] = 1'b0;
  assign Preamble_table_data[23] = 1'b0;
  assign Preamble_table_data[24] = 1'b1;
  assign Preamble_table_data[25] = 1'b1;
  assign Preamble_table_data[26] = 1'b0;
  assign Preamble_table_data[27] = 1'b0;
  assign Preamble_table_data[28] = 1'b0;
  assign Preamble_table_data[29] = 1'b0;
  assign Preamble_table_data[30] = 1'b0;
  assign Preamble_table_data[31] = 1'b0;
  assign Preamble_out1 = Preamble_table_data[Extract_Bits_out1];

  assign Switch_out1 = (actualPreamble == 1'b0 ? Constant_out1 :
              Preamble_out1);

  assign preamble = Switch_out1;

endmodule  // Preamble_Bits_Store

