// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Preamble_Bits_Generator.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Preamble_Bits_Generator
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/Bit Packetizer/Preamble Bits Generator
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Preamble_Bits_Generator
          (clk,
           reset,
           enb_1_2_0,
           activeFrame,
           sampleCount,
           sampleCountValid,
           preambleBits);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   activeFrame;
  input   [14:0] sampleCount;  // ufix15
  input   sampleCountValid;
  output  preambleBits;


  wire Compare_To_Constant2_y;
  wire Logical_Operator3_out1;
  reg  Unit_Delay_Enabled_Synchronous_out1;
  wire Preamble_Bits_Store_preamble;


  Compare_To_Constant2_block u_Compare_To_Constant2 (.u(sampleCount),  // ufix15
                                                                      .y(Compare_To_Constant2_y)
                                                                      );

  assign Logical_Operator3_out1 = Compare_To_Constant2_y & sampleCountValid;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0 && Logical_Operator3_out1) begin
          Unit_Delay_Enabled_Synchronous_out1 <= activeFrame;
        end
      end
    end

  Preamble_Bits_Store u_Preamble_Bits_Store (.actualPreamble(Unit_Delay_Enabled_Synchronous_out1),
                                                              .sampleCount(sampleCount),  // ufix15
                                                              .preamble(Preamble_Bits_Store_preamble)
                                                              );

  assign preambleBits = Preamble_Bits_Store_preamble;

endmodule  // Preamble_Bits_Generator

