// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/QPSK_Tx.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: QPSK_Tx
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx
// Hierarchy Level: 2
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module QPSK_Tx
          (clk,
           reset,
           enb_1_2_0,
           dataIn,
           validIn,
           dataReady,
           dataOut_re,
           dataOut_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   dataIn;
  input   validIn;
  output  dataReady;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14


  wire Bit_Packetizer_bitsOut;
  wire Bit_Packetizer_dataStart;
  wire Bit_Packetizer_dataEnd;
  wire Bit_Packetizer_bitsValid;
  wire Bit_Packetizer_dataReady;
  wire HDL_Data_Scrambler_dataOut;
  wire HDL_Data_Scrambler_validOut;
  wire signed [15:0] QPSKConstellationPoints_re;  // sfix16_En15
  wire signed [15:0] QPSKConstellationPoints_im;  // sfix16_En15
  wire QPSKConstellationValid;
  wire signed [15:0] RRC_Transmit_Filter_dataOut_re;  // sfix16_En14
  wire signed [15:0] RRC_Transmit_Filter_dataOut_im;  // sfix16_En14


  Bit_Packetizer u_Bit_Packetizer (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .dataIn(dataIn),
                                                    .validIn(validIn),
                                                    .bitsOut(Bit_Packetizer_bitsOut),
                                                    .dataStart(Bit_Packetizer_dataStart),
                                                    .dataEnd(Bit_Packetizer_dataEnd),
                                                    .bitsValid(Bit_Packetizer_bitsValid),
                                                    .dataReady(Bit_Packetizer_dataReady)
                                                    );

  assign dataReady = Bit_Packetizer_dataReady;

  HDL_Data_Scrambler u_HDL_Data_Scrambler (.clk(clk),
                                                            .reset(reset),
                                                            .enb_1_2_0(enb_1_2_0),
                                                            .dataIn(Bit_Packetizer_bitsOut),
                                                            .startIn(Bit_Packetizer_dataStart),
                                                            .endIn(Bit_Packetizer_dataEnd),
                                                            .validIn(Bit_Packetizer_bitsValid),
                                                            .dataOut(HDL_Data_Scrambler_dataOut),
                                                            .validOut(HDL_Data_Scrambler_validOut)
                                                            );

  QPSK_Modulator u_QPSK_Modulator (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .dataIn(HDL_Data_Scrambler_dataOut),
                                                    .validIn(HDL_Data_Scrambler_validOut),
                                                    .dataOut_re(QPSKConstellationPoints_re),  // sfix16_En15
                                                    .dataOut_im(QPSKConstellationPoints_im),  // sfix16_En15
                                                    .validOut(QPSKConstellationValid)
                                                    );

  RRC_Transmit_Filter u_RRC_Transmit_Filter (.clk(clk),
                                                              .reset(reset),
                                                              .enb_1_2_0(enb_1_2_0),
                                                              .dataIn_re(QPSKConstellationPoints_re),  // sfix16_En15
                                                              .dataIn_im(QPSKConstellationPoints_im),  // sfix16_En15
                                                              .validIn(QPSKConstellationValid),
                                                              .dataOut_re(RRC_Transmit_Filter_dataOut_re),  // sfix16_En14
                                                              .dataOut_im(RRC_Transmit_Filter_dataOut_im)  // sfix16_En14
                                                              );

  assign dataOut_re = RRC_Transmit_Filter_dataOut_re;

  assign dataOut_im = RRC_Transmit_Filter_dataOut_im;

endmodule  // QPSK_Tx

