// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/QPSK_Modulator_Baseband.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: QPSK_Modulator_Baseband
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/QPSK Modulator/QPSK Modulator Baseband
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module QPSK_Modulator_Baseband
          (in0_0,
           in0_1,
           out0_re,
           out0_im);


  input   in0_0;  // boolean
  input   in0_1;  // boolean
  output  signed [15:0] out0_re;  // sfix16_En15
  output  signed [15:0] out0_im;  // sfix16_En15


  wire [1:0] in0;  // boolean [2]
  wire [1:0] constellationLUTaddress;  // ufix2
  wire signed [15:0] constellationLUT_t1_re [0:3];  // sfix16_En15 [4]
  wire signed [15:0] constellationLUT_t1_im [0:3];  // sfix16_En15 [4]


  assign in0[0] = in0_0;
  assign in0[1] = in0_1;

  assign constellationLUTaddress = {in0[0], in0[1]};

  assign constellationLUT_t1_re[0] = 16'sb0101101010000010;
  assign constellationLUT_t1_re[1] = 16'sb1010010101111110;
  assign constellationLUT_t1_re[2] = 16'sb0101101010000010;
  assign constellationLUT_t1_re[3] = 16'sb1010010101111110;
  assign constellationLUT_t1_im[0] = 16'sb0101101010000010;
  assign constellationLUT_t1_im[1] = 16'sb0101101010000010;
  assign constellationLUT_t1_im[2] = 16'sb1010010101111110;
  assign constellationLUT_t1_im[3] = 16'sb1010010101111110;
  assign out0_re = constellationLUT_t1_re[constellationLUTaddress];
  assign out0_im = constellationLUT_t1_im[constellationLUTaddress];

endmodule  // QPSK_Modulator_Baseband

