// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/REP_TxI.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: REP_TxI
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/REP_TxI
// Hierarchy Level: 1
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module REP_TxI
          (clk,
           reset,
           enb,
           REP_TxI_In,
           REP_TxI_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] REP_TxI_In;  // int16
  output  signed [15:0] REP_TxI_out;  // int16


  wire signed [15:0] Upsample_out1;  // int16
  reg  HDL_Counter_out1;  // ufix1
  wire signed [15:0] coeffphaseSig1;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2;  // sfix16_En15
  wire signed [15:0] prodMux10_out1;  // sfix16_En15
  reg signed [15:0] delayMatch24_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch24_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_1;  // sfix16_En15
  wire signed [31:0] Product10_out1;  // sfix32_En15
  reg signed [31:0] Product10_out1_1;  // sfix32_En15
  wire stateControl_1;
  reg  [1:0] delayMatch1_reg;  // ufix1 [2]
  wire stateControl_2;
  wire Compare_To_Constant_out1;  // ufix1
  wire Constant1_out1;  // ufix1
  wire Logical_Operator_out1;  // ufix1
  reg  [1:0] reduced_reg;  // ufix1 [2]
  wire Logical_Operator_out1_1;  // ufix1
  wire switch_compare_1;
  reg signed [15:0] Delay0_out1;  // int16
  wire signed [15:0] Switch_out1;  // int16
  wire signed [15:0] Switch_out1_1;  // int16
  wire signed [15:0] coeffphaseSig1_1;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_1;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_2;  // sfix16_En15
  reg signed [15:0] delayMatch25_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch25_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_3;  // sfix16_En15
  wire signed [31:0] Product10_out1_2;  // sfix32_En15
  reg signed [31:0] Product10_out1_3;  // sfix32_En15
  wire signed [35:0] addtree_add_cast;  // sfix36_En15
  wire signed [35:0] addtree_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_1;  // sfix36_En15
  reg signed [35:0] addtree_2;  // sfix36_En15
  wire stateControl_3;
  reg  [1:0] delayMatch3_reg;  // ufix1 [2]
  wire stateControl_4;
  wire switch_compare_1_1;
  reg signed [15:0] Delay0_out1_1;  // int16
  wire signed [15:0] Switch_out1_2;  // int16
  wire signed [15:0] Switch_out1_3;  // int16
  wire signed [15:0] coeffphaseSig1_2;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_2;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_4;  // sfix16_En15
  reg signed [15:0] delayMatch26_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch26_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_5;  // sfix16_En15
  wire signed [31:0] Product10_out1_4;  // sfix32_En15
  reg signed [31:0] Product10_out1_5;  // sfix32_En15
  wire stateControl_5;
  reg  [1:0] delayMatch5_reg;  // ufix1 [2]
  wire stateControl_6;
  wire switch_compare_1_2;
  reg signed [15:0] Delay0_out1_2;  // int16
  wire signed [15:0] Switch_out1_4;  // int16
  wire signed [15:0] Switch_out1_5;  // int16
  wire signed [15:0] coeffphaseSig1_3;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_3;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_6;  // sfix16_En15
  reg signed [15:0] delayMatch27_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch27_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_7;  // sfix16_En15
  wire signed [31:0] Product10_out1_6;  // sfix32_En15
  reg signed [31:0] Product10_out1_7;  // sfix32_En15
  wire signed [35:0] addtree1_add_cast;  // sfix36_En15
  wire signed [35:0] addtree1_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_3;  // sfix36_En15
  reg signed [35:0] addtree_4;  // sfix36_En15
  wire signed [36:0] addtree6_add_cast;  // sfix37_En15
  wire signed [36:0] addtree6_add_cast_1;  // sfix37_En15
  wire signed [36:0] addtree6_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_5;  // sfix36_En15
  reg signed [35:0] addtree_6;  // sfix36_En15
  wire stateControl_7;
  reg  [1:0] delayMatch7_reg;  // ufix1 [2]
  wire stateControl_8;
  wire switch_compare_1_3;
  reg signed [15:0] Delay0_out1_3;  // int16
  wire signed [15:0] Switch_out1_6;  // int16
  wire signed [15:0] Switch_out1_7;  // int16
  wire signed [15:0] coeffphaseSig1_4;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_4;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_8;  // sfix16_En15
  reg signed [15:0] delayMatch28_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch28_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_9;  // sfix16_En15
  wire signed [31:0] Product10_out1_8;  // sfix32_En15
  reg signed [31:0] Product10_out1_9;  // sfix32_En15
  wire stateControl_9;
  reg  [1:0] delayMatch9_reg;  // ufix1 [2]
  wire stateControl_10;
  wire switch_compare_1_4;
  reg signed [15:0] Delay0_out1_4;  // int16
  wire signed [15:0] Switch_out1_8;  // int16
  wire signed [15:0] Switch_out1_9;  // int16
  wire signed [15:0] coeffphaseSig1_5;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_5;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_10;  // sfix16_En15
  reg signed [15:0] delayMatch29_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch29_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_11;  // sfix16_En15
  wire signed [31:0] Product10_out1_10;  // sfix32_En15
  reg signed [31:0] Product10_out1_11;  // sfix32_En15
  wire signed [35:0] addtree2_add_cast;  // sfix36_En15
  wire signed [35:0] addtree2_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_7;  // sfix36_En15
  reg signed [35:0] addtree_8;  // sfix36_En15
  wire stateControl_11;
  reg  [1:0] delayMatch11_reg;  // ufix1 [2]
  wire stateControl_12;
  wire switch_compare_1_5;
  reg signed [15:0] Delay0_out1_5;  // int16
  wire signed [15:0] Switch_out1_10;  // int16
  wire signed [15:0] Switch_out1_11;  // int16
  wire signed [15:0] coeffphaseSig1_6;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_6;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_12;  // sfix16_En15
  reg signed [15:0] delayMatch30_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch30_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_13;  // sfix16_En15
  wire signed [31:0] Product10_out1_12;  // sfix32_En15
  reg signed [31:0] Product10_out1_13;  // sfix32_En15
  wire stateControl_13;
  reg  [1:0] delayMatch13_reg;  // ufix1 [2]
  wire stateControl_14;
  wire switch_compare_1_6;
  reg signed [15:0] Delay0_out1_6;  // int16
  wire signed [15:0] Switch_out1_12;  // int16
  wire signed [15:0] Switch_out1_13;  // int16
  wire signed [15:0] coeffphaseSig1_7;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_7;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_14;  // sfix16_En15
  reg signed [15:0] delayMatch31_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch31_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_15;  // sfix16_En15
  wire signed [31:0] Product10_out1_14;  // sfix32_En15
  reg signed [31:0] Product10_out1_15;  // sfix32_En15
  wire signed [35:0] addtree3_add_cast;  // sfix36_En15
  wire signed [35:0] addtree3_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_9;  // sfix36_En15
  reg signed [35:0] addtree_10;  // sfix36_En15
  wire signed [36:0] addtree7_add_cast;  // sfix37_En15
  wire signed [36:0] addtree7_add_cast_1;  // sfix37_En15
  wire signed [36:0] addtree7_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_11;  // sfix36_En15
  reg signed [35:0] addtree_12;  // sfix36_En15
  wire signed [36:0] addtree9_add_cast;  // sfix37_En15
  wire signed [36:0] addtree9_add_cast_1;  // sfix37_En15
  wire signed [36:0] addtree9_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_13;  // sfix36_En15
  reg signed [35:0] addtree_14;  // sfix36_En15
  wire stateControl_15;
  reg  [1:0] delayMatch15_reg;  // ufix1 [2]
  wire stateControl_16;
  wire switch_compare_1_7;
  reg signed [15:0] Delay0_out1_7;  // int16
  wire signed [15:0] Switch_out1_14;  // int16
  wire signed [15:0] Switch_out1_15;  // int16
  wire signed [15:0] coeffphaseSig1_8;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_8;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_16;  // sfix16_En15
  reg signed [15:0] delayMatch32_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch32_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_17;  // sfix16_En15
  wire signed [31:0] Product10_out1_16;  // sfix32_En15
  reg signed [31:0] Product10_out1_17;  // sfix32_En15
  wire stateControl_17;
  reg  [1:0] delayMatch17_reg;  // ufix1 [2]
  wire stateControl_18;
  wire switch_compare_1_8;
  reg signed [15:0] Delay0_out1_8;  // int16
  wire signed [15:0] Switch_out1_16;  // int16
  wire signed [15:0] Switch_out1_17;  // int16
  wire signed [15:0] coeffphaseSig1_9;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_9;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_18;  // sfix16_En15
  reg signed [15:0] delayMatch33_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch33_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_19;  // sfix16_En15
  wire signed [31:0] Product10_out1_18;  // sfix32_En15
  reg signed [31:0] Product10_out1_19;  // sfix32_En15
  wire signed [35:0] addtree4_add_cast;  // sfix36_En15
  wire signed [35:0] addtree4_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_15;  // sfix36_En15
  reg signed [35:0] addtree_16;  // sfix36_En15
  wire stateControl_19;
  reg  [1:0] delayMatch19_reg;  // ufix1 [2]
  wire stateControl_20;
  wire switch_compare_1_9;
  reg signed [15:0] Delay0_out1_9;  // int16
  wire signed [15:0] Switch_out1_18;  // int16
  wire signed [15:0] Switch_out1_19;  // int16
  wire signed [15:0] coeffphaseSig1_10;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_10;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_20;  // sfix16_En15
  reg signed [15:0] delayMatch34_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch34_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_21;  // sfix16_En15
  wire signed [31:0] Product10_out1_20;  // sfix32_En15
  reg signed [31:0] Product10_out1_21;  // sfix32_En15
  wire stateControl_21;
  reg  [1:0] delayMatch21_reg;  // ufix1 [2]
  wire stateControl_22;
  wire switch_compare_1_10;
  reg signed [15:0] Delay0_out1_10;  // int16
  wire signed [15:0] Switch_out1_20;  // int16
  wire signed [15:0] Switch_out1_21;  // int16
  wire signed [15:0] coeffphaseSig1_11;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_11;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_22;  // sfix16_En15
  reg signed [15:0] delayMatch35_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch35_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_23;  // sfix16_En15
  wire signed [31:0] Product10_out1_22;  // sfix32_En15
  reg signed [31:0] Product10_out1_23;  // sfix32_En15
  wire signed [35:0] addtree5_add_cast;  // sfix36_En15
  wire signed [35:0] addtree5_add_cast_1;  // sfix36_En15
  wire signed [35:0] addtree_17;  // sfix36_En15
  reg signed [35:0] addtree_18;  // sfix36_En15
  wire signed [36:0] addtree8_add_cast;  // sfix37_En15
  wire signed [36:0] addtree8_add_cast_1;  // sfix37_En15
  wire signed [36:0] addtree8_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_19;  // sfix36_En15
  reg signed [35:0] addtree_20;  // sfix36_En15
  wire stateControl_23;
  reg  [1:0] delayMatch23_reg;  // ufix1 [2]
  wire stateControl_24;
  wire switch_compare_1_11;
  reg signed [15:0] Delay0_out1_11;  // int16
  wire signed [15:0] Switch_out1_22;  // int16
  wire signed [15:0] Switch_out1_23;  // int16
  wire signed [15:0] coeffphaseSig1_12;  // sfix16_En15
  wire signed [15:0] coeffphaseSig2_12;  // sfix16_En15
  wire signed [15:0] prodMux10_out1_24;  // sfix16_En15
  reg signed [15:0] delayMatch36_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch36_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] prodMux10_out1_25;  // sfix16_En15
  wire signed [31:0] Product10_out1_24;  // sfix32_En15
  reg signed [31:0] delayMatch37_reg [0:2];  // sfix32 [3]
  reg signed [31:0] delayMatch37_reg_next [0:2];  // sfix32_En15 [3]
  reg signed [31:0] Product10_out1_25;  // sfix32_En15
  wire signed [36:0] addtree10_add_cast;  // sfix37_En15
  wire signed [35:0] addtree10_add_cast_1;  // sfix36_En15
  wire signed [36:0] addtree10_add_cast_2;  // sfix37_En15
  wire signed [36:0] addtree10_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_21;  // sfix36_En15
  reg signed [35:0] addtree_22;  // sfix36_En15
  wire signed [36:0] addtree11_add_cast;  // sfix37_En15
  wire signed [36:0] addtree11_add_cast_1;  // sfix37_En15
  wire signed [36:0] addtree11_add_temp;  // sfix37_En15
  wire signed [35:0] addtree_23;  // sfix36_En15
  reg signed [35:0] addtree_24;  // sfix36_En15
  reg signed [31:0] delayMatch24_t_0_0;  // int32
  reg signed [31:0] delayMatch24_t_1;  // int32
  reg signed [31:0] delayMatch25_t_0_0;  // int32
  reg signed [31:0] delayMatch25_t_1;  // int32
  reg signed [31:0] delayMatch26_t_0_0;  // int32
  reg signed [31:0] delayMatch26_t_1;  // int32
  reg signed [31:0] delayMatch27_t_0_0;  // int32
  reg signed [31:0] delayMatch27_t_1;  // int32
  reg signed [31:0] delayMatch28_t_0_0;  // int32
  reg signed [31:0] delayMatch28_t_1;  // int32
  reg signed [31:0] delayMatch29_t_0_0;  // int32
  reg signed [31:0] delayMatch29_t_1;  // int32
  reg signed [31:0] delayMatch30_t_0_0;  // int32
  reg signed [31:0] delayMatch30_t_1;  // int32
  reg signed [31:0] delayMatch31_t_0_0;  // int32
  reg signed [31:0] delayMatch31_t_1;  // int32
  reg signed [31:0] delayMatch32_t_0_0;  // int32
  reg signed [31:0] delayMatch32_t_1;  // int32
  reg signed [31:0] delayMatch33_t_0_0;  // int32
  reg signed [31:0] delayMatch33_t_1;  // int32
  reg signed [31:0] delayMatch34_t_0_0;  // int32
  reg signed [31:0] delayMatch34_t_1;  // int32
  reg signed [31:0] delayMatch35_t_0_0;  // int32
  reg signed [31:0] delayMatch35_t_1;  // int32
  reg signed [31:0] delayMatch36_t_0_0;  // int32
  reg signed [31:0] delayMatch36_t_1;  // int32
  reg signed [31:0] delayMatch37_t_0_0;  // int32
  reg signed [31:0] delayMatch37_t_0_1;  // int32
  reg signed [31:0] delayMatch37_t_1;  // int32


  assign Upsample_out1 = REP_TxI_In;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <=  ~ HDL_Counter_out1;
        end
      end
    end

  assign coeffphaseSig1 = 16'sb1111111101111100;

  assign coeffphaseSig2 = 16'sb0000000000011100;

  assign prodMux10_out1 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1 :
              coeffphaseSig2);

  always @(posedge clk or posedge reset)
    begin : delayMatch24_process
      if (reset == 1'b1) begin
        for(delayMatch24_t_1 = 32'sd0; delayMatch24_t_1 <= 32'sd1; delayMatch24_t_1 = delayMatch24_t_1 + 32'sd1) begin
          delayMatch24_reg[delayMatch24_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch24_t_0_0 = 32'sd0; delayMatch24_t_0_0 <= 32'sd1; delayMatch24_t_0_0 = delayMatch24_t_0_0 + 32'sd1) begin
            delayMatch24_reg[delayMatch24_t_0_0] <= delayMatch24_reg_next[delayMatch24_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_1 = delayMatch24_reg[1];
  assign delayMatch24_reg_next[0] = prodMux10_out1;
  assign delayMatch24_reg_next[1] = delayMatch24_reg[0];

  assign Product10_out1 = Upsample_out1 * prodMux10_out1_1;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe_process
      if (reset == 1'b1) begin
        Product10_out1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_1 <= Product10_out1;
        end
      end
    end

  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[1] <= delayMatch1_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[1];

  assign Compare_To_Constant_out1 = HDL_Counter_out1 == 1'b1;

  assign Constant1_out1 = 1'b1;

  assign Logical_Operator_out1 = Compare_To_Constant_out1 & Constant1_out1;

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= Logical_Operator_out1;
          reduced_reg[1] <= reduced_reg[0];
        end
      end
    end

  assign Logical_Operator_out1_1 = reduced_reg[1];

  assign switch_compare_1 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Delay0_out1 :
              Upsample_out1);

  assign Switch_out1_1 = (stateControl_2 == 1'b0 ? Delay0_out1 :
              Switch_out1);

  always @(posedge clk or posedge reset)
    begin : Delay0_process
      if (reset == 1'b1) begin
        Delay0_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1 <= Switch_out1_1;
        end
      end
    end

  assign coeffphaseSig1_1 = 16'sb0000000100101000;

  assign coeffphaseSig2_1 = 16'sb0000000001001110;

  assign prodMux10_out1_2 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_1 :
              coeffphaseSig2_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch25_process
      if (reset == 1'b1) begin
        for(delayMatch25_t_1 = 32'sd0; delayMatch25_t_1 <= 32'sd1; delayMatch25_t_1 = delayMatch25_t_1 + 32'sd1) begin
          delayMatch25_reg[delayMatch25_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch25_t_0_0 = 32'sd0; delayMatch25_t_0_0 <= 32'sd1; delayMatch25_t_0_0 = delayMatch25_t_0_0 + 32'sd1) begin
            delayMatch25_reg[delayMatch25_t_0_0] <= delayMatch25_reg_next[delayMatch25_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_3 = delayMatch25_reg[1];
  assign delayMatch25_reg_next[0] = prodMux10_out1_2;
  assign delayMatch25_reg_next[1] = delayMatch25_reg[0];

  assign Product10_out1_2 = Delay0_out1 * prodMux10_out1_3;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe1_process
      if (reset == 1'b1) begin
        Product10_out1_3 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_3 <= Product10_out1_2;
        end
      end
    end

  assign addtree_add_cast = {{4{Product10_out1_1[31]}}, Product10_out1_1};
  assign addtree_add_cast_1 = {{4{Product10_out1_3[31]}}, Product10_out1_3};
  assign addtree_1 = addtree_add_cast + addtree_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe_process
      if (reset == 1'b1) begin
        addtree_2 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_2 <= addtree_1;
        end
      end
    end

  assign stateControl_3 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        delayMatch3_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch3_reg[0] <= stateControl_3;
          delayMatch3_reg[1] <= delayMatch3_reg[0];
        end
      end
    end

  assign stateControl_4 = delayMatch3_reg[1];

  assign switch_compare_1_1 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_2 = (switch_compare_1_1 == 1'b0 ? Delay0_out1_1 :
              Delay0_out1);

  assign Switch_out1_3 = (stateControl_4 == 1'b0 ? Delay0_out1_1 :
              Switch_out1_2);

  always @(posedge clk or posedge reset)
    begin : Delay01_process
      if (reset == 1'b1) begin
        Delay0_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_1 <= Switch_out1_3;
        end
      end
    end

  assign coeffphaseSig1_2 = 16'sb1111110011111110;

  assign coeffphaseSig2_2 = 16'sb1111110111000110;

  assign prodMux10_out1_4 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_2 :
              coeffphaseSig2_2);

  always @(posedge clk or posedge reset)
    begin : delayMatch26_process
      if (reset == 1'b1) begin
        for(delayMatch26_t_1 = 32'sd0; delayMatch26_t_1 <= 32'sd1; delayMatch26_t_1 = delayMatch26_t_1 + 32'sd1) begin
          delayMatch26_reg[delayMatch26_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch26_t_0_0 = 32'sd0; delayMatch26_t_0_0 <= 32'sd1; delayMatch26_t_0_0 = delayMatch26_t_0_0 + 32'sd1) begin
            delayMatch26_reg[delayMatch26_t_0_0] <= delayMatch26_reg_next[delayMatch26_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_5 = delayMatch26_reg[1];
  assign delayMatch26_reg_next[0] = prodMux10_out1_4;
  assign delayMatch26_reg_next[1] = delayMatch26_reg[0];

  assign Product10_out1_4 = Delay0_out1_1 * prodMux10_out1_5;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe2_process
      if (reset == 1'b1) begin
        Product10_out1_5 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_5 <= Product10_out1_4;
        end
      end
    end

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        delayMatch5_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch5_reg[0] <= stateControl_5;
          delayMatch5_reg[1] <= delayMatch5_reg[0];
        end
      end
    end

  assign stateControl_6 = delayMatch5_reg[1];

  assign switch_compare_1_2 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_4 = (switch_compare_1_2 == 1'b0 ? Delay0_out1_2 :
              Delay0_out1_1);

  assign Switch_out1_5 = (stateControl_6 == 1'b0 ? Delay0_out1_2 :
              Switch_out1_4);

  always @(posedge clk or posedge reset)
    begin : Delay02_process
      if (reset == 1'b1) begin
        Delay0_out1_2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_2 <= Switch_out1_5;
        end
      end
    end

  assign coeffphaseSig1_3 = 16'sb0000010111110001;

  assign coeffphaseSig2_3 = 16'sb0000011110011011;

  assign prodMux10_out1_6 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_3 :
              coeffphaseSig2_3);

  always @(posedge clk or posedge reset)
    begin : delayMatch27_process
      if (reset == 1'b1) begin
        for(delayMatch27_t_1 = 32'sd0; delayMatch27_t_1 <= 32'sd1; delayMatch27_t_1 = delayMatch27_t_1 + 32'sd1) begin
          delayMatch27_reg[delayMatch27_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch27_t_0_0 = 32'sd0; delayMatch27_t_0_0 <= 32'sd1; delayMatch27_t_0_0 = delayMatch27_t_0_0 + 32'sd1) begin
            delayMatch27_reg[delayMatch27_t_0_0] <= delayMatch27_reg_next[delayMatch27_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_7 = delayMatch27_reg[1];
  assign delayMatch27_reg_next[0] = prodMux10_out1_6;
  assign delayMatch27_reg_next[1] = delayMatch27_reg[0];

  assign Product10_out1_6 = Delay0_out1_2 * prodMux10_out1_7;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe3_process
      if (reset == 1'b1) begin
        Product10_out1_7 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_7 <= Product10_out1_6;
        end
      end
    end

  assign addtree1_add_cast = {{4{Product10_out1_5[31]}}, Product10_out1_5};
  assign addtree1_add_cast_1 = {{4{Product10_out1_7[31]}}, Product10_out1_7};
  assign addtree_3 = addtree1_add_cast + addtree1_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe1_process
      if (reset == 1'b1) begin
        addtree_4 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_4 <= addtree_3;
        end
      end
    end

  assign addtree6_add_cast = {addtree_2[35], addtree_2};
  assign addtree6_add_cast_1 = {addtree_4[35], addtree_4};
  assign addtree6_add_temp = addtree6_add_cast + addtree6_add_cast_1;
  assign addtree_5 = ((addtree6_add_temp[36] == 1'b0) && (addtree6_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree6_add_temp[36] == 1'b1) && (addtree6_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree6_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe6_process
      if (reset == 1'b1) begin
        addtree_6 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_6 <= addtree_5;
        end
      end
    end

  assign stateControl_7 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        delayMatch7_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch7_reg[0] <= stateControl_7;
          delayMatch7_reg[1] <= delayMatch7_reg[0];
        end
      end
    end

  assign stateControl_8 = delayMatch7_reg[1];

  assign switch_compare_1_3 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_6 = (switch_compare_1_3 == 1'b0 ? Delay0_out1_3 :
              Delay0_out1_2);

  assign Switch_out1_7 = (stateControl_8 == 1'b0 ? Delay0_out1_3 :
              Switch_out1_6);

  always @(posedge clk or posedge reset)
    begin : Delay03_process
      if (reset == 1'b1) begin
        Delay0_out1_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_3 <= Switch_out1_7;
        end
      end
    end

  assign coeffphaseSig1_4 = 16'sb1111011011000100;

  assign coeffphaseSig2_4 = 16'sb1110101100001000;

  assign prodMux10_out1_8 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_4 :
              coeffphaseSig2_4);

  always @(posedge clk or posedge reset)
    begin : delayMatch28_process
      if (reset == 1'b1) begin
        for(delayMatch28_t_1 = 32'sd0; delayMatch28_t_1 <= 32'sd1; delayMatch28_t_1 = delayMatch28_t_1 + 32'sd1) begin
          delayMatch28_reg[delayMatch28_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch28_t_0_0 = 32'sd0; delayMatch28_t_0_0 <= 32'sd1; delayMatch28_t_0_0 = delayMatch28_t_0_0 + 32'sd1) begin
            delayMatch28_reg[delayMatch28_t_0_0] <= delayMatch28_reg_next[delayMatch28_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_9 = delayMatch28_reg[1];
  assign delayMatch28_reg_next[0] = prodMux10_out1_8;
  assign delayMatch28_reg_next[1] = delayMatch28_reg[0];

  assign Product10_out1_8 = Delay0_out1_3 * prodMux10_out1_9;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe4_process
      if (reset == 1'b1) begin
        Product10_out1_9 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_9 <= Product10_out1_8;
        end
      end
    end

  assign stateControl_9 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch9_process
      if (reset == 1'b1) begin
        delayMatch9_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch9_reg[0] <= stateControl_9;
          delayMatch9_reg[1] <= delayMatch9_reg[0];
        end
      end
    end

  assign stateControl_10 = delayMatch9_reg[1];

  assign switch_compare_1_4 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_8 = (switch_compare_1_4 == 1'b0 ? Delay0_out1_4 :
              Delay0_out1_3);

  assign Switch_out1_9 = (stateControl_10 == 1'b0 ? Delay0_out1_4 :
              Switch_out1_8);

  always @(posedge clk or posedge reset)
    begin : Delay04_process
      if (reset == 1'b1) begin
        Delay0_out1_4 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_4 <= Switch_out1_9;
        end
      end
    end

  assign coeffphaseSig1_5 = 16'sb0000101111010101;

  assign coeffphaseSig2_5 = 16'sb0100111101010100;

  assign prodMux10_out1_10 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_5 :
              coeffphaseSig2_5);

  always @(posedge clk or posedge reset)
    begin : delayMatch29_process
      if (reset == 1'b1) begin
        for(delayMatch29_t_1 = 32'sd0; delayMatch29_t_1 <= 32'sd1; delayMatch29_t_1 = delayMatch29_t_1 + 32'sd1) begin
          delayMatch29_reg[delayMatch29_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch29_t_0_0 = 32'sd0; delayMatch29_t_0_0 <= 32'sd1; delayMatch29_t_0_0 = delayMatch29_t_0_0 + 32'sd1) begin
            delayMatch29_reg[delayMatch29_t_0_0] <= delayMatch29_reg_next[delayMatch29_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_11 = delayMatch29_reg[1];
  assign delayMatch29_reg_next[0] = prodMux10_out1_10;
  assign delayMatch29_reg_next[1] = delayMatch29_reg[0];

  assign Product10_out1_10 = Delay0_out1_4 * prodMux10_out1_11;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe5_process
      if (reset == 1'b1) begin
        Product10_out1_11 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_11 <= Product10_out1_10;
        end
      end
    end

  assign addtree2_add_cast = {{4{Product10_out1_9[31]}}, Product10_out1_9};
  assign addtree2_add_cast_1 = {{4{Product10_out1_11[31]}}, Product10_out1_11};
  assign addtree_7 = addtree2_add_cast + addtree2_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe2_process
      if (reset == 1'b1) begin
        addtree_8 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_8 <= addtree_7;
        end
      end
    end

  assign stateControl_11 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch11_process
      if (reset == 1'b1) begin
        delayMatch11_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch11_reg[0] <= stateControl_11;
          delayMatch11_reg[1] <= delayMatch11_reg[0];
        end
      end
    end

  assign stateControl_12 = delayMatch11_reg[1];

  assign switch_compare_1_5 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_10 = (switch_compare_1_5 == 1'b0 ? Delay0_out1_5 :
              Delay0_out1_4);

  assign Switch_out1_11 = (stateControl_12 == 1'b0 ? Delay0_out1_5 :
              Switch_out1_10);

  always @(posedge clk or posedge reset)
    begin : Delay05_process
      if (reset == 1'b1) begin
        Delay0_out1_5 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_5 <= Switch_out1_11;
        end
      end
    end

  assign coeffphaseSig1_6 = 16'sb0111001101011011;

  assign coeffphaseSig2_6 = 16'sb0100111101010100;

  assign prodMux10_out1_12 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_6 :
              coeffphaseSig2_6);

  always @(posedge clk or posedge reset)
    begin : delayMatch30_process
      if (reset == 1'b1) begin
        for(delayMatch30_t_1 = 32'sd0; delayMatch30_t_1 <= 32'sd1; delayMatch30_t_1 = delayMatch30_t_1 + 32'sd1) begin
          delayMatch30_reg[delayMatch30_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch30_t_0_0 = 32'sd0; delayMatch30_t_0_0 <= 32'sd1; delayMatch30_t_0_0 = delayMatch30_t_0_0 + 32'sd1) begin
            delayMatch30_reg[delayMatch30_t_0_0] <= delayMatch30_reg_next[delayMatch30_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_13 = delayMatch30_reg[1];
  assign delayMatch30_reg_next[0] = prodMux10_out1_12;
  assign delayMatch30_reg_next[1] = delayMatch30_reg[0];

  assign Product10_out1_12 = Delay0_out1_5 * prodMux10_out1_13;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe6_process
      if (reset == 1'b1) begin
        Product10_out1_13 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_13 <= Product10_out1_12;
        end
      end
    end

  assign stateControl_13 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch13_process
      if (reset == 1'b1) begin
        delayMatch13_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch13_reg[0] <= stateControl_13;
          delayMatch13_reg[1] <= delayMatch13_reg[0];
        end
      end
    end

  assign stateControl_14 = delayMatch13_reg[1];

  assign switch_compare_1_6 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_12 = (switch_compare_1_6 == 1'b0 ? Delay0_out1_6 :
              Delay0_out1_5);

  assign Switch_out1_13 = (stateControl_14 == 1'b0 ? Delay0_out1_6 :
              Switch_out1_12);

  always @(posedge clk or posedge reset)
    begin : Delay06_process
      if (reset == 1'b1) begin
        Delay0_out1_6 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_6 <= Switch_out1_13;
        end
      end
    end

  assign coeffphaseSig1_7 = 16'sb0000101111010101;

  assign coeffphaseSig2_7 = 16'sb1110101100001000;

  assign prodMux10_out1_14 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_7 :
              coeffphaseSig2_7);

  always @(posedge clk or posedge reset)
    begin : delayMatch31_process
      if (reset == 1'b1) begin
        for(delayMatch31_t_1 = 32'sd0; delayMatch31_t_1 <= 32'sd1; delayMatch31_t_1 = delayMatch31_t_1 + 32'sd1) begin
          delayMatch31_reg[delayMatch31_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch31_t_0_0 = 32'sd0; delayMatch31_t_0_0 <= 32'sd1; delayMatch31_t_0_0 = delayMatch31_t_0_0 + 32'sd1) begin
            delayMatch31_reg[delayMatch31_t_0_0] <= delayMatch31_reg_next[delayMatch31_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_15 = delayMatch31_reg[1];
  assign delayMatch31_reg_next[0] = prodMux10_out1_14;
  assign delayMatch31_reg_next[1] = delayMatch31_reg[0];

  assign Product10_out1_14 = Delay0_out1_6 * prodMux10_out1_15;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe7_process
      if (reset == 1'b1) begin
        Product10_out1_15 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_15 <= Product10_out1_14;
        end
      end
    end

  assign addtree3_add_cast = {{4{Product10_out1_13[31]}}, Product10_out1_13};
  assign addtree3_add_cast_1 = {{4{Product10_out1_15[31]}}, Product10_out1_15};
  assign addtree_9 = addtree3_add_cast + addtree3_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe3_process
      if (reset == 1'b1) begin
        addtree_10 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_10 <= addtree_9;
        end
      end
    end

  assign addtree7_add_cast = {addtree_8[35], addtree_8};
  assign addtree7_add_cast_1 = {addtree_10[35], addtree_10};
  assign addtree7_add_temp = addtree7_add_cast + addtree7_add_cast_1;
  assign addtree_11 = ((addtree7_add_temp[36] == 1'b0) && (addtree7_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree7_add_temp[36] == 1'b1) && (addtree7_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree7_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe7_process
      if (reset == 1'b1) begin
        addtree_12 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_12 <= addtree_11;
        end
      end
    end

  assign addtree9_add_cast = {addtree_6[35], addtree_6};
  assign addtree9_add_cast_1 = {addtree_12[35], addtree_12};
  assign addtree9_add_temp = addtree9_add_cast + addtree9_add_cast_1;
  assign addtree_13 = ((addtree9_add_temp[36] == 1'b0) && (addtree9_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree9_add_temp[36] == 1'b1) && (addtree9_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree9_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe9_process
      if (reset == 1'b1) begin
        addtree_14 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_14 <= addtree_13;
        end
      end
    end

  assign stateControl_15 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch15_process
      if (reset == 1'b1) begin
        delayMatch15_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch15_reg[0] <= stateControl_15;
          delayMatch15_reg[1] <= delayMatch15_reg[0];
        end
      end
    end

  assign stateControl_16 = delayMatch15_reg[1];

  assign switch_compare_1_7 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_14 = (switch_compare_1_7 == 1'b0 ? Delay0_out1_7 :
              Delay0_out1_6);

  assign Switch_out1_15 = (stateControl_16 == 1'b0 ? Delay0_out1_7 :
              Switch_out1_14);

  always @(posedge clk or posedge reset)
    begin : Delay07_process
      if (reset == 1'b1) begin
        Delay0_out1_7 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_7 <= Switch_out1_15;
        end
      end
    end

  assign coeffphaseSig1_8 = 16'sb1111011011000100;

  assign coeffphaseSig2_8 = 16'sb0000011110011011;

  assign prodMux10_out1_16 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_8 :
              coeffphaseSig2_8);

  always @(posedge clk or posedge reset)
    begin : delayMatch32_process
      if (reset == 1'b1) begin
        for(delayMatch32_t_1 = 32'sd0; delayMatch32_t_1 <= 32'sd1; delayMatch32_t_1 = delayMatch32_t_1 + 32'sd1) begin
          delayMatch32_reg[delayMatch32_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch32_t_0_0 = 32'sd0; delayMatch32_t_0_0 <= 32'sd1; delayMatch32_t_0_0 = delayMatch32_t_0_0 + 32'sd1) begin
            delayMatch32_reg[delayMatch32_t_0_0] <= delayMatch32_reg_next[delayMatch32_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_17 = delayMatch32_reg[1];
  assign delayMatch32_reg_next[0] = prodMux10_out1_16;
  assign delayMatch32_reg_next[1] = delayMatch32_reg[0];

  assign Product10_out1_16 = Delay0_out1_7 * prodMux10_out1_17;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe8_process
      if (reset == 1'b1) begin
        Product10_out1_17 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_17 <= Product10_out1_16;
        end
      end
    end

  assign stateControl_17 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch17_process
      if (reset == 1'b1) begin
        delayMatch17_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch17_reg[0] <= stateControl_17;
          delayMatch17_reg[1] <= delayMatch17_reg[0];
        end
      end
    end

  assign stateControl_18 = delayMatch17_reg[1];

  assign switch_compare_1_8 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_16 = (switch_compare_1_8 == 1'b0 ? Delay0_out1_8 :
              Delay0_out1_7);

  assign Switch_out1_17 = (stateControl_18 == 1'b0 ? Delay0_out1_8 :
              Switch_out1_16);

  always @(posedge clk or posedge reset)
    begin : Delay08_process
      if (reset == 1'b1) begin
        Delay0_out1_8 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_8 <= Switch_out1_17;
        end
      end
    end

  assign coeffphaseSig1_9 = 16'sb0000010111110001;

  assign coeffphaseSig2_9 = 16'sb1111110111000110;

  assign prodMux10_out1_18 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_9 :
              coeffphaseSig2_9);

  always @(posedge clk or posedge reset)
    begin : delayMatch33_process
      if (reset == 1'b1) begin
        for(delayMatch33_t_1 = 32'sd0; delayMatch33_t_1 <= 32'sd1; delayMatch33_t_1 = delayMatch33_t_1 + 32'sd1) begin
          delayMatch33_reg[delayMatch33_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch33_t_0_0 = 32'sd0; delayMatch33_t_0_0 <= 32'sd1; delayMatch33_t_0_0 = delayMatch33_t_0_0 + 32'sd1) begin
            delayMatch33_reg[delayMatch33_t_0_0] <= delayMatch33_reg_next[delayMatch33_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_19 = delayMatch33_reg[1];
  assign delayMatch33_reg_next[0] = prodMux10_out1_18;
  assign delayMatch33_reg_next[1] = delayMatch33_reg[0];

  assign Product10_out1_18 = Delay0_out1_8 * prodMux10_out1_19;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe9_process
      if (reset == 1'b1) begin
        Product10_out1_19 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_19 <= Product10_out1_18;
        end
      end
    end

  assign addtree4_add_cast = {{4{Product10_out1_17[31]}}, Product10_out1_17};
  assign addtree4_add_cast_1 = {{4{Product10_out1_19[31]}}, Product10_out1_19};
  assign addtree_15 = addtree4_add_cast + addtree4_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe4_process
      if (reset == 1'b1) begin
        addtree_16 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_16 <= addtree_15;
        end
      end
    end

  assign stateControl_19 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch19_process
      if (reset == 1'b1) begin
        delayMatch19_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch19_reg[0] <= stateControl_19;
          delayMatch19_reg[1] <= delayMatch19_reg[0];
        end
      end
    end

  assign stateControl_20 = delayMatch19_reg[1];

  assign switch_compare_1_9 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_18 = (switch_compare_1_9 == 1'b0 ? Delay0_out1_9 :
              Delay0_out1_8);

  assign Switch_out1_19 = (stateControl_20 == 1'b0 ? Delay0_out1_9 :
              Switch_out1_18);

  always @(posedge clk or posedge reset)
    begin : Delay09_process
      if (reset == 1'b1) begin
        Delay0_out1_9 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_9 <= Switch_out1_19;
        end
      end
    end

  assign coeffphaseSig1_10 = 16'sb1111110011111110;

  assign coeffphaseSig2_10 = 16'sb0000000001001110;

  assign prodMux10_out1_20 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_10 :
              coeffphaseSig2_10);

  always @(posedge clk or posedge reset)
    begin : delayMatch34_process
      if (reset == 1'b1) begin
        for(delayMatch34_t_1 = 32'sd0; delayMatch34_t_1 <= 32'sd1; delayMatch34_t_1 = delayMatch34_t_1 + 32'sd1) begin
          delayMatch34_reg[delayMatch34_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch34_t_0_0 = 32'sd0; delayMatch34_t_0_0 <= 32'sd1; delayMatch34_t_0_0 = delayMatch34_t_0_0 + 32'sd1) begin
            delayMatch34_reg[delayMatch34_t_0_0] <= delayMatch34_reg_next[delayMatch34_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_21 = delayMatch34_reg[1];
  assign delayMatch34_reg_next[0] = prodMux10_out1_20;
  assign delayMatch34_reg_next[1] = delayMatch34_reg[0];

  assign Product10_out1_20 = Delay0_out1_9 * prodMux10_out1_21;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe10_process
      if (reset == 1'b1) begin
        Product10_out1_21 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_21 <= Product10_out1_20;
        end
      end
    end

  assign stateControl_21 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch21_process
      if (reset == 1'b1) begin
        delayMatch21_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch21_reg[0] <= stateControl_21;
          delayMatch21_reg[1] <= delayMatch21_reg[0];
        end
      end
    end

  assign stateControl_22 = delayMatch21_reg[1];

  assign switch_compare_1_10 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_20 = (switch_compare_1_10 == 1'b0 ? Delay0_out1_10 :
              Delay0_out1_9);

  assign Switch_out1_21 = (stateControl_22 == 1'b0 ? Delay0_out1_10 :
              Switch_out1_20);

  always @(posedge clk or posedge reset)
    begin : Delay010_process
      if (reset == 1'b1) begin
        Delay0_out1_10 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_10 <= Switch_out1_21;
        end
      end
    end

  assign coeffphaseSig1_11 = 16'sb0000000100101000;

  assign coeffphaseSig2_11 = 16'sb0000000000011100;

  assign prodMux10_out1_22 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_11 :
              coeffphaseSig2_11);

  always @(posedge clk or posedge reset)
    begin : delayMatch35_process
      if (reset == 1'b1) begin
        for(delayMatch35_t_1 = 32'sd0; delayMatch35_t_1 <= 32'sd1; delayMatch35_t_1 = delayMatch35_t_1 + 32'sd1) begin
          delayMatch35_reg[delayMatch35_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch35_t_0_0 = 32'sd0; delayMatch35_t_0_0 <= 32'sd1; delayMatch35_t_0_0 = delayMatch35_t_0_0 + 32'sd1) begin
            delayMatch35_reg[delayMatch35_t_0_0] <= delayMatch35_reg_next[delayMatch35_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_23 = delayMatch35_reg[1];
  assign delayMatch35_reg_next[0] = prodMux10_out1_22;
  assign delayMatch35_reg_next[1] = delayMatch35_reg[0];

  assign Product10_out1_22 = Delay0_out1_10 * prodMux10_out1_23;

  always @(posedge clk or posedge reset)
    begin : Product10_out_pipe11_process
      if (reset == 1'b1) begin
        Product10_out1_23 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Product10_out1_23 <= Product10_out1_22;
        end
      end
    end

  assign addtree5_add_cast = {{4{Product10_out1_21[31]}}, Product10_out1_21};
  assign addtree5_add_cast_1 = {{4{Product10_out1_23[31]}}, Product10_out1_23};
  assign addtree_17 = addtree5_add_cast + addtree5_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe5_process
      if (reset == 1'b1) begin
        addtree_18 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_18 <= addtree_17;
        end
      end
    end

  assign addtree8_add_cast = {addtree_16[35], addtree_16};
  assign addtree8_add_cast_1 = {addtree_18[35], addtree_18};
  assign addtree8_add_temp = addtree8_add_cast + addtree8_add_cast_1;
  assign addtree_19 = ((addtree8_add_temp[36] == 1'b0) && (addtree8_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree8_add_temp[36] == 1'b1) && (addtree8_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree8_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe8_process
      if (reset == 1'b1) begin
        addtree_20 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_20 <= addtree_19;
        end
      end
    end

  assign stateControl_23 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch23_process
      if (reset == 1'b1) begin
        delayMatch23_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch23_reg[0] <= stateControl_23;
          delayMatch23_reg[1] <= delayMatch23_reg[0];
        end
      end
    end

  assign stateControl_24 = delayMatch23_reg[1];

  assign switch_compare_1_11 = Logical_Operator_out1_1 > 1'b0;

  assign Switch_out1_22 = (switch_compare_1_11 == 1'b0 ? Delay0_out1_11 :
              Delay0_out1_10);

  assign Switch_out1_23 = (stateControl_24 == 1'b0 ? Delay0_out1_11 :
              Switch_out1_22);

  always @(posedge clk or posedge reset)
    begin : Delay011_process
      if (reset == 1'b1) begin
        Delay0_out1_11 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay0_out1_11 <= Switch_out1_23;
        end
      end
    end

  assign coeffphaseSig1_12 = 16'sb1111111101111100;

  assign coeffphaseSig2_12 = 16'sb0000000000000000;

  assign prodMux10_out1_24 = (HDL_Counter_out1 == 1'b0 ? coeffphaseSig1_12 :
              coeffphaseSig2_12);

  always @(posedge clk or posedge reset)
    begin : delayMatch36_process
      if (reset == 1'b1) begin
        for(delayMatch36_t_1 = 32'sd0; delayMatch36_t_1 <= 32'sd1; delayMatch36_t_1 = delayMatch36_t_1 + 32'sd1) begin
          delayMatch36_reg[delayMatch36_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch36_t_0_0 = 32'sd0; delayMatch36_t_0_0 <= 32'sd1; delayMatch36_t_0_0 = delayMatch36_t_0_0 + 32'sd1) begin
            delayMatch36_reg[delayMatch36_t_0_0] <= delayMatch36_reg_next[delayMatch36_t_0_0];
          end
        end
      end
    end

  assign prodMux10_out1_25 = delayMatch36_reg[1];
  assign delayMatch36_reg_next[0] = prodMux10_out1_24;
  assign delayMatch36_reg_next[1] = delayMatch36_reg[0];

  assign Product10_out1_24 = Delay0_out1_11 * prodMux10_out1_25;

  always @(posedge clk or posedge reset)
    begin : delayMatch37_process
      if (reset == 1'b1) begin
        for(delayMatch37_t_1 = 32'sd0; delayMatch37_t_1 <= 32'sd2; delayMatch37_t_1 = delayMatch37_t_1 + 32'sd1) begin
          delayMatch37_reg[delayMatch37_t_1] <= 32'sb00000000000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch37_t_0_1 = 32'sd0; delayMatch37_t_0_1 <= 32'sd2; delayMatch37_t_0_1 = delayMatch37_t_0_1 + 32'sd1) begin
            delayMatch37_reg[delayMatch37_t_0_1] <= delayMatch37_reg_next[delayMatch37_t_0_1];
          end
        end
      end
    end

  always @* begin
    Product10_out1_25 = delayMatch37_reg[2];
    delayMatch37_reg_next[0] = Product10_out1_24;

    for(delayMatch37_t_0_0 = 32'sd0; delayMatch37_t_0_0 <= 32'sd1; delayMatch37_t_0_0 = delayMatch37_t_0_0 + 32'sd1) begin
      delayMatch37_reg_next[delayMatch37_t_0_0 + 32'sd1] = delayMatch37_reg[delayMatch37_t_0_0];
    end

  end

  assign addtree10_add_cast = {addtree_20[35], addtree_20};
  assign addtree10_add_cast_1 = {{4{Product10_out1_25[31]}}, Product10_out1_25};
  assign addtree10_add_cast_2 = {addtree10_add_cast_1[35], addtree10_add_cast_1};
  assign addtree10_add_temp = addtree10_add_cast + addtree10_add_cast_2;
  assign addtree_21 = ((addtree10_add_temp[36] == 1'b0) && (addtree10_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree10_add_temp[36] == 1'b1) && (addtree10_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree10_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe10_process
      if (reset == 1'b1) begin
        addtree_22 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_22 <= addtree_21;
        end
      end
    end

  assign addtree11_add_cast = {addtree_14[35], addtree_14};
  assign addtree11_add_cast_1 = {addtree_22[35], addtree_22};
  assign addtree11_add_temp = addtree11_add_cast + addtree11_add_cast_1;
  assign addtree_23 = ((addtree11_add_temp[36] == 1'b0) && (addtree11_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((addtree11_add_temp[36] == 1'b1) && (addtree11_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(addtree11_add_temp[35:0])));

  always @(posedge clk or posedge reset)
    begin : addtree_out_pipe11_process
      if (reset == 1'b1) begin
        addtree_24 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          addtree_24 <= addtree_23;
        end
      end
    end

  assign REP_TxI_out = (((addtree_24[35] == 1'b0) && (addtree_24[34:30] != 5'b00000)) || ((addtree_24[35] == 1'b0) && (addtree_24[30:15] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((addtree_24[35] == 1'b1) && (addtree_24[34:30] != 5'b11111) ? 16'sb1000000000000000 :
              addtree_24[30:15] + $signed({1'b0, addtree_24[14]})));

endmodule  // REP_TxI

