// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Reset_Generator.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Reset_Generator
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency 
// Compensator/Coarse Frequency Estimator/Integrator/Reset Generato
// Hierarchy Level: 7
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Reset_Generator
          (clk,
           reset,
           enb_1_2_0,
           validIn,
           reset_1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   validIn;
  output  reset_1;


  wire [12:0] count_step;  // ufix13
  wire [12:0] count_from;  // ufix13
  reg [12:0] HDL_Counter_out1;  // ufix13
  wire [12:0] count;  // ufix13
  wire need_to_wrap;
  wire [12:0] count_value;  // ufix13
  wire [12:0] count_1;  // ufix13
  reg  Delay1_out1;
  reg [12:0] Delay5_out1;  // ufix13
  wire Compare_To_Constant_out1;
  wire Logical_Operator_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 4096
  assign count_step = 13'b0000000000001;

  assign count_from = 13'b0000000000000;

  assign count = HDL_Counter_out1 + count_step;

  assign need_to_wrap = HDL_Counter_out1 == 13'b1000000000000;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? HDL_Counter_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 13'b0000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 13'b0000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= HDL_Counter_out1;
        end
      end
    end

  assign Compare_To_Constant_out1 = Delay5_out1 == 13'b1000000000000;

  assign Logical_Operator_out1 = Delay1_out1 & Compare_To_Constant_out1;

  assign reset_1 = Logical_Operator_out1;

endmodule  // Reset_Generator

