// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/RRC_Transmit_Filter.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RRC_Transmit_Filter
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/RRC Transmit Filter
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RRC_Transmit_Filter
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En15
  input   signed [15:0] dataIn_im;  // sfix16_En15
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14


  wire signed [16:0] Data_Type_Conversion_out1_re;  // sfix17_En16
  wire signed [16:0] Data_Type_Conversion_out1_im;  // sfix17_En16
  reg signed [16:0] Delay3_out1_re;  // sfix17_En16
  reg signed [16:0] Delay3_out1_im;  // sfix17_En16
  reg  Unit_Delay_Enabled_Synchronous1_out1;
  reg  Unit_Delay_Enabled_Synchronous1_out1_1;
  wire signed [16:0] RRC_Filter_out1_re;  // sfix17_En14
  wire signed [16:0] RRC_Filter_out1_im;  // sfix17_En14
  wire signed [15:0] Data_Type_Conversion1_out1_re;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion1_out1_im;  // sfix16_En14
  reg signed [15:0] Delay1_out1_re;  // sfix16_En14
  reg signed [15:0] Delay1_out1_im;  // sfix16_En14


  assign Data_Type_Conversion_out1_re = {dataIn_re, 1'b0};
  assign Data_Type_Conversion_out1_im = {dataIn_im, 1'b0};

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1_re <= 17'sb00000000000000000;
        Delay3_out1_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1_re <= Data_Type_Conversion_out1_re;
          Delay3_out1_im <= Data_Type_Conversion_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous1_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0 && validIn) begin
          Unit_Delay_Enabled_Synchronous1_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous1_out1_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Unit_Delay_Enabled_Synchronous1_out1_1 <= Unit_Delay_Enabled_Synchronous1_out1;
        end
      end
    end

  RRC_Filter u_RRC_Filter (.clk(clk),
                                            .reset(reset),
                                            .enb_1_2_0(enb_1_2_0),
                                            .dataIn_re(Delay3_out1_re),  // sfix17_En16
                                            .dataIn_im(Delay3_out1_im),  // sfix17_En16
                                            .validIn(Unit_Delay_Enabled_Synchronous1_out1_1),
                                            .dataOut_re(RRC_Filter_out1_re),  // sfix17_En14
                                            .dataOut_im(RRC_Filter_out1_im)  // sfix17_En14
                                            );

  assign Data_Type_Conversion1_out1_re = RRC_Filter_out1_re[15:0];
  assign Data_Type_Conversion1_out1_im = RRC_Filter_out1_im[15:0];

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= Data_Type_Conversion1_out1_re;
          Delay1_out1_im <= Data_Type_Conversion1_out1_im;
        end
      end
    end

  assign dataOut_re = Delay1_out1_re;

  assign dataOut_im = Delay1_out1_im;

endmodule  // RRC_Transmit_Filter

