// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/RstCsCounter.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RstCsCounter
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/RstCsCounter
// Hierarchy Level: 3
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RstCsCounter
          (clk,
           reset,
           enb_1_2_0,
           e,
           c);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   e;
  output  [31:0] c;  // uint32


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg [31:0] c_1;  // uint32
  reg  prev;
  reg [31:0] cnt;  // uint32
  reg  prev_next;
  reg [31:0] cnt_next;  // uint32
  reg [31:0] c_last_value;  // uint32
  reg [31:0] n;  // uint32
  reg [32:0] add_temp;  // ufix33
  reg [32:0] t_0;  // ufix33


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : RstCsCounter_process
      if (reset == 1'b1) begin
        prev <= 1'b0;
        cnt <= 32'd0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          prev <= prev_next;
          cnt <= cnt_next;
        end
      end
    end

  always @(cnt, e, prev) begin
    add_temp = 33'h000000000;
    t_0 = 33'h000000000;
    // Count RISING EDGES of the CFO-step-detector carrier-sync reset (AXI 0x150).
    // Saturating; reset by the modem soft-reset 0x000 via the persistent init.
    n = cnt;
    if ((e && ( ! prev)) && (cnt < 32'd4294967295)) begin
      t_0 = {1'b0, cnt};
      add_temp = t_0 + 33'h000000001;
      if (add_temp[32] != 1'b0) begin
        n = 32'b11111111111111111111111111111111;
      end
      else begin
        n = add_temp[31:0];
      end
    end
    cnt_next = n;
    prev_next = e;
    c_1 = n;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        c_last_value <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          c_last_value <= c;
        end
      end
    end

  assign c = (stateControl_2 == 1'b0 ? c_last_value :
              c_1);

endmodule  // RstCsCounter

