// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/sample_discard_controller.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sample_discard_controller
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Packet Controller/sample 
// discard controlle
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sample_discard_controller
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           startIn,
           endIn,
           dataOut_re,
           dataOut_im,
           startOut,
           endOut,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  input   startIn;
  input   endIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  startOut;
  output  endOut;
  output  validOut;


  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  reg signed [15:0] dataOut_re_1;  // sfix16_En14
  reg signed [15:0] dataOut_im_1;  // sfix16_En14
  reg  startOut_1;
  reg  endOut_1;
  reg  validOut_1;
  reg  active;
  reg signed [15:0] dataOutReg_re;  // sfix16_En14
  reg signed [15:0] dataOutReg_im;  // sfix16_En14
  reg  validOutReg;
  reg  startOutReg;
  reg  endOutReg;
  reg  active_next;
  reg signed [15:0] dataOutReg_next_re;  // sfix16_En14
  reg signed [15:0] dataOutReg_next_im;  // sfix16_En14
  reg  validOutReg_next;
  reg  startOutReg_next;
  reg  endOutReg_next;
  reg signed [15:0] dataOut_last_value_re;  // sfix16_En14
  reg signed [15:0] dataOut_last_value_im;  // sfix16_En14
  reg  startOut_last_value;
  reg  endOut_last_value;
  reg  validOut_last_value;
  reg  active_temp;


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : sample_discard_controller_process
      if (reset == 1'b1) begin
        active <= 1'b0;
        dataOutReg_re <= 16'sb0000000000000000;
        dataOutReg_im <= 16'sb0000000000000000;
        validOutReg <= 1'b0;
        startOutReg <= 1'b0;
        endOutReg <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          active <= active_next;
          dataOutReg_re <= dataOutReg_next_re;
          dataOutReg_im <= dataOutReg_next_im;
          validOutReg <= validOutReg_next;
          startOutReg <= startOutReg_next;
          endOutReg <= endOutReg_next;
        end
      end
    end

  always @(active, dataIn_im, dataIn_re, dataOutReg_im, dataOutReg_re, endIn, endOutReg,
       startIn, startOutReg, validIn, validOutReg) begin
    active_temp = active;
    startOutReg_next = startIn;
    endOutReg_next = endIn;
    if (startIn) begin
      active_temp = 1'b1;
    end
    if (active_temp) begin
      dataOutReg_next_re = dataIn_re;
      dataOutReg_next_im = dataIn_im;
      validOutReg_next = validIn;
    end
    else begin
      dataOutReg_next_re = 16'sb0000000000000000;
      dataOutReg_next_im = 16'sb0000000000000000;
      validOutReg_next = 1'b0;
    end
    if (endIn) begin
      endOutReg_next = active_temp;
      active_temp = 1'b0;
    end
    dataOut_re_1 = dataOutReg_re;
    dataOut_im_1 = dataOutReg_im;
    startOut_1 = startOutReg;
    endOut_1 = endOutReg;
    validOut_1 = validOutReg;
    active_next = active_temp;
  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        dataOut_last_value_re <= 16'sb0000000000000000;
        dataOut_last_value_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          dataOut_last_value_re <= dataOut_re;
          dataOut_last_value_im <= dataOut_im;
        end
      end
    end

  assign dataOut_re = (stateControl_2 == 1'b0 ? dataOut_last_value_re :
              dataOut_re_1);
  assign dataOut_im = (stateControl_2 == 1'b0 ? dataOut_last_value_im :
              dataOut_im_1);

  always @(posedge clk or posedge reset)
    begin : out1_bypass_process
      if (reset == 1'b1) begin
        startOut_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          startOut_last_value <= startOut;
        end
      end
    end

  assign startOut = (stateControl_2 == 1'b0 ? startOut_last_value :
              startOut_1);

  always @(posedge clk or posedge reset)
    begin : out2_bypass_process
      if (reset == 1'b1) begin
        endOut_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          endOut_last_value <= endOut;
        end
      end
    end

  assign endOut = (stateControl_2 == 1'b0 ? endOut_last_value :
              endOut_1);

  always @(posedge clk or posedge reset)
    begin : out3_bypass_process
      if (reset == 1'b1) begin
        validOut_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          validOut_last_value <= validOut;
        end
      end
    end

  assign validOut = (stateControl_2 == 1'b0 ? validOut_last_value :
              validOut_1);

endmodule  // sample_discard_controller

