// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/subFilter_block1.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter_block1
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/QPSK Tx/RRC Transmit Filter/RRC Filter/Filter/subFilter
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter_block1
          (clk,
           reset,
           enb_1_2_0,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           coefIn_16,
           dinRegVld,
           syncReset,
           dout_1_re);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [16:0] dinReg2_0_re;  // sfix17_En16
  input   signed [16:0] coefIn_0;  // sfix17_En16
  input   signed [16:0] coefIn_1;  // sfix17_En16
  input   signed [16:0] coefIn_2;  // sfix17_En16
  input   signed [16:0] coefIn_3;  // sfix17_En16
  input   signed [16:0] coefIn_4;  // sfix17_En16
  input   signed [16:0] coefIn_5;  // sfix17_En16
  input   signed [16:0] coefIn_6;  // sfix17_En16
  input   signed [16:0] coefIn_7;  // sfix17_En16
  input   signed [16:0] coefIn_8;  // sfix17_En16
  input   signed [16:0] coefIn_9;  // sfix17_En16
  input   signed [16:0] coefIn_10;  // sfix17_En16
  input   signed [16:0] coefIn_11;  // sfix17_En16
  input   signed [16:0] coefIn_12;  // sfix17_En16
  input   signed [16:0] coefIn_13;  // sfix17_En16
  input   signed [16:0] coefIn_14;  // sfix17_En16
  input   signed [16:0] coefIn_15;  // sfix17_En16
  input   signed [16:0] coefIn_16;  // sfix17_En16
  input   dinRegVld;
  input   syncReset;
  output  signed [16:0] dout_1_re;  // sfix17_En14


  reg  [12:0] intdelay_reg;  // ufix1 [13]
  wire vldShift;
  wire vldOutTmp;
  wire signed [47:0] addin;  // sfix48_En32
  wire signed [16:0] dinDly2;  // sfix17_En16
  reg signed [16:0] dinPreAdd;  // sfix17_En16
  wire signed [16:0] dinDly2_1;  // sfix17_En16
  wire signed [47:0] tapout;  // sfix48_En32
  wire signed [16:0] dinDly2_2;  // sfix17_En16
  wire signed [47:0] tapout_1;  // sfix48_En32
  wire signed [16:0] dinDly2_3;  // sfix17_En16
  wire signed [47:0] tapout_2;  // sfix48_En32
  wire signed [16:0] dinDly2_4;  // sfix17_En16
  wire signed [47:0] tapout_3;  // sfix48_En32
  wire signed [16:0] dinDly2_5;  // sfix17_En16
  wire signed [47:0] tapout_4;  // sfix48_En32
  wire signed [16:0] dinDly2_6;  // sfix17_En16
  wire signed [47:0] tapout_5;  // sfix48_En32
  wire signed [16:0] dinDly2_7;  // sfix17_En16
  wire signed [47:0] tapout_6;  // sfix48_En32
  wire signed [47:0] tapout_7;  // sfix48_En32
  wire signed [16:0] ZERO;  // sfix17_En16
  wire signed [16:0] ZERO_OUT;  // sfix17_En14
  wire signed [16:0] dinDly2deadOut;  // sfix17_En16
  wire signed [47:0] tapout_8;  // sfix48_En32
  wire signed [16:0] dout_cast;  // sfix17_En14
  wire signed [16:0] muxOut;  // sfix17_En14
  reg signed [16:0] dout_1_re_1;  // sfix17_En14


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg <= {13{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {13{1'b0}};
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= dinRegVld;
              intdelay_reg[32'sd12:32'sd1] <= intdelay_reg[32'sd11:32'sd0];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[12];

  assign vldOutTmp = dinRegVld & vldShift;

  assign addin = 48'sh000000000000;

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinPreAdd <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinPreAdd <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinPreAdd <= dinDly2;
            end
          end
        end
      end
    end

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_1 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinReg2_0_re),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_0),  // sfix17_En16
                                                                     .addin(addin),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_1),  // sfix17_En16
                                                                     .tapout(tapout)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_2 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_1),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_1),  // sfix17_En16
                                                                     .addin(tapout),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_2),  // sfix17_En16
                                                                     .tapout(tapout_1)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_3 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_2),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_2),  // sfix17_En16
                                                                     .addin(tapout_1),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_3),  // sfix17_En16
                                                                     .tapout(tapout_2)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_4 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_3),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_3),  // sfix17_En16
                                                                     .addin(tapout_2),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_4),  // sfix17_En16
                                                                     .tapout(tapout_3)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_5 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_4),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_4),  // sfix17_En16
                                                                     .addin(tapout_3),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_5),  // sfix17_En16
                                                                     .tapout(tapout_4)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_6 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_5),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_5),  // sfix17_En16
                                                                     .addin(tapout_4),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_6),  // sfix17_En16
                                                                     .tapout(tapout_5)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_7 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_6),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_6),  // sfix17_En16
                                                                     .addin(tapout_5),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2_7),  // sfix17_En16
                                                                     .tapout(tapout_6)  // sfix48_En32
                                                                     );

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_8 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2_7),  // sfix17_En16
                                                                     .dinPreAdd(dinPreAdd),  // sfix17_En16
                                                                     .coefIn_0(coefIn_7),  // sfix17_En16
                                                                     .addin(tapout_6),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2),  // sfix17_En16
                                                                     .tapout(tapout_7)  // sfix48_En32
                                                                     );

  assign ZERO = 17'sb00000000000000000;

  assign ZERO_OUT = 17'sb00000000000000000;

  FilterTapSystolicPreAddWvlIn_block u_FilterTap_9 (.clk(clk),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .dinReg2_0_re(dinDly2),  // sfix17_En16
                                                                     .dinPreAdd(ZERO),  // sfix17_En16
                                                                     .coefIn_0(coefIn_8),  // sfix17_En16
                                                                     .addin(tapout_7),  // sfix48_En32
                                                                     .dinRegVld(dinRegVld),
                                                                     .syncReset(syncReset),
                                                                     .dinDly2(dinDly2deadOut),  // sfix17_En16
                                                                     .tapout(tapout_8)  // sfix48_En32
                                                                     );

  assign dout_cast = tapout_8[34:18];

  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              dout_cast);

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dout_1_re_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 17'sb00000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end

  assign dout_1_re = dout_1_re_1;

endmodule  // subFilter_block1

