// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Subsystem1.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem1
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity 
// Estimation and Correction/Phase Ambiguity Estimator/Subsystem
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem1
          (In1,
           validIn,
           validOut);


  input   In1;
  input   validIn;
  output  validOut;


  wire Logical_Operator2_out1;
  wire Logical_Operator1_out1;


  assign Logical_Operator2_out1 =  ~ In1;

  assign Logical_Operator1_out1 = Logical_Operator2_out1 & validIn;

  assign validOut = Logical_Operator1_out1;

endmodule  // Subsystem1

