// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Symbol_Synchronizer.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Symbol_Synchronizer
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Symbol_Synchronizer
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           ss_prop_gain,
           ss_integ_gain,
           bfGridEn,
           dataOut_re,
           dataOut_im,
           validOut,
           beatobsRhCtr,
           beatobsPush,
           beatobsPop);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En12
  input   signed [15:0] dataIn_im;  // sfix16_En12
  input   validIn;
  input   [31:0] ss_prop_gain;  // uint32
  input   [31:0] ss_integ_gain;  // uint32
  input   bfGridEn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  validOut;
  output  [7:0] beatobsRhCtr;  // uint8
  output  [4:0] beatobsPush;  // ufix5
  output  [4:0] beatobsPop;  // ufix5


  reg signed [15:0] Integer_Delay1_out1_re;  // sfix16_En12
  reg signed [15:0] Integer_Delay1_out1_im;  // sfix16_En12
  wire stateControl;
  reg  stateControl_1;
  wire enb_1_2_0_gated;
  wire stateControl_3;
  reg  stateControl_4;
  wire enb_1_2_0_gated_1;
  wire stateControl_5;
  reg  stateControl_6;
  wire enb_1_2_0_gated_2;
  wire stateControl_7;
  reg  stateControl_8;
  wire enb_1_2_0_gated_3;
  wire stateControl_9;
  reg  stateControl_10;
  wire enb_1_2_0_gated_4;
  reg [31:0] ss_prop_gain_1;  // uint32
  reg [31:0] ss_integ_gain_1;  // uint32
  wire stateControl_11;
  reg  stateControl_12;
  wire enb_1_2_0_gated_5;
  wire stateControl_13;
  reg  stateControl_14;
  wire enb_1_2_0_gated_6;
  wire Underflow;
  reg  Integer_Delay3_out1;
  reg  [11:0] Delay5_reg;  // ufix1 [12]
  wire Delay5_out1;
  reg  Delay9_out1;
  wire signed [18:0] Interpolation_Filter_interpolant_re;  // sfix19_En12
  wire signed [18:0] Interpolation_Filter_interpolant_im;  // sfix19_En12
  reg signed [18:0] Delay8_out1_re;  // sfix19_En12
  reg signed [18:0] Delay8_out1_im;  // sfix19_En12
  wire signed [39:0] Gardner_TED_e;  // sfix40_En24
  reg signed [39:0] Delay3_out1;  // sfix40_En24
  wire signed [10:0] Loop_Filter_v;  // sfix11_En10
  reg signed [10:0] Delay4_out1;  // sfix11_En10
  wire signed [10:0] mu;  // sfix11_En10
  reg signed [10:0] Integer_Delay4_out1;  // sfix11_En10
  reg signed [18:0] Delay1_out1_re;  // sfix19_En12
  reg signed [18:0] Delay1_out1_im;  // sfix19_En12
  wire signed [15:0] Data_Type_Conversion4_out1_re;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion4_out1_im;  // sfix16_En14
  reg  Delay2_out1;
  reg  Integer_Delay2_out1;
  reg  [11:0] Delay7_reg;  // ufix1 [12]
  wire Delay7_out1;
  reg  Delay6_out1;
  wire signed [15:0] Rate_Handle_dataOut_re;  // sfix16_En14
  wire signed [15:0] Rate_Handle_dataOut_im;  // sfix16_En14
  wire Rate_Handle_validOut;
  wire [7:0] Rate_Handle_beatobsRhCtr;  // uint8
  wire [4:0] Rate_Handle_beatobsPush;  // ufix5
  wire [4:0] Rate_Handle_beatobsPop;  // ufix5


  always @(posedge clk or posedge reset)
    begin : Integer_Delay1_process
      if (reset == 1'b1) begin
        Integer_Delay1_out1_re <= 16'sb0000000000000000;
        Integer_Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Integer_Delay1_out1_re <= dataIn_re;
          Integer_Delay1_out1_im <= dataIn_im;
        end
      end
    end

  assign stateControl = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        stateControl_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_1 <= stateControl;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_1 && enb_1_2_0;

  assign stateControl_3 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_4 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_4 <= stateControl_3;
        end
      end
    end

  assign enb_1_2_0_gated_1 = stateControl_4 && enb_1_2_0;

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        stateControl_6 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_6 <= stateControl_5;
        end
      end
    end

  assign enb_1_2_0_gated_2 = stateControl_6 && enb_1_2_0;

  assign stateControl_7 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        stateControl_8 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_8 <= stateControl_7;
        end
      end
    end

  assign enb_1_2_0_gated_3 = stateControl_8 && enb_1_2_0;

  assign stateControl_9 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        stateControl_10 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_10 <= stateControl_9;
        end
      end
    end

  assign enb_1_2_0_gated_4 = stateControl_10 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        ss_prop_gain_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          ss_prop_gain_1 <= ss_prop_gain;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        ss_integ_gain_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          ss_integ_gain_1 <= ss_integ_gain;
        end
      end
    end

  assign stateControl_11 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        stateControl_12 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_12 <= stateControl_11;
        end
      end
    end

  assign enb_1_2_0_gated_5 = stateControl_12 && enb_1_2_0;

  assign stateControl_13 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch8_process
      if (reset == 1'b1) begin
        stateControl_14 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_14 <= stateControl_13;
        end
      end
    end

  assign enb_1_2_0_gated_6 = stateControl_14 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Integer_Delay3_process
      if (reset == 1'b1) begin
        Integer_Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated_1) begin
          Integer_Delay3_out1 <= Underflow;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_reg <= {12{1'b0}};
      end
      else begin
        if (enb_1_2_0_gated_2) begin
          Delay5_reg[0] <= Integer_Delay3_out1;
          Delay5_reg[32'sd11:32'sd1] <= Delay5_reg[32'sd10:32'sd0];
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[11];

  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated_3) begin
          Delay9_out1 <= Delay5_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1_re <= 19'sb0000000000000000000;
        Delay8_out1_im <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          Delay8_out1_re <= Interpolation_Filter_interpolant_re;
          Delay8_out1_im <= Interpolation_Filter_interpolant_im;
        end
      end
    end

  Gardner_TED u_Gardner_TED (.clk(clk),
                                              .reset(reset),
                                              .enb_1_2_0(enb_1_2_0),
                                              .data_re(Delay8_out1_re),  // sfix19_En12
                                              .data_im(Delay8_out1_im),  // sfix19_En12
                                              .strobe(Delay9_out1),
                                              .e(Gardner_TED_e)  // sfix40_En24
                                              );

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb_1_2_0_gated_4) begin
          Delay3_out1 <= Gardner_TED_e;
        end
      end
    end

  Loop_Filter_block1 u_Loop_Filter (.clk(clk),
                                                     .reset(reset),
                                                     .enb_1_2_0(enb_1_2_0),
                                                     .e(Delay3_out1),  // sfix40_En24
                                                     .ss_prop_gain(ss_prop_gain_1),  // uint32
                                                     .ss_integ_gain(ss_integ_gain_1),  // uint32
                                                     .v(Loop_Filter_v)  // sfix11_En10
                                                     );

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0_gated_5) begin
          Delay4_out1 <= Loop_Filter_v;
        end
      end
    end

  Interpolation_Control u_Interpolation_Control (.clk(clk),
                                                                  .reset(reset),
                                                                  .enb_1_2_0(enb_1_2_0),
                                                                  .Delta(Delay4_out1),  // sfix11_En10
                                                                  .mu(mu),  // sfix11_En10
                                                                  .Underflow(Underflow)
                                                                  );

  always @(posedge clk or posedge reset)
    begin : Integer_Delay4_process
      if (reset == 1'b1) begin
        Integer_Delay4_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0_gated_6) begin
          Integer_Delay4_out1 <= mu;
        end
      end
    end

  Interpolation_Filter u_Interpolation_Filter (.clk(clk),
                                                                .reset(reset),
                                                                .enb_1_2_0(enb_1_2_0),
                                                                .In_re(Integer_Delay1_out1_re),  // sfix16_En12
                                                                .In_im(Integer_Delay1_out1_im),  // sfix16_En12
                                                                .mu(Integer_Delay4_out1),  // sfix11_En10
                                                                .interpolant_re(Interpolation_Filter_interpolant_re),  // sfix19_En12
                                                                .interpolant_im(Interpolation_Filter_interpolant_im)  // sfix19_En12
                                                                );

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 19'sb0000000000000000000;
        Delay1_out1_im <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= Interpolation_Filter_interpolant_re;
          Delay1_out1_im <= Interpolation_Filter_interpolant_im;
        end
      end
    end

  assign Data_Type_Conversion4_out1_re = {Delay1_out1_re[13:0], 2'b00};
  assign Data_Type_Conversion4_out1_im = {Delay1_out1_im[13:0], 2'b00};

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Delay5_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Integer_Delay2_process
      if (reset == 1'b1) begin
        Integer_Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Integer_Delay2_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_reg <= {12{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_reg[0] <= Integer_Delay2_out1;
          Delay7_reg[32'sd11:32'sd1] <= Delay7_reg[32'sd10:32'sd0];
        end
      end
    end

  assign Delay7_out1 = Delay7_reg[11];

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_out1 <= Delay7_out1;
        end
      end
    end

  Rate_Handle u_Rate_Handle (.clk(clk),
                                              .reset(reset),
                                              .enb_1_2_0(enb_1_2_0),
                                              .dataIn_re(Data_Type_Conversion4_out1_re),  // sfix16_En14
                                              .dataIn_im(Data_Type_Conversion4_out1_im),  // sfix16_En14
                                              .strobe(Delay2_out1),
                                              .validIn(Delay6_out1),
                                              .bfGridEn(bfGridEn),
                                              .dataOut_re(Rate_Handle_dataOut_re),  // sfix16_En14
                                              .dataOut_im(Rate_Handle_dataOut_im),  // sfix16_En14
                                              .validOut(Rate_Handle_validOut),
                                              .beatobsRhCtr(Rate_Handle_beatobsRhCtr),  // uint8
                                              .beatobsPush(Rate_Handle_beatobsPush),  // ufix5
                                              .beatobsPop(Rate_Handle_beatobsPop)  // ufix5
                                              );

  assign dataOut_re = Rate_Handle_dataOut_re;

  assign dataOut_im = Rate_Handle_dataOut_im;

  assign validOut = Rate_Handle_validOut;

  assign beatobsRhCtr = Rate_Handle_beatobsRhCtr;

  assign beatobsPush = Rate_Handle_beatobsPush;

  assign beatobsPop = Rate_Handle_beatobsPop;

endmodule  // Symbol_Synchronizer

