// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/ThresholdLimiter.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ThresholdLimiter
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/ThresholdLimiter
// Hierarchy Level: 6
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ThresholdLimiter
          (x,
           y);


  input   signed [31:0] x;  // sfix32_En28
  output  signed [31:0] y;  // sfix32_En28




  // Apply a lower limit to the threshold.
  // Threshold is computed by summing across 63 samples.
  // Set lower limit to be equivalent of all 63 samples
  // having their LSB set to 1 and all others set to 0. 
  assign y = (x < 32'sb00000000001010001111010111000010 ? 32'sb00000000001010001111010111000010 :
              x);

endmodule  // ThresholdLimiter

