// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Timing_Adjust.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Timing_Adjust
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Timing 
// Adjus
// Hierarchy Level: 5
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Timing_Adjust
          (clk,
           reset,
           enb_1_2_0,
           timingOffset,
           timingOffsetValid,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut,
           SyncPulse,
           p1c_armed,
           p1c_taref,
           p1c_accoff);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   [13:0] timingOffset;  // ufix14
  input   timingOffsetValid;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  validOut;
  output  SyncPulse;
  output  p1c_armed;
  output  [13:0] p1c_taref;  // ufix14
  output  [13:0] p1c_accoff;  // ufix14


  reg signed [15:0] Delay4_out1_re;  // sfix16_En14
  reg signed [15:0] Delay4_out1_im;  // sfix16_En14
  reg  Delay3_out1;
  wire [13:0] count_step;  // ufix14
  wire [13:0] count_from;  // ufix14
  reg [13:0] timing_Reference_out1;  // ufix14
  wire [13:0] count;  // ufix14
  wire need_to_wrap;
  wire [13:0] count_value;  // ufix14
  wire [13:0] count_1;  // ufix14
  reg [13:0] Unit_Delay_Enabled_Synchronous3_out1;  // ufix14
  wire Relational_Operator_out1;
  wire stateControl_1;
  reg  stateControl_2;
  wire enb_1_2_0_gated;
  wire Logical_Operator2_out1;
  reg  Delay2_out1;
  reg  State_Register_out1;
  reg  Delay_out1;


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1_re <= 16'sb0000000000000000;
        Delay4_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1_re <= dataIn_re;
          Delay4_out1_im <= dataIn_im;
        end
      end
    end

  assign dataOut_re = Delay4_out1_re;

  assign dataOut_im = Delay4_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= validIn;
        end
      end
    end

  assign validOut = Delay3_out1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 12332
  assign count_step = 14'b00000000000001;

  assign count_from = 14'b00000000000000;

  assign count = timing_Reference_out1 + count_step;

  assign need_to_wrap = timing_Reference_out1 == 14'b11000000101100;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? timing_Reference_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : timing_Reference_process
      if (reset == 1'b1) begin
        timing_Reference_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          timing_Reference_out1 <= count_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous3_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous3_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb_1_2_0 && timingOffsetValid) begin
          Unit_Delay_Enabled_Synchronous3_out1 <= timingOffset;
        end
      end
    end

  assign Relational_Operator_out1 = timing_Reference_out1 == Unit_Delay_Enabled_Synchronous3_out1;

  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        stateControl_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          stateControl_2 <= stateControl_1;
        end
      end
    end

  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          Delay2_out1 <= Logical_Operator2_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : State_Register_process
      if (reset == 1'b1) begin
        State_Register_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (Delay2_out1 == 1'b1) begin
            State_Register_out1 <= 1'b0;
          end
          else begin
            if (timingOffsetValid) begin
              State_Register_out1 <= timingOffsetValid;
            end
          end
        end
      end
    end

  assign Logical_Operator2_out1 = State_Register_out1 & (validIn & Relational_Operator_out1);

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= Logical_Operator2_out1;
        end
      end
    end

  assign SyncPulse = Delay_out1;

  assign p1c_armed = State_Register_out1;

  assign p1c_taref = timing_Reference_out1;

  assign p1c_accoff = Unit_Delay_Enabled_Synchronous3_out1;

endmodule  // Timing_Adjust

