// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/TracebackUnit.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TracebackUnit
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/FEC Decoder Wrapper/VitGate/Viterbi/Traceback/TracebackUnit
// Hierarchy Level: 7
// Model version: 11.331
// 
// Traceback Decoding Unit
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TracebackUnit
          (clk,
           reset,
           enb_1_2_0,
           dec_in_0,
           dec_in_1,
           dec_in_2,
           dec_in_3,
           dec_in_4,
           dec_in_5,
           dec_in_6,
           dec_in_7,
           dec_in_8,
           dec_in_9,
           dec_in_10,
           dec_in_11,
           dec_in_12,
           dec_in_13,
           dec_in_14,
           dec_in_15,
           idx_in,
           tb_reset,
           dec_out_0,
           dec_out_1,
           dec_out_2,
           dec_out_3,
           dec_out_4,
           dec_out_5,
           dec_out_6,
           dec_out_7,
           dec_out_8,
           dec_out_9,
           dec_out_10,
           dec_out_11,
           dec_out_12,
           dec_out_13,
           dec_out_14,
           dec_out_15,
           idx_out);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   dec_in_0;  // ufix1
  input   dec_in_1;  // ufix1
  input   dec_in_2;  // ufix1
  input   dec_in_3;  // ufix1
  input   dec_in_4;  // ufix1
  input   dec_in_5;  // ufix1
  input   dec_in_6;  // ufix1
  input   dec_in_7;  // ufix1
  input   dec_in_8;  // ufix1
  input   dec_in_9;  // ufix1
  input   dec_in_10;  // ufix1
  input   dec_in_11;  // ufix1
  input   dec_in_12;  // ufix1
  input   dec_in_13;  // ufix1
  input   dec_in_14;  // ufix1
  input   dec_in_15;  // ufix1
  input   [3:0] idx_in;  // ufix4
  input   tb_reset;  // ufix1
  output  dec_out_0;  // ufix1
  output  dec_out_1;  // ufix1
  output  dec_out_2;  // ufix1
  output  dec_out_3;  // ufix1
  output  dec_out_4;  // ufix1
  output  dec_out_5;  // ufix1
  output  dec_out_6;  // ufix1
  output  dec_out_7;  // ufix1
  output  dec_out_8;  // ufix1
  output  dec_out_9;  // ufix1
  output  dec_out_10;  // ufix1
  output  dec_out_11;  // ufix1
  output  dec_out_12;  // ufix1
  output  dec_out_13;  // ufix1
  output  dec_out_14;  // ufix1
  output  dec_out_15;  // ufix1
  output  [3:0] idx_out;  // ufix4


  wire [15:0] dec_in;  // ufix1 [16]
  reg  [15:0] dec_out;  // ufix1 [16]
  wire [2:0] slicedidx;  // ufix3
  wire thread;  // ufix1


  assign dec_in[0] = dec_in_0;
  assign dec_in[1] = dec_in_1;
  assign dec_in[2] = dec_in_2;
  assign dec_in[3] = dec_in_3;
  assign dec_in[4] = dec_in_4;
  assign dec_in[5] = dec_in_5;
  assign dec_in[6] = dec_in_6;
  assign dec_in[7] = dec_in_7;
  assign dec_in[8] = dec_in_8;
  assign dec_in[9] = dec_in_9;
  assign dec_in[10] = dec_in_10;
  assign dec_in[11] = dec_in_11;
  assign dec_in[12] = dec_in_12;
  assign dec_in[13] = dec_in_13;
  assign dec_in[14] = dec_in_14;
  assign dec_in[15] = dec_in_15;

  always @(posedge clk or posedge reset)
    begin : decshiftRegister_process
      if (reset == 1'b1) begin
        dec_out <= {16{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          if (tb_reset == 1'b1) begin
            dec_out <= {16{1'b0}};
          end
          else begin
            dec_out <= dec_in;
          end
        end
      end
    end

  assign dec_out_0 = dec_out[0];

  assign dec_out_1 = dec_out[1];

  assign dec_out_2 = dec_out[2];

  assign dec_out_3 = dec_out[3];

  assign dec_out_4 = dec_out[4];

  assign dec_out_5 = dec_out[5];

  assign dec_out_6 = dec_out[6];

  assign dec_out_7 = dec_out[7];

  assign dec_out_8 = dec_out[8];

  assign dec_out_9 = dec_out[9];

  assign dec_out_10 = dec_out[10];

  assign dec_out_11 = dec_out[11];

  assign dec_out_12 = dec_out[12];

  assign dec_out_13 = dec_out[13];

  assign dec_out_14 = dec_out[14];

  assign dec_out_15 = dec_out[15];

  assign slicedidx = idx_in[2:0];

  // Decode the previous state based on current state and the decision branch
  assign thread = (idx_in == 4'b0000 ? dec_in[0] :
              (idx_in == 4'b0001 ? dec_in[1] :
              (idx_in == 4'b0010 ? dec_in[2] :
              (idx_in == 4'b0011 ? dec_in[3] :
              (idx_in == 4'b0100 ? dec_in[4] :
              (idx_in == 4'b0101 ? dec_in[5] :
              (idx_in == 4'b0110 ? dec_in[6] :
              (idx_in == 4'b0111 ? dec_in[7] :
              (idx_in == 4'b1000 ? dec_in[8] :
              (idx_in == 4'b1001 ? dec_in[9] :
              (idx_in == 4'b1010 ? dec_in[10] :
              (idx_in == 4'b1011 ? dec_in[11] :
              (idx_in == 4'b1100 ? dec_in[12] :
              (idx_in == 4'b1101 ? dec_in[13] :
              (idx_in == 4'b1110 ? dec_in[14] :
              dec_in[15])))))))))))))));

  assign idx_out = {slicedidx, thread};

endmodule  // TracebackUnit

