// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/TxInterleaveK5.v
// Created: 2026-08-21 23:31:05
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TxInterleaveK5
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Transmitter/Input Data/FEC Tx Encoder K5/TxInterleaveK5
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TxInterleaveK5
          (clk,
           reset,
           enb,
           enb_1_2_1,
           enb_1_2_0,
           codedPair_0,
           codedPair_1,
           infoValid,
           beatIdx,
           frameValid,
           frameStart,
           dataOut);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_2_1;
  input   enb_1_2_0;
  input   codedPair_0;  // boolean
  input   codedPair_1;  // boolean
  input   infoValid;
  input   [15:0] beatIdx;  // uint16
  input   frameValid;
  input   frameStart;
  output  dataOut;


  wire init_guard_true_1;
  reg  init_guard_true_2;
  wire tmpinit_guard_default;
  reg  frameValid_1;
  wire dataOut_1;
  reg  dataOut_2;
  wire s;
  reg  s_1;
  wire dataOut_3;
  wire [47:0] p102dataOut_1;  // boolean [48]
  reg  dataOut_4;
  wire s_2;
  wire [15:0] rr;  // uint16
  wire [15:0] rr_1;  // uint16
  wire [15:0] tmp;  // uint16
  wire [15:0] rr_2;  // uint16
  wire [16:0] p76rr_add_temp;  // ufix17
  wire [16:0] p76rr_1;  // ufix17
  wire rr_3;
  wire [15:0] tmp_1;  // uint16
  reg [15:0] rrow;  // uint16
  wire [15:0] tmp_2;  // uint16
  wire [15:0] tmp_3;  // uint16
  wire [15:0] cc;  // uint16
  wire [15:0] tmp_4;  // uint16
  wire [15:0] tmp_5;  // uint16
  wire [16:0] p74tmp_add_temp;  // ufix17
  wire [16:0] p74tmp_1;  // ufix17
  wire [15:0] tmp_6;  // uint16
  reg [15:0] rcol;  // uint16
  wire [15:0] tmp_7;  // uint16
  wire [15:0] tmp_8;  // uint16
  wire [15:0] perm;  // uint16
  wire [31:0] p75perm_add_cast;  // ufix32
  wire [15:0] p75perm_add_cast_1;  // uint16
  wire [16:0] p75perm_add_cast_2;  // ufix17
  wire [16:0] p75perm_add_temp;  // ufix17
  wire [16:0] p75perm_1;  // ufix17
  wire perm_1;
  reg  perm_2;
  reg  rdBank;
  wire tmp_9;
  wire tmp_10;
  wire tmp_11;
  reg  counterSig;  // ufix1
  wire v0;  // ufix1
  wire signed [31:0] s_3;  // int32
  wire [15:0] w;  // uint16
  wire [15:0] tmp_12;  // uint16
  wire [15:0] tmp_13;  // uint16
  wire signed [31:0] p59tmp_add_temp;  // int32
  wire signed [31:0] p59tmp_1;  // int32
  wire [15:0] tmp_14;  // uint16
  wire [15:0] tmp_15;  // uint16
  wire tmp_16;
  wire tmp_17;
  wire [15:0] tmp_18;  // uint16
  wire [15:0] tmp_19;  // uint16
  reg [15:0] wptr;  // uint16
  wire [15:0] tmp_20;  // uint16
  wire [1:0] codedPair;  // boolean [2]
  wire signed [7:0] s_4;  // int8
  wire v0_1;  // ufix1
  wire tmp_21;  // ufix1
  wire tmp_22;  // ufix1
  wire tmp_23;  // ufix1
  wire wr_data_overclock2_0;  // ufix1
  wire v1;  // ufix1
  wire signed [7:0] s_5;  // int8
  wire v1_1;  // ufix1
  wire tmp_24;  // ufix1
  wire tmp_25;  // ufix1
  wire tmp_26;  // ufix1
  wire wr_data_overclock2_1;  // ufix1
  wire [15:0] wr0;  // uint16
  wire [15:0] tmp_27;  // uint16
  wire [15:0] tmp_28;  // uint16
  wire [15:0] tmp_29;  // uint16
  wire signed [31:0] tmp_30;  // int32
  wire [14:0] indexLogic_fixptsig;  // ufix15
  wire [14:0] wr_addr_overclock2_0;  // ufix15
  wire [15:0] wr1;  // uint16
  wire [15:0] tmp_31;  // uint16
  wire [15:0] tmp_32;  // uint16
  wire [15:0] tmp_33;  // uint16
  wire signed [31:0] tmp_34;  // int32
  wire [14:0] indexLogic_fixptsig_1;  // ufix15
  wire [14:0] wr_addr_overclock2_1;  // ufix15
  wire wr_data;  // ufix1
  wire [14:0] wr_addr;  // ufix15
  wire doW0;
  wire doW0_1;
  wire tmp_35;
  wire tmp_36;
  wire tmp_37;
  wire sel;
  wire sel_1;
  wire s_6;
  wire sel_2;
  wire sel_2_1;
  wire ramA_ram_wr_en_sig_overclock2_0;
  wire doW1;
  wire doW1_1;
  wire tmp_38;
  wire tmp_39;
  wire tmp_40;
  wire sel_3;
  wire sel_4;
  wire s_7;
  wire sel_2_2;
  wire sel_2_3;
  wire ramA_ram_wr_en_sig_overclock2_1;
  wire signed [31:0] tmp_41;  // int32
  wire [14:0] indexLogic_fixptsig_2;  // ufix15
  wire [14:0] rd_addr_overclock2_0;  // ufix15
  wire [14:0] rd_addr_overclock2_1;  // ufix15
  wire ramA_ram_wr_en_sig;
  wire [14:0] rd_addr;  // ufix15
  wire rd_data;  // ufix1
  reg [7:0] sel_5;  // ufix8
  reg [7:0] sel_6;  // ufix8
  reg  [1:0] ramA_ram_demux_yreg;  // ufix1 [2]
  wire [1:0] ramA_ram_demux_yreg_next;  // ufix1 [2]
  wire signed [31:0] ramA_ram_demux_ctr1;  // int32
  wire [1:0] ramA_ram_demux_ytmp;  // ufix1 [2]
  wire signed [31:0] ramA_ram_demux_1;  // int32
  wire [1:0] rd_data_overclock2;  // ufix1 [2]
  wire wr_data_overclock2_0_1;  // ufix1
  wire wr_data_overclock2_1_1;  // ufix1
  wire signed [31:0] tmp_42;  // int32
  wire [14:0] indexLogic_fixptsig_3;  // ufix15
  wire [14:0] wr_addr_overclock2_0_1;  // ufix15
  wire signed [31:0] tmp_43;  // int32
  wire [14:0] indexLogic_fixptsig_4;  // ufix15
  wire [14:0] wr_addr_overclock2_1_1;  // ufix15
  wire wr_data_1;  // ufix1
  wire [14:0] wr_addr_1;  // ufix15
  wire sel_7;
  wire s_8;
  wire sel_8;
  wire sel_2_4;
  wire sel_2_5;
  wire ramB_ram_wr_en_sig_overclock2_0;
  wire sel_9;
  wire s_9;
  wire sel_10;
  wire sel_2_6;
  wire sel_2_7;
  wire ramB_ram_wr_en_sig_overclock2_1;
  wire signed [31:0] tmp_44;  // int32
  wire [14:0] indexLogic_fixptsig_5;  // ufix15
  wire [14:0] rd_addr_overclock2_0_1;  // ufix15
  wire [14:0] rd_addr_overclock2_1_1;  // ufix15
  wire ramB_ram_wr_en_sig;
  wire [14:0] rd_addr_1;  // ufix15
  wire rd_data_1;  // ufix1
  reg [7:0] sel_11;  // ufix8
  reg  [1:0] ramB_ram_demux_yreg;  // ufix1 [2]
  wire [1:0] ramB_ram_demux_yreg_next;  // ufix1 [2]
  wire signed [31:0] ramB_ram_demux_ctr1;  // int32
  wire [1:0] ramB_ram_demux_ytmp;  // ufix1 [2]
  wire signed [31:0] ramB_ram_demux_1;  // int32
  wire [1:0] rd_data_overclock2_1;  // ufix1 [2]
  reg  tmp_45;
  reg  [1:0] rd_data_overclock2_downsample2_bypass_reg;  // ufix1 [2]
  wire [1:0] rd_data_overclock2_2;  // ufix1 [2]
  wire ramA;  // ufix1
  wire dataOut_5;
  reg  [1:0] rd_data_overclock2_downsample2_bypass_reg_1;  // ufix1 [2]
  wire [1:0] rd_data_overclock2_3;  // ufix1 [2]
  wire ramB;  // ufix1
  wire dataOut_6;
  wire tmp_46;
  wire tmp_47;
  wire tmp_48;
  wire tmp_49;
  wire tmp_50;


  assign init_guard_true_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : matching_delays_process
      if (reset == 1'b1) begin
        init_guard_true_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          init_guard_true_2 <= init_guard_true_1;
        end
      end
    end

  assign tmpinit_guard_default = 1'b0;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        frameValid_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          frameValid_1 <= frameValid;
        end
      end
    end

  assign dataOut_1 = 1'b0;

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        dataOut_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          dataOut_2 <= dataOut_1;
        end
      end
    end

  assign s = beatIdx < 16'd24592;

  always @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        s_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          s_1 <= s;
        end
      end
    end

  assign p102dataOut_1[0] = 1'b1;
  assign p102dataOut_1[1] = 1'b1;
  assign p102dataOut_1[2] = 1'b1;
  assign p102dataOut_1[3] = 1'b1;
  assign p102dataOut_1[4] = 1'b1;
  assign p102dataOut_1[5] = 1'b1;
  assign p102dataOut_1[6] = 1'b1;
  assign p102dataOut_1[7] = 1'b1;
  assign p102dataOut_1[8] = 1'b1;
  assign p102dataOut_1[9] = 1'b0;
  assign p102dataOut_1[10] = 1'b0;
  assign p102dataOut_1[11] = 1'b0;
  assign p102dataOut_1[12] = 1'b0;
  assign p102dataOut_1[13] = 1'b0;
  assign p102dataOut_1[14] = 1'b1;
  assign p102dataOut_1[15] = 1'b1;
  assign p102dataOut_1[16] = 1'b1;
  assign p102dataOut_1[17] = 1'b1;
  assign p102dataOut_1[18] = 1'b0;
  assign p102dataOut_1[19] = 1'b1;
  assign p102dataOut_1[20] = 1'b1;
  assign p102dataOut_1[21] = 1'b1;
  assign p102dataOut_1[22] = 1'b1;
  assign p102dataOut_1[23] = 1'b1;
  assign p102dataOut_1[24] = 1'b0;
  assign p102dataOut_1[25] = 1'b0;
  assign p102dataOut_1[26] = 1'b0;
  assign p102dataOut_1[27] = 1'b1;
  assign p102dataOut_1[28] = 1'b0;
  assign p102dataOut_1[29] = 1'b1;
  assign p102dataOut_1[30] = 1'b1;
  assign p102dataOut_1[31] = 1'b1;
  assign p102dataOut_1[32] = 1'b0;
  assign p102dataOut_1[33] = 1'b0;
  assign p102dataOut_1[34] = 1'b1;
  assign p102dataOut_1[35] = 1'b1;
  assign p102dataOut_1[36] = 1'b0;
  assign p102dataOut_1[37] = 1'b0;
  assign p102dataOut_1[38] = 1'b1;
  assign p102dataOut_1[39] = 1'b0;
  assign p102dataOut_1[40] = 1'b0;
  assign p102dataOut_1[41] = 1'b0;
  assign p102dataOut_1[42] = 1'b0;
  assign p102dataOut_1[43] = 1'b0;
  assign p102dataOut_1[44] = 1'b1;
  assign p102dataOut_1[45] = 1'b0;
  assign p102dataOut_1[46] = 1'b0;
  assign p102dataOut_1[47] = 1'b1;
  assign dataOut_3 = p102dataOut_1[$signed({1'b0, beatIdx}) - 32'sd24592];

  always @(posedge clk or posedge reset)
    begin : delayMatch_2_process
      if (reset == 1'b1) begin
        dataOut_4 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          dataOut_4 <= dataOut_3;
        end
      end
    end

  assign s_2 = beatIdx == 16'd0;

  assign rr = 16'd0;

  assign rr_1 = 16'd0;

  assign p76rr_1 = {1'b0, tmp};
  assign p76rr_add_temp = p76rr_1 + 17'b00000000000000001;
  assign rr_2 = (p76rr_add_temp[16] != 1'b0 ? 16'b1111111111111111 :
              p76rr_add_temp[15:0]);

  assign rr_3 = rr_2 == 16'd1537;

  assign tmp_1 = (rr_3 == 1'b0 ? rr_2 :
              rr);

  assign tmp_2 = (s == 1'b0 ? rrow :
              tmp_1);

  assign tmp_3 = (frameValid == 1'b0 ? rrow :
              tmp_2);

  always @(posedge clk or posedge reset)
    begin : rrow_reg_process
      if (reset == 1'b1) begin
        rrow <= 16'b0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          rrow <= tmp_3;
        end
      end
    end

  assign tmp = (s_2 == 1'b0 ? rrow :
              rr_1);

  assign cc = 16'd0;

  assign p74tmp_1 = {1'b0, tmp_4};
  assign p74tmp_add_temp = p74tmp_1 + 17'b00000000000000001;
  assign tmp_5 = (p74tmp_add_temp[16] != 1'b0 ? 16'b1111111111111111 :
              p74tmp_add_temp[15:0]);

  assign tmp_6 = (rr_3 == 1'b0 ? tmp_4 :
              tmp_5);

  assign tmp_7 = (s == 1'b0 ? rcol :
              tmp_6);

  assign tmp_8 = (frameValid == 1'b0 ? rcol :
              tmp_7);

  always @(posedge clk or posedge reset)
    begin : rcol_reg_process
      if (reset == 1'b1) begin
        rcol <= 16'b0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          rcol <= tmp_8;
        end
      end
    end

  assign tmp_4 = (s_2 == 1'b0 ? rcol :
              cc);

  assign p75perm_add_cast = {12'b0, {tmp, 4'b0000}};
  assign p75perm_add_cast_1 = (p75perm_add_cast[31:16] != 16'b0000000000000000 ? 16'b1111111111111111 :
              p75perm_add_cast[15:0]);
  assign p75perm_add_cast_2 = {1'b0, p75perm_add_cast_1};
  assign p75perm_1 = {1'b0, tmp_4};
  assign p75perm_add_temp = p75perm_add_cast_2 + p75perm_1;
  assign perm = (p75perm_add_temp[16] != 1'b0 ? 16'b1111111111111111 :
              p75perm_add_temp[15:0]);

  assign perm_1 = perm < 16'd24592;

  always @(posedge clk or posedge reset)
    begin : delayMatch_3_process
      if (reset == 1'b1) begin
        perm_2 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          perm_2 <= perm_1;
        end
      end
    end

  // ---- WRITE side: two coded bits per encoder-advance beat ----
  // arithmetic derived the address from beatIdx alone and needed no such reset).
  // frame to re-seed the row/col counters (the old stateless per-beat address
  // precondition: bit-exactness requires a contiguous beatIdx hitting 0 once per
  // PN9 filler, beats CODED..2239
  // per in-range beat -- replaces the old per-beat divide-by-ROWS. No divide.
  // incremental counters, reset on beatIdx==0, advancing +1 row with col carry
  // divisionless read address: rr (row 0..ROWS-1) / cc (col 0..COLS-1) are
  // ---- READ side (previous frame, opposite bank), legacy perm r*COLS+c ----
  assign tmp_9 =  ! rdBank;

  assign tmp_11 = (frameValid == 1'b0 ? rdBank :
              tmp_10);

  always @(posedge clk or posedge reset)
    begin : rdBank_reg_process
      if (reset == 1'b1) begin
        rdBank <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          rdBank <= tmp_11;
        end
      end
    end

  assign tmp_10 = (frameStart == 1'b0 ? rdBank :
              tmp_9);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : ctr_0_1_process
      if (reset == 1'b1) begin
        counterSig <= 1'b0;
      end
      else begin
        if (enb) begin
          counterSig <=  ~ counterSig;
        end
      end
    end

  assign v0 = 1'b0;

  assign s_3 = 32'sd1;

  // 64-bit PN9 filler (T8 fix 6bcaa62)
  assign w = 16'd0;

  assign p59tmp_1 = {16'b0, tmp_12};
  assign p59tmp_add_temp = p59tmp_1 + s_3;
  assign tmp_13 = p59tmp_add_temp[15:0];

  assign tmp_15 = tmp_14 + 16'd1;

  assign tmp_12 = (tmp_16 == 1'b0 ? tmp_14 :
              tmp_15);

  assign tmp_17 = tmp_12 < 16'd24592;

  assign tmp_18 = (tmp_17 == 1'b0 ? tmp_12 :
              tmp_13);

  assign tmp_19 = (infoValid == 1'b0 ? tmp_14 :
              tmp_18);

  assign tmp_20 = (frameValid == 1'b0 ? wptr :
              tmp_19);

  always @(posedge clk or posedge reset)
    begin : wptr_reg_process
      if (reset == 1'b1) begin
        wptr <= 16'b0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          wptr <= tmp_20;
        end
      end
    end

  assign tmp_14 = (frameStart == 1'b0 ? wptr :
              w);

  assign tmp_16 = tmp_14 < 16'd24592;

  assign codedPair[0] = codedPair_0;
  assign codedPair[1] = codedPair_1;

  assign s_4 = {7'b0, codedPair[0]};

  assign v0_1 = s_4 != 8'sd0;

  assign tmp_21 = (tmp_16 == 1'b0 ? v0 :
              v0_1);

  assign tmp_22 = (infoValid == 1'b0 ? v0 :
              tmp_21);

  assign tmp_23 = (frameValid == 1'b0 ? v0 :
              tmp_22);

  assign wr_data_overclock2_0 = tmp_23;

  assign v1 = 1'b0;

  assign s_5 = {7'b0, codedPair[1]};

  assign v1_1 = s_5 != 8'sd0;

  assign tmp_24 = (tmp_17 == 1'b0 ? v1 :
              v1_1);

  assign tmp_25 = (infoValid == 1'b0 ? v1 :
              tmp_24);

  assign tmp_26 = (frameValid == 1'b0 ? v1 :
              tmp_25);

  assign wr_data_overclock2_1 = tmp_26;

  assign wr0 = 16'd0;

  assign tmp_27 = (tmp_16 == 1'b0 ? wr0 :
              tmp_14);

  assign tmp_28 = (infoValid == 1'b0 ? wr0 :
              tmp_27);

  assign tmp_29 = (frameValid == 1'b0 ? wr0 :
              tmp_28);

  assign tmp_30 = {16'b0, tmp_29};

  assign indexLogic_fixptsig = tmp_30[14:0];

  assign wr_addr_overclock2_0 = indexLogic_fixptsig;

  assign wr1 = 16'd0;

  assign tmp_31 = (tmp_17 == 1'b0 ? wr1 :
              tmp_12);

  assign tmp_32 = (infoValid == 1'b0 ? wr1 :
              tmp_31);

  assign tmp_33 = (frameValid == 1'b0 ? wr1 :
              tmp_32);

  assign tmp_34 = {16'b0, tmp_33};

  assign indexLogic_fixptsig_1 = tmp_34[14:0];

  assign wr_addr_overclock2_1 = indexLogic_fixptsig_1;

  assign wr_data = (counterSig == 1'b0 ? wr_data_overclock2_0 :
              wr_data_overclock2_1);

  assign wr_addr = (counterSig == 1'b0 ? wr_addr_overclock2_0 :
              wr_addr_overclock2_1);

  assign doW0 = 1'b0;

  assign doW0_1 = 1'b1;

  assign tmp_35 = (tmp_16 == 1'b0 ? doW0 :
              doW0_1);

  assign tmp_36 = (infoValid == 1'b0 ? doW0 :
              tmp_35);

  assign tmp_37 = (frameValid == 1'b0 ? doW0 :
              tmp_36);

  assign sel = 1'b0;

  // ---- persist state last (write bank = opposite of read bank) ----
  assign sel_1 = 1'b0;

  assign s_6 = 1'b1;

  assign sel_2 = (tmp_11 == 1'b0 ? sel_1 :
              s_6);

  assign sel_2_1 = (tmp_37 == 1'b0 ? sel :
              sel_2);

  assign ramA_ram_wr_en_sig_overclock2_0 = sel_2_1;

  assign doW1 = 1'b0;

  assign doW1_1 = 1'b1;

  assign tmp_38 = (tmp_17 == 1'b0 ? doW1 :
              doW1_1);

  assign tmp_39 = (infoValid == 1'b0 ? doW1 :
              tmp_38);

  assign tmp_40 = (frameValid == 1'b0 ? doW1 :
              tmp_39);

  assign sel_3 = 1'b0;

  assign sel_4 = 1'b0;

  assign s_7 = 1'b1;

  assign sel_2_2 = (tmp_11 == 1'b0 ? sel_4 :
              s_7);

  assign sel_2_3 = (tmp_40 == 1'b0 ? sel_3 :
              sel_2_2);

  assign ramA_ram_wr_en_sig_overclock2_1 = sel_2_3;

  assign tmp_41 = {16'b0, perm};

  assign indexLogic_fixptsig_2 = tmp_41[14:0];

  assign rd_addr_overclock2_0 = indexLogic_fixptsig_2;

  assign rd_addr_overclock2_1 = indexLogic_fixptsig_2;

  assign ramA_ram_wr_en_sig = (counterSig == 1'b0 ? ramA_ram_wr_en_sig_overclock2_0 :
              ramA_ram_wr_en_sig_overclock2_1);

  assign rd_addr = (counterSig == 1'b0 ? rd_addr_overclock2_0 :
              rd_addr_overclock2_1);

  SimpleDualPortRAM_singlebit #(.AddrWidth(15),
                                                 .DataWidth(1)
                                                 )
                                               u_ramA_ram (.clk(clk),
                                                           .enb(enb),
                                                           .wr_din(wr_data),  // ufix1
                                                           .wr_addr(wr_addr),
                                                           .wr_en(ramA_ram_wr_en_sig),
                                                           .rd_addr(rd_addr),
                                                           .dout(rd_data)  // ufix1
                                                           );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : c_process
      if (reset == 1'b1) begin
        sel_5 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (sel_5 >= 8'b00000001) begin
            sel_5 <= 8'b00000000;
          end
          else begin
            sel_5 <= sel_5 + 8'b00000001;
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch_4_process
      if (reset == 1'b1) begin
        sel_6 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          sel_6 <= sel_5;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : ramA_ram_demux_process
      if (reset == 1'b1) begin
        ramA_ram_demux_yreg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          ramA_ram_demux_yreg <= ramA_ram_demux_yreg_next;
        end
      end
    end

  assign ramA_ram_demux_1 = {24'b0, sel_6};
  assign ramA_ram_demux_ctr1 = ramA_ram_demux_1 + 32'sd1;
  assign ramA_ram_demux_ytmp[0] = (ramA_ram_demux_ctr1 == 32'sd1 ? rd_data :
              ramA_ram_demux_yreg[0]);
  assign ramA_ram_demux_ytmp[1] = (ramA_ram_demux_ctr1 == 32'sd2 ? rd_data :
              ramA_ram_demux_yreg[1]);
  assign ramA_ram_demux_yreg_next[0] = ramA_ram_demux_ytmp[0];
  assign rd_data_overclock2[0] = ramA_ram_demux_ytmp[0];
  assign ramA_ram_demux_yreg_next[1] = ramA_ram_demux_ytmp[1];
  assign rd_data_overclock2[1] = ramA_ram_demux_ytmp[1];

  assign wr_data_overclock2_0_1 = tmp_23;

  assign wr_data_overclock2_1_1 = tmp_26;

  assign tmp_42 = {16'b0, tmp_29};

  assign indexLogic_fixptsig_3 = tmp_42[14:0];

  assign wr_addr_overclock2_0_1 = indexLogic_fixptsig_3;

  assign tmp_43 = {16'b0, tmp_33};

  assign indexLogic_fixptsig_4 = tmp_43[14:0];

  assign wr_addr_overclock2_1_1 = indexLogic_fixptsig_4;

  assign wr_data_1 = (counterSig == 1'b0 ? wr_data_overclock2_0_1 :
              wr_data_overclock2_1_1);

  assign wr_addr_1 = (counterSig == 1'b0 ? wr_addr_overclock2_0_1 :
              wr_addr_overclock2_1_1);

  assign sel_7 = 1'b0;

  assign s_8 = 1'b1;

  assign sel_8 = 1'b0;

  assign sel_2_4 = (tmp_11 == 1'b0 ? s_8 :
              sel_8);

  assign sel_2_5 = (tmp_37 == 1'b0 ? sel_7 :
              sel_2_4);

  assign ramB_ram_wr_en_sig_overclock2_0 = sel_2_5;

  assign sel_9 = 1'b0;

  assign s_9 = 1'b1;

  assign sel_10 = 1'b0;

  assign sel_2_6 = (tmp_11 == 1'b0 ? s_9 :
              sel_10);

  assign sel_2_7 = (tmp_40 == 1'b0 ? sel_9 :
              sel_2_6);

  assign ramB_ram_wr_en_sig_overclock2_1 = sel_2_7;

  assign tmp_44 = {16'b0, perm};

  assign indexLogic_fixptsig_5 = tmp_44[14:0];

  assign rd_addr_overclock2_0_1 = indexLogic_fixptsig_5;

  assign rd_addr_overclock2_1_1 = indexLogic_fixptsig_5;

  assign ramB_ram_wr_en_sig = (counterSig == 1'b0 ? ramB_ram_wr_en_sig_overclock2_0 :
              ramB_ram_wr_en_sig_overclock2_1);

  assign rd_addr_1 = (counterSig == 1'b0 ? rd_addr_overclock2_0_1 :
              rd_addr_overclock2_1_1);

  SimpleDualPortRAM_singlebit #(.AddrWidth(15),
                                                 .DataWidth(1)
                                                 )
                                               u_ramB_ram (.clk(clk),
                                                           .enb(enb),
                                                           .wr_din(wr_data_1),  // ufix1
                                                           .wr_addr(wr_addr_1),
                                                           .wr_en(ramB_ram_wr_en_sig),
                                                           .rd_addr(rd_addr_1),
                                                           .dout(rd_data_1)  // ufix1
                                                           );

  always @(posedge clk or posedge reset)
    begin : delayMatch_5_process
      if (reset == 1'b1) begin
        sel_11 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          sel_11 <= sel_5;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : ramB_ram_demux_process
      if (reset == 1'b1) begin
        ramB_ram_demux_yreg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          ramB_ram_demux_yreg <= ramB_ram_demux_yreg_next;
        end
      end
    end

  assign ramB_ram_demux_1 = {24'b0, sel_11};
  assign ramB_ram_demux_ctr1 = ramB_ram_demux_1 + 32'sd1;
  assign ramB_ram_demux_ytmp[0] = (ramB_ram_demux_ctr1 == 32'sd1 ? rd_data_1 :
              ramB_ram_demux_yreg[0]);
  assign ramB_ram_demux_ytmp[1] = (ramB_ram_demux_ctr1 == 32'sd2 ? rd_data_1 :
              ramB_ram_demux_yreg[1]);
  assign ramB_ram_demux_yreg_next[0] = ramB_ram_demux_ytmp[0];
  assign rd_data_overclock2_1[0] = ramB_ram_demux_ytmp[0];
  assign ramB_ram_demux_yreg_next[1] = ramB_ram_demux_ytmp[1];
  assign rd_data_overclock2_1[1] = ramB_ram_demux_ytmp[1];

  always @(posedge clk or posedge reset)
    begin : delayMatch_6_process
      if (reset == 1'b1) begin
        tmp_45 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          tmp_45 <= tmp_10;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rd_data_overclock2_downsample2_bypass_process
      if (reset == 1'b1) begin
        rd_data_overclock2_downsample2_bypass_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_1) begin
          rd_data_overclock2_downsample2_bypass_reg <= rd_data_overclock2;
        end
      end
    end

  assign rd_data_overclock2_2 = (enb_1_2_1 == 1'b1 ? rd_data_overclock2 :
              rd_data_overclock2_downsample2_bypass_reg);

  assign ramA = rd_data_overclock2_2[0];

  assign dataOut_5 = ramA != 1'b0;

  always @(posedge clk or posedge reset)
    begin : rd_data_overclock2_downsample2_bypass_1_process
      if (reset == 1'b1) begin
        rd_data_overclock2_downsample2_bypass_reg_1 <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_1) begin
          rd_data_overclock2_downsample2_bypass_reg_1 <= rd_data_overclock2_1;
        end
      end
    end

  assign rd_data_overclock2_3 = (enb_1_2_1 == 1'b1 ? rd_data_overclock2_1 :
              rd_data_overclock2_downsample2_bypass_reg_1);

  assign ramB = rd_data_overclock2_3[0];

  assign dataOut_6 = ramB != 1'b0;

  assign tmp_46 = (tmp_45 == 1'b0 ? dataOut_5 :
              dataOut_6);

  assign tmp_47 = (perm_2 == 1'b0 ? dataOut_2 :
              tmp_46);

  assign tmp_48 = (s_1 == 1'b0 ? dataOut_4 :
              tmp_47);

  assign tmp_49 = (frameValid_1 == 1'b0 ? dataOut_2 :
              tmp_48);

  assign tmp_50 = (init_guard_true_2 == 1'b0 ? tmpinit_guard_default :
              tmp_49);

  assign dataOut = tmp_50;

endmodule  // TxInterleaveK5

