// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/TxRxCompo_ip_dut.v
// Created: 2026-08-21 23:32:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TxRxCompo_ip_dut
// Source Path: TxRxCompo_ip/TxRxCompo_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TxRxCompo_ip_dut
          (clk,
           reset,
           dut_enable,
           adc_validIn,
           adc_dataInI,
           adc_dataInQ,
           rstCS,
           iq_debug_mux,
           rx_input_select,
           host_txI,
           host_txQ,
           host_txValid,
           tx_source_select,
           skip_count,
           byte_data,
           byte_valid,
           tx_data_source,
           byte_first,
           byte_rx_ready,
           cs_prop_gain,
           cs_integ_gain,
           ss_prop_gain,
           ss_integ_gain,
           agc_loop_gain,
           cfo_threshold,
           framestat_pop,
           fixctl,
           ce_out_0,
           ce_out_1,
           count_out,
           packets_out,
           bit_errors_out,
           debugI,
           debugQ,
           debugValid,
           debugI1,
           debugQ1,
           tx_dataOutI,
           tx_dataOutQ,
           tx_validOut,
           cnt_descr_in,
           cnt_frame_start,
           cnt_vit_reset,
           cnt_deint_valid,
           cnt_dec_bits,
           cnt_bist_start,
           dbg_sentinel,
           cap_in,
           cap_deint,
           cap_out,
           cap_cad,
           rstcs_count,
           cfc_est,
           byte_ready,
           byte_rx_data,
           byte_rx_valid,
           byte_rx_last,
           byte_rx_user,
           byte_fifo_ovf,
           framestat_head_lo,
           framestat_head_hi,
           framestat_stat,
           framestat_wordcnt,
           beatfix_viol_count,
           beatfix_viol_latch);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   adc_validIn;  // ufix1
  input   signed [15:0] adc_dataInI;  // sfix16
  input   signed [15:0] adc_dataInQ;  // sfix16
  input   rstCS;  // ufix1
  input   [31:0] iq_debug_mux;  // ufix32
  input   rx_input_select;  // ufix1
  input   signed [15:0] host_txI;  // sfix16
  input   signed [15:0] host_txQ;  // sfix16
  input   host_txValid;  // ufix1
  input   [31:0] tx_source_select;  // ufix32
  input   [31:0] skip_count;  // ufix32
  input   [63:0] byte_data;  // ufix64
  input   byte_valid;  // ufix1
  input   [31:0] tx_data_source;  // ufix32
  input   byte_first;  // ufix1
  input   byte_rx_ready;  // ufix1
  input   [31:0] cs_prop_gain;  // ufix32
  input   [31:0] cs_integ_gain;  // ufix32
  input   [31:0] ss_prop_gain;  // ufix32
  input   [31:0] ss_integ_gain;  // ufix32
  input   [31:0] agc_loop_gain;  // ufix32
  input   [31:0] cfo_threshold;  // ufix32
  input   [31:0] framestat_pop;  // ufix32
  input   [31:0] fixctl;  // ufix32
  output  ce_out_0;  // ufix1
  output  ce_out_1;  // ufix1
  output  [31:0] count_out;  // ufix32
  output  [31:0] packets_out;  // ufix32
  output  [31:0] bit_errors_out;  // ufix32
  output  signed [15:0] debugI;  // sfix16
  output  signed [15:0] debugQ;  // sfix16
  output  debugValid;  // ufix1
  output  signed [15:0] debugI1;  // sfix16
  output  signed [15:0] debugQ1;  // sfix16
  output  signed [15:0] tx_dataOutI;  // sfix16
  output  signed [15:0] tx_dataOutQ;  // sfix16
  output  tx_validOut;  // ufix1
  output  [31:0] cnt_descr_in;  // ufix32
  output  [31:0] cnt_frame_start;  // ufix32
  output  [31:0] cnt_vit_reset;  // ufix32
  output  [31:0] cnt_deint_valid;  // ufix32
  output  [31:0] cnt_dec_bits;  // ufix32
  output  [31:0] cnt_bist_start;  // ufix32
  output  [31:0] dbg_sentinel;  // ufix32
  output  [31:0] cap_in;  // ufix32
  output  [31:0] cap_deint;  // ufix32
  output  [31:0] cap_out;  // ufix32
  output  [31:0] cap_cad;  // ufix32
  output  [31:0] rstcs_count;  // ufix32
  output  [31:0] cfc_est;  // ufix32
  output  byte_ready;  // ufix1
  output  [63:0] byte_rx_data;  // ufix64
  output  byte_rx_valid;  // ufix1
  output  byte_rx_last;  // ufix1
  output  byte_rx_user;  // ufix1
  output  [31:0] byte_fifo_ovf;  // ufix32
  output  [31:0] framestat_head_lo;  // ufix32
  output  [31:0] framestat_head_hi;  // ufix32
  output  [31:0] framestat_stat;  // ufix32
  output  [31:0] framestat_wordcnt;  // ufix32
  output  [31:0] beatfix_viol_count;  // ufix32
  output  [31:0] beatfix_viol_latch;  // ufix32


  wire enb;
  wire ce_out_0_sig;  // ufix1
  wire ce_out_1_sig;  // ufix1
  wire [31:0] count_out_sig;  // ufix32
  wire [31:0] packets_out_sig;  // ufix32
  wire [31:0] bit_errors_out_sig;  // ufix32
  wire signed [15:0] debugI_sig;  // sfix16
  wire signed [15:0] debugQ_sig;  // sfix16
  wire debugValid_sig;  // ufix1
  wire signed [15:0] debugI1_sig;  // sfix16
  wire signed [15:0] debugQ1_sig;  // sfix16
  wire signed [15:0] tx_dataOutI_sig;  // sfix16
  wire signed [15:0] tx_dataOutQ_sig;  // sfix16
  wire tx_validOut_sig;  // ufix1
  wire [31:0] cnt_descr_in_sig;  // ufix32
  wire [31:0] cnt_frame_start_sig;  // ufix32
  wire [31:0] cnt_vit_reset_sig;  // ufix32
  wire [31:0] cnt_deint_valid_sig;  // ufix32
  wire [31:0] cnt_dec_bits_sig;  // ufix32
  wire [31:0] cnt_bist_start_sig;  // ufix32
  wire [31:0] dbg_sentinel_sig;  // ufix32
  wire [31:0] cap_in_sig;  // ufix32
  wire [31:0] cap_deint_sig;  // ufix32
  wire [31:0] cap_out_sig;  // ufix32
  wire [31:0] cap_cad_sig;  // ufix32
  wire [31:0] rstcs_count_sig;  // ufix32
  wire [31:0] cfc_est_sig;  // ufix32
  wire byte_ready_sig;  // ufix1
  wire [63:0] byte_rx_data_sig;  // ufix64
  wire byte_rx_valid_sig;  // ufix1
  wire byte_rx_last_sig;  // ufix1
  wire byte_rx_user_sig;  // ufix1
  wire [31:0] byte_fifo_ovf_sig;  // ufix32
  wire [31:0] framestat_head_lo_sig;  // ufix32
  wire [31:0] framestat_head_hi_sig;  // ufix32
  wire [31:0] framestat_stat_sig;  // ufix32
  wire [31:0] framestat_wordcnt_sig;  // ufix32
  wire [31:0] beatfix_viol_count_sig;  // ufix32
  wire [31:0] beatfix_viol_latch_sig;  // ufix32


  assign enb = dut_enable;

  TxRxComposite u_TxRxComposite (.clk(clk),
                                                                   .clk_enable(enb),
                                                                   .reset(reset),
                                                                   .adc_validIn(adc_validIn),  // ufix1
                                                                   .adc_dataInI(adc_dataInI),  // sfix16
                                                                   .adc_dataInQ(adc_dataInQ),  // sfix16
                                                                   .rstCS(rstCS),  // ufix1
                                                                   .iq_debug_mux(iq_debug_mux),  // ufix32
                                                                   .rx_input_select(rx_input_select),  // ufix1
                                                                   .host_txI(host_txI),  // sfix16
                                                                   .host_txQ(host_txQ),  // sfix16
                                                                   .host_txValid(host_txValid),  // ufix1
                                                                   .tx_source_select(tx_source_select),  // ufix32
                                                                   .skip_count(skip_count),  // ufix32
                                                                   .byte_data(byte_data),  // ufix64
                                                                   .byte_valid(byte_valid),  // ufix1
                                                                   .tx_data_source(tx_data_source),  // ufix32
                                                                   .byte_first(byte_first),  // ufix1
                                                                   .byte_rx_ready(byte_rx_ready),  // ufix1
                                                                   .cs_prop_gain(cs_prop_gain),  // ufix32
                                                                   .cs_integ_gain(cs_integ_gain),  // ufix32
                                                                   .ss_prop_gain(ss_prop_gain),  // ufix32
                                                                   .ss_integ_gain(ss_integ_gain),  // ufix32
                                                                   .agc_loop_gain(agc_loop_gain),  // ufix32
                                                                   .cfo_threshold(cfo_threshold),  // ufix32
                                                                   .framestat_pop(framestat_pop),  // ufix32
                                                                   .fixctl(fixctl),  // ufix32
                                                                   .ce_out_0(ce_out_0_sig),  // ufix1
                                                                   .ce_out_1(ce_out_1_sig),  // ufix1
                                                                   .count_out(count_out_sig),  // ufix32
                                                                   .packets_out(packets_out_sig),  // ufix32
                                                                   .bit_errors_out(bit_errors_out_sig),  // ufix32
                                                                   .debugI(debugI_sig),  // sfix16
                                                                   .debugQ(debugQ_sig),  // sfix16
                                                                   .debugValid(debugValid_sig),  // ufix1
                                                                   .debugI1(debugI1_sig),  // sfix16
                                                                   .debugQ1(debugQ1_sig),  // sfix16
                                                                   .tx_dataOutI(tx_dataOutI_sig),  // sfix16
                                                                   .tx_dataOutQ(tx_dataOutQ_sig),  // sfix16
                                                                   .tx_validOut(tx_validOut_sig),  // ufix1
                                                                   .cnt_descr_in(cnt_descr_in_sig),  // ufix32
                                                                   .cnt_frame_start(cnt_frame_start_sig),  // ufix32
                                                                   .cnt_vit_reset(cnt_vit_reset_sig),  // ufix32
                                                                   .cnt_deint_valid(cnt_deint_valid_sig),  // ufix32
                                                                   .cnt_dec_bits(cnt_dec_bits_sig),  // ufix32
                                                                   .cnt_bist_start(cnt_bist_start_sig),  // ufix32
                                                                   .dbg_sentinel(dbg_sentinel_sig),  // ufix32
                                                                   .cap_in(cap_in_sig),  // ufix32
                                                                   .cap_deint(cap_deint_sig),  // ufix32
                                                                   .cap_out(cap_out_sig),  // ufix32
                                                                   .cap_cad(cap_cad_sig),  // ufix32
                                                                   .rstcs_count(rstcs_count_sig),  // ufix32
                                                                   .cfc_est(cfc_est_sig),  // ufix32
                                                                   .byte_ready(byte_ready_sig),  // ufix1
                                                                   .byte_rx_data(byte_rx_data_sig),  // ufix64
                                                                   .byte_rx_valid(byte_rx_valid_sig),  // ufix1
                                                                   .byte_rx_last(byte_rx_last_sig),  // ufix1
                                                                   .byte_rx_user(byte_rx_user_sig),  // ufix1
                                                                   .byte_fifo_ovf(byte_fifo_ovf_sig),  // ufix32
                                                                   .framestat_head_lo(framestat_head_lo_sig),  // ufix32
                                                                   .framestat_head_hi(framestat_head_hi_sig),  // ufix32
                                                                   .framestat_stat(framestat_stat_sig),  // ufix32
                                                                   .framestat_wordcnt(framestat_wordcnt_sig),  // ufix32
                                                                   .beatfix_viol_count(beatfix_viol_count_sig),  // ufix32
                                                                   .beatfix_viol_latch(beatfix_viol_latch_sig)  // ufix32
                                                                   );

  assign ce_out_0 = ce_out_0_sig;

  assign ce_out_1 = ce_out_1_sig;

  assign count_out = count_out_sig;

  assign packets_out = packets_out_sig;

  assign bit_errors_out = bit_errors_out_sig;

  assign debugI = debugI_sig;

  assign debugQ = debugQ_sig;

  assign debugValid = debugValid_sig;

  assign debugI1 = debugI1_sig;

  assign debugQ1 = debugQ1_sig;

  assign tx_dataOutI = tx_dataOutI_sig;

  assign tx_dataOutQ = tx_dataOutQ_sig;

  assign tx_validOut = tx_validOut_sig;

  assign cnt_descr_in = cnt_descr_in_sig;

  assign cnt_frame_start = cnt_frame_start_sig;

  assign cnt_vit_reset = cnt_vit_reset_sig;

  assign cnt_deint_valid = cnt_deint_valid_sig;

  assign cnt_dec_bits = cnt_dec_bits_sig;

  assign cnt_bist_start = cnt_bist_start_sig;

  assign dbg_sentinel = dbg_sentinel_sig;

  assign cap_in = cap_in_sig;

  assign cap_deint = cap_deint_sig;

  assign cap_out = cap_out_sig;

  assign cap_cad = cap_cad_sig;

  assign rstcs_count = rstcs_count_sig;

  assign cfc_est = cfc_est_sig;

  assign byte_ready = byte_ready_sig;

  assign byte_rx_data = byte_rx_data_sig;

  assign byte_rx_valid = byte_rx_valid_sig;

  assign byte_rx_last = byte_rx_last_sig;

  assign byte_rx_user = byte_rx_user_sig;

  assign byte_fifo_ovf = byte_fifo_ovf_sig;

  assign framestat_head_lo = framestat_head_lo_sig;

  assign framestat_head_hi = framestat_head_hi_sig;

  assign framestat_stat = framestat_stat_sig;

  assign framestat_wordcnt = framestat_wordcnt_sig;

  assign beatfix_viol_count = beatfix_viol_count_sig;

  assign beatfix_viol_latch = beatfix_viol_latch_sig;

endmodule  // TxRxCompo_ip_dut

