// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/TxRxComposite.v
// Created: 2026-08-21 23:31:06
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 3.25521e-08
// Target subsystem base rate: 3.25521e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out_1      3.25521e-08
// ce_out_0      6.51042e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// count_out                     ce_out_0      6.51042e-08
// packets_out                   ce_out_0      6.51042e-08
// bit_errors_out                ce_out_0      6.51042e-08
// debugI                        ce_out_0      6.51042e-08
// debugQ                        ce_out_0      6.51042e-08
// debugValid                    ce_out_1      3.25521e-08
// debugI1                       ce_out_0      6.51042e-08
// debugQ1                       ce_out_0      6.51042e-08
// tx_dataOutI                   ce_out_1      3.25521e-08
// tx_dataOutQ                   ce_out_1      3.25521e-08
// tx_validOut                   ce_out_1      3.25521e-08
// cnt_descr_in                  ce_out_0      6.51042e-08
// cnt_frame_start               ce_out_0      6.51042e-08
// cnt_vit_reset                 ce_out_0      6.51042e-08
// cnt_deint_valid               ce_out_0      6.51042e-08
// cnt_dec_bits                  ce_out_0      6.51042e-08
// cnt_bist_start                ce_out_0      6.51042e-08
// dbg_sentinel                  ce_out_0      6.51042e-08
// cap_in                        ce_out_0      6.51042e-08
// cap_deint                     ce_out_0      6.51042e-08
// cap_out                       ce_out_0      6.51042e-08
// cap_cad                       ce_out_0      6.51042e-08
// rstcs_count                   ce_out_0      6.51042e-08
// cfc_est                       ce_out_0      6.51042e-08
// byte_ready                    ce_out_1      3.25521e-08
// byte_rx_data                  ce_out_1      3.25521e-08
// byte_rx_valid                 ce_out_1      3.25521e-08
// byte_rx_last                  ce_out_1      3.25521e-08
// byte_rx_user                  ce_out_1      3.25521e-08
// byte_fifo_ovf                 ce_out_1      3.25521e-08
// framestat_head_lo             ce_out_0      6.51042e-08
// framestat_head_hi             ce_out_0      6.51042e-08
// framestat_stat                ce_out_0      6.51042e-08
// framestat_wordcnt             ce_out_1      3.25521e-08
// beatfix_viol_count            ce_out_0      6.51042e-08
// beatfix_viol_latch            ce_out_0      6.51042e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TxRxComposite
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite
// Hierarchy Level: 0
// Model version: 11.331
// 
// Simulink model description for commhdlQPSKTxRxLoopback:
// 
// frame=f1536 variant=jupiter_240k5_byte(sps4/Rsym3840000-T8ratefix,K5[35 23]TB25 rx+GATED-txenc,ROMf1536+byteDMA,noscr+nodescr,taps 
// 0x150/0x154/0x15C,agcEn10,txds 0x158,WPP191) pre=variant_pre_composite_verif+cfc_a12+bytek5 build=21-Aug-2026 23:21:45
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TxRxComposite
          (clk,
           reset,
           clk_enable,
           adc_validIn,
           adc_dataInI,
           adc_dataInQ,
           rstCS,
           iq_debug_mux,
           rx_input_select,
           host_txI,
           host_txQ,
           host_txValid,
           tx_source_select,
           skip_count,
           byte_data,
           byte_valid,
           tx_data_source,
           byte_first,
           byte_rx_ready,
           cs_prop_gain,
           cs_integ_gain,
           ss_prop_gain,
           ss_integ_gain,
           agc_loop_gain,
           cfo_threshold,
           framestat_pop,
           fixctl,
           ce_out_0,
           ce_out_1,
           count_out,
           packets_out,
           bit_errors_out,
           debugI,
           debugQ,
           debugValid,
           debugI1,
           debugQ1,
           tx_dataOutI,
           tx_dataOutQ,
           tx_validOut,
           cnt_descr_in,
           cnt_frame_start,
           cnt_vit_reset,
           cnt_deint_valid,
           cnt_dec_bits,
           cnt_bist_start,
           dbg_sentinel,
           cap_in,
           cap_deint,
           cap_out,
           cap_cad,
           rstcs_count,
           cfc_est,
           byte_ready,
           byte_rx_data,
           byte_rx_valid,
           byte_rx_last,
           byte_rx_user,
           byte_fifo_ovf,
           framestat_head_lo,
           framestat_head_hi,
           framestat_stat,
           framestat_wordcnt,
           beatfix_viol_count,
           beatfix_viol_latch);


  input   clk;
  input   reset;
  input   clk_enable;
  input   adc_validIn;
  input   signed [15:0] adc_dataInI;  // int16
  input   signed [15:0] adc_dataInQ;  // int16
  input   rstCS;
  input   [31:0] iq_debug_mux;  // uint32
  input   rx_input_select;
  input   signed [15:0] host_txI;  // int16
  input   signed [15:0] host_txQ;  // int16
  input   host_txValid;
  input   [31:0] tx_source_select;  // uint32
  input   [31:0] skip_count;  // uint32
  input   [63:0] byte_data;  // ufix64
  input   byte_valid;
  input   [31:0] tx_data_source;  // uint32
  input   byte_first;
  input   byte_rx_ready;
  input   [31:0] cs_prop_gain;  // uint32
  input   [31:0] cs_integ_gain;  // uint32
  input   [31:0] ss_prop_gain;  // uint32
  input   [31:0] ss_integ_gain;  // uint32
  input   [31:0] agc_loop_gain;  // uint32
  input   [31:0] cfo_threshold;  // uint32
  input   [31:0] framestat_pop;  // uint32
  input   [31:0] fixctl;  // uint32
  output  ce_out_0;
  output  ce_out_1;
  output  [31:0] count_out;  // uint32
  output  [31:0] packets_out;  // uint32
  output  [31:0] bit_errors_out;  // uint32
  output  signed [15:0] debugI;  // int16
  output  signed [15:0] debugQ;  // int16
  output  debugValid;
  output  signed [15:0] debugI1;  // int16
  output  signed [15:0] debugQ1;  // int16
  output  signed [15:0] tx_dataOutI;  // int16
  output  signed [15:0] tx_dataOutQ;  // int16
  output  tx_validOut;
  output  [31:0] cnt_descr_in;  // uint32
  output  [31:0] cnt_frame_start;  // uint32
  output  [31:0] cnt_vit_reset;  // uint32
  output  [31:0] cnt_deint_valid;  // uint32
  output  [31:0] cnt_dec_bits;  // uint32
  output  [31:0] cnt_bist_start;  // uint32
  output  [31:0] dbg_sentinel;  // uint32
  output  [31:0] cap_in;  // uint32
  output  [31:0] cap_deint;  // uint32
  output  [31:0] cap_out;  // uint32
  output  [31:0] cap_cad;  // uint32
  output  [31:0] rstcs_count;  // uint32
  output  [31:0] cfc_est;  // uint32
  output  byte_ready;
  output  [63:0] byte_rx_data;  // ufix64
  output  byte_rx_valid;
  output  byte_rx_last;
  output  byte_rx_user;
  output  [31:0] byte_fifo_ovf;  // uint32
  output  [31:0] framestat_head_lo;  // uint32
  output  [31:0] framestat_head_hi;  // uint32
  output  [31:0] framestat_stat;  // uint32
  output  [31:0] framestat_wordcnt;  // uint32
  output  [31:0] beatfix_viol_count;  // uint32
  output  [31:0] beatfix_viol_latch;  // uint32


  wire enb;
  wire enb_1_2_1;
  wire enb_1_2_0;
  wire enb_1_1_1;
  wire IntValidConst_out1;
  wire RxValidConst_out1;
  wire MUX_RxValid_out1;
  reg  rx_input_select_1;
  wire ByteSel_out1;
  wire wordFirst;
  reg  FirstRT_bypass_reg;  // ufix1
  wire FirstRT_out1;
  wire avail;
  reg  AvailRT_bypass_reg;  // ufix1
  wire AvailRT_out1;
  reg  PopRT_out1;
  reg  PopDly_out1;
  wire Transmitter_extWordPop;
  wire PopEdge_out1;
  wire [63:0] word;  // ufix64
  wire readyNext;
  reg [63:0] WordRT_bypass_reg;  // ufix64
  wire [63:0] WordRT_out1;  // ufix64
  wire signed [15:0] Transmitter_dataOutI;  // int16
  wire signed [15:0] Transmitter_dataOutQ;  // int16
  reg signed [15:0] AdcCapI_bypass_delay;  // sfix16
  reg signed [15:0] AdcCapI_reg;  // sfix16
  wire signed [15:0] AdcCapI_out1;  // int16
  reg signed [15:0] AdcRTI_out1;  // int16
  reg signed [15:0] AdcStabI_out1;  // int16
  reg signed [15:0] AdcStabI_out1_1;  // int16
  wire signed [15:0] MUX_RxI_out1;  // int16
  reg signed [15:0] AdcCapQ_bypass_delay;  // sfix16
  reg signed [15:0] AdcCapQ_reg;  // sfix16
  wire signed [15:0] AdcCapQ_out1;  // int16
  reg signed [15:0] AdcRTQ_out1;  // int16
  reg signed [15:0] AdcStabQ_out1;  // int16
  reg signed [15:0] AdcStabQ_out1_1;  // int16
  wire signed [15:0] MUX_RxQ_out1;  // int16
  wire [31:0] Receiver_count_out;  // uint32
  wire [31:0] Receiver_packets_out;  // uint32
  wire [31:0] Receiver_bit_errors_out;  // uint32
  wire signed [15:0] Receiver_debugI;  // int16
  wire signed [15:0] Receiver_debugQ;  // int16
  wire [31:0] Receiver_cnt_descr_in;  // uint32
  wire [31:0] Receiver_cnt_frame_start;  // uint32
  wire [31:0] Receiver_cnt_vit_reset;  // uint32
  wire [31:0] Receiver_cnt_deint_valid;  // uint32
  wire [31:0] Receiver_cnt_dec_bits;  // uint32
  wire [31:0] Receiver_cnt_bist_start;  // uint32
  wire [31:0] Receiver_cap_in;  // uint32
  wire [31:0] Receiver_cap_deint;  // uint32
  wire [31:0] Receiver_cap_out;  // uint32
  wire [31:0] Receiver_cap_cad;  // uint32
  wire [31:0] Receiver_rstcs_count;  // uint32
  wire [31:0] Receiver_cfc_est;  // uint32
  wire Receiver_recBit;
  wire Receiver_recBitValid;
  wire Receiver_recStart;
  wire signed [31:0] Receiver_fs_runmax;  // sfix32_En26
  wire signed [15:0] Receiver_beatobsI1;  // int16
  wire signed [15:0] Receiver_beatobsQ1;  // int16
  wire [31:0] Receiver_beatfix_viol_count;  // uint32
  wire [31:0] Receiver_beatfix_viol_latch;  // uint32
  reg [31:0] delayMatch10_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch10_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_count_out_1;  // uint32
  reg [31:0] delayMatch11_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch11_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_packets_out_1;  // uint32
  reg [31:0] delayMatch12_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch12_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_bit_errors_out_1;  // uint32
  reg signed [15:0] delayMatch13_reg [0:2];  // sfix16 [3]
  reg signed [15:0] delayMatch13_reg_next [0:2];  // sfix16 [3]
  reg signed [15:0] Receiver_debugI_1;  // int16
  reg signed [15:0] delayMatch14_reg [0:2];  // sfix16 [3]
  reg signed [15:0] delayMatch14_reg_next [0:2];  // sfix16 [3]
  reg signed [15:0] Receiver_debugQ_1;  // int16
  reg  [7:0] delayMatch15_reg;  // ufix1 [8]
  wire adc_validIn_1;
  reg signed [15:0] delayMatch16_reg [0:2];  // sfix16 [3]
  reg signed [15:0] delayMatch16_reg_next [0:2];  // sfix16 [3]
  reg signed [15:0] Receiver_beatobsI1_1;  // int16
  reg signed [15:0] delayMatch17_reg [0:2];  // sfix16 [3]
  reg signed [15:0] delayMatch17_reg_next [0:2];  // sfix16 [3]
  reg signed [15:0] Receiver_beatobsQ1_1;  // int16
  reg [31:0] reduced_reg [0:3];  // ufix32 [4]
  reg [31:0] reduced_reg_next [0:3];  // ufix32 [4]
  reg [31:0] tx_source_select_1;  // uint32
  wire signed [15:0] REP_TxI_out1;  // int16
  reg signed [15:0] REP_TxI_out1_1;  // int16
  reg signed [15:0] HostCapI_bypass_delay;  // sfix16
  reg signed [15:0] HostCapI_reg;  // sfix16
  wire signed [15:0] HostCapI_out1;  // int16
  reg signed [15:0] delayMatch4_reg [0:7];  // sfix16 [8]
  reg signed [15:0] delayMatch4_reg_next [0:7];  // sfix16 [8]
  reg signed [15:0] HostRTI_out1;  // int16
  wire signed [15:0] MUX_DacI_out1;  // int16
  wire signed [15:0] REP_TxQ_out1;  // int16
  reg signed [15:0] REP_TxQ_out1_1;  // int16
  reg signed [15:0] HostCapQ_bypass_delay;  // sfix16
  reg signed [15:0] HostCapQ_reg;  // sfix16
  wire signed [15:0] HostCapQ_out1;  // int16
  reg signed [15:0] delayMatch7_reg [0:7];  // sfix16 [8]
  reg signed [15:0] delayMatch7_reg_next [0:7];  // sfix16 [8]
  reg signed [15:0] HostRTQ_out1;  // int16
  wire signed [15:0] MUX_DacQ_out1;  // int16
  reg  [7:0] delayMatch18_reg;  // ufix1 [8]
  wire host_txValid_1;
  reg [31:0] delayMatch19_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch19_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_descr_in_1;  // uint32
  reg [31:0] delayMatch20_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch20_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_frame_start_1;  // uint32
  reg [31:0] delayMatch21_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch21_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_vit_reset_1;  // uint32
  reg [31:0] delayMatch22_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch22_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_deint_valid_1;  // uint32
  reg [31:0] delayMatch23_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch23_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_dec_bits_1;  // uint32
  reg [31:0] delayMatch24_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch24_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cnt_bist_start_1;  // uint32
  wire [31:0] DbgSentinelConst_out1;  // uint32
  reg [31:0] delayMatch25_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch25_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cap_in_1;  // uint32
  reg [31:0] delayMatch26_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch26_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cap_deint_1;  // uint32
  reg [31:0] delayMatch27_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch27_reg_next [0:1];  // ufix32 [2]
  wire [31:0] Receiver_cap_out_1;  // uint32
  reg [31:0] delayMatch28_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch28_reg_next [0:2];  // ufix32 [3]
  reg [31:0] Receiver_cap_cad_1;  // uint32
  reg [31:0] delayMatch29_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch29_reg_next [0:2];  // ufix32 [3]
  reg [31:0] Receiver_rstcs_count_1;  // uint32
  reg [31:0] delayMatch30_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch30_reg_next [0:2];  // ufix32 [3]
  reg [31:0] Receiver_cfc_est_1;  // uint32
  reg  ReadyDly_out1;
  reg  [7:0] delayMatch31_reg;  // ufix1 [8]
  wire ReadyDly_out1_1;
  reg  RxReadyRT_bypass_reg;  // ufix1
  wire RxReadyRT_out1;
  wire [63:0] word_1;  // ufix64
  wire wordTog;
  wire wordLast;
  wire wordFirst_1;
  reg [63:0] SerWordRT_out1;  // ufix64
  reg  SerTogRT_out1;
  reg  SerLastRT_out1;
  reg  SerFirstRT_out1;
  wire [63:0] outWord;  // ufix64
  wire valid;
  wire outLast;
  wire outFirst;
  wire [31:0] ovf;  // uint32
  reg [63:0] delayMatch32_reg [0:3];  // ufix64 [4]
  reg [63:0] delayMatch32_reg_next [0:3];  // ufix64 [4]
  reg [63:0] outWord_1;  // ufix64
  reg  [3:0] delayMatch33_reg;  // ufix1 [4]
  wire valid_1;
  reg  [3:0] delayMatch34_reg;  // ufix1 [4]
  wire outLast_1;
  reg  [3:0] delayMatch35_reg;  // ufix1 [4]
  wire outFirst_1;
  reg [31:0] delayMatch36_reg [0:3];  // ufix32 [4]
  reg [31:0] delayMatch36_reg_next [0:3];  // ufix32 [4]
  reg [31:0] ovf_1;  // uint32
  wire [31:0] FsRunSi_out1;  // uint32
  wire [31:0] FsAgcZero_out1;  // uint32
  wire [15:0] chk;  // uint16
  wire [63:0] rec;  // ufix64
  wire push;
  wire [31:0] headLo;  // uint32
  wire [31:0] headHi;  // uint32
  wire [31:0] stat;  // uint32
  reg [31:0] delayMatch37_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch37_reg_next [0:1];  // ufix32 [2]
  wire [31:0] headLo_1;  // uint32
  reg [31:0] delayMatch38_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch38_reg_next [0:1];  // ufix32 [2]
  wire [31:0] headHi_1;  // uint32
  reg [31:0] delayMatch39_reg [0:1];  // ufix32 [2]
  wire [31:0] delayMatch39_reg_next [0:1];  // ufix32 [2]
  wire [31:0] stat_1;  // uint32
  wire [31:0] cnt;  // uint32
  reg [31:0] delayMatch40_reg [0:3];  // ufix32 [4]
  reg [31:0] delayMatch40_reg_next [0:3];  // ufix32 [4]
  reg [31:0] cnt_1;  // uint32
  reg [31:0] delayMatch41_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch41_reg_next [0:2];  // ufix32 [3]
  reg [31:0] Receiver_beatfix_viol_count_1;  // uint32
  reg [31:0] delayMatch42_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch42_reg_next [0:2];  // ufix32 [3]
  reg [31:0] Receiver_beatfix_viol_latch_1;  // uint32
  reg signed [31:0] delayMatch10_t_0_0;  // int32
  reg signed [31:0] delayMatch10_t_1;  // int32
  reg signed [31:0] delayMatch11_t_0_0;  // int32
  reg signed [31:0] delayMatch11_t_1;  // int32
  reg signed [31:0] delayMatch12_t_0_0;  // int32
  reg signed [31:0] delayMatch12_t_1;  // int32
  reg signed [31:0] delayMatch13_t_0_0;  // int32
  reg signed [31:0] delayMatch13_t_0_1;  // int32
  reg signed [31:0] delayMatch13_t_1;  // int32
  reg signed [31:0] delayMatch14_t_0_0;  // int32
  reg signed [31:0] delayMatch14_t_0_1;  // int32
  reg signed [31:0] delayMatch14_t_1;  // int32
  reg signed [31:0] delayMatch16_t_0_0;  // int32
  reg signed [31:0] delayMatch16_t_0_1;  // int32
  reg signed [31:0] delayMatch16_t_1;  // int32
  reg signed [31:0] delayMatch17_t_0_0;  // int32
  reg signed [31:0] delayMatch17_t_0_1;  // int32
  reg signed [31:0] delayMatch17_t_1;  // int32
  reg signed [31:0] reduced_t_0_0;  // int32
  reg signed [31:0] reduced_t_0_1;  // int32
  reg signed [31:0] reduced_t_1;  // int32
  reg signed [31:0] delayMatch4_t_0_0;  // int32
  reg signed [31:0] delayMatch4_t_0_1;  // int32
  reg signed [31:0] delayMatch4_t_1;  // int32
  reg signed [31:0] delayMatch7_t_0_0;  // int32
  reg signed [31:0] delayMatch7_t_0_1;  // int32
  reg signed [31:0] delayMatch7_t_1;  // int32
  reg signed [31:0] delayMatch19_t_0_0;  // int32
  reg signed [31:0] delayMatch19_t_1;  // int32
  reg signed [31:0] delayMatch20_t_0_0;  // int32
  reg signed [31:0] delayMatch20_t_1;  // int32
  reg signed [31:0] delayMatch21_t_0_0;  // int32
  reg signed [31:0] delayMatch21_t_1;  // int32
  reg signed [31:0] delayMatch22_t_0_0;  // int32
  reg signed [31:0] delayMatch22_t_1;  // int32
  reg signed [31:0] delayMatch23_t_0_0;  // int32
  reg signed [31:0] delayMatch23_t_1;  // int32
  reg signed [31:0] delayMatch24_t_0_0;  // int32
  reg signed [31:0] delayMatch24_t_1;  // int32
  reg signed [31:0] delayMatch25_t_0_0;  // int32
  reg signed [31:0] delayMatch25_t_1;  // int32
  reg signed [31:0] delayMatch26_t_0_0;  // int32
  reg signed [31:0] delayMatch26_t_1;  // int32
  reg signed [31:0] delayMatch27_t_0_0;  // int32
  reg signed [31:0] delayMatch27_t_1;  // int32
  reg signed [31:0] delayMatch28_t_0_0;  // int32
  reg signed [31:0] delayMatch28_t_0_1;  // int32
  reg signed [31:0] delayMatch28_t_1;  // int32
  reg signed [31:0] delayMatch29_t_0_0;  // int32
  reg signed [31:0] delayMatch29_t_0_1;  // int32
  reg signed [31:0] delayMatch29_t_1;  // int32
  reg signed [31:0] delayMatch30_t_0_0;  // int32
  reg signed [31:0] delayMatch30_t_0_1;  // int32
  reg signed [31:0] delayMatch30_t_1;  // int32
  reg signed [31:0] delayMatch32_t_0_0;  // int32
  reg signed [31:0] delayMatch32_t_0_1;  // int32
  reg signed [31:0] delayMatch32_t_1;  // int32
  reg signed [31:0] delayMatch36_t_0_0;  // int32
  reg signed [31:0] delayMatch36_t_0_1;  // int32
  reg signed [31:0] delayMatch36_t_1;  // int32
  reg signed [31:0] delayMatch37_t_0_0;  // int32
  reg signed [31:0] delayMatch37_t_1;  // int32
  reg signed [31:0] delayMatch38_t_0_0;  // int32
  reg signed [31:0] delayMatch38_t_1;  // int32
  reg signed [31:0] delayMatch39_t_0_0;  // int32
  reg signed [31:0] delayMatch39_t_1;  // int32
  reg signed [31:0] delayMatch40_t_0_0;  // int32
  reg signed [31:0] delayMatch40_t_0_1;  // int32
  reg signed [31:0] delayMatch40_t_1;  // int32
  reg signed [31:0] delayMatch41_t_0_0;  // int32
  reg signed [31:0] delayMatch41_t_0_1;  // int32
  reg signed [31:0] delayMatch41_t_1;  // int32
  reg signed [31:0] delayMatch42_t_0_0;  // int32
  reg signed [31:0] delayMatch42_t_0_1;  // int32
  reg signed [31:0] delayMatch42_t_1;  // int32


  assign IntValidConst_out1 = 1'b1;

  assign RxValidConst_out1 = 1'b1;

  assign MUX_RxValid_out1 = (rx_input_select == 1'b0 ? IntValidConst_out1 :
              RxValidConst_out1);

  TxRxComposite_tc u_TxRxComposite_tc (.clk(clk),
                                                        .reset(reset),
                                                        .clk_enable(clk_enable),
                                                        .enb(enb),
                                                        .enb_1_1_1(enb_1_1_1),
                                                        .enb_1_2_0(enb_1_2_0),
                                                        .enb_1_2_1(enb_1_2_1)
                                                        );

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        rx_input_select_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          rx_input_select_1 <= rx_input_select;
        end
      end
    end

  assign ByteSel_out1 = tx_data_source != 32'b00000000000000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : FirstRT_bypass_process
      if (reset == 1'b1) begin
        FirstRT_bypass_reg <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          FirstRT_bypass_reg <= wordFirst;
        end
      end
    end

  assign FirstRT_out1 = (enb_1_2_1 == 1'b1 ? wordFirst :
              FirstRT_bypass_reg);

  always @(posedge clk or posedge reset)
    begin : AvailRT_bypass_process
      if (reset == 1'b1) begin
        AvailRT_bypass_reg <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          AvailRT_bypass_reg <= avail;
        end
      end
    end

  assign AvailRT_out1 = (enb_1_2_1 == 1'b1 ? avail :
              AvailRT_bypass_reg);

  always @(posedge clk or posedge reset)
    begin : PopDly_process
      if (reset == 1'b1) begin
        PopDly_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          PopDly_out1 <= PopRT_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : PopRT_process
      if (reset == 1'b1) begin
        PopRT_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          PopRT_out1 <= Transmitter_extWordPop;
        end
      end
    end

  assign PopEdge_out1 = PopRT_out1 ^ PopDly_out1;

  ByteWordBuffer u_ByteWordBuffer (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dataIn(byte_data),  // ufix64
                                                    .validIn(byte_valid),
                                                    .popReq(PopEdge_out1),
                                                    .firstIn(byte_first),
                                                    .word(word),  // ufix64
                                                    .avail(avail),
                                                    .readyNext(readyNext),
                                                    .wordFirst(wordFirst)
                                                    );

  always @(posedge clk or posedge reset)
    begin : WordRT_bypass_process
      if (reset == 1'b1) begin
        WordRT_bypass_reg <= 64'h0000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          WordRT_bypass_reg <= word;
        end
      end
    end

  assign WordRT_out1 = (enb_1_2_1 == 1'b1 ? word :
              WordRT_bypass_reg);

  Transmitter u_Transmitter (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .enb_1_2_1(enb_1_2_1),
                                              .enb_1_2_0(enb_1_2_0),
                                              .extWord(WordRT_out1),  // ufix64
                                              .extWordAvail(AvailRT_out1),
                                              .extBitSel(ByteSel_out1),
                                              .extWordFirst(FirstRT_out1),
                                              .dataOutI(Transmitter_dataOutI),  // int16
                                              .dataOutQ(Transmitter_dataOutQ),  // int16
                                              .extWordPop(Transmitter_extWordPop)
                                              );

  always @(posedge clk or posedge reset)
    begin : AdcCapI_process
      if (reset == 1'b1) begin
        AdcCapI_bypass_delay <= 16'sb0000000000000000;
        AdcCapI_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb && adc_validIn) begin
          AdcCapI_bypass_delay <= AdcCapI_reg;
          AdcCapI_reg <= adc_dataInI;
        end
      end
    end

  assign AdcCapI_out1 = (adc_validIn == 1'b1 ? AdcCapI_reg :
              AdcCapI_bypass_delay);

  always @(posedge clk or posedge reset)
    begin : AdcRTI_output_process
      if (reset == 1'b1) begin
        AdcRTI_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          AdcRTI_out1 <= AdcCapI_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : AdcStabI_process
      if (reset == 1'b1) begin
        AdcStabI_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          AdcStabI_out1 <= AdcRTI_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        AdcStabI_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          AdcStabI_out1_1 <= AdcStabI_out1;
        end
      end
    end

  assign MUX_RxI_out1 = (rx_input_select_1 == 1'b0 ? Transmitter_dataOutI :
              AdcStabI_out1_1);

  always @(posedge clk or posedge reset)
    begin : AdcCapQ_process
      if (reset == 1'b1) begin
        AdcCapQ_bypass_delay <= 16'sb0000000000000000;
        AdcCapQ_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb && adc_validIn) begin
          AdcCapQ_bypass_delay <= AdcCapQ_reg;
          AdcCapQ_reg <= adc_dataInQ;
        end
      end
    end

  assign AdcCapQ_out1 = (adc_validIn == 1'b1 ? AdcCapQ_reg :
              AdcCapQ_bypass_delay);

  always @(posedge clk or posedge reset)
    begin : AdcRTQ_output_process
      if (reset == 1'b1) begin
        AdcRTQ_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          AdcRTQ_out1 <= AdcCapQ_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : AdcStabQ_process
      if (reset == 1'b1) begin
        AdcStabQ_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          AdcStabQ_out1 <= AdcRTQ_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        AdcStabQ_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          AdcStabQ_out1_1 <= AdcStabQ_out1;
        end
      end
    end

  assign MUX_RxQ_out1 = (rx_input_select_1 == 1'b0 ? Transmitter_dataOutQ :
              AdcStabQ_out1_1);

  Receiver u_Receiver (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .enb_1_2_1(enb_1_2_1),
                                        .enb_1_2_0(enb_1_2_0),
                                        .validIn(MUX_RxValid_out1),
                                        .dataInI(MUX_RxI_out1),  // int16
                                        .dataInQ(MUX_RxQ_out1),  // int16
                                        .rstCS(rstCS),
                                        .iq_debug_mux(iq_debug_mux),  // uint32
                                        .skip_count(skip_count),  // uint32
                                        .cs_prop_gain(cs_prop_gain),  // uint32
                                        .cs_integ_gain(cs_integ_gain),  // uint32
                                        .ss_prop_gain(ss_prop_gain),  // uint32
                                        .ss_integ_gain(ss_integ_gain),  // uint32
                                        .agc_loop_gain(agc_loop_gain),  // uint32
                                        .cfo_threshold(cfo_threshold),  // uint32
                                        .fixctl(fixctl),  // uint32
                                        .count_out(Receiver_count_out),  // uint32
                                        .packets_out(Receiver_packets_out),  // uint32
                                        .bit_errors_out(Receiver_bit_errors_out),  // uint32
                                        .debugI(Receiver_debugI),  // int16
                                        .debugQ(Receiver_debugQ),  // int16
                                        .cnt_descr_in(Receiver_cnt_descr_in),  // uint32
                                        .cnt_frame_start(Receiver_cnt_frame_start),  // uint32
                                        .cnt_vit_reset(Receiver_cnt_vit_reset),  // uint32
                                        .cnt_deint_valid(Receiver_cnt_deint_valid),  // uint32
                                        .cnt_dec_bits(Receiver_cnt_dec_bits),  // uint32
                                        .cnt_bist_start(Receiver_cnt_bist_start),  // uint32
                                        .cap_in(Receiver_cap_in),  // uint32
                                        .cap_deint(Receiver_cap_deint),  // uint32
                                        .cap_out(Receiver_cap_out),  // uint32
                                        .cap_cad(Receiver_cap_cad),  // uint32
                                        .rstcs_count(Receiver_rstcs_count),  // uint32
                                        .cfc_est(Receiver_cfc_est),  // uint32
                                        .recBit(Receiver_recBit),
                                        .recBitValid(Receiver_recBitValid),
                                        .recStart(Receiver_recStart),
                                        .fs_runmax(Receiver_fs_runmax),  // sfix32_En26
                                        .beatobsI1(Receiver_beatobsI1),  // int16
                                        .beatobsQ1(Receiver_beatobsQ1),  // int16
                                        .beatfix_viol_count(Receiver_beatfix_viol_count),  // uint32
                                        .beatfix_viol_latch(Receiver_beatfix_viol_latch)  // uint32
                                        );

  always @(posedge clk or posedge reset)
    begin : delayMatch10_process
      if (reset == 1'b1) begin
        for(delayMatch10_t_1 = 32'sd0; delayMatch10_t_1 <= 32'sd1; delayMatch10_t_1 = delayMatch10_t_1 + 32'sd1) begin
          delayMatch10_reg[delayMatch10_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch10_t_0_0 = 32'sd0; delayMatch10_t_0_0 <= 32'sd1; delayMatch10_t_0_0 = delayMatch10_t_0_0 + 32'sd1) begin
            delayMatch10_reg[delayMatch10_t_0_0] <= delayMatch10_reg_next[delayMatch10_t_0_0];
          end
        end
      end
    end

  assign Receiver_count_out_1 = delayMatch10_reg[1];
  assign delayMatch10_reg_next[0] = Receiver_count_out;
  assign delayMatch10_reg_next[1] = delayMatch10_reg[0];

  assign count_out = Receiver_count_out_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch11_process
      if (reset == 1'b1) begin
        for(delayMatch11_t_1 = 32'sd0; delayMatch11_t_1 <= 32'sd1; delayMatch11_t_1 = delayMatch11_t_1 + 32'sd1) begin
          delayMatch11_reg[delayMatch11_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch11_t_0_0 = 32'sd0; delayMatch11_t_0_0 <= 32'sd1; delayMatch11_t_0_0 = delayMatch11_t_0_0 + 32'sd1) begin
            delayMatch11_reg[delayMatch11_t_0_0] <= delayMatch11_reg_next[delayMatch11_t_0_0];
          end
        end
      end
    end

  assign Receiver_packets_out_1 = delayMatch11_reg[1];
  assign delayMatch11_reg_next[0] = Receiver_packets_out;
  assign delayMatch11_reg_next[1] = delayMatch11_reg[0];

  assign packets_out = Receiver_packets_out_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch12_process
      if (reset == 1'b1) begin
        for(delayMatch12_t_1 = 32'sd0; delayMatch12_t_1 <= 32'sd1; delayMatch12_t_1 = delayMatch12_t_1 + 32'sd1) begin
          delayMatch12_reg[delayMatch12_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch12_t_0_0 = 32'sd0; delayMatch12_t_0_0 <= 32'sd1; delayMatch12_t_0_0 = delayMatch12_t_0_0 + 32'sd1) begin
            delayMatch12_reg[delayMatch12_t_0_0] <= delayMatch12_reg_next[delayMatch12_t_0_0];
          end
        end
      end
    end

  assign Receiver_bit_errors_out_1 = delayMatch12_reg[1];
  assign delayMatch12_reg_next[0] = Receiver_bit_errors_out;
  assign delayMatch12_reg_next[1] = delayMatch12_reg[0];

  assign bit_errors_out = Receiver_bit_errors_out_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch13_process
      if (reset == 1'b1) begin
        for(delayMatch13_t_1 = 32'sd0; delayMatch13_t_1 <= 32'sd2; delayMatch13_t_1 = delayMatch13_t_1 + 32'sd1) begin
          delayMatch13_reg[delayMatch13_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch13_t_0_1 = 32'sd0; delayMatch13_t_0_1 <= 32'sd2; delayMatch13_t_0_1 = delayMatch13_t_0_1 + 32'sd1) begin
            delayMatch13_reg[delayMatch13_t_0_1] <= delayMatch13_reg_next[delayMatch13_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_debugI_1 = delayMatch13_reg[2];
    delayMatch13_reg_next[0] = Receiver_debugI;

    for(delayMatch13_t_0_0 = 32'sd0; delayMatch13_t_0_0 <= 32'sd1; delayMatch13_t_0_0 = delayMatch13_t_0_0 + 32'sd1) begin
      delayMatch13_reg_next[delayMatch13_t_0_0 + 32'sd1] = delayMatch13_reg[delayMatch13_t_0_0];
    end

  end

  assign debugI = Receiver_debugI_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch14_process
      if (reset == 1'b1) begin
        for(delayMatch14_t_1 = 32'sd0; delayMatch14_t_1 <= 32'sd2; delayMatch14_t_1 = delayMatch14_t_1 + 32'sd1) begin
          delayMatch14_reg[delayMatch14_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch14_t_0_1 = 32'sd0; delayMatch14_t_0_1 <= 32'sd2; delayMatch14_t_0_1 = delayMatch14_t_0_1 + 32'sd1) begin
            delayMatch14_reg[delayMatch14_t_0_1] <= delayMatch14_reg_next[delayMatch14_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_debugQ_1 = delayMatch14_reg[2];
    delayMatch14_reg_next[0] = Receiver_debugQ;

    for(delayMatch14_t_0_0 = 32'sd0; delayMatch14_t_0_0 <= 32'sd1; delayMatch14_t_0_0 = delayMatch14_t_0_0 + 32'sd1) begin
      delayMatch14_reg_next[delayMatch14_t_0_0 + 32'sd1] = delayMatch14_reg[delayMatch14_t_0_0];
    end

  end

  assign debugQ = Receiver_debugQ_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch15_process
      if (reset == 1'b1) begin
        delayMatch15_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch15_reg[0] <= adc_validIn;
          delayMatch15_reg[32'sd7:32'sd1] <= delayMatch15_reg[32'sd6:32'sd0];
        end
      end
    end

  assign adc_validIn_1 = delayMatch15_reg[7];

  assign debugValid = adc_validIn_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch16_process
      if (reset == 1'b1) begin
        for(delayMatch16_t_1 = 32'sd0; delayMatch16_t_1 <= 32'sd2; delayMatch16_t_1 = delayMatch16_t_1 + 32'sd1) begin
          delayMatch16_reg[delayMatch16_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch16_t_0_1 = 32'sd0; delayMatch16_t_0_1 <= 32'sd2; delayMatch16_t_0_1 = delayMatch16_t_0_1 + 32'sd1) begin
            delayMatch16_reg[delayMatch16_t_0_1] <= delayMatch16_reg_next[delayMatch16_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_beatobsI1_1 = delayMatch16_reg[2];
    delayMatch16_reg_next[0] = Receiver_beatobsI1;

    for(delayMatch16_t_0_0 = 32'sd0; delayMatch16_t_0_0 <= 32'sd1; delayMatch16_t_0_0 = delayMatch16_t_0_0 + 32'sd1) begin
      delayMatch16_reg_next[delayMatch16_t_0_0 + 32'sd1] = delayMatch16_reg[delayMatch16_t_0_0];
    end

  end

  assign debugI1 = Receiver_beatobsI1_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch17_process
      if (reset == 1'b1) begin
        for(delayMatch17_t_1 = 32'sd0; delayMatch17_t_1 <= 32'sd2; delayMatch17_t_1 = delayMatch17_t_1 + 32'sd1) begin
          delayMatch17_reg[delayMatch17_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch17_t_0_1 = 32'sd0; delayMatch17_t_0_1 <= 32'sd2; delayMatch17_t_0_1 = delayMatch17_t_0_1 + 32'sd1) begin
            delayMatch17_reg[delayMatch17_t_0_1] <= delayMatch17_reg_next[delayMatch17_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_beatobsQ1_1 = delayMatch17_reg[2];
    delayMatch17_reg_next[0] = Receiver_beatobsQ1;

    for(delayMatch17_t_0_0 = 32'sd0; delayMatch17_t_0_0 <= 32'sd1; delayMatch17_t_0_0 = delayMatch17_t_0_0 + 32'sd1) begin
      delayMatch17_reg_next[delayMatch17_t_0_0 + 32'sd1] = delayMatch17_reg[delayMatch17_t_0_0];
    end

  end

  assign debugQ1 = Receiver_beatobsQ1_1;

  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd3; reduced_t_1 = reduced_t_1 + 32'sd1) begin
          reduced_reg[reduced_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(reduced_t_0_1 = 32'sd0; reduced_t_0_1 <= 32'sd3; reduced_t_0_1 = reduced_t_0_1 + 32'sd1) begin
            reduced_reg[reduced_t_0_1] <= reduced_reg_next[reduced_t_0_1];
          end
        end
      end
    end

  always @* begin
    tx_source_select_1 = reduced_reg[3];
    reduced_reg_next[0] = tx_source_select;

    for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd2; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
      reduced_reg_next[reduced_t_0_0 + 32'sd1] = reduced_reg[reduced_t_0_0];
    end

  end

  REP_TxI u_REP_TxI (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .REP_TxI_In(Transmitter_dataOutI),  // int16
                                      .REP_TxI_out(REP_TxI_out1)  // int16
                                      );

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        REP_TxI_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          REP_TxI_out1_1 <= REP_TxI_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : HostCapI_process
      if (reset == 1'b1) begin
        HostCapI_bypass_delay <= 16'sb0000000000000000;
        HostCapI_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb && host_txValid) begin
          HostCapI_bypass_delay <= HostCapI_reg;
          HostCapI_reg <= host_txI;
        end
      end
    end

  assign HostCapI_out1 = (host_txValid == 1'b1 ? HostCapI_reg :
              HostCapI_bypass_delay);

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        for(delayMatch4_t_1 = 32'sd0; delayMatch4_t_1 <= 32'sd7; delayMatch4_t_1 = delayMatch4_t_1 + 32'sd1) begin
          delayMatch4_reg[delayMatch4_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch4_t_0_1 = 32'sd0; delayMatch4_t_0_1 <= 32'sd7; delayMatch4_t_0_1 = delayMatch4_t_0_1 + 32'sd1) begin
            delayMatch4_reg[delayMatch4_t_0_1] <= delayMatch4_reg_next[delayMatch4_t_0_1];
          end
        end
      end
    end

  always @* begin
    HostRTI_out1 = delayMatch4_reg[7];
    delayMatch4_reg_next[0] = HostCapI_out1;

    for(delayMatch4_t_0_0 = 32'sd0; delayMatch4_t_0_0 <= 32'sd6; delayMatch4_t_0_0 = delayMatch4_t_0_0 + 32'sd1) begin
      delayMatch4_reg_next[delayMatch4_t_0_0 + 32'sd1] = delayMatch4_reg[delayMatch4_t_0_0];
    end

  end

  assign MUX_DacI_out1 = (tx_source_select_1 == 32'b00000000000000000000000000000000 ? REP_TxI_out1_1 :
              HostRTI_out1);

  assign tx_dataOutI = MUX_DacI_out1;

  REP_TxQ u_REP_TxQ (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .REP_TxQ_In(Transmitter_dataOutQ),  // int16
                                      .REP_TxQ_out(REP_TxQ_out1)  // int16
                                      );

  always @(posedge clk or posedge reset)
    begin : delayMatch9_process
      if (reset == 1'b1) begin
        REP_TxQ_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          REP_TxQ_out1_1 <= REP_TxQ_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : HostCapQ_process
      if (reset == 1'b1) begin
        HostCapQ_bypass_delay <= 16'sb0000000000000000;
        HostCapQ_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb && host_txValid) begin
          HostCapQ_bypass_delay <= HostCapQ_reg;
          HostCapQ_reg <= host_txQ;
        end
      end
    end

  assign HostCapQ_out1 = (host_txValid == 1'b1 ? HostCapQ_reg :
              HostCapQ_bypass_delay);

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        for(delayMatch7_t_1 = 32'sd0; delayMatch7_t_1 <= 32'sd7; delayMatch7_t_1 = delayMatch7_t_1 + 32'sd1) begin
          delayMatch7_reg[delayMatch7_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch7_t_0_1 = 32'sd0; delayMatch7_t_0_1 <= 32'sd7; delayMatch7_t_0_1 = delayMatch7_t_0_1 + 32'sd1) begin
            delayMatch7_reg[delayMatch7_t_0_1] <= delayMatch7_reg_next[delayMatch7_t_0_1];
          end
        end
      end
    end

  always @* begin
    HostRTQ_out1 = delayMatch7_reg[7];
    delayMatch7_reg_next[0] = HostCapQ_out1;

    for(delayMatch7_t_0_0 = 32'sd0; delayMatch7_t_0_0 <= 32'sd6; delayMatch7_t_0_0 = delayMatch7_t_0_0 + 32'sd1) begin
      delayMatch7_reg_next[delayMatch7_t_0_0 + 32'sd1] = delayMatch7_reg[delayMatch7_t_0_0];
    end

  end

  assign MUX_DacQ_out1 = (tx_source_select_1 == 32'b00000000000000000000000000000000 ? REP_TxQ_out1_1 :
              HostRTQ_out1);

  assign tx_dataOutQ = MUX_DacQ_out1;

  always @(posedge clk or posedge reset)
    begin : delayMatch18_process
      if (reset == 1'b1) begin
        delayMatch18_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch18_reg[0] <= host_txValid;
          delayMatch18_reg[32'sd7:32'sd1] <= delayMatch18_reg[32'sd6:32'sd0];
        end
      end
    end

  assign host_txValid_1 = delayMatch18_reg[7];

  assign tx_validOut = host_txValid_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch19_process
      if (reset == 1'b1) begin
        for(delayMatch19_t_1 = 32'sd0; delayMatch19_t_1 <= 32'sd1; delayMatch19_t_1 = delayMatch19_t_1 + 32'sd1) begin
          delayMatch19_reg[delayMatch19_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch19_t_0_0 = 32'sd0; delayMatch19_t_0_0 <= 32'sd1; delayMatch19_t_0_0 = delayMatch19_t_0_0 + 32'sd1) begin
            delayMatch19_reg[delayMatch19_t_0_0] <= delayMatch19_reg_next[delayMatch19_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_descr_in_1 = delayMatch19_reg[1];
  assign delayMatch19_reg_next[0] = Receiver_cnt_descr_in;
  assign delayMatch19_reg_next[1] = delayMatch19_reg[0];

  assign cnt_descr_in = Receiver_cnt_descr_in_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch20_process
      if (reset == 1'b1) begin
        for(delayMatch20_t_1 = 32'sd0; delayMatch20_t_1 <= 32'sd1; delayMatch20_t_1 = delayMatch20_t_1 + 32'sd1) begin
          delayMatch20_reg[delayMatch20_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch20_t_0_0 = 32'sd0; delayMatch20_t_0_0 <= 32'sd1; delayMatch20_t_0_0 = delayMatch20_t_0_0 + 32'sd1) begin
            delayMatch20_reg[delayMatch20_t_0_0] <= delayMatch20_reg_next[delayMatch20_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_frame_start_1 = delayMatch20_reg[1];
  assign delayMatch20_reg_next[0] = Receiver_cnt_frame_start;
  assign delayMatch20_reg_next[1] = delayMatch20_reg[0];

  assign cnt_frame_start = Receiver_cnt_frame_start_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch21_process
      if (reset == 1'b1) begin
        for(delayMatch21_t_1 = 32'sd0; delayMatch21_t_1 <= 32'sd1; delayMatch21_t_1 = delayMatch21_t_1 + 32'sd1) begin
          delayMatch21_reg[delayMatch21_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch21_t_0_0 = 32'sd0; delayMatch21_t_0_0 <= 32'sd1; delayMatch21_t_0_0 = delayMatch21_t_0_0 + 32'sd1) begin
            delayMatch21_reg[delayMatch21_t_0_0] <= delayMatch21_reg_next[delayMatch21_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_vit_reset_1 = delayMatch21_reg[1];
  assign delayMatch21_reg_next[0] = Receiver_cnt_vit_reset;
  assign delayMatch21_reg_next[1] = delayMatch21_reg[0];

  assign cnt_vit_reset = Receiver_cnt_vit_reset_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch22_process
      if (reset == 1'b1) begin
        for(delayMatch22_t_1 = 32'sd0; delayMatch22_t_1 <= 32'sd1; delayMatch22_t_1 = delayMatch22_t_1 + 32'sd1) begin
          delayMatch22_reg[delayMatch22_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch22_t_0_0 = 32'sd0; delayMatch22_t_0_0 <= 32'sd1; delayMatch22_t_0_0 = delayMatch22_t_0_0 + 32'sd1) begin
            delayMatch22_reg[delayMatch22_t_0_0] <= delayMatch22_reg_next[delayMatch22_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_deint_valid_1 = delayMatch22_reg[1];
  assign delayMatch22_reg_next[0] = Receiver_cnt_deint_valid;
  assign delayMatch22_reg_next[1] = delayMatch22_reg[0];

  assign cnt_deint_valid = Receiver_cnt_deint_valid_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch23_process
      if (reset == 1'b1) begin
        for(delayMatch23_t_1 = 32'sd0; delayMatch23_t_1 <= 32'sd1; delayMatch23_t_1 = delayMatch23_t_1 + 32'sd1) begin
          delayMatch23_reg[delayMatch23_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch23_t_0_0 = 32'sd0; delayMatch23_t_0_0 <= 32'sd1; delayMatch23_t_0_0 = delayMatch23_t_0_0 + 32'sd1) begin
            delayMatch23_reg[delayMatch23_t_0_0] <= delayMatch23_reg_next[delayMatch23_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_dec_bits_1 = delayMatch23_reg[1];
  assign delayMatch23_reg_next[0] = Receiver_cnt_dec_bits;
  assign delayMatch23_reg_next[1] = delayMatch23_reg[0];

  assign cnt_dec_bits = Receiver_cnt_dec_bits_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch24_process
      if (reset == 1'b1) begin
        for(delayMatch24_t_1 = 32'sd0; delayMatch24_t_1 <= 32'sd1; delayMatch24_t_1 = delayMatch24_t_1 + 32'sd1) begin
          delayMatch24_reg[delayMatch24_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch24_t_0_0 = 32'sd0; delayMatch24_t_0_0 <= 32'sd1; delayMatch24_t_0_0 = delayMatch24_t_0_0 + 32'sd1) begin
            delayMatch24_reg[delayMatch24_t_0_0] <= delayMatch24_reg_next[delayMatch24_t_0_0];
          end
        end
      end
    end

  assign Receiver_cnt_bist_start_1 = delayMatch24_reg[1];
  assign delayMatch24_reg_next[0] = Receiver_cnt_bist_start;
  assign delayMatch24_reg_next[1] = delayMatch24_reg[0];

  assign cnt_bist_start = Receiver_cnt_bist_start_1;

  assign DbgSentinelConst_out1 = 32'b11111110110001101100101101100000;

  assign dbg_sentinel = DbgSentinelConst_out1;

  always @(posedge clk or posedge reset)
    begin : delayMatch25_process
      if (reset == 1'b1) begin
        for(delayMatch25_t_1 = 32'sd0; delayMatch25_t_1 <= 32'sd1; delayMatch25_t_1 = delayMatch25_t_1 + 32'sd1) begin
          delayMatch25_reg[delayMatch25_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch25_t_0_0 = 32'sd0; delayMatch25_t_0_0 <= 32'sd1; delayMatch25_t_0_0 = delayMatch25_t_0_0 + 32'sd1) begin
            delayMatch25_reg[delayMatch25_t_0_0] <= delayMatch25_reg_next[delayMatch25_t_0_0];
          end
        end
      end
    end

  assign Receiver_cap_in_1 = delayMatch25_reg[1];
  assign delayMatch25_reg_next[0] = Receiver_cap_in;
  assign delayMatch25_reg_next[1] = delayMatch25_reg[0];

  assign cap_in = Receiver_cap_in_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch26_process
      if (reset == 1'b1) begin
        for(delayMatch26_t_1 = 32'sd0; delayMatch26_t_1 <= 32'sd1; delayMatch26_t_1 = delayMatch26_t_1 + 32'sd1) begin
          delayMatch26_reg[delayMatch26_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch26_t_0_0 = 32'sd0; delayMatch26_t_0_0 <= 32'sd1; delayMatch26_t_0_0 = delayMatch26_t_0_0 + 32'sd1) begin
            delayMatch26_reg[delayMatch26_t_0_0] <= delayMatch26_reg_next[delayMatch26_t_0_0];
          end
        end
      end
    end

  assign Receiver_cap_deint_1 = delayMatch26_reg[1];
  assign delayMatch26_reg_next[0] = Receiver_cap_deint;
  assign delayMatch26_reg_next[1] = delayMatch26_reg[0];

  assign cap_deint = Receiver_cap_deint_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch27_process
      if (reset == 1'b1) begin
        for(delayMatch27_t_1 = 32'sd0; delayMatch27_t_1 <= 32'sd1; delayMatch27_t_1 = delayMatch27_t_1 + 32'sd1) begin
          delayMatch27_reg[delayMatch27_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch27_t_0_0 = 32'sd0; delayMatch27_t_0_0 <= 32'sd1; delayMatch27_t_0_0 = delayMatch27_t_0_0 + 32'sd1) begin
            delayMatch27_reg[delayMatch27_t_0_0] <= delayMatch27_reg_next[delayMatch27_t_0_0];
          end
        end
      end
    end

  assign Receiver_cap_out_1 = delayMatch27_reg[1];
  assign delayMatch27_reg_next[0] = Receiver_cap_out;
  assign delayMatch27_reg_next[1] = delayMatch27_reg[0];

  assign cap_out = Receiver_cap_out_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch28_process
      if (reset == 1'b1) begin
        for(delayMatch28_t_1 = 32'sd0; delayMatch28_t_1 <= 32'sd2; delayMatch28_t_1 = delayMatch28_t_1 + 32'sd1) begin
          delayMatch28_reg[delayMatch28_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch28_t_0_1 = 32'sd0; delayMatch28_t_0_1 <= 32'sd2; delayMatch28_t_0_1 = delayMatch28_t_0_1 + 32'sd1) begin
            delayMatch28_reg[delayMatch28_t_0_1] <= delayMatch28_reg_next[delayMatch28_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_cap_cad_1 = delayMatch28_reg[2];
    delayMatch28_reg_next[0] = Receiver_cap_cad;

    for(delayMatch28_t_0_0 = 32'sd0; delayMatch28_t_0_0 <= 32'sd1; delayMatch28_t_0_0 = delayMatch28_t_0_0 + 32'sd1) begin
      delayMatch28_reg_next[delayMatch28_t_0_0 + 32'sd1] = delayMatch28_reg[delayMatch28_t_0_0];
    end

  end

  assign cap_cad = Receiver_cap_cad_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch29_process
      if (reset == 1'b1) begin
        for(delayMatch29_t_1 = 32'sd0; delayMatch29_t_1 <= 32'sd2; delayMatch29_t_1 = delayMatch29_t_1 + 32'sd1) begin
          delayMatch29_reg[delayMatch29_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch29_t_0_1 = 32'sd0; delayMatch29_t_0_1 <= 32'sd2; delayMatch29_t_0_1 = delayMatch29_t_0_1 + 32'sd1) begin
            delayMatch29_reg[delayMatch29_t_0_1] <= delayMatch29_reg_next[delayMatch29_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_rstcs_count_1 = delayMatch29_reg[2];
    delayMatch29_reg_next[0] = Receiver_rstcs_count;

    for(delayMatch29_t_0_0 = 32'sd0; delayMatch29_t_0_0 <= 32'sd1; delayMatch29_t_0_0 = delayMatch29_t_0_0 + 32'sd1) begin
      delayMatch29_reg_next[delayMatch29_t_0_0 + 32'sd1] = delayMatch29_reg[delayMatch29_t_0_0];
    end

  end

  assign rstcs_count = Receiver_rstcs_count_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch30_process
      if (reset == 1'b1) begin
        for(delayMatch30_t_1 = 32'sd0; delayMatch30_t_1 <= 32'sd2; delayMatch30_t_1 = delayMatch30_t_1 + 32'sd1) begin
          delayMatch30_reg[delayMatch30_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch30_t_0_1 = 32'sd0; delayMatch30_t_0_1 <= 32'sd2; delayMatch30_t_0_1 = delayMatch30_t_0_1 + 32'sd1) begin
            delayMatch30_reg[delayMatch30_t_0_1] <= delayMatch30_reg_next[delayMatch30_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_cfc_est_1 = delayMatch30_reg[2];
    delayMatch30_reg_next[0] = Receiver_cfc_est;

    for(delayMatch30_t_0_0 = 32'sd0; delayMatch30_t_0_0 <= 32'sd1; delayMatch30_t_0_0 = delayMatch30_t_0_0 + 32'sd1) begin
      delayMatch30_reg_next[delayMatch30_t_0_0 + 32'sd1] = delayMatch30_reg[delayMatch30_t_0_0];
    end

  end

  assign cfc_est = Receiver_cfc_est_1;

  always @(posedge clk or posedge reset)
    begin : ReadyDly_process
      if (reset == 1'b1) begin
        ReadyDly_out1 <= 1'b1;
      end
      else begin
        if (enb) begin
          ReadyDly_out1 <= readyNext;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch31_process
      if (reset == 1'b1) begin
        delayMatch31_reg <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch31_reg[0] <= ReadyDly_out1;
          delayMatch31_reg[32'sd7:32'sd1] <= delayMatch31_reg[32'sd6:32'sd0];
        end
      end
    end

  assign ReadyDly_out1_1 = delayMatch31_reg[7];

  assign byte_ready = ReadyDly_out1_1;

  always @(posedge clk or posedge reset)
    begin : RxReadyRT_bypass_process
      if (reset == 1'b1) begin
        RxReadyRT_bypass_reg <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          RxReadyRT_bypass_reg <= byte_rx_ready;
        end
      end
    end

  assign RxReadyRT_out1 = (enb_1_2_1 == 1'b1 ? byte_rx_ready :
              RxReadyRT_bypass_reg);

  ByteSerializer u_ByteSerializer (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .bitIn(Receiver_recBit),
                                                    .bitValid(Receiver_recBitValid),
                                                    .start(Receiver_recStart),
                                                    .ready(RxReadyRT_out1),
                                                    .word(word_1),  // ufix64
                                                    .wordTog(wordTog),
                                                    .wordLast(wordLast),
                                                    .wordFirst(wordFirst_1)
                                                    );

  always @(posedge clk or posedge reset)
    begin : SerWordRT_process
      if (reset == 1'b1) begin
        SerWordRT_out1 <= 64'h0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          SerWordRT_out1 <= word_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : SerTogRT_process
      if (reset == 1'b1) begin
        SerTogRT_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          SerTogRT_out1 <= wordTog;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : SerLastRT_process
      if (reset == 1'b1) begin
        SerLastRT_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          SerLastRT_out1 <= wordLast;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : SerFirstRT_process
      if (reset == 1'b1) begin
        SerFirstRT_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          SerFirstRT_out1 <= wordFirst_1;
        end
      end
    end

  ByteRxFifo u_ByteRxFifo (.clk(clk),
                                            .reset(reset),
                                            .enb(enb),
                                            .word(SerWordRT_out1),  // ufix64
                                            .tog(SerTogRT_out1),
                                            .wLast(SerLastRT_out1),
                                            .wFirst(SerFirstRT_out1),
                                            .ready(byte_rx_ready),
                                            .outWord(outWord),  // ufix64
                                            .valid(valid),
                                            .outLast(outLast),
                                            .outFirst(outFirst),
                                            .ovf(ovf)  // uint32
                                            );

  always @(posedge clk or posedge reset)
    begin : delayMatch32_process
      if (reset == 1'b1) begin
        for(delayMatch32_t_1 = 32'sd0; delayMatch32_t_1 <= 32'sd3; delayMatch32_t_1 = delayMatch32_t_1 + 32'sd1) begin
          delayMatch32_reg[delayMatch32_t_1] <= 64'h0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch32_t_0_1 = 32'sd0; delayMatch32_t_0_1 <= 32'sd3; delayMatch32_t_0_1 = delayMatch32_t_0_1 + 32'sd1) begin
            delayMatch32_reg[delayMatch32_t_0_1] <= delayMatch32_reg_next[delayMatch32_t_0_1];
          end
        end
      end
    end

  always @* begin
    outWord_1 = delayMatch32_reg[3];
    delayMatch32_reg_next[0] = outWord;

    for(delayMatch32_t_0_0 = 32'sd0; delayMatch32_t_0_0 <= 32'sd2; delayMatch32_t_0_0 = delayMatch32_t_0_0 + 32'sd1) begin
      delayMatch32_reg_next[delayMatch32_t_0_0 + 32'sd1] = delayMatch32_reg[delayMatch32_t_0_0];
    end

  end

  assign byte_rx_data = outWord_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch33_process
      if (reset == 1'b1) begin
        delayMatch33_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch33_reg[0] <= valid;
          delayMatch33_reg[32'sd3:32'sd1] <= delayMatch33_reg[32'sd2:32'sd0];
        end
      end
    end

  assign valid_1 = delayMatch33_reg[3];

  assign byte_rx_valid = valid_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch34_process
      if (reset == 1'b1) begin
        delayMatch34_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch34_reg[0] <= outLast;
          delayMatch34_reg[32'sd3:32'sd1] <= delayMatch34_reg[32'sd2:32'sd0];
        end
      end
    end

  assign outLast_1 = delayMatch34_reg[3];

  assign byte_rx_last = outLast_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch35_process
      if (reset == 1'b1) begin
        delayMatch35_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch35_reg[0] <= outFirst;
          delayMatch35_reg[32'sd3:32'sd1] <= delayMatch35_reg[32'sd2:32'sd0];
        end
      end
    end

  assign outFirst_1 = delayMatch35_reg[3];

  assign byte_rx_user = outFirst_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch36_process
      if (reset == 1'b1) begin
        for(delayMatch36_t_1 = 32'sd0; delayMatch36_t_1 <= 32'sd3; delayMatch36_t_1 = delayMatch36_t_1 + 32'sd1) begin
          delayMatch36_reg[delayMatch36_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch36_t_0_1 = 32'sd0; delayMatch36_t_0_1 <= 32'sd3; delayMatch36_t_0_1 = delayMatch36_t_0_1 + 32'sd1) begin
            delayMatch36_reg[delayMatch36_t_0_1] <= delayMatch36_reg_next[delayMatch36_t_0_1];
          end
        end
      end
    end

  always @* begin
    ovf_1 = delayMatch36_reg[3];
    delayMatch36_reg_next[0] = ovf;

    for(delayMatch36_t_0_0 = 32'sd0; delayMatch36_t_0_0 <= 32'sd2; delayMatch36_t_0_0 = delayMatch36_t_0_0 + 32'sd1) begin
      delayMatch36_reg_next[delayMatch36_t_0_0 + 32'sd1] = delayMatch36_reg[delayMatch36_t_0_0];
    end

  end

  assign byte_fifo_ovf = ovf_1;

  assign FsRunSi_out1 = Receiver_fs_runmax;

  assign FsAgcZero_out1 = 32'b00000000000000000000000000000000;

  FrameStatChecksum u_FrameStatChecksum (.clk(clk),
                                                          .reset(reset),
                                                          .enb_1_2_0(enb_1_2_0),
                                                          .word(word_1),  // ufix64
                                                          .wordTog(wordTog),
                                                          .strobe(Receiver_recStart),
                                                          .chk(chk)  // uint16
                                                          );

  FrameStatProbe u_FrameStatProbe (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .pktCnt(Receiver_packets_out),  // uint32
                                                    .rstcsCnt(Receiver_rstcs_count),  // uint32
                                                    .runMax(FsRunSi_out1),  // uint32
                                                    .adcFor(FsAgcZero_out1),  // uint32
                                                    .cfcEst(Receiver_cfc_est),  // uint32
                                                    .chk(chk),  // uint16
                                                    .strobe(Receiver_recStart),
                                                    .rec(rec),  // ufix64
                                                    .push(push)
                                                    );

  FrameStatFifo u_FrameStatFifo (.clk(clk),
                                                  .reset(reset),
                                                  .enb_1_2_0(enb_1_2_0),
                                                  .rec(rec),  // ufix64
                                                  .push(push),
                                                  .popTok(framestat_pop),  // uint32
                                                  .headLo(headLo),  // uint32
                                                  .headHi(headHi),  // uint32
                                                  .stat(stat)  // uint32
                                                  );

  always @(posedge clk or posedge reset)
    begin : delayMatch37_process
      if (reset == 1'b1) begin
        for(delayMatch37_t_1 = 32'sd0; delayMatch37_t_1 <= 32'sd1; delayMatch37_t_1 = delayMatch37_t_1 + 32'sd1) begin
          delayMatch37_reg[delayMatch37_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch37_t_0_0 = 32'sd0; delayMatch37_t_0_0 <= 32'sd1; delayMatch37_t_0_0 = delayMatch37_t_0_0 + 32'sd1) begin
            delayMatch37_reg[delayMatch37_t_0_0] <= delayMatch37_reg_next[delayMatch37_t_0_0];
          end
        end
      end
    end

  assign headLo_1 = delayMatch37_reg[1];
  assign delayMatch37_reg_next[0] = headLo;
  assign delayMatch37_reg_next[1] = delayMatch37_reg[0];

  assign framestat_head_lo = headLo_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch38_process
      if (reset == 1'b1) begin
        for(delayMatch38_t_1 = 32'sd0; delayMatch38_t_1 <= 32'sd1; delayMatch38_t_1 = delayMatch38_t_1 + 32'sd1) begin
          delayMatch38_reg[delayMatch38_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch38_t_0_0 = 32'sd0; delayMatch38_t_0_0 <= 32'sd1; delayMatch38_t_0_0 = delayMatch38_t_0_0 + 32'sd1) begin
            delayMatch38_reg[delayMatch38_t_0_0] <= delayMatch38_reg_next[delayMatch38_t_0_0];
          end
        end
      end
    end

  assign headHi_1 = delayMatch38_reg[1];
  assign delayMatch38_reg_next[0] = headHi;
  assign delayMatch38_reg_next[1] = delayMatch38_reg[0];

  assign framestat_head_hi = headHi_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch39_process
      if (reset == 1'b1) begin
        for(delayMatch39_t_1 = 32'sd0; delayMatch39_t_1 <= 32'sd1; delayMatch39_t_1 = delayMatch39_t_1 + 32'sd1) begin
          delayMatch39_reg[delayMatch39_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch39_t_0_0 = 32'sd0; delayMatch39_t_0_0 <= 32'sd1; delayMatch39_t_0_0 = delayMatch39_t_0_0 + 32'sd1) begin
            delayMatch39_reg[delayMatch39_t_0_0] <= delayMatch39_reg_next[delayMatch39_t_0_0];
          end
        end
      end
    end

  assign stat_1 = delayMatch39_reg[1];
  assign delayMatch39_reg_next[0] = stat;
  assign delayMatch39_reg_next[1] = delayMatch39_reg[0];

  assign framestat_stat = stat_1;

  FrameStatWordCnt u_FrameStatWordCnt (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .vld(valid),
                                                        .rdy(byte_rx_ready),
                                                        .cnt(cnt)  // uint32
                                                        );

  always @(posedge clk or posedge reset)
    begin : delayMatch40_process
      if (reset == 1'b1) begin
        for(delayMatch40_t_1 = 32'sd0; delayMatch40_t_1 <= 32'sd3; delayMatch40_t_1 = delayMatch40_t_1 + 32'sd1) begin
          delayMatch40_reg[delayMatch40_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch40_t_0_1 = 32'sd0; delayMatch40_t_0_1 <= 32'sd3; delayMatch40_t_0_1 = delayMatch40_t_0_1 + 32'sd1) begin
            delayMatch40_reg[delayMatch40_t_0_1] <= delayMatch40_reg_next[delayMatch40_t_0_1];
          end
        end
      end
    end

  always @* begin
    cnt_1 = delayMatch40_reg[3];
    delayMatch40_reg_next[0] = cnt;

    for(delayMatch40_t_0_0 = 32'sd0; delayMatch40_t_0_0 <= 32'sd2; delayMatch40_t_0_0 = delayMatch40_t_0_0 + 32'sd1) begin
      delayMatch40_reg_next[delayMatch40_t_0_0 + 32'sd1] = delayMatch40_reg[delayMatch40_t_0_0];
    end

  end

  assign framestat_wordcnt = cnt_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch41_process
      if (reset == 1'b1) begin
        for(delayMatch41_t_1 = 32'sd0; delayMatch41_t_1 <= 32'sd2; delayMatch41_t_1 = delayMatch41_t_1 + 32'sd1) begin
          delayMatch41_reg[delayMatch41_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch41_t_0_1 = 32'sd0; delayMatch41_t_0_1 <= 32'sd2; delayMatch41_t_0_1 = delayMatch41_t_0_1 + 32'sd1) begin
            delayMatch41_reg[delayMatch41_t_0_1] <= delayMatch41_reg_next[delayMatch41_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_beatfix_viol_count_1 = delayMatch41_reg[2];
    delayMatch41_reg_next[0] = Receiver_beatfix_viol_count;

    for(delayMatch41_t_0_0 = 32'sd0; delayMatch41_t_0_0 <= 32'sd1; delayMatch41_t_0_0 = delayMatch41_t_0_0 + 32'sd1) begin
      delayMatch41_reg_next[delayMatch41_t_0_0 + 32'sd1] = delayMatch41_reg[delayMatch41_t_0_0];
    end

  end

  assign beatfix_viol_count = Receiver_beatfix_viol_count_1;

  always @(posedge clk or posedge reset)
    begin : delayMatch42_process
      if (reset == 1'b1) begin
        for(delayMatch42_t_1 = 32'sd0; delayMatch42_t_1 <= 32'sd2; delayMatch42_t_1 = delayMatch42_t_1 + 32'sd1) begin
          delayMatch42_reg[delayMatch42_t_1] <= 32'b00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(delayMatch42_t_0_1 = 32'sd0; delayMatch42_t_0_1 <= 32'sd2; delayMatch42_t_0_1 = delayMatch42_t_0_1 + 32'sd1) begin
            delayMatch42_reg[delayMatch42_t_0_1] <= delayMatch42_reg_next[delayMatch42_t_0_1];
          end
        end
      end
    end

  always @* begin
    Receiver_beatfix_viol_latch_1 = delayMatch42_reg[2];
    delayMatch42_reg_next[0] = Receiver_beatfix_viol_latch;

    for(delayMatch42_t_0_0 = 32'sd0; delayMatch42_t_0_0 <= 32'sd1; delayMatch42_t_0_0 = delayMatch42_t_0_0 + 32'sd1) begin
      delayMatch42_reg_next[delayMatch42_t_0_0 + 32'sd1] = delayMatch42_reg[delayMatch42_t_0_0];
    end

  end

  assign beatfix_viol_latch = Receiver_beatfix_viol_latch_1;

  assign ce_out_0 = enb_1_2_1;

  assign ce_out_1 = enb_1_1_1;

endmodule  // TxRxComposite

