// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/TxRxCompo_ip.v
// Created: 2026-08-21 23:32:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TxRxCompo_ip
// Source Path: TxRxCompo_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TxRxCompo_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           dut_data_valid_in_rx,
           dut_data_in_0_rx,
           dut_data_in_1_rx,
           dut_data_valid_in_tx,
           dut_data_in_0_tx,
           dut_data_in_1_tx,
           dut_byte_data_in,
           dut_byte_valid_in,
           dut_byte_first_in,
           dut_byte_ready_in,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           dut_data_valid_out_rx,
           dut_data_out_0_rx,
           dut_data_out_1_rx,
           dut_data_out_2_rx,
           dut_data_out_3_rx,
           dut_data_valid_out_tx,
           dut_data_out_0_tx,
           dut_data_out_1_tx,
           dut_byte_ready_out,
           dut_byte_data_out,
           dut_byte_valid_out,
           dut_byte_last_out,
           dut_byte_user_out,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   dut_data_valid_in_rx;  // ufix1
  input   [15:0] dut_data_in_0_rx;  // ufix16
  input   [15:0] dut_data_in_1_rx;  // ufix16
  input   dut_data_valid_in_tx;  // ufix1
  input   [15:0] dut_data_in_0_tx;  // ufix16
  input   [15:0] dut_data_in_1_tx;  // ufix16
  input   [63:0] dut_byte_data_in;  // ufix64
  input   dut_byte_valid_in;  // ufix1
  input   dut_byte_first_in;  // ufix1
  input   dut_byte_ready_in;  // ufix1
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  dut_data_valid_out_rx;  // ufix1
  output  [15:0] dut_data_out_0_rx;  // ufix16
  output  [15:0] dut_data_out_1_rx;  // ufix16
  output  [15:0] dut_data_out_2_rx;  // ufix16
  output  [15:0] dut_data_out_3_rx;  // ufix16
  output  dut_data_valid_out_tx;  // ufix1
  output  [15:0] dut_data_out_0_tx;  // ufix16
  output  [15:0] dut_data_out_1_tx;  // ufix16
  output  dut_byte_ready_out;  // ufix1
  output  [63:0] dut_byte_data_out;  // ufix64
  output  dut_byte_valid_out;  // ufix1
  output  dut_byte_last_out;  // ufix1
  output  dut_byte_user_out;  // ufix1
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire signed [15:0] adc_dataInI_sig;  // sfix16
  wire signed [15:0] adc_dataInQ_sig;  // sfix16
  wire signed [15:0] host_txI_sig;  // sfix16
  wire signed [15:0] host_txQ_sig;  // sfix16
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire [31:0] count_out_sig;  // ufix32
  wire [31:0] packets_out_sig;  // ufix32
  wire [31:0] bit_errors_out_sig;  // ufix32
  wire [31:0] dbg_sentinel_sig;  // ufix32
  wire [31:0] cnt_descr_in_sig;  // ufix32
  wire [31:0] cnt_frame_start_sig;  // ufix32
  wire [31:0] cnt_vit_reset_sig;  // ufix32
  wire [31:0] cnt_deint_valid_sig;  // ufix32
  wire [31:0] cnt_dec_bits_sig;  // ufix32
  wire [31:0] cnt_bist_start_sig;  // ufix32
  wire [31:0] cap_in_sig;  // ufix32
  wire [31:0] cap_deint_sig;  // ufix32
  wire [31:0] cap_out_sig;  // ufix32
  wire [31:0] cap_cad_sig;  // ufix32
  wire [31:0] rstcs_count_sig;  // ufix32
  wire [31:0] cfc_est_sig;  // ufix32
  wire [31:0] byte_fifo_ovf_sig;  // ufix32
  wire [31:0] framestat_wordcnt_sig;  // ufix32
  wire [31:0] framestat_head_lo_sig;  // ufix32
  wire [31:0] framestat_head_hi_sig;  // ufix32
  wire [31:0] framestat_stat_sig;  // ufix32
  wire [31:0] beatfix_viol_count_sig;  // ufix32
  wire [31:0] beatfix_viol_latch_sig;  // ufix32
  wire write_axi_enable;  // ufix1
  wire [31:0] write_iq_debug_mux;  // ufix32
  wire write_rstCS;  // ufix1
  wire write_rx_input_select;  // ufix1
  wire [31:0] write_tx_source_select;  // ufix32
  wire [31:0] write_skip_count;  // ufix32
  wire [31:0] write_tx_data_source;  // ufix32
  wire [31:0] write_cs_prop_gain;  // ufix32
  wire [31:0] write_cs_integ_gain;  // ufix32
  wire [31:0] write_ss_prop_gain;  // ufix32
  wire [31:0] write_ss_integ_gain;  // ufix32
  wire [31:0] write_agc_loop_gain;  // ufix32
  wire [31:0] write_cfo_threshold;  // ufix32
  wire [31:0] write_framestat_pop;  // ufix32
  wire [31:0] write_fixctl;  // ufix32
  wire ce_out_0_sig;  // ufix1
  wire ce_out_1_sig;  // ufix1
  wire signed [15:0] debugI_sig;  // sfix16
  wire signed [15:0] debugQ_sig;  // sfix16
  wire debugValid_sig;  // ufix1
  wire signed [15:0] debugI1_sig;  // sfix16
  wire signed [15:0] debugQ1_sig;  // sfix16
  wire signed [15:0] tx_dataOutI_sig;  // sfix16
  wire signed [15:0] tx_dataOutQ_sig;  // sfix16
  wire tx_validOut_sig;  // ufix1
  wire byte_ready_sig;  // ufix1
  wire [63:0] byte_rx_data_sig;  // ufix64
  wire byte_rx_valid_sig;  // ufix1
  wire byte_rx_last_sig;  // ufix1
  wire byte_rx_user_sig;  // ufix1


  assign ip_timestamp = 32'b10011011011101100010100101101011;

  assign reset_cm =  ~ IPCORE_RESETN;

  assign adc_dataInI_sig = dut_data_in_0_rx;

  assign adc_dataInQ_sig = dut_data_in_1_rx;

  assign host_txI_sig = dut_data_in_0_tx;

  assign host_txQ_sig = dut_data_in_1_tx;

  assign reset_before_sync = reset_cm | reset_internal;

  TxRxCompo_ip_reset_sync u_TxRxCompo_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                          .reset_in(reset_before_sync),  // ufix1
                                                          .reset_out(reset)
                                                          );

  TxRxCompo_ip_axi_lite u_TxRxCompo_ip_axi_lite_inst (.reset(reset),
                                                      .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                                      .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                      .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                      .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                      .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                      .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                      .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                      .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                      .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                      .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                      .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                      .read_ip_timestamp(ip_timestamp),  // ufix32
                                                      .read_count_out(count_out_sig),  // ufix32
                                                      .read_packets_out(packets_out_sig),  // ufix32
                                                      .read_bit_errors_out(bit_errors_out_sig),  // ufix32
                                                      .read_dbg_sentinel(dbg_sentinel_sig),  // ufix32
                                                      .read_cnt_descr_in(cnt_descr_in_sig),  // ufix32
                                                      .read_cnt_frame_start(cnt_frame_start_sig),  // ufix32
                                                      .read_cnt_vit_reset(cnt_vit_reset_sig),  // ufix32
                                                      .read_cnt_deint_valid(cnt_deint_valid_sig),  // ufix32
                                                      .read_cnt_dec_bits(cnt_dec_bits_sig),  // ufix32
                                                      .read_cnt_bist_start(cnt_bist_start_sig),  // ufix32
                                                      .read_cap_in(cap_in_sig),  // ufix32
                                                      .read_cap_deint(cap_deint_sig),  // ufix32
                                                      .read_cap_out(cap_out_sig),  // ufix32
                                                      .read_cap_cad(cap_cad_sig),  // ufix32
                                                      .read_rstcs_count(rstcs_count_sig),  // ufix32
                                                      .read_cfc_est(cfc_est_sig),  // ufix32
                                                      .read_byte_fifo_ovf(byte_fifo_ovf_sig),  // ufix32
                                                      .read_framestat_wordcnt(framestat_wordcnt_sig),  // ufix32
                                                      .read_framestat_head_lo(framestat_head_lo_sig),  // ufix32
                                                      .read_framestat_head_hi(framestat_head_hi_sig),  // ufix32
                                                      .read_framestat_stat(framestat_stat_sig),  // ufix32
                                                      .read_beatfix_viol_count(beatfix_viol_count_sig),  // ufix32
                                                      .read_beatfix_viol_latch(beatfix_viol_latch_sig),  // ufix32
                                                      .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                      .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                      .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                      .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                      .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                      .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                      .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                      .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                      .write_axi_enable(write_axi_enable),  // ufix1
                                                      .write_iq_debug_mux(write_iq_debug_mux),  // ufix32
                                                      .write_rstCS(write_rstCS),  // ufix1
                                                      .write_rx_input_select(write_rx_input_select),  // ufix1
                                                      .write_tx_source_select(write_tx_source_select),  // ufix32
                                                      .write_skip_count(write_skip_count),  // ufix32
                                                      .write_tx_data_source(write_tx_data_source),  // ufix32
                                                      .write_cs_prop_gain(write_cs_prop_gain),  // ufix32
                                                      .write_cs_integ_gain(write_cs_integ_gain),  // ufix32
                                                      .write_ss_prop_gain(write_ss_prop_gain),  // ufix32
                                                      .write_ss_integ_gain(write_ss_integ_gain),  // ufix32
                                                      .write_agc_loop_gain(write_agc_loop_gain),  // ufix32
                                                      .write_cfo_threshold(write_cfo_threshold),  // ufix32
                                                      .write_framestat_pop(write_framestat_pop),  // ufix32
                                                      .write_fixctl(write_fixctl),  // ufix32
                                                      .reset_internal(reset_internal)  // ufix1
                                                      );

  TxRxCompo_ip_dut u_TxRxCompo_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                            .reset(reset),
                                            .dut_enable(write_axi_enable),  // ufix1
                                            .adc_validIn(dut_data_valid_in_rx),  // ufix1
                                            .adc_dataInI(adc_dataInI_sig),  // sfix16
                                            .adc_dataInQ(adc_dataInQ_sig),  // sfix16
                                            .rstCS(write_rstCS),  // ufix1
                                            .iq_debug_mux(write_iq_debug_mux),  // ufix32
                                            .rx_input_select(write_rx_input_select),  // ufix1
                                            .host_txI(host_txI_sig),  // sfix16
                                            .host_txQ(host_txQ_sig),  // sfix16
                                            .host_txValid(dut_data_valid_in_tx),  // ufix1
                                            .tx_source_select(write_tx_source_select),  // ufix32
                                            .skip_count(write_skip_count),  // ufix32
                                            .byte_data(dut_byte_data_in),  // ufix64
                                            .byte_valid(dut_byte_valid_in),  // ufix1
                                            .tx_data_source(write_tx_data_source),  // ufix32
                                            .byte_first(dut_byte_first_in),  // ufix1
                                            .byte_rx_ready(dut_byte_ready_in),  // ufix1
                                            .cs_prop_gain(write_cs_prop_gain),  // ufix32
                                            .cs_integ_gain(write_cs_integ_gain),  // ufix32
                                            .ss_prop_gain(write_ss_prop_gain),  // ufix32
                                            .ss_integ_gain(write_ss_integ_gain),  // ufix32
                                            .agc_loop_gain(write_agc_loop_gain),  // ufix32
                                            .cfo_threshold(write_cfo_threshold),  // ufix32
                                            .framestat_pop(write_framestat_pop),  // ufix32
                                            .fixctl(write_fixctl),  // ufix32
                                            .ce_out_0(ce_out_0_sig),  // ufix1
                                            .ce_out_1(ce_out_1_sig),  // ufix1
                                            .count_out(count_out_sig),  // ufix32
                                            .packets_out(packets_out_sig),  // ufix32
                                            .bit_errors_out(bit_errors_out_sig),  // ufix32
                                            .debugI(debugI_sig),  // sfix16
                                            .debugQ(debugQ_sig),  // sfix16
                                            .debugValid(debugValid_sig),  // ufix1
                                            .debugI1(debugI1_sig),  // sfix16
                                            .debugQ1(debugQ1_sig),  // sfix16
                                            .tx_dataOutI(tx_dataOutI_sig),  // sfix16
                                            .tx_dataOutQ(tx_dataOutQ_sig),  // sfix16
                                            .tx_validOut(tx_validOut_sig),  // ufix1
                                            .cnt_descr_in(cnt_descr_in_sig),  // ufix32
                                            .cnt_frame_start(cnt_frame_start_sig),  // ufix32
                                            .cnt_vit_reset(cnt_vit_reset_sig),  // ufix32
                                            .cnt_deint_valid(cnt_deint_valid_sig),  // ufix32
                                            .cnt_dec_bits(cnt_dec_bits_sig),  // ufix32
                                            .cnt_bist_start(cnt_bist_start_sig),  // ufix32
                                            .dbg_sentinel(dbg_sentinel_sig),  // ufix32
                                            .cap_in(cap_in_sig),  // ufix32
                                            .cap_deint(cap_deint_sig),  // ufix32
                                            .cap_out(cap_out_sig),  // ufix32
                                            .cap_cad(cap_cad_sig),  // ufix32
                                            .rstcs_count(rstcs_count_sig),  // ufix32
                                            .cfc_est(cfc_est_sig),  // ufix32
                                            .byte_ready(byte_ready_sig),  // ufix1
                                            .byte_rx_data(byte_rx_data_sig),  // ufix64
                                            .byte_rx_valid(byte_rx_valid_sig),  // ufix1
                                            .byte_rx_last(byte_rx_last_sig),  // ufix1
                                            .byte_rx_user(byte_rx_user_sig),  // ufix1
                                            .byte_fifo_ovf(byte_fifo_ovf_sig),  // ufix32
                                            .framestat_head_lo(framestat_head_lo_sig),  // ufix32
                                            .framestat_head_hi(framestat_head_hi_sig),  // ufix32
                                            .framestat_stat(framestat_stat_sig),  // ufix32
                                            .framestat_wordcnt(framestat_wordcnt_sig),  // ufix32
                                            .beatfix_viol_count(beatfix_viol_count_sig),  // ufix32
                                            .beatfix_viol_latch(beatfix_viol_latch_sig)  // ufix32
                                            );

  assign dut_data_valid_out_rx = debugValid_sig;

  assign dut_data_out_0_rx = debugI1_sig;

  assign dut_data_out_1_rx = debugQ1_sig;

  assign dut_data_out_2_rx = debugI_sig;

  assign dut_data_out_3_rx = debugQ_sig;

  assign dut_data_valid_out_tx = tx_validOut_sig;

  assign dut_data_out_0_tx = tx_dataOutI_sig;

  assign dut_data_out_1_tx = tx_dataOutQ_sig;

  assign dut_byte_ready_out = byte_ready_sig;

  assign dut_byte_data_out = byte_rx_data_sig;

  assign dut_byte_valid_out = byte_rx_valid_sig;

  assign dut_byte_last_out = byte_rx_last_sig;

  assign dut_byte_user_out = byte_rx_user_sig;

endmodule  // TxRxCompo_ip

