// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/Viterbi.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Viterbi
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/FEC Decoder Wrapper/VitGate/Viterbi
// Hierarchy Level: 5
// Model version: 11.331
// 
// Top level of Viterbi Decoder, consists of three basic components: Branch Metric, ACS,and Traceback 
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Viterbi
          (clk,
           reset,
           enb_1_2_0,
           Viterbi_in_0,
           Viterbi_in_1,
           Viterbi_rst,
           decoded);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   Viterbi_in_0;  // ufix1
  input   Viterbi_in_1;  // ufix1
  input   Viterbi_rst;
  output  decoded;


  wire [1:0] Viterbi_in;  // ufix1 [2]
  reg  [1:0] regin;  // ufix1 [2]
  wire [1:0] bMet_0;  // ufix2
  wire [1:0] bMet_1;  // ufix2
  wire [1:0] bMet_2;  // ufix2
  wire [1:0] bMet_3;  // ufix2
  wire [1:0] bMet [0:3];  // ufix2 [4]
  reg [1:0] regBMet [0:3];  // ufix2 [4]
  wire dec_0;  // ufix1
  wire dec_1;  // ufix1
  wire dec_2;  // ufix1
  wire dec_3;  // ufix1
  wire dec_4;  // ufix1
  wire dec_5;  // ufix1
  wire dec_6;  // ufix1
  wire dec_7;  // ufix1
  wire dec_8;  // ufix1
  wire dec_9;  // ufix1
  wire dec_10;  // ufix1
  wire dec_11;  // ufix1
  wire dec_12;  // ufix1
  wire dec_13;  // ufix1
  wire dec_14;  // ufix1
  wire dec_15;  // ufix1
  wire [3:0] idx;  // ufix4
  wire [15:0] dec;  // ufix1 [16]
  reg  [15:0] regdec;  // ufix1 [16]
  reg [3:0] regidx;  // ufix4
  wire decoded_1;  // ufix1
  reg  outreg;  // ufix1
  reg signed [31:0] BMetRegister_t_0_0;  // int32
  reg signed [31:0] BMetRegister_t_1;  // int32


  assign Viterbi_in[0] = Viterbi_in_0;
  assign Viterbi_in[1] = Viterbi_in_1;

  // Input Register
  always @(posedge clk or posedge reset)
    begin : InputRegister_process
      if (reset == 1'b1) begin
        regin <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          regin <= Viterbi_in;
        end
      end
    end

  BranchMetric u_BMet_inst (.din_0(regin[0]),  // ufix1
                                             .din_1(regin[1]),  // ufix1
                                             .bMet_0(bMet_0),  // ufix2
                                             .bMet_1(bMet_1),  // ufix2
                                             .bMet_2(bMet_2),  // ufix2
                                             .bMet_3(bMet_3)  // ufix2
                                             );

  assign bMet[0] = bMet_0;
  assign bMet[1] = bMet_1;
  assign bMet[2] = bMet_2;
  assign bMet[3] = bMet_3;

  // Branch Metric output Register
  always @(posedge clk or posedge reset)
    begin : BMetRegister_process
      if (reset == 1'b1) begin
        for(BMetRegister_t_1 = 32'sd0; BMetRegister_t_1 <= 32'sd3; BMetRegister_t_1 = BMetRegister_t_1 + 32'sd1) begin
          regBMet[BMetRegister_t_1] <= 2'b00;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(BMetRegister_t_0_0 = 32'sd0; BMetRegister_t_0_0 <= 32'sd3; BMetRegister_t_0_0 = BMetRegister_t_0_0 + 32'sd1) begin
            regBMet[BMetRegister_t_0_0] <= bMet[BMetRegister_t_0_0];
          end
        end
      end
    end

  ACS u_ACS_inst (.clk(clk),
                                   .reset(reset),
                                   .enb_1_2_0(enb_1_2_0),
                                   .acs_in_0(regBMet[0]),  // ufix2
                                   .acs_in_1(regBMet[1]),  // ufix2
                                   .acs_in_2(regBMet[2]),  // ufix2
                                   .acs_in_3(regBMet[3]),  // ufix2
                                   .acs_rst(Viterbi_rst),
                                   .dec_0(dec_0),  // ufix1
                                   .dec_1(dec_1),  // ufix1
                                   .dec_2(dec_2),  // ufix1
                                   .dec_3(dec_3),  // ufix1
                                   .dec_4(dec_4),  // ufix1
                                   .dec_5(dec_5),  // ufix1
                                   .dec_6(dec_6),  // ufix1
                                   .dec_7(dec_7),  // ufix1
                                   .dec_8(dec_8),  // ufix1
                                   .dec_9(dec_9),  // ufix1
                                   .dec_10(dec_10),  // ufix1
                                   .dec_11(dec_11),  // ufix1
                                   .dec_12(dec_12),  // ufix1
                                   .dec_13(dec_13),  // ufix1
                                   .dec_14(dec_14),  // ufix1
                                   .dec_15(dec_15),  // ufix1
                                   .idx(idx)  // ufix4
                                   );

  assign dec[0] = dec_0;
  assign dec[1] = dec_1;
  assign dec[2] = dec_2;
  assign dec[3] = dec_3;
  assign dec[4] = dec_4;
  assign dec[5] = dec_5;
  assign dec[6] = dec_6;
  assign dec[7] = dec_7;
  assign dec[8] = dec_8;
  assign dec[9] = dec_9;
  assign dec[10] = dec_10;
  assign dec[11] = dec_11;
  assign dec[12] = dec_12;
  assign dec[13] = dec_13;
  assign dec[14] = dec_14;
  assign dec[15] = dec_15;

  // ACS dec output Register
  always @(posedge clk or posedge reset)
    begin : decRegister_process
      if (reset == 1'b1) begin
        regdec <= {16{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          regdec <= dec;
        end
      end
    end

  // ACS idx output Register
  always @(posedge clk or posedge reset)
    begin : idxRegister_process
      if (reset == 1'b1) begin
        regidx <= 4'b0000;
      end
      else begin
        if (enb_1_2_0) begin
          regidx <= idx;
        end
      end
    end

  Traceback u_Traceback_inst (.clk(clk),
                                               .reset(reset),
                                               .enb_1_2_0(enb_1_2_0),
                                               .dec_0(regdec[0]),  // ufix1
                                               .dec_1(regdec[1]),  // ufix1
                                               .dec_2(regdec[2]),  // ufix1
                                               .dec_3(regdec[3]),  // ufix1
                                               .dec_4(regdec[4]),  // ufix1
                                               .dec_5(regdec[5]),  // ufix1
                                               .dec_6(regdec[6]),  // ufix1
                                               .dec_7(regdec[7]),  // ufix1
                                               .dec_8(regdec[8]),  // ufix1
                                               .dec_9(regdec[9]),  // ufix1
                                               .dec_10(regdec[10]),  // ufix1
                                               .dec_11(regdec[11]),  // ufix1
                                               .dec_12(regdec[12]),  // ufix1
                                               .dec_13(regdec[13]),  // ufix1
                                               .dec_14(regdec[14]),  // ufix1
                                               .dec_15(regdec[15]),  // ufix1
                                               .idx(regidx),  // ufix4
                                               .tb_rst(Viterbi_rst),
                                               .decoded(decoded_1)  // ufix1
                                               );

  // Viterbi Decoder output Register
  always @(posedge clk or posedge reset)
    begin : DecoderoutputRegister_process
      if (reset == 1'b1) begin
        outreg <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          outreg <= decoded_1;
        end
      end
    end

  // Output data type conversion
  assign decoded = outreg;

endmodule  // Viterbi

