// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_composite/hdlsrc/commhdlQPSKTxRxLoopback/VitGate.v
// Created: 2026-08-21 23:31:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: VitGate
// Source Path: commhdlQPSKTxRxLoopback/TxRxComposite/Receiver/QPSK Rx/FEC Decoder Wrapper/VitGate
// Hierarchy Level: 4
// Model version: 11.331
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module VitGate
          (clk,
           reset,
           enb_1_2_0,
           pairIn_0,
           pairIn_1,
           rstIn,
           Enable,
           decOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   pairIn_0;  // ufix1
  input   pairIn_1;  // ufix1
  input   rstIn;
  input   Enable;
  output  decOut;


  wire enb_1_2_0_gated;
  wire Viterbi_out1;
  wire Viterbi_out1_bypass;
  reg  Viterbi_out1_last_value;


  assign enb_1_2_0_gated = Enable && enb_1_2_0;

  Viterbi u_Viterbi (.clk(clk),
                                      .reset(reset),
                                      .enb_1_2_0(enb_1_2_0_gated),
                                      .Viterbi_in_0(pairIn_0),  // ufix1
                                      .Viterbi_in_1(pairIn_1),  // ufix1
                                      .Viterbi_rst(rstIn),
                                      .decoded(Viterbi_out1)
                                      );

  always @(posedge clk or posedge reset)
    begin : decOut_bypass_process
      if (reset == 1'b1) begin
        Viterbi_out1_last_value <= 1'b0;
      end
      else begin
        if (enb_1_2_0_gated) begin
          Viterbi_out1_last_value <= Viterbi_out1_bypass;
        end
      end
    end

  assign Viterbi_out1_bypass = (Enable == 1'b0 ? Viterbi_out1_last_value :
              Viterbi_out1);

  assign decOut = Viterbi_out1_bypass;

endmodule  // VitGate

